*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZSDSV_ZSDSCOC001................................*
FORM GET_DATA_ZSDSV_ZSDSCOC001.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZSDSCOC001 WHERE
(VIM_WHERETAB) .
    CLEAR ZSDSV_ZSDSCOC001 .
ZSDSV_ZSDSCOC001-MANDT =
ZSDSCOC001-MANDT .
ZSDSV_ZSDSCOC001-K2_CODE =
ZSDSCOC001-K2_CODE .
ZSDSV_ZSDSCOC001-NR_OBJECT =
ZSDSCOC001-NR_OBJECT .
ZSDSV_ZSDSCOC001-NR_NUMBER =
ZSDSCOC001-NR_NUMBER .
ZSDSV_ZSDSCOC001-ZDEL_FLG =
ZSDSCOC001-ZDEL_FLG .
ZSDSV_ZSDSCOC001-ZCRT_DATE =
ZSDSCOC001-ZCRT_DATE .
ZSDSV_ZSDSCOC001-ZCRT_TIME =
ZSDSCOC001-ZCRT_TIME .
ZSDSV_ZSDSCOC001-ZCRT_USER =
ZSDSCOC001-ZCRT_USER .
ZSDSV_ZSDSCOC001-ZCRT_PGM =
ZSDSCOC001-ZCRT_PGM .
ZSDSV_ZSDSCOC001-ZUPD_DATE =
ZSDSCOC001-ZUPD_DATE .
ZSDSV_ZSDSCOC001-ZUPD_TIME =
ZSDSCOC001-ZUPD_TIME .
ZSDSV_ZSDSCOC001-ZUPD_USER =
ZSDSCOC001-ZUPD_USER .
ZSDSV_ZSDSCOC001-ZUPD_PGM =
ZSDSCOC001-ZUPD_PGM .
<VIM_TOTAL_STRUC> = ZSDSV_ZSDSCOC001.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZSDSV_ZSDSCOC001 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZSDSV_ZSDSCOC001.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZSDSV_ZSDSCOC001-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZSDSCOC001 WHERE
  K2_CODE = ZSDSV_ZSDSCOC001-K2_CODE .
    IF SY-SUBRC = 0.
    DELETE ZSDSCOC001 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZSDSCOC001 WHERE
  K2_CODE = ZSDSV_ZSDSCOC001-K2_CODE .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZSDSCOC001.
    ENDIF.
ZSDSCOC001-MANDT =
ZSDSV_ZSDSCOC001-MANDT .
ZSDSCOC001-K2_CODE =
ZSDSV_ZSDSCOC001-K2_CODE .
ZSDSCOC001-NR_OBJECT =
ZSDSV_ZSDSCOC001-NR_OBJECT .
ZSDSCOC001-NR_NUMBER =
ZSDSV_ZSDSCOC001-NR_NUMBER .
ZSDSCOC001-ZDEL_FLG =
ZSDSV_ZSDSCOC001-ZDEL_FLG .
ZSDSCOC001-ZCRT_DATE =
ZSDSV_ZSDSCOC001-ZCRT_DATE .
ZSDSCOC001-ZCRT_TIME =
ZSDSV_ZSDSCOC001-ZCRT_TIME .
ZSDSCOC001-ZCRT_USER =
ZSDSV_ZSDSCOC001-ZCRT_USER .
ZSDSCOC001-ZCRT_PGM =
ZSDSV_ZSDSCOC001-ZCRT_PGM .
ZSDSCOC001-ZUPD_DATE =
ZSDSV_ZSDSCOC001-ZUPD_DATE .
ZSDSCOC001-ZUPD_TIME =
ZSDSV_ZSDSCOC001-ZUPD_TIME .
ZSDSCOC001-ZUPD_USER =
ZSDSV_ZSDSCOC001-ZUPD_USER .
ZSDSCOC001-ZUPD_PGM =
ZSDSV_ZSDSCOC001-ZUPD_PGM .
    IF SY-SUBRC = 0.
    UPDATE ZSDSCOC001 ##WARN_OK.
    ELSE.
    INSERT ZSDSCOC001 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZSDSV_ZSDSCOC001-UPD_FLAG,
STATUS_ZSDSV_ZSDSCOC001-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZSDSV_ZSDSCOC001.
  SELECT SINGLE * FROM ZSDSCOC001 WHERE
K2_CODE = ZSDSV_ZSDSCOC001-K2_CODE .
ZSDSV_ZSDSCOC001-MANDT =
ZSDSCOC001-MANDT .
ZSDSV_ZSDSCOC001-K2_CODE =
ZSDSCOC001-K2_CODE .
ZSDSV_ZSDSCOC001-NR_OBJECT =
ZSDSCOC001-NR_OBJECT .
ZSDSV_ZSDSCOC001-NR_NUMBER =
ZSDSCOC001-NR_NUMBER .
ZSDSV_ZSDSCOC001-ZDEL_FLG =
ZSDSCOC001-ZDEL_FLG .
ZSDSV_ZSDSCOC001-ZCRT_DATE =
ZSDSCOC001-ZCRT_DATE .
ZSDSV_ZSDSCOC001-ZCRT_TIME =
ZSDSCOC001-ZCRT_TIME .
ZSDSV_ZSDSCOC001-ZCRT_USER =
ZSDSCOC001-ZCRT_USER .
ZSDSV_ZSDSCOC001-ZCRT_PGM =
ZSDSCOC001-ZCRT_PGM .
ZSDSV_ZSDSCOC001-ZUPD_DATE =
ZSDSCOC001-ZUPD_DATE .
ZSDSV_ZSDSCOC001-ZUPD_TIME =
ZSDSCOC001-ZUPD_TIME .
ZSDSV_ZSDSCOC001-ZUPD_USER =
ZSDSCOC001-ZUPD_USER .
ZSDSV_ZSDSCOC001-ZUPD_PGM =
ZSDSCOC001-ZUPD_PGM .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZSDSV_ZSDSCOC001 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZSDSV_ZSDSCOC001-K2_CODE TO
ZSDSCOC001-K2_CODE .
MOVE ZSDSV_ZSDSCOC001-MANDT TO
ZSDSCOC001-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZSDSCOC001'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZSDSCOC001 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZSDSCOC001'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
