FUNCTION-POOL ZSDSCO02.                     "MESSAGE-ID ..

* INCLUDE LZSDSCO02D...                      " Local class definition

TYPES: BEGIN OF TS_SERV,
         OBJECT_ID       TYPE CRMS4D_SERV_H-OBJECT_ID,
         PROCESS_TYPE    TYPE CRMS4D_SERV_H-PROCESS_TYPE,
         SALES_ORG_SD    TYPE CRMS4D_SERV_H-SALES_ORG_SD,
         DIS_CHANNEL     TYPE CRMS4D_SERV_H-DIS_CHANNEL,
         DIVISION        TYPE CRMS4D_SERV_H-DIVISION,
         SALES_OFFICE_SD TYPE CRMS4D_SERV_H-SALES_OFFICE_SD,
         SALES_GROUP_SD  TYPE CRMS4D_SERV_H-SALES_GROUP_SD,
         SOLD_TO_PARTY   TYPE CRMS4D_SERV_H-SOLD_TO_PARTY,
         SHIP_TO_PARTY   TYPE CRMS4D_SERV_H-SHIP_TO_PARTY,
         PERSON_RESP     TYPE CRMS4D_SERV_H-PERSON_RESP,
         PRODUCT_ID      TYPE CRMS4D_SERV_I-PRODUCT_ID,
         PROD_HIERARCHY  TYPE CRMS4D_SERV_I-PROD_HIERARCHY,     "CH01+
       END OF TS_SERV.

* Begin of insertion - CH01 - 420000223 - 03.03.2025
TYPES: BEGIN OF TS_PRPS,
         PSPNR TYPE PRPS-PSPNR,
         POSID TYPE PRPS-POSID,
         POST1 TYPE PRPS-POST1,
       END OF TS_PRPS.

TYPES: TT_PRPS TYPE STANDARD TABLE OF TS_PRPS.
* End of insertion - CH01 - 420000223 - 03.03.2025
