FUNCTION-POOL ZSDSCO01.                     "MESSAGE-ID ..

TYPES: BEGIN OF TY_COSP,
         LEDNR  TYPE V_COSP_VIEW-LEDNR,
         VERSN  TYPE V_COSP_VIEW-VERSN,
         OBJNR  TYPE V_COSP_VIEW-OBJNR,
         WRTTP  TYPE V_COSP_VIEW-WRTTP,
         GJAHR  TYPE V_COSP_VIEW-GJAHR,
         KSTAR  TYPE V_COSP_VIEW-KSTAR,
         VRGNG  TYPE V_COSP_VIEW-VRGNG,                     "+420000674
         TWAER  TYPE V_COSP_VIEW-TWAER,
         WOG001 TYPE WOGXXX,
         WOG002 TYPE WOGXXX,
         WOG003 TYPE WOGXXX,
         WOG004 TYPE WOGXXX,
         WOG005 TYPE WOGXXX,
         WOG006 TYPE WOGXXX,
         WOG007 TYPE WOGXXX,
         WOG008 TYPE WOGXXX,
         WOG009 TYPE WOGXXX,
         WOG010 TYPE WOGXXX,
         WOG011 TYPE WOGXXX,
         WOG012 TYPE WOGXXX,
       END OF TY_COSP.
TYPES: TT_COSP TYPE STANDARD TABLE OF TY_COSP WITH EMPTY KEY.

DATA:
##NEEDED GT_BDCDATA      TYPE STANDARD TABLE OF BDCDATA,
##NEEDED GS_BDCDATA      TYPE BDCDATA,
      ##NEEDED
      GT_MESSTAB      TYPE STANDARD TABLE OF BDCMSGCOLL,
      ##NEEDED
      GF_LAST_PROGRAM TYPE BDCDATA-PROGRAM,
      ##NEEDED
      GF_LAST_DYNPRO  TYPE BDCDATA-DYNPRO.
##NEEDED

DATA: GF_MODE(1) TYPE C VALUE 'N' .
##NEEDED
* INCLUDE LZSDSCO01D...                      " Local class definition
