@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_73449F93A04E'

extend view C_MARKETSEGMENTQ2501 with ZZ1_JGH437XADIQC2EJ5IBKBVZSDKA
  
{ 
  ZZ1_ZZPMT_MSE as ZZ1_ZZPMT_MSE
}
