@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_70CDE71EE220'

extend view C_GLLINEITEMSQ0001 with ZZ1_SOUEEHDCRD5UPEPCQCUBQIRU4A
  
{ 
  ZZ1_ZZCAV_MSE as ZZ1_ZZCAV_MSE
}
