@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_4EAFB96B014E'

extend view C_MARKETSEGMENTPLANACTQ2501 with ZZ1_6BLAOVAJY5NIRXWYBCE6I4LA44
  
{ 
  ZZ1_SERVTYPE_APM as ZZ1_SERVTYPE_APM
}
