@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_04FFDE8EF43B'

extend view C_MARKETSEGMENTPLANACTQ2501 with ZZ1_U5HGZDLN4W2UWV6ZTHPBN6XF3I
  
{ 
  ZZ1_PROJTYPE_APM as ZZ1_PROJTYPE_APM
}
