@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_50FEA856FE27'

extend view C_MARKETSEGMENTQ2501 with ZZ1_BDCQRI444YKPUQGJMLAUZQPAHQ
  
{ 
  ZZ1_SERVTYPE_MSE as ZZ1_SERVTYPE_MSE
}
