@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_8A4A76B6DF6D'

extend view C_GLLINEITEMSQ0001 with ZZ1_JXN524LFFVDZFWUJXJAIAA3RJY
  
{ 
  ZZ1_ZZREFTN_MSE as ZZ1_ZZREFTN_MSE
}
