@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_2ECCD45E3B68'

extend view C_PROFITANDLOSSQ2901 with ZZ1_25GXHCYMV3PIIDDJG7DCOBNLXQ
  
{ 
  ZZ1_APPLTN as ZZ1_APPLTN
}
