@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_5A5F8FBEB2F5'

extend view C_MARKETSEGMENTPLANACTQ2501 with ZZ1_SCPXPVEMAYPHGXQVH3Z5JM5GP4
  
{ 
  ZZ1_SHOPTYPE_APM as ZZ1_SHOPTYPE_APM
}
