@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_DF9C06AE7A8A'

extend view C_MARKETSEGMENTQ2501 with ZZ1_NW47ZNYKXRLB54UBOA3OIOYITA
  
{ 
  ZZ1_SDSDIST_MSE as ZZ1_SDSDIST_MSE
}
