@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_D77CCD4FAB1A'

extend view C_PROFITANDLOSSQ2901 with ZZ1_BGYSVVSD4AVH7YKR5D5PJMQGZA
  
{ 
  ZZ1_SERVTYPE_MSE as ZZ1_SERVTYPE_MSE
}
