CLASS ZCL_ZSDSSD_SALES_PROCE_DPC_EXT DEFINITION
  PUBLIC
  INHERITING FROM ZCL_ZSDSSD_SALES_PROCE_DPC
  CREATE PUBLIC .

  PUBLIC SECTION.

    CONSTANTS : BEGIN OF  GC_CON,
                  CONFIRM_QTY TYPE C LENGTH 16 VALUE 'getConfirmQtySet',
                END OF GC_CON .

    METHODS /IWBEP/IF_MGW_APPL_SRV_RUNTIME~CREATE_DEEP_ENTITY
        REDEFINITION .
protected section.

  methods GETCONFIRMQTYSET_GET_ENTITYSET
    redefinition .
private section.
ENDCLASS.



CLASS ZCL_ZSDSSD_SALES_PROCE_DPC_EXT IMPLEMENTATION.


  METHOD /IWBEP/IF_MGW_APPL_SRV_RUNTIME~CREATE_DEEP_ENTITY.
    DATA : LS_SO_SCHDULE   TYPE ZSDSSDS126.

    FIELD-SYMBOLS <LFS_DATA> TYPE ANY.

    IF IO_DATA_PROVIDER IS NOT INITIAL.
      IF     IV_ENTITY_SET_NAME EQ GC_CON-CONFIRM_QTY.
        IO_DATA_PROVIDER->READ_ENTRY_DATA( IMPORTING ES_DATA = LS_SO_SCHDULE ).
        LCL_DATA=>GET_DATA_SCHDULE( CHANGING CT_DATA = LS_SO_SCHDULE ).
        ASSIGN LS_SO_SCHDULE TO <LFS_DATA>.
      ENDIF.

      COPY_DATA_TO_REF(
           EXPORTING
           IS_DATA = <LFS_DATA>
           CHANGING
           CR_DATA = ER_DEEP_ENTITY
           ).
    ENDIF.
  ENDMETHOD.


  method GETCONFIRMQTYSET_GET_ENTITYSET.
**TRY.
*CALL METHOD SUPER->GETCONFIRMQTYSET_GET_ENTITYSET
*  EXPORTING
*    IV_ENTITY_NAME           =
*    IV_ENTITY_SET_NAME       =
*    IV_SOURCE_NAME           =
*    IT_FILTER_SELECT_OPTIONS =
*    IS_PAGING                =
*    IT_KEY_TAB               =
*    IT_NAVIGATION_PATH       =
*    IT_ORDER                 =
*    IV_FILTER_STRING         =
*    IV_SEARCH_STRING         =
**    IO_TECH_REQUEST_CONTEXT  =
**  IMPORTING
**    ET_ENTITYSET             =
**    ES_RESPONSE_CONTEXT      =
*    .
**  CATCH /IWBEP/CX_MGW_BUSI_EXCEPTION.
**  CATCH /IWBEP/CX_MGW_TECH_EXCEPTION.
**ENDTRY.
  endmethod.
ENDCLASS.
