class ZCL_ZSDSSD_SO_PROCESS_DPC_EXT definition
  public
  inheriting from ZCL_ZSDSSD_SO_PROCESS_DPC
  create public .

public section.
protected section.

  methods UPDATEADDRESSSET_CREATE_ENTITY
    redefinition .
private section.
ENDCLASS.



CLASS ZCL_ZSDSSD_SO_PROCESS_DPC_EXT IMPLEMENTATION.


  METHOD UPDATEADDRESSSET_CREATE_ENTITY.
**TRY.
*CALL METHOD SUPER->UPDATEADDRESSSET_CREATE_ENTITY
*  EXPORTING
*    IV_ENTITY_NAME          =
*    IV_ENTITY_SET_NAME      =
*    IV_SOURCE_NAME          =
*    IT_KEY_TAB              =
**    IO_TECH_REQUEST_CONTEXT =
*    IT_NAVIGATION_PATH      =
**    IO_DATA_PROVIDER        =
**  IMPORTING
**    ER_ENTITY               =
*    .
**  CATCH /IWBEP/CX_MGW_BUSI_EXCEPTION.
**  CATCH /IWBEP/CX_MGW_TECH_EXCEPTION.
**ENDTRY.

    DATA: LV_VBELN   TYPE VBAK-VBELN,
          LS_ADDRESS TYPE ZSDSSDS120,
          LS_RETURN  TYPE BAPIRET2.

    DATA : LS_DATA TYPE ZCL_ZSDSSD_SO_PROCESS_MPC=>TS_UPDATEADDRESS.

    IF IO_DATA_PROVIDER IS NOT INITIAL.
      IO_DATA_PROVIDER->READ_ENTRY_DATA( IMPORTING ES_DATA = LS_DATA ).
    ENDIF.

    LV_VBELN = LS_DATA-VBELN.
    MOVE-CORRESPONDING LS_DATA TO LS_ADDRESS.

    CALL FUNCTION 'Z_SDSSD_UPDATE_SO_ADDR'
      EXPORTING
        IV_VBELN   = LV_VBELN
        IS_ADDRESS = LS_ADDRESS
      IMPORTING
        ES_RETURN  = LS_RETURN.

    ER_ENTITY-VBELN = LV_VBELN.
    MOVE-CORRESPONDING LS_ADDRESS TO ER_ENTITY.
    ER_ENTITY-TYPE    = LS_RETURN-TYPE.
    ER_ENTITY-MESSAGE = LS_RETURN-MESSAGE.


  ENDMETHOD.
ENDCLASS.
