CLASS ZCL_SDSSD_BILLING_ENHANCE DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    CONSTANTS : BEGIN OF GC_CON,
                  BILLING_DATE TYPE C LENGTH 21 VALUE '(SAPMV60A)RV60A-FKDAT',
                END OF GC_CON .

    METHODS VALIDATION_BILLING
      IMPORTING
        VALUE(I_VBRK)    TYPE VBRK OPTIONAL
        VALUE(I_VBRP)    TYPE VBRP OPTIONAL
        VALUE(I_VBPA)    TYPE VBPA OPTIONAL
      RETURNING
        VALUE(R_MESSAGE) TYPE CHAR255 .
protected section.
private section.
ENDCLASS.



CLASS ZCL_SDSSD_BILLING_ENHANCE IMPLEMENTATION.


  METHOD VALIDATION_BILLING.

    FIELD-SYMBOLS : <FS> TYPE ANY.
    DATA : LV_DATE TYPE SY-DATUM.

    ASSIGN (GC_CON-BILLING_DATE) TO <FS>.

    IF <FS> IS ASSIGNED AND
       <FS> IS NOT INITIAL.
      LV_DATE = <FS>.
    ELSE.
      LV_DATE = I_VBRK-FKDAT.
    ENDIF.

    IF LV_DATE+0(6) LT SY-DATUM+0(6).
      R_MESSAGE = TEXT-E01.
    ENDIF.

  ENDMETHOD.
ENDCLASS.
