CLASS ZCL_SDSSD_SALES_DOCUMENT DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    TYPES:
      BEGIN OF GY_SCHDULE,
        VBELN TYPE VBEP-VBELN,
        POSNR TYPE VBEP-POSNR,
        ETENR TYPE VBEP-ETENR,
        EDATU TYPE VBEP-EDATU,
      END OF GY_SCHDULE .

    TYPES:
      BEGIN OF GY_SCHDULE_QTY,
        VBELN TYPE VBEP-VBELN,
        POSNR TYPE VBEP-POSNR,
        ETENR TYPE VBEP-ETENR,
        EDATU TYPE VBEP-EDATU,
        BMENG TYPE VBEP-BMENG,
      END OF GY_SCHDULE_QTY.

    CLASS-DATA:
      GTY_SCHDULE_LINE TYPE TABLE OF GY_SCHDULE .
    CLASS-DATA GY_SCHDULE_LINE TYPE GY_SCHDULE .

    CLASS-DATA:
      GTY_SCHDULE_LINE_QTY TYPE TABLE OF GY_SCHDULE_QTY.
    CLASS-DATA GY_SCHDULE_LINE_QTY TYPE GY_SCHDULE_QTY.

    METHODS CANCEL_CONFIRM_QTY
      IMPORTING
        !IT_VBELN        TYPE ZSDSSDS127_TT
      RETURNING
        VALUE(RT_RETURN) TYPE ZSDSSDS124_TT .
    METHODS GET_OPEN_SCHDULE_LINE_SO
      IMPORTING
        !I_MATNR         TYPE MATNR
      RETURNING
        VALUE(RT_RETURN) TYPE ZSDSSDS127_TT .
    METHODS CONFIRM_QTY_V_V2
      IMPORTING
        !IT_MATNR TYPE FIP_T_MATNR_RANGE .
    METHODS CHANGE_CONFIRM_QTY
      IMPORTING
        !IT_VBELN        TYPE ZSDSSDS128_TT
      RETURNING
        VALUE(RT_RETURN) TYPE ZSDSSDS124_TT .
protected section.
private section.

  constants:
    BEGIN OF GC_CON,
                E TYPE C LENGTH 1 VALUE 'E',
                S TYPE C LENGTH 1 VALUE 'S',
                C TYPE C LENGTH 1 VALUE 'C',
              END OF GC_CON .
ENDCLASS.



CLASS ZCL_SDSSD_SALES_DOCUMENT IMPLEMENTATION.


  METHOD CANCEL_CONFIRM_QTY.

    DATA : LS_RETURN LIKE LINE OF RT_RETURN.

    DATA : LT_DATA TYPE TABLE OF ZSDSSDS127 WITH EMPTY KEY.

    IF IT_VBELN IS NOT INITIAL.
      LT_DATA = IT_VBELN.
      DATA(LT_SCHDULE_LINE) = LCL_DATA=>GET_SCHDULE_LINE( LT_DATA ).

      LOOP AT LT_SCHDULE_LINE INTO DATA(LS_SCHDULE_LINE).
        DATA(LT_RETURN) = LCL_DATA=>CALL_UPDATE_CANCEL_CONF_QTY( LS_SCHDULE_LINE ).
*        LCL_DATA=>SET_DELIVERY_BLOCK( LS_SCHDULE_LINE ).
      ENDLOOP.
      APPEND LINES OF LT_RETURN TO RT_RETURN.
    ELSE.
      LS_RETURN-STATU = GC_CON-E.
      LS_RETURN-MESSG = TEXT-E01.
      APPEND LS_RETURN TO RT_RETURN.
    ENDIF.

  ENDMETHOD.


  METHOD CHANGE_CONFIRM_QTY.
    DATA : LS_RETURN LIKE LINE OF RT_RETURN.

    DATA : LT_DATA TYPE TABLE OF ZSDSSDS128 WITH EMPTY KEY.

    DATA : LS_LINE LIKE ZCL_SDSSD_SALES_DOCUMENT=>GY_SCHDULE_LINE.

    IF IT_VBELN IS NOT INITIAL.
      LT_DATA = IT_VBELN.
      DATA(LT_SCHDULE_LINE) = LCL_DATA=>GET_SCHDULE_LINE_QTY( LT_DATA ).

      LOOP AT LT_SCHDULE_LINE INTO DATA(LS_SCHDULE_LINE).
        DATA(LT_RETURN) = LCL_DATA=>CALL_UPDATE_CONF_QTY( LS_SCHDULE_LINE ).
        MOVE-CORRESPONDING LS_SCHDULE_LINE TO LS_LINE.
*        LCL_DATA=>SET_DELIVERY_BLOCK( LS_LINE ).
      ENDLOOP.
      APPEND LINES OF LT_RETURN TO RT_RETURN.
    ELSE.
      LS_RETURN-STATU = GC_CON-E.
      LS_RETURN-MESSG = TEXT-E01.
      APPEND LS_RETURN TO RT_RETURN.
    ENDIF.

  ENDMETHOD.


  METHOD CONFIRM_QTY_V_V2.

    DATA: LV_JOBNAME  TYPE TBTCO-JOBNAME,
          LV_JOBCOUNT TYPE TBTCO-JOBCOUNT.

    DATA : LS_SELTAB    TYPE TABLE OF RSPARAMS.

    DATA : LS_PRINT_PARAMETERS TYPE PRI_PARAMS.

    DATA : S_WERKS TYPE RANGE OF MARD-WERKS.

    CONCATENATE 'V_V2' '_' SY-DATUM '_' SY-UZEIT INTO LV_JOBNAME.

    S_WERKS =  VALUE #( ( SIGN  = 'I' OPTION = 'EQ' LOW = '1000' ) ).

    CALL FUNCTION 'JOB_OPEN'
      EXPORTING
        JOBNAME          = LV_JOBNAME
      IMPORTING
        JOBCOUNT         = LV_JOBCOUNT
      EXCEPTIONS
        CANT_CREATE_JOB  = 1
        INVALID_JOB_DATA = 2
        JOBNAME_MISSING  = 3
        OTHERS           = 4.
    CASE SY-SUBRC.
      WHEN 0.
      WHEN OTHERS.
        MESSAGE E208(00) WITH 'Error'.
    ENDCASE.

    CALL FUNCTION 'GET_PRINT_PARAMETERS'
      EXPORTING
*       immediately            = 'X'
        NO_DIALOG              = 'X'
        USER                   = SY-UNAME
      IMPORTING
        OUT_PARAMETERS         = LS_PRINT_PARAMETERS
      EXCEPTIONS
        ARCHIVE_INFO_NOT_FOUND = 1
        INVALID_PRINT_PARAMS   = 2
        INVALID_ARCHIVE_PARAMS = 3
        OTHERS                 = 4.

    SUBMIT SDV03V02 TO SAP-SPOOL AND RETURN
                                     WITH SELECTION-TABLE LS_SELTAB
                                                     USER SY-UNAME
                                         SPOOL PARAMETERS LS_PRINT_PARAMETERS
                                     WITHOUT SPOOL DYNPRO
                                                  VIA JOB LV_JOBNAME
                                                   NUMBER LV_JOBCOUNT
                           USING SELECTION-SCREEN  1000
                            WITH S_MATNR IN IT_MATNR[]
                            WITH S_WERKS IN S_WERKS[].

    CALL FUNCTION 'JOB_CLOSE'
      EXPORTING
        JOBCOUNT             = LV_JOBCOUNT
        JOBNAME              = LV_JOBNAME
        STRTIMMED            = ABAP_TRUE
      EXCEPTIONS
        CANT_START_IMMEDIATE = 1
        INVALID_STARTDATE    = 2
        JOBNAME_MISSING      = 3
        JOB_CLOSE_FAILED     = 4
        JOB_NOSTEPS          = 5
        JOB_NOTEX            = 6
        LOCK_FAILED          = 7
        OTHERS               = 8.

  ENDMETHOD.


  METHOD GET_OPEN_SCHDULE_LINE_SO.
    SELECT A~VBELN,
           A~POSNR
      FROM VBAP AS A
*      INNER JOIN VBEP ON A~VBELN EQ VBEP~VBELN AND
*                         A~POSNR EQ VBEP~POSNR
      WHERE MATNR EQ @I_MATNR
        AND GBSTA NE @GC_CON-C
        AND NOT EXISTS ( SELECT VBELN,
                                POSNR
                           FROM LIPS
                           WHERE LIPS~VGBEL EQ A~VBELN
                             AND LIPS~VGPOS EQ A~POSNR )
      INTO TABLE @RT_RETURN.

  ENDMETHOD.
ENDCLASS.
