*"* use this source file for the definition and implementation of
*"* local helper classes, interface definitions and type
*"* declarations
CLASS LCL_DATA DEFINITION.
  PUBLIC SECTION.
    METHODS :
      CONSTRUCTOR.

    CLASS-METHODS :
      GET_DATA_SCHDULE CHANGING CT_DATA TYPE ZSDSSDS126.
ENDCLASS.
CLASS LCL_DATA IMPLEMENTATION.
  METHOD CONSTRUCTOR.

  ENDMETHOD.
  METHOD GET_DATA_SCHDULE.
    DATA : LV_CHECL TYPE VBEP-WMENG.

    DATA : LV_DATE TYPE SY-DATUM.

    DATA : LS_DATA LIKE LINE OF CT_DATA-SCHDULE_DETAIL.

    SELECT VBEP~VBELN,
           VBEP~POSNR,
           VBEP~ETENR,
           VBEP~EDATU,
           VBEP~WMENG,
           VBEP~BMENG,
           VBEP~VRKME,
           VBAP~MATNR
      FROM VBEP
      INNER JOIN VBAP ON VBEP~VBELN EQ VBAP~VBELN AND
                         VBEP~POSNR EQ VBAP~POSNR
      WHERE VBEP~VBELN EQ @CT_DATA-SONO
      INTO TABLE @DATA(LT_TMP).

    LOOP AT LT_TMP ASSIGNING FIELD-SYMBOL(<LFS_DATA>).
      LS_DATA-VBELN = <LFS_DATA>-VBELN.
      LS_DATA-POSNR = <LFS_DATA>-POSNR.
      LS_DATA-ETENR = <LFS_DATA>-ETENR.
      WRITE <LFS_DATA>-EDATU TO LS_DATA-EDATU.
      LS_DATA-WMENG = <LFS_DATA>-WMENG.
      LS_DATA-BMENG = <LFS_DATA>-BMENG.
      LS_DATA-VRKME = <LFS_DATA>-VRKME.
      LS_DATA-MATNR = <LFS_DATA>-MATNR.
      LV_CHECL = <LFS_DATA>-WMENG - <LFS_DATA>-BMENG.
      IF LV_CHECL EQ 0.
        WRITE <LFS_DATA>-EDATU TO LS_DATA-CONFD.
      ELSE.
        IF <LFS_DATA>-BMENG NE 0 AND
           <LFS_DATA>-WMENG EQ 0.
          WRITE <LFS_DATA>-EDATU TO LS_DATA-CONFD.
        ENDIF.
      ENDIF.
      APPEND LS_DATA TO CT_DATA-SCHDULE_DETAIL.
      CLEAR : LS_DATA.
    ENDLOOP.

    SORT CT_DATA-SCHDULE_DETAIL BY VBELN POSNR ETENR.

  ENDMETHOD.
ENDCLASS.
