CLASS ZCL_ZSDSSD_SO_FROM_SF_MPC_EXT DEFINITION
  PUBLIC
  INHERITING FROM ZCL_ZSDSSD_SO_FROM_SF_MPC
  CREATE PUBLIC .

  PUBLIC SECTION.

    TYPES:
      BEGIN OF TS_SALESORDERITEM_DEEP.
        INCLUDE TYPE TS_SALESORDERITEM.
    TYPES: SCHEDULELINE TYPE STANDARD TABLE OF TS_SCHEDULELINE WITH DEFAULT KEY,
      END OF TS_SALESORDERITEM_DEEP .

    TYPES:
      BEGIN OF TS_SALESORDER_DEEP.
        INCLUDE TYPE TS_SALESORDER.
    TYPES: SALESORDERITEM TYPE STANDARD TABLE OF TS_SALESORDERITEM_DEEP WITH DEFAULT KEY,
           RESPONSE       TYPE STANDARD TABLE OF TS_RESPONSE WITH DEFAULT KEY,
      END OF TS_SALESORDER_DEEP .

    METHODS DEFINE
        REDEFINITION .
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_ZSDSSD_SO_FROM_SF_MPC_EXT IMPLEMENTATION.


  METHOD DEFINE.
    DATA LO_ENTITY_TYPE TYPE REF TO /IWBEP/IF_MGW_ODATA_ENTITY_TYP.
    SUPER->DEFINE( ).
* Header Entity Name
    LO_ENTITY_TYPE = MODEL->GET_ENTITY_TYPE( IV_ENTITY_NAME = 'SalesOrder' ).
* MPC_EXT Deep Structure Name
    LO_ENTITY_TYPE->BIND_STRUCTURE( IV_STRUCTURE_NAME = 'ZCL_ZSDSSD_SO_FROM_SF_MPC_EXT=>TS_SALESORDER_DEEP' ).
  ENDMETHOD.
ENDCLASS.
