class ZCL_ZSDSSD_SO_FROM_SF_DPC_EXT definition
  public
  inheriting from ZCL_ZSDSSD_SO_FROM_SF_DPC
  create public .

public section.

  methods /IWBEP/IF_MGW_APPL_SRV_RUNTIME~CREATE_DEEP_ENTITY
    redefinition .
protected section.

  methods SALESORDERSET_GET_ENTITY
    redefinition .
  methods SALESORDERSET_GET_ENTITYSET
    redefinition .
private section.
ENDCLASS.



CLASS ZCL_ZSDSSD_SO_FROM_SF_DPC_EXT IMPLEMENTATION.


  METHOD /IWBEP/IF_MGW_APPL_SRV_RUNTIME~CREATE_DEEP_ENTITY.

    DATA:
      LS_DEEP_ENTITY    TYPE ZCL_ZSDSSD_SO_FROM_SF_MPC_EXT=>TS_SALESORDER_DEEP,
      LS_SALESORDER     TYPE ZCL_ZSDSSD_SO_FROM_SF_MPC_EXT=>TS_SALESORDER,
      LT_SALESORDERITEM TYPE ZCL_ZSDSSD_SO_FROM_SF_MPC_EXT=>TT_SALESORDERITEM,
      LT_SCHEDULELINE   TYPE ZCL_ZSDSSD_SO_FROM_SF_MPC_EXT=>TT_SCHEDULELINE.


    TRY.
        CALL METHOD IO_DATA_PROVIDER->READ_ENTRY_DATA
          IMPORTING
            ES_DATA = LS_DEEP_ENTITY.
        IF LS_DEEP_ENTITY IS NOT INITIAL.
          CLEAR LS_DEEP_ENTITY-RESPONSE.

          MOVE-CORRESPONDING LS_DEEP_ENTITY TO LS_SALESORDER.
          MOVE-CORRESPONDING LS_DEEP_ENTITY-SALESORDERITEM[] TO LT_SALESORDERITEM.
          LOOP AT LS_DEEP_ENTITY-SALESORDERITEM INTO DATA(LS_SO_ITEM).
            APPEND LINES OF LS_SO_ITEM-SCHEDULELINE[] TO LT_SCHEDULELINE.
          ENDLOOP.


          CALL METHOD ZCL_SDSSD_SO_FROM_SF_CREATION=>SALES_ORDER_PROCESS
            EXPORTING
              IF_TESTRUN        = ''
            IMPORTING
              EF_SALES_DOC      = LS_SALESORDER-SAPSALESORDERNO
            CHANGING
              CS_SALESORDER     = LS_SALESORDER
              CT_SALESORDERITEM = LT_SALESORDERITEM
              CT_SCHEDULELINE   = LT_SCHEDULELINE
              CT_RESPONSE       = LS_DEEP_ENTITY-RESPONSE.


          MOVE-CORRESPONDING LS_SALESORDER TO LS_DEEP_ENTITY.

          CALL METHOD ME->COPY_DATA_TO_REF   "Populating the ER_DEEP_ENTITY
            EXPORTING
              IS_DATA = LS_DEEP_ENTITY
            CHANGING
              CR_DATA = ER_DEEP_ENTITY.
        ENDIF.
      CATCH /IWBEP/CX_MGW_TECH_EXCEPTION.
        "Do Nothing[
    ENDTRY.

**TRY.
*CALL METHOD SUPER->/IWBEP/IF_MGW_APPL_SRV_RUNTIME~CREATE_DEEP_ENTITY
*  EXPORTING
**    IV_ENTITY_NAME          =
**    IV_ENTITY_SET_NAME      =
**    IV_SOURCE_NAME          =
*    IO_DATA_PROVIDER        =
**    IT_KEY_TAB              =
**    IT_NAVIGATION_PATH      =
*    IO_EXPAND               =
**    IO_TECH_REQUEST_CONTEXT =
**  IMPORTING
**    ER_DEEP_ENTITY          =
*    .
**  CATCH /IWBEP/CX_MGW_BUSI_EXCEPTION.
**  CATCH /IWBEP/CX_MGW_TECH_EXCEPTION.
**ENDTRY.
  ENDMETHOD.


  method SALESORDERSET_GET_ENTITY.
**TRY.
*CALL METHOD SUPER->SALESORDERSET_GET_ENTITY
*  EXPORTING
*    IV_ENTITY_NAME          =
*    IV_ENTITY_SET_NAME      =
*    IV_SOURCE_NAME          =
*    IT_KEY_TAB              =
**    IO_REQUEST_OBJECT       =
**    IO_TECH_REQUEST_CONTEXT =
*    IT_NAVIGATION_PATH      =
**  IMPORTING
**    ER_ENTITY               =
**    ES_RESPONSE_CONTEXT     =
*    .
**  CATCH /IWBEP/CX_MGW_BUSI_EXCEPTION.
**  CATCH /IWBEP/CX_MGW_TECH_EXCEPTION.
**ENDTRY.
  endmethod.


  method SALESORDERSET_GET_ENTITYSET.
**TRY.
*CALL METHOD SUPER->SALESORDERSET_GET_ENTITYSET
*  EXPORTING
*    IV_ENTITY_NAME           =
*    IV_ENTITY_SET_NAME       =
*    IV_SOURCE_NAME           =
*    IT_FILTER_SELECT_OPTIONS =
*    IS_PAGING                =
*    IT_KEY_TAB               =
*    IT_NAVIGATION_PATH       =
*    IT_ORDER                 =
*    IV_FILTER_STRING         =
*    IV_SEARCH_STRING         =
**    IO_TECH_REQUEST_CONTEXT  =
**  IMPORTING
**    ET_ENTITYSET             =
**    ES_RESPONSE_CONTEXT      =
*    .
**  CATCH /IWBEP/CX_MGW_BUSI_EXCEPTION.
**  CATCH /IWBEP/CX_MGW_TECH_EXCEPTION.
**ENDTRY.
  endmethod.
ENDCLASS.
