*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZSDSV_ETAX_TAXM.................................*
FORM GET_DATA_ZSDSV_ETAX_TAXM.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZSDSSDC021 WHERE
(VIM_WHERETAB) .
    CLEAR ZSDSV_ETAX_TAXM .
ZSDSV_ETAX_TAXM-MANDT =
ZSDSSDC021-MANDT .
ZSDSV_ETAX_TAXM-MWSKZ =
ZSDSSDC021-MWSKZ .
ZSDSV_ETAX_TAXM-TAXTY =
ZSDSSDC021-TAXTY .
ZSDSV_ETAX_TAXM-ZDEL_FLG =
ZSDSSDC021-ZDEL_FLG .
ZSDSV_ETAX_TAXM-ZCRT_DATE =
ZSDSSDC021-ZCRT_DATE .
ZSDSV_ETAX_TAXM-ZCRT_TIME =
ZSDSSDC021-ZCRT_TIME .
ZSDSV_ETAX_TAXM-ZCRT_USER =
ZSDSSDC021-ZCRT_USER .
ZSDSV_ETAX_TAXM-ZCRT_PGM =
ZSDSSDC021-ZCRT_PGM .
ZSDSV_ETAX_TAXM-ZUPD_DATE =
ZSDSSDC021-ZUPD_DATE .
ZSDSV_ETAX_TAXM-ZUPD_TIME =
ZSDSSDC021-ZUPD_TIME .
ZSDSV_ETAX_TAXM-ZUPD_USER =
ZSDSSDC021-ZUPD_USER .
ZSDSV_ETAX_TAXM-ZUPD_PGM =
ZSDSSDC021-ZUPD_PGM .
<VIM_TOTAL_STRUC> = ZSDSV_ETAX_TAXM.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZSDSV_ETAX_TAXM .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZSDSV_ETAX_TAXM.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZSDSV_ETAX_TAXM-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZSDSSDC021 WHERE
  MWSKZ = ZSDSV_ETAX_TAXM-MWSKZ .
    IF SY-SUBRC = 0.
    DELETE ZSDSSDC021 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZSDSSDC021 WHERE
  MWSKZ = ZSDSV_ETAX_TAXM-MWSKZ .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZSDSSDC021.
    ENDIF.
ZSDSSDC021-MANDT =
ZSDSV_ETAX_TAXM-MANDT .
ZSDSSDC021-MWSKZ =
ZSDSV_ETAX_TAXM-MWSKZ .
ZSDSSDC021-TAXTY =
ZSDSV_ETAX_TAXM-TAXTY .
ZSDSSDC021-ZDEL_FLG =
ZSDSV_ETAX_TAXM-ZDEL_FLG .
ZSDSSDC021-ZCRT_DATE =
ZSDSV_ETAX_TAXM-ZCRT_DATE .
ZSDSSDC021-ZCRT_TIME =
ZSDSV_ETAX_TAXM-ZCRT_TIME .
ZSDSSDC021-ZCRT_USER =
ZSDSV_ETAX_TAXM-ZCRT_USER .
ZSDSSDC021-ZCRT_PGM =
ZSDSV_ETAX_TAXM-ZCRT_PGM .
ZSDSSDC021-ZUPD_DATE =
ZSDSV_ETAX_TAXM-ZUPD_DATE .
ZSDSSDC021-ZUPD_TIME =
ZSDSV_ETAX_TAXM-ZUPD_TIME .
ZSDSSDC021-ZUPD_USER =
ZSDSV_ETAX_TAXM-ZUPD_USER .
ZSDSSDC021-ZUPD_PGM =
ZSDSV_ETAX_TAXM-ZUPD_PGM .
    IF SY-SUBRC = 0.
    UPDATE ZSDSSDC021 ##WARN_OK.
    ELSE.
    INSERT ZSDSSDC021 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZSDSV_ETAX_TAXM-UPD_FLAG,
STATUS_ZSDSV_ETAX_TAXM-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZSDSV_ETAX_TAXM.
  SELECT SINGLE * FROM ZSDSSDC021 WHERE
MWSKZ = ZSDSV_ETAX_TAXM-MWSKZ .
ZSDSV_ETAX_TAXM-MANDT =
ZSDSSDC021-MANDT .
ZSDSV_ETAX_TAXM-MWSKZ =
ZSDSSDC021-MWSKZ .
ZSDSV_ETAX_TAXM-TAXTY =
ZSDSSDC021-TAXTY .
ZSDSV_ETAX_TAXM-ZDEL_FLG =
ZSDSSDC021-ZDEL_FLG .
ZSDSV_ETAX_TAXM-ZCRT_DATE =
ZSDSSDC021-ZCRT_DATE .
ZSDSV_ETAX_TAXM-ZCRT_TIME =
ZSDSSDC021-ZCRT_TIME .
ZSDSV_ETAX_TAXM-ZCRT_USER =
ZSDSSDC021-ZCRT_USER .
ZSDSV_ETAX_TAXM-ZCRT_PGM =
ZSDSSDC021-ZCRT_PGM .
ZSDSV_ETAX_TAXM-ZUPD_DATE =
ZSDSSDC021-ZUPD_DATE .
ZSDSV_ETAX_TAXM-ZUPD_TIME =
ZSDSSDC021-ZUPD_TIME .
ZSDSV_ETAX_TAXM-ZUPD_USER =
ZSDSSDC021-ZUPD_USER .
ZSDSV_ETAX_TAXM-ZUPD_PGM =
ZSDSSDC021-ZUPD_PGM .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZSDSV_ETAX_TAXM USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZSDSV_ETAX_TAXM-MWSKZ TO
ZSDSSDC021-MWSKZ .
MOVE ZSDSV_ETAX_TAXM-MANDT TO
ZSDSSDC021-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZSDSSDC021'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZSDSSDC021 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZSDSSDC021'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
