"Name: \PR:SAPLV50R_VIEW\EX:LV50R_VIEWF10_04\EI
ENHANCEMENT 0 ZSDS_FILED_TRANSFER.
DATA : LCL_DATA TYPE REF TO ZCL_SDSSD_ENHANCE_REPORT.

IF LCL_DATA IS NOT BOUND.
  CREATE OBJECT LCL_DATA.
ENDIF.
LCL_DATA->VL10E( CHANGING CT_DATA = CT_POSTAB ).
ENDENHANCEMENT.
