*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZSDSV_SO_APPV...................................*
FORM GET_DATA_ZSDSV_SO_APPV.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZSDSSDT009 WHERE
(VIM_WHERETAB) .
    CLEAR ZSDSV_SO_APPV .
ZSDSV_SO_APPV-MANDT =
ZSDSSDT009-MANDT .
ZSDSV_SO_APPV-VBELN =
ZSDSSDT009-VBELN .
ZSDSV_SO_APPV-POSNR =
ZSDSSDT009-POSNR .
ZSDSV_SO_APPV-ETENR =
ZSDSSDT009-ETENR .
ZSDSV_SO_APPV-CO_APPV_STAT =
ZSDSSDT009-CO_APPV_STAT .
ZSDSV_SO_APPV-CO_APPV_BY =
ZSDSSDT009-CO_APPV_BY .
ZSDSV_SO_APPV-CO_APPV_DATE =
ZSDSSDT009-CO_APPV_DATE .
ZSDSV_SO_APPV-CO_APPV_TIME =
ZSDSSDT009-CO_APPV_TIME .
ZSDSV_SO_APPV-MGR_APPV_STAT =
ZSDSSDT009-MGR_APPV_STAT .
ZSDSV_SO_APPV-MGR_APPV_BY =
ZSDSSDT009-MGR_APPV_BY .
ZSDSV_SO_APPV-MGR_APPV_DATE =
ZSDSSDT009-MGR_APPV_DATE .
ZSDSV_SO_APPV-MGR_APPV_TIME =
ZSDSSDT009-MGR_APPV_TIME .
<VIM_TOTAL_STRUC> = ZSDSV_SO_APPV.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZSDSV_SO_APPV .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZSDSV_SO_APPV.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZSDSV_SO_APPV-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZSDSSDT009 WHERE
  VBELN = ZSDSV_SO_APPV-VBELN AND
  POSNR = ZSDSV_SO_APPV-POSNR AND
  ETENR = ZSDSV_SO_APPV-ETENR .
    IF SY-SUBRC = 0.
    DELETE ZSDSSDT009 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZSDSSDT009 WHERE
  VBELN = ZSDSV_SO_APPV-VBELN AND
  POSNR = ZSDSV_SO_APPV-POSNR AND
  ETENR = ZSDSV_SO_APPV-ETENR .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZSDSSDT009.
    ENDIF.
ZSDSSDT009-MANDT =
ZSDSV_SO_APPV-MANDT .
ZSDSSDT009-VBELN =
ZSDSV_SO_APPV-VBELN .
ZSDSSDT009-POSNR =
ZSDSV_SO_APPV-POSNR .
ZSDSSDT009-ETENR =
ZSDSV_SO_APPV-ETENR .
ZSDSSDT009-CO_APPV_STAT =
ZSDSV_SO_APPV-CO_APPV_STAT .
ZSDSSDT009-CO_APPV_BY =
ZSDSV_SO_APPV-CO_APPV_BY .
ZSDSSDT009-CO_APPV_DATE =
ZSDSV_SO_APPV-CO_APPV_DATE .
ZSDSSDT009-CO_APPV_TIME =
ZSDSV_SO_APPV-CO_APPV_TIME .
ZSDSSDT009-MGR_APPV_STAT =
ZSDSV_SO_APPV-MGR_APPV_STAT .
ZSDSSDT009-MGR_APPV_BY =
ZSDSV_SO_APPV-MGR_APPV_BY .
ZSDSSDT009-MGR_APPV_DATE =
ZSDSV_SO_APPV-MGR_APPV_DATE .
ZSDSSDT009-MGR_APPV_TIME =
ZSDSV_SO_APPV-MGR_APPV_TIME .
    IF SY-SUBRC = 0.
    UPDATE ZSDSSDT009 ##WARN_OK.
    ELSE.
    INSERT ZSDSSDT009 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZSDSV_SO_APPV-UPD_FLAG,
STATUS_ZSDSV_SO_APPV-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZSDSV_SO_APPV.
  SELECT SINGLE * FROM ZSDSSDT009 WHERE
VBELN = ZSDSV_SO_APPV-VBELN AND
POSNR = ZSDSV_SO_APPV-POSNR AND
ETENR = ZSDSV_SO_APPV-ETENR .
ZSDSV_SO_APPV-MANDT =
ZSDSSDT009-MANDT .
ZSDSV_SO_APPV-VBELN =
ZSDSSDT009-VBELN .
ZSDSV_SO_APPV-POSNR =
ZSDSSDT009-POSNR .
ZSDSV_SO_APPV-ETENR =
ZSDSSDT009-ETENR .
ZSDSV_SO_APPV-CO_APPV_STAT =
ZSDSSDT009-CO_APPV_STAT .
ZSDSV_SO_APPV-CO_APPV_BY =
ZSDSSDT009-CO_APPV_BY .
ZSDSV_SO_APPV-CO_APPV_DATE =
ZSDSSDT009-CO_APPV_DATE .
ZSDSV_SO_APPV-CO_APPV_TIME =
ZSDSSDT009-CO_APPV_TIME .
ZSDSV_SO_APPV-MGR_APPV_STAT =
ZSDSSDT009-MGR_APPV_STAT .
ZSDSV_SO_APPV-MGR_APPV_BY =
ZSDSSDT009-MGR_APPV_BY .
ZSDSV_SO_APPV-MGR_APPV_DATE =
ZSDSSDT009-MGR_APPV_DATE .
ZSDSV_SO_APPV-MGR_APPV_TIME =
ZSDSSDT009-MGR_APPV_TIME .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZSDSV_SO_APPV USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZSDSV_SO_APPV-VBELN TO
ZSDSSDT009-VBELN .
MOVE ZSDSV_SO_APPV-POSNR TO
ZSDSSDT009-POSNR .
MOVE ZSDSV_SO_APPV-ETENR TO
ZSDSSDT009-ETENR .
MOVE ZSDSV_SO_APPV-MANDT TO
ZSDSSDT009-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZSDSSDT009'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZSDSSDT009 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZSDSSDT009'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
