*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZSDSV_ETAX_CNTYM................................*
FORM GET_DATA_ZSDSV_ETAX_CNTYM.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZSDSSDC020 WHERE
(VIM_WHERETAB) .
    CLEAR ZSDSV_ETAX_CNTYM .
ZSDSV_ETAX_CNTYM-MANDT =
ZSDSSDC020-MANDT .
ZSDSV_ETAX_CNTYM-LAND1 =
ZSDSSDC020-LAND1 .
ZSDSV_ETAX_CNTYM-SCHEMA_ID =
ZSDSSDC020-SCHEMA_ID .
ZSDSV_ETAX_CNTYM-ZDEL_FLG =
ZSDSSDC020-ZDEL_FLG .
ZSDSV_ETAX_CNTYM-ZCRT_DATE =
ZSDSSDC020-ZCRT_DATE .
ZSDSV_ETAX_CNTYM-ZCRT_TIME =
ZSDSSDC020-ZCRT_TIME .
ZSDSV_ETAX_CNTYM-ZCRT_USER =
ZSDSSDC020-ZCRT_USER .
ZSDSV_ETAX_CNTYM-ZCRT_PGM =
ZSDSSDC020-ZCRT_PGM .
ZSDSV_ETAX_CNTYM-ZUPD_DATE =
ZSDSSDC020-ZUPD_DATE .
ZSDSV_ETAX_CNTYM-ZUPD_TIME =
ZSDSSDC020-ZUPD_TIME .
ZSDSV_ETAX_CNTYM-ZUPD_USER =
ZSDSSDC020-ZUPD_USER .
ZSDSV_ETAX_CNTYM-ZUPD_PGM =
ZSDSSDC020-ZUPD_PGM .
<VIM_TOTAL_STRUC> = ZSDSV_ETAX_CNTYM.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZSDSV_ETAX_CNTYM .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZSDSV_ETAX_CNTYM.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZSDSV_ETAX_CNTYM-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZSDSSDC020 WHERE
  LAND1 = ZSDSV_ETAX_CNTYM-LAND1 .
    IF SY-SUBRC = 0.
    DELETE ZSDSSDC020 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZSDSSDC020 WHERE
  LAND1 = ZSDSV_ETAX_CNTYM-LAND1 .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZSDSSDC020.
    ENDIF.
ZSDSSDC020-MANDT =
ZSDSV_ETAX_CNTYM-MANDT .
ZSDSSDC020-LAND1 =
ZSDSV_ETAX_CNTYM-LAND1 .
ZSDSSDC020-SCHEMA_ID =
ZSDSV_ETAX_CNTYM-SCHEMA_ID .
ZSDSSDC020-ZDEL_FLG =
ZSDSV_ETAX_CNTYM-ZDEL_FLG .
ZSDSSDC020-ZCRT_DATE =
ZSDSV_ETAX_CNTYM-ZCRT_DATE .
ZSDSSDC020-ZCRT_TIME =
ZSDSV_ETAX_CNTYM-ZCRT_TIME .
ZSDSSDC020-ZCRT_USER =
ZSDSV_ETAX_CNTYM-ZCRT_USER .
ZSDSSDC020-ZCRT_PGM =
ZSDSV_ETAX_CNTYM-ZCRT_PGM .
ZSDSSDC020-ZUPD_DATE =
ZSDSV_ETAX_CNTYM-ZUPD_DATE .
ZSDSSDC020-ZUPD_TIME =
ZSDSV_ETAX_CNTYM-ZUPD_TIME .
ZSDSSDC020-ZUPD_USER =
ZSDSV_ETAX_CNTYM-ZUPD_USER .
ZSDSSDC020-ZUPD_PGM =
ZSDSV_ETAX_CNTYM-ZUPD_PGM .
    IF SY-SUBRC = 0.
    UPDATE ZSDSSDC020 ##WARN_OK.
    ELSE.
    INSERT ZSDSSDC020 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZSDSV_ETAX_CNTYM-UPD_FLAG,
STATUS_ZSDSV_ETAX_CNTYM-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZSDSV_ETAX_CNTYM.
  SELECT SINGLE * FROM ZSDSSDC020 WHERE
LAND1 = ZSDSV_ETAX_CNTYM-LAND1 .
ZSDSV_ETAX_CNTYM-MANDT =
ZSDSSDC020-MANDT .
ZSDSV_ETAX_CNTYM-LAND1 =
ZSDSSDC020-LAND1 .
ZSDSV_ETAX_CNTYM-SCHEMA_ID =
ZSDSSDC020-SCHEMA_ID .
ZSDSV_ETAX_CNTYM-ZDEL_FLG =
ZSDSSDC020-ZDEL_FLG .
ZSDSV_ETAX_CNTYM-ZCRT_DATE =
ZSDSSDC020-ZCRT_DATE .
ZSDSV_ETAX_CNTYM-ZCRT_TIME =
ZSDSSDC020-ZCRT_TIME .
ZSDSV_ETAX_CNTYM-ZCRT_USER =
ZSDSSDC020-ZCRT_USER .
ZSDSV_ETAX_CNTYM-ZCRT_PGM =
ZSDSSDC020-ZCRT_PGM .
ZSDSV_ETAX_CNTYM-ZUPD_DATE =
ZSDSSDC020-ZUPD_DATE .
ZSDSV_ETAX_CNTYM-ZUPD_TIME =
ZSDSSDC020-ZUPD_TIME .
ZSDSV_ETAX_CNTYM-ZUPD_USER =
ZSDSSDC020-ZUPD_USER .
ZSDSV_ETAX_CNTYM-ZUPD_PGM =
ZSDSSDC020-ZUPD_PGM .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZSDSV_ETAX_CNTYM USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZSDSV_ETAX_CNTYM-LAND1 TO
ZSDSSDC020-LAND1 .
MOVE ZSDSV_ETAX_CNTYM-MANDT TO
ZSDSSDC020-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZSDSSDC020'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZSDSSDC020 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZSDSSDC020'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
