"Name: \PR:SAPMV45A\FO:USEREXIT_CHECK_VBAK\SE:END\EI
ENHANCEMENT 0 ZSDS_SD_SO_USEREXIT1.
* SDS User Exit Implementation
  ZCL_SDSSD_SALESORDER_ENH=>USEREXIT_CHECK_VBAK(
        EXPORTING IS_YVBAK = YVBAK
        CHANGING  CS_XVBAK = VBAK
                  CT_XVBAP = XVBAP[] ).
ENDENHANCEMENT.
