*&---------------------------------------------------------------------*
*& Include          ZSDSSDR0440_TOP
*&---------------------------------------------------------------------*
*-----------------------------------------------------------------------
* T A B L E S
*-----------------------------------------------------------------------
TABLES : VBRK,VBRP,VBPA,VBKD,VBAK.
*-----------------------------------------------------------------------
* T Y P E S
*-----------------------------------------------------------------------
TYPES : BEGIN OF GY_RESULT.
          INCLUDE TYPE ZSDSSDS040.
TYPES :   INS_P    TYPE P DECIMALS 2,
          MIT_P    TYPE P DECIMALS 2,
          SLA_P    TYPE P DECIMALS 2,
          MOD_P    TYPE P DECIMALS 2,
          EXW_P    TYPE P DECIMALS 2,
          STW_P    TYPE P DECIMALS 2,
          TOTFG    TYPE P DECIMALS 2,
          ZZPOB    TYPE VBAK-ZZPOB,
          CHECK    TYPE C,
          BU_GROUP TYPE BUT000-BU_GROUP,
          BU_DESC  TYPE TB002-TXT15,
          CN_INV_REF TYPE VBRK-VBELN,
          INV_TYPE TYPE VBRK-FKART,
          INV_VTEXT TYPE TVFKT-VTEXT,
        END OF GY_RESULT.

TYPES : GTY_DATA    TYPE TABLE OF ZSDSVC_SALES_RESULT WITH EMPTY KEY,
*TYPES : GTY_DATA    TYPE SORTED TABLE OF ZSDSVC_SALES_RESULT WITH UNIQUE KEY VBELN POSNR,
        GTY_ADDRESS TYPE STANDARD TABLE OF ZSDSVC_CUSTOMER_INFO WITH EMPTY KEY,
        GTY_ADVANCE TYPE TABLE OF ZSDSVC_GET_ADVANCE WITH EMPTY KEY.

TYPES:
  BEGIN OF TS_SHIPMENT,
    VBELN    TYPE VBRK-VBELN,
    DO_VBELN TYPE VBAK-VBELN,
    TKNUM    TYPE VTTK-TKNUM,
    VSART    TYPE VTTK-VSART,
    DTDIS    TYPE VTTK-DTDIS,
    ROUTE    TYPE VTTK-ROUTE,
    UZDIS    TYPE VTTK-UZDIS,
    EXTI1    TYPE VTTK-EXTI1,
    EXTI2    TYPE VTTK-EXTI2,
    DATEN    TYPE VTTK-DATEN,
    UATEN    TYPE VTTK-UATEN,
  END OF TS_SHIPMENT .
TYPES:
  TT_SHIPMENT TYPE SORTED TABLE OF TS_SHIPMENT
                         WITH NON-UNIQUE KEY VBELN .

TYPES:
  BEGIN OF GY_KUNAG,
    KUNAG TYPE VBRK-KUNAG,
  END OF GY_KUNAG.
TYPES:
  GTY_KUNAG TYPE HASHED TABLE OF GY_KUNAG
                    WITH UNIQUE KEY KUNAG.

TYPES:
  BEGIN OF GY_INV,
    VBELN TYPE VBRK-VBELN,
  END OF GY_INV.
TYPES:
  GTY_INV TYPE HASHED TABLE OF GY_INV
                    WITH UNIQUE KEY VBELN.

TYPES:
  BEGIN OF GY_DONUM,
    DONUM TYPE LIKP-VBELN,
    VBELN TYPE LIKP-VBELN,
  END OF GY_DONUM.
TYPES:
  GTY_DONUM TYPE HASHED TABLE OF GY_DONUM
                    WITH UNIQUE KEY DONUM VBELN.

TYPES:
  BEGIN OF TS_PRCD_EL_KEY,
    KNUMV TYPE PRCD_ELEMENTS-KNUMV,
    KPOSN TYPE PRCD_ELEMENTS-KPOSN,
  END OF TS_PRCD_EL_KEY .
TYPES:
  TT_PRCD_EL_KEY TYPE HASHED TABLE OF TS_PRCD_EL_KEY
                                   WITH UNIQUE KEY KNUMV KPOSN .

TYPES:
  BEGIN OF TS_PSTYV,
    PSTYV TYPE VBRP-PSTYV,
  END OF TS_PSTYV .
TYPES:
  TT_PSTYV TYPE HASHED TABLE OF TS_PSTYV
                             WITH UNIQUE KEY PSTYV .
TYPES:
  BEGIN OF TS_GENC,
    T_ITEMCAT_BOM        TYPE TT_PSTYV,
    SD_DOCCAT_BILL_RANGE TYPE RANGE OF VBRK-VBTYP,
    SD_DOCCAT_RANGE      TYPE RANGE OF VBAK-VBTYP,
    DISCOUNT_HD_RANGE    TYPE RANGE OF PRCD_ELEMENTS-KSCHL,
    DISCOUNT_CASH_RANGE  TYPE RANGE OF PRCD_ELEMENTS-KSCHL,
    ITEMCAT_BOM_RANGE    TYPE RANGE OF VBRP-PSTYV,
    BILLTYPE_MINUS_RANGE TYPE RANGE OF VBRK-FKART,
  END OF TS_GENC .

TYPES:
  BEGIN OF TS_KNUMV,
    KNUMV TYPE PRCD_ELEMENTS-KNUMV,
  END OF TS_KNUMV .
TYPES:
  TT_KNUMV TYPE HASHED TABLE OF TS_KNUMV
                             WITH UNIQUE KEY KNUMV .

TYPES:
  BEGIN OF TS_DISCOUNT,
    KNUMV     TYPE PRCD_ELEMENTS-KNUMV,
    SUM_KWERT TYPE VFPRC_ELEMENT_AMOUNT,
  END OF TS_DISCOUNT .
TYPES:
  TT_DISCOUNT TYPE SORTED TABLE OF TS_DISCOUNT
                              WITH NON-UNIQUE KEY KNUMV .

TYPES:
  BEGIN OF TS_OBJECT_ID,
    OBJECT_ID TYPE CRMS4D_SERV_H-OBJECT_ID,
  END OF TS_OBJECT_ID .
TYPES:
  TT_OBJECT_ID TYPE HASHED TABLE OF TS_OBJECT_ID
                                 WITH UNIQUE KEY OBJECT_ID .

TYPES:
  BEGIN OF TS_PERNR,
    PERNR TYPE PA0002-PERNR,
  END OF TS_PERNR .
TYPES:
  TT_PERNR TYPE HASHED TABLE OF TS_PERNR
                              WITH UNIQUE KEY PERNR .

TYPES:
  BEGIN OF TS_VBELN,
    VBELN TYPE VBAK-VBELN,
  END OF TS_VBELN .
TYPES:
  TT_VBELN TYPE HASHED TABLE OF TS_VBELN
                             WITH UNIQUE KEY VBELN .

TYPES:
  BEGIN OF TS_BILL_BOM_ITEM,
    VBELN TYPE VBRP-VBELN,
    UEPOS TYPE VBRP-UEPOS,
    POSNR TYPE VBRP-POSNR,
    NETWR TYPE VBRP-NETWR,
    MWSBP TYPE VBRP-MWSBP,
    KNUMV TYPE VBRK-KNUMV,
  END OF TS_BILL_BOM_ITEM .
TYPES:
  TT_BILL_BOM_ITEM TYPE STANDARD TABLE OF TS_BILL_BOM_ITEM
                                     WITH EMPTY KEY .

TYPES:
  BEGIN OF TS_KOWRR,
    KOWRR TYPE VBRP-KOWRR,
  END OF TS_KOWRR .
TYPES:
  TT_KOWRR TYPE HASHED TABLE OF TS_KOWRR
                             WITH UNIQUE KEY KOWRR .

TYPES:
  BEGIN OF TS_CAL_PRICE,
    KNUMV TYPE PRCD_ELEMENTS-KNUMV,
    KPOSN TYPE PRCD_ELEMENTS-KPOSN,
    KSCHL TYPE PRCD_ELEMENTS-KSCHL,
    KWERT TYPE PRCD_ELEMENTS-KWERT,
  END OF TS_CAL_PRICE.
TYPES:
  TT_CAL_PRICE TYPE TABLE OF TS_CAL_PRICE WITH EMPTY KEY.

TYPES: BEGIN OF GY_VBFA,
    VBELV   TYPE VBFA-VBELV,
    POSNV   TYPE VBFA-POSNV,
    VBELN   TYPE VBFA-VBELN,
    POSNN   TYPE VBFA-POSNN,
    VBTYP_N TYPE VBFA-VBTYP_N,
    VBTYP_V TYPE VBFA-VBTYP_V,
  END OF GY_VBFA.
TYPES: BEGIN OF GY_TVFKT,
   FKART   TYPE TVFKT-FKART,
   VTEXT   TYPE TVFKT-VTEXT,
  END OF GY_TVFKT.

TYPES: BEGIN OF GY_INVREF,
   VBELN TYPE VBRK-VBELN,
   FKART TYPE VBRK-FKART,
   VBTYP TYPE VBRK-VBTYP,
  END OF GY_INVREF.
*-----------------------------------------------------------------------
* D A T A
*-----------------------------------------------------------------------
DATA : GT_RESULT TYPE TABLE OF GY_RESULT,
       GS_RESULT TYPE GY_RESULT.

DATA : GV_COST TYPE C.

DATA : BDCDATA LIKE BDCDATA OCCURS 0 WITH HEADER LINE.

DATA : MESSTAB   LIKE BDCMSGCOLL OCCURS 0 WITH HEADER LINE,
       T_MESSTAB LIKE BDCMSGCOLL OCCURS 0 WITH HEADER LINE,
       S_MESSTAB LIKE BDCMSGCOLL.

DATA : DYNPFIELDS  LIKE DYNPREAD OCCURS 5 WITH HEADER LINE.

DATA : GT_FCAT   TYPE SLIS_T_FIELDCAT_ALV,
       GS_LAYOUT TYPE SLIS_LAYOUT_ALV,
       GT_SORT   TYPE SLIS_T_SORTINFO_ALV,
       GS_SORT   TYPE SLIS_SORTINFO_ALV.

DATA: GT_VBFA_QT TYPE STANDARD TABLE OF  GY_VBFA,
      GS_VBFA_QT TYPE GY_VBFA,
      GT_VBFA_INV TYPE STANDARD TABLE OF  GY_VBFA,
      GS_VBFA_INV TYPE GY_VBFA,
      GT_TVFKT TYPE STANDARD TABLE OF GY_TVFKT,
      GS_TVFKT TYPE GY_TVFKT,
      GT_INVREF TYPE STANDARD TABLE OF GY_INVREF,
      GS_INVREF TYPE GY_INVREF.


*-----------------------------------------------------------------------
* C O N S T A N T S
*-----------------------------------------------------------------------
CONSTANTS: GC_I  TYPE C LENGTH 1 VALUE 'I',
           GC_EQ TYPE C LENGTH 2 VALUE 'EQ',
           GC_S  TYPE C LENGTH 1 VALUE 'S',
           GC_E  TYPE C LENGTH 1 VALUE 'E',
           GC_X  TYPE C LENGTH 1 VALUE 'X',
           GC_A  TYPE C LENGTH 1 VALUE 'A',
           GC_L  TYPE C LENGTH 1 VALUE 'L'.

CONSTANTS:
  GC_STRUCTURE_1 TYPE TABNAME VALUE 'ZSDSSDS040',
  GC_TRUE        TYPE C       VALUE 'X'.

CONSTANTS:
  BEGIN OF GC_TDID,
    REASON     TYPE THEAD-TDID VALUE 'ZH01',
    REMARK_QT  TYPE THEAD-TDID VALUE 'ZH02',
    PROJECT_TX TYPE THEAD-TDID VALUE 'ZH06',
    INV_REMARK TYPE THEAD-TDID VALUE 'ZH13',
    REQ_REMARK TYPE THEAD-TDID VALUE 'ZH10',
    LAND_NO    TYPE THEAD-TDID VALUE 'ZH11',
    REF_MEMO   TYPE THEAD-TDID VALUE 'ZH17',
  END OF GC_TDID .

CONSTANTS:
  BEGIN OF GC_TDOBJECT,
    VBBK TYPE  STXH-TDOBJECT  VALUE 'VBBK',
  END OF GC_TDOBJECT .

CONSTANTS:
  BEGIN OF GC_VBTYP,
    SALE_ORDER      TYPE VBAK-VBTYP VALUE 'C',
    SHIP_TO         TYPE VBAK-VBTYP VALUE '8',
    DELIVERY        TYPE VBAK-VBTYP VALUE 'J',
    QUOTATION       TYPE VBAK-VBTYP VALUE 'B',
    CREDIT_MEMO_REQ TYPE VBAK-VBTYP VALUE 'K',
    DEBIT_MEMO_REQ  TYPE VBAK-VBTYP VALUE 'L',
    RETURN          TYPE VBAK-VBTYP VALUE 'H',
  END OF GC_VBTYP .

CONSTANTS:
  BEGIN OF GC_SEPARATE,
    COMMA TYPE CHAR01 VALUE ',',
  END OF GC_SEPARATE .

CONSTANTS GC_REPID TYPE SY-REPID  VALUE 'ZSDSSDR0190'.

CONSTANTS:
  BEGIN OF GC_AC_OBJECT_TYPE,
    INT_ORDER TYPE CRMS4D_SERV_H-AC_OBJECT_TYPE VALUE '01',
    WBS       TYPE CRMS4D_SERV_H-AC_OBJECT_TYPE VALUE '03',
  END OF GC_AC_OBJECT_TYPE .

CONSTANTS GC_INBOX_STATUS_COMPLETE TYPE CRMS4D_SERV_H-INBOX_STATUS VALUE '0003' ##NO_TEXT.

CONSTANTS : GC_SALE_COUNT_FLAG_0 TYPE MARA-ZZSCF VALUE '0',
            GC_PRODH2_CDU        TYPE PRODH3     VALUE 'CDU'.

CONSTANTS : BEGIN OF GC_CAL_PRICE,
              ZPS1 TYPE C LENGTH 4 VALUE 'ZPS1',
              ZPS2 TYPE C LENGTH 4 VALUE 'ZPS2',
              ZPS3 TYPE C LENGTH 4 VALUE 'ZPS3',
              ZPS4 TYPE C LENGTH 4 VALUE 'ZPS4',
              ZWR3 TYPE C LENGTH 4 VALUE 'ZWR3',
              ZWR1 TYPE C LENGTH 4 VALUE 'ZWR1',
            END OF GC_CAL_PRICE.

CONSTANTS:
  BEGIN OF GC_PARVW,
    PAYER         TYPE VBPA-PARVW VALUE 'RG',
    SHIP_TO       TYPE VBPA-PARVW VALUE 'WE',
    SALE_EMPLOYEE TYPE VBPA-PARVW VALUE 'VE',
    EMPLOYEE_RESP TYPE VBPA-PARVW VALUE 'ZM',
  END OF GC_PARVW .
*-----------------------------------------------------------------------
* R A N G E S
*-----------------------------------------------------------------------
*DATA:
*-----------------------------------------------------------------------
* M A C R O S
*-----------------------------------------------------------------------
*DEFINE.
*END-OF-DEFINITION.

*-----------------------------------------------------------------------
* F I E L D – S Y M B O L S
*-----------------------------------------------------------------------
*FIELD-SYMBOLS:

*-----------------------------------------------------------------------
* F I E L D – G R O U P S
*-----------------------------------------------------------------------
*FIELD-GROUPS:
