*&---------------------------------------------------------------------*
*& Include          ZSDSSDR0260_CLASS
*&---------------------------------------------------------------------*
CLASS LCL_DATA DEFINITION.
  PUBLIC SECTION.
    METHODS :
      CONSTRUCTOR.

    CLASS-METHODS :
      GET_QUOTA_GROUP RETURNING VALUE(R) TYPE TT_QUOTA_GROUP,
      SET_EMPTY_QUOTA IMPORTING I_DATA TYPE TT_ZSDSSDT018.
ENDCLASS.
CLASS LCL_DATA IMPLEMENTATION.
  METHOD CONSTRUCTOR.

  ENDMETHOD.
  METHOD GET_QUOTA_GROUP.
    SELECT DISTINCT QUOTAGRP
      FROM ZSDSSDC013
      INTO TABLE R.
  ENDMETHOD.
  METHOD SET_EMPTY_QUOTA.
    DATA : LS_DATA LIKE LINE OF I_DATA.

    DATA : LT_ZSDSSDT018 TYPE TABLE OF ZSDSSDT018.
*           LS_ZSDSSDT018 TYPE ZSDSSDT018.

    DATA(LT_GROUP) = LCL_DATA=>GET_QUOTA_GROUP( ).

    LOOP AT I_DATA INTO DATA(LS_DATA_TMP).
      MOVE-CORRESPONDING LS_DATA_TMP TO LS_DATA.
      READ TABLE LT_GROUP ASSIGNING FIELD-SYMBOL(<LFS_GROUP>)
      WITH KEY QUOTAGRP = LS_DATA-QUOTAGRP.
      IF SY-SUBRC EQ 0.
        <LFS_GROUP>-FLAG = ABAP_TRUE.
      ELSE.
        <LFS_GROUP>-FLAG = ABAP_FALSE.
      ENDIF.

      AT END OF MATNR.
        LOOP AT LT_GROUP INTO DATA(LS_GROUP) WHERE FLAG EQ SPACE.
          LS_DATA-PORTION_PERC = 0.
          LS_DATA-PORTION_QTY  = 0.
          LS_DATA-QUOTAGRP     = LS_GROUP-QUOTAGRP.
          APPEND LS_DATA TO LT_ZSDSSDT018.
        ENDLOOP.
        LS_GROUP-FLAG = ABAP_FALSE.
        MODIFY LT_GROUP FROM LS_GROUP TRANSPORTING FLAG
                                      WHERE FLAG EQ ABAP_TRUE.

      ENDAT.
    ENDLOOP.

    IF LT_ZSDSSDT018 IS NOT INITIAL.
      MODIFY ZSDSSDT018 FROM TABLE LT_ZSDSSDT018.
    ENDIF.

  ENDMETHOD.
ENDCLASS.
