*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZSDSV_SO_PRCTR..................................*
FORM GET_DATA_ZSDSV_SO_PRCTR.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZSDSSDC001 WHERE
(VIM_WHERETAB) .
    CLEAR ZSDSV_SO_PRCTR .
ZSDSV_SO_PRCTR-MANDT =
ZSDSSDC001-MANDT .
ZSDSV_SO_PRCTR-VKORG =
ZSDSSDC001-VKORG .
ZSDSV_SO_PRCTR-AUART =
ZSDSSDC001-AUART .
ZSDSV_SO_PRCTR-VKBUR =
ZSDSSDC001-VKBUR .
ZSDSV_SO_PRCTR-VKGRP =
ZSDSSDC001-VKGRP .
ZSDSV_SO_PRCTR-PRCTR =
ZSDSSDC001-PRCTR .
ZSDSV_SO_PRCTR-ZDEL_FLG =
ZSDSSDC001-ZDEL_FLG .
ZSDSV_SO_PRCTR-ZCRT_DATE =
ZSDSSDC001-ZCRT_DATE .
ZSDSV_SO_PRCTR-ZCRT_TIME =
ZSDSSDC001-ZCRT_TIME .
ZSDSV_SO_PRCTR-ZCRT_USER =
ZSDSSDC001-ZCRT_USER .
ZSDSV_SO_PRCTR-ZCRT_PGM =
ZSDSSDC001-ZCRT_PGM .
ZSDSV_SO_PRCTR-ZUPD_DATE =
ZSDSSDC001-ZUPD_DATE .
ZSDSV_SO_PRCTR-ZUPD_TIME =
ZSDSSDC001-ZUPD_TIME .
ZSDSV_SO_PRCTR-ZUPD_USER =
ZSDSSDC001-ZUPD_USER .
ZSDSV_SO_PRCTR-ZUPD_PGM =
ZSDSSDC001-ZUPD_PGM .
<VIM_TOTAL_STRUC> = ZSDSV_SO_PRCTR.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZSDSV_SO_PRCTR .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZSDSV_SO_PRCTR.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZSDSV_SO_PRCTR-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZSDSSDC001 WHERE
  VKORG = ZSDSV_SO_PRCTR-VKORG AND
  AUART = ZSDSV_SO_PRCTR-AUART AND
  VKBUR = ZSDSV_SO_PRCTR-VKBUR AND
  VKGRP = ZSDSV_SO_PRCTR-VKGRP .
    IF SY-SUBRC = 0.
    DELETE ZSDSSDC001 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZSDSSDC001 WHERE
  VKORG = ZSDSV_SO_PRCTR-VKORG AND
  AUART = ZSDSV_SO_PRCTR-AUART AND
  VKBUR = ZSDSV_SO_PRCTR-VKBUR AND
  VKGRP = ZSDSV_SO_PRCTR-VKGRP .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZSDSSDC001.
    ENDIF.
ZSDSSDC001-MANDT =
ZSDSV_SO_PRCTR-MANDT .
ZSDSSDC001-VKORG =
ZSDSV_SO_PRCTR-VKORG .
ZSDSSDC001-AUART =
ZSDSV_SO_PRCTR-AUART .
ZSDSSDC001-VKBUR =
ZSDSV_SO_PRCTR-VKBUR .
ZSDSSDC001-VKGRP =
ZSDSV_SO_PRCTR-VKGRP .
ZSDSSDC001-PRCTR =
ZSDSV_SO_PRCTR-PRCTR .
ZSDSSDC001-ZDEL_FLG =
ZSDSV_SO_PRCTR-ZDEL_FLG .
ZSDSSDC001-ZCRT_DATE =
ZSDSV_SO_PRCTR-ZCRT_DATE .
ZSDSSDC001-ZCRT_TIME =
ZSDSV_SO_PRCTR-ZCRT_TIME .
ZSDSSDC001-ZCRT_USER =
ZSDSV_SO_PRCTR-ZCRT_USER .
ZSDSSDC001-ZCRT_PGM =
ZSDSV_SO_PRCTR-ZCRT_PGM .
ZSDSSDC001-ZUPD_DATE =
ZSDSV_SO_PRCTR-ZUPD_DATE .
ZSDSSDC001-ZUPD_TIME =
ZSDSV_SO_PRCTR-ZUPD_TIME .
ZSDSSDC001-ZUPD_USER =
ZSDSV_SO_PRCTR-ZUPD_USER .
ZSDSSDC001-ZUPD_PGM =
ZSDSV_SO_PRCTR-ZUPD_PGM .
    IF SY-SUBRC = 0.
    UPDATE ZSDSSDC001 ##WARN_OK.
    ELSE.
    INSERT ZSDSSDC001 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZSDSV_SO_PRCTR-UPD_FLAG,
STATUS_ZSDSV_SO_PRCTR-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZSDSV_SO_PRCTR.
  SELECT SINGLE * FROM ZSDSSDC001 WHERE
VKORG = ZSDSV_SO_PRCTR-VKORG AND
AUART = ZSDSV_SO_PRCTR-AUART AND
VKBUR = ZSDSV_SO_PRCTR-VKBUR AND
VKGRP = ZSDSV_SO_PRCTR-VKGRP .
ZSDSV_SO_PRCTR-MANDT =
ZSDSSDC001-MANDT .
ZSDSV_SO_PRCTR-VKORG =
ZSDSSDC001-VKORG .
ZSDSV_SO_PRCTR-AUART =
ZSDSSDC001-AUART .
ZSDSV_SO_PRCTR-VKBUR =
ZSDSSDC001-VKBUR .
ZSDSV_SO_PRCTR-VKGRP =
ZSDSSDC001-VKGRP .
ZSDSV_SO_PRCTR-PRCTR =
ZSDSSDC001-PRCTR .
ZSDSV_SO_PRCTR-ZDEL_FLG =
ZSDSSDC001-ZDEL_FLG .
ZSDSV_SO_PRCTR-ZCRT_DATE =
ZSDSSDC001-ZCRT_DATE .
ZSDSV_SO_PRCTR-ZCRT_TIME =
ZSDSSDC001-ZCRT_TIME .
ZSDSV_SO_PRCTR-ZCRT_USER =
ZSDSSDC001-ZCRT_USER .
ZSDSV_SO_PRCTR-ZCRT_PGM =
ZSDSSDC001-ZCRT_PGM .
ZSDSV_SO_PRCTR-ZUPD_DATE =
ZSDSSDC001-ZUPD_DATE .
ZSDSV_SO_PRCTR-ZUPD_TIME =
ZSDSSDC001-ZUPD_TIME .
ZSDSV_SO_PRCTR-ZUPD_USER =
ZSDSSDC001-ZUPD_USER .
ZSDSV_SO_PRCTR-ZUPD_PGM =
ZSDSSDC001-ZUPD_PGM .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZSDSV_SO_PRCTR USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZSDSV_SO_PRCTR-VKORG TO
ZSDSSDC001-VKORG .
MOVE ZSDSV_SO_PRCTR-AUART TO
ZSDSSDC001-AUART .
MOVE ZSDSV_SO_PRCTR-VKBUR TO
ZSDSSDC001-VKBUR .
MOVE ZSDSV_SO_PRCTR-VKGRP TO
ZSDSSDC001-VKGRP .
MOVE ZSDSV_SO_PRCTR-MANDT TO
ZSDSSDC001-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZSDSSDC001'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZSDSSDC001 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZSDSSDC001'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
