*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZSDSV_ETAX_POSTM................................*
FORM GET_DATA_ZSDSV_ETAX_POSTM.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZSDSSDC025 WHERE
(VIM_WHERETAB) .
    CLEAR ZSDSV_ETAX_POSTM .
ZSDSV_ETAX_POSTM-MANDT =
ZSDSSDC025-MANDT .
ZSDSV_ETAX_POSTM-POSTAL_FROM =
ZSDSSDC025-POSTAL_FROM .
ZSDSV_ETAX_POSTM-POSTAL_TO =
ZSDSSDC025-POSTAL_TO .
ZSDSV_ETAX_POSTM-PROVINCE_CD =
ZSDSSDC025-PROVINCE_CD .
ZSDSV_ETAX_POSTM-ZDEL_FLG =
ZSDSSDC025-ZDEL_FLG .
ZSDSV_ETAX_POSTM-ZCRT_DATE =
ZSDSSDC025-ZCRT_DATE .
ZSDSV_ETAX_POSTM-ZCRT_TIME =
ZSDSSDC025-ZCRT_TIME .
ZSDSV_ETAX_POSTM-ZCRT_USER =
ZSDSSDC025-ZCRT_USER .
ZSDSV_ETAX_POSTM-ZCRT_PGM =
ZSDSSDC025-ZCRT_PGM .
ZSDSV_ETAX_POSTM-ZUPD_DATE =
ZSDSSDC025-ZUPD_DATE .
ZSDSV_ETAX_POSTM-ZUPD_TIME =
ZSDSSDC025-ZUPD_TIME .
ZSDSV_ETAX_POSTM-ZUPD_USER =
ZSDSSDC025-ZUPD_USER .
ZSDSV_ETAX_POSTM-ZUPD_PGM =
ZSDSSDC025-ZUPD_PGM .
<VIM_TOTAL_STRUC> = ZSDSV_ETAX_POSTM.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZSDSV_ETAX_POSTM .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZSDSV_ETAX_POSTM.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZSDSV_ETAX_POSTM-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZSDSSDC025 WHERE
  POSTAL_FROM = ZSDSV_ETAX_POSTM-POSTAL_FROM AND
  POSTAL_TO = ZSDSV_ETAX_POSTM-POSTAL_TO .
    IF SY-SUBRC = 0.
    DELETE ZSDSSDC025 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZSDSSDC025 WHERE
  POSTAL_FROM = ZSDSV_ETAX_POSTM-POSTAL_FROM AND
  POSTAL_TO = ZSDSV_ETAX_POSTM-POSTAL_TO .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZSDSSDC025.
    ENDIF.
ZSDSSDC025-MANDT =
ZSDSV_ETAX_POSTM-MANDT .
ZSDSSDC025-POSTAL_FROM =
ZSDSV_ETAX_POSTM-POSTAL_FROM .
ZSDSSDC025-POSTAL_TO =
ZSDSV_ETAX_POSTM-POSTAL_TO .
ZSDSSDC025-PROVINCE_CD =
ZSDSV_ETAX_POSTM-PROVINCE_CD .
ZSDSSDC025-ZDEL_FLG =
ZSDSV_ETAX_POSTM-ZDEL_FLG .
ZSDSSDC025-ZCRT_DATE =
ZSDSV_ETAX_POSTM-ZCRT_DATE .
ZSDSSDC025-ZCRT_TIME =
ZSDSV_ETAX_POSTM-ZCRT_TIME .
ZSDSSDC025-ZCRT_USER =
ZSDSV_ETAX_POSTM-ZCRT_USER .
ZSDSSDC025-ZCRT_PGM =
ZSDSV_ETAX_POSTM-ZCRT_PGM .
ZSDSSDC025-ZUPD_DATE =
ZSDSV_ETAX_POSTM-ZUPD_DATE .
ZSDSSDC025-ZUPD_TIME =
ZSDSV_ETAX_POSTM-ZUPD_TIME .
ZSDSSDC025-ZUPD_USER =
ZSDSV_ETAX_POSTM-ZUPD_USER .
ZSDSSDC025-ZUPD_PGM =
ZSDSV_ETAX_POSTM-ZUPD_PGM .
    IF SY-SUBRC = 0.
    UPDATE ZSDSSDC025 ##WARN_OK.
    ELSE.
    INSERT ZSDSSDC025 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZSDSV_ETAX_POSTM-UPD_FLAG,
STATUS_ZSDSV_ETAX_POSTM-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZSDSV_ETAX_POSTM.
  SELECT SINGLE * FROM ZSDSSDC025 WHERE
POSTAL_FROM = ZSDSV_ETAX_POSTM-POSTAL_FROM AND
POSTAL_TO = ZSDSV_ETAX_POSTM-POSTAL_TO .
ZSDSV_ETAX_POSTM-MANDT =
ZSDSSDC025-MANDT .
ZSDSV_ETAX_POSTM-POSTAL_FROM =
ZSDSSDC025-POSTAL_FROM .
ZSDSV_ETAX_POSTM-POSTAL_TO =
ZSDSSDC025-POSTAL_TO .
ZSDSV_ETAX_POSTM-PROVINCE_CD =
ZSDSSDC025-PROVINCE_CD .
ZSDSV_ETAX_POSTM-ZDEL_FLG =
ZSDSSDC025-ZDEL_FLG .
ZSDSV_ETAX_POSTM-ZCRT_DATE =
ZSDSSDC025-ZCRT_DATE .
ZSDSV_ETAX_POSTM-ZCRT_TIME =
ZSDSSDC025-ZCRT_TIME .
ZSDSV_ETAX_POSTM-ZCRT_USER =
ZSDSSDC025-ZCRT_USER .
ZSDSV_ETAX_POSTM-ZCRT_PGM =
ZSDSSDC025-ZCRT_PGM .
ZSDSV_ETAX_POSTM-ZUPD_DATE =
ZSDSSDC025-ZUPD_DATE .
ZSDSV_ETAX_POSTM-ZUPD_TIME =
ZSDSSDC025-ZUPD_TIME .
ZSDSV_ETAX_POSTM-ZUPD_USER =
ZSDSSDC025-ZUPD_USER .
ZSDSV_ETAX_POSTM-ZUPD_PGM =
ZSDSSDC025-ZUPD_PGM .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZSDSV_ETAX_POSTM USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZSDSV_ETAX_POSTM-POSTAL_FROM TO
ZSDSSDC025-POSTAL_FROM .
MOVE ZSDSV_ETAX_POSTM-POSTAL_TO TO
ZSDSSDC025-POSTAL_TO .
MOVE ZSDSV_ETAX_POSTM-MANDT TO
ZSDSSDC025-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZSDSSDC025'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZSDSSDC025 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZSDSSDC025'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
