*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZSDSV_ETAX_DTYM2................................*
FORM GET_DATA_ZSDSV_ETAX_DTYM2.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZSDSSDC026 WHERE
(VIM_WHERETAB) .
    CLEAR ZSDSV_ETAX_DTYM2 .
ZSDSV_ETAX_DTYM2-MANDT =
ZSDSSDC026-MANDT .
ZSDSV_ETAX_DTYM2-BLART =
ZSDSSDC026-BLART .
ZSDSV_ETAX_DTYM2-MWSKZ =
ZSDSSDC026-MWSKZ .
ZSDSV_ETAX_DTYM2-DOCTY =
ZSDSSDC026-DOCTY .
ZSDSV_ETAX_DTYM2-ZDEL_FLG =
ZSDSSDC026-ZDEL_FLG .
ZSDSV_ETAX_DTYM2-ZCRT_DATE =
ZSDSSDC026-ZCRT_DATE .
ZSDSV_ETAX_DTYM2-ZCRT_TIME =
ZSDSSDC026-ZCRT_TIME .
ZSDSV_ETAX_DTYM2-ZCRT_USER =
ZSDSSDC026-ZCRT_USER .
ZSDSV_ETAX_DTYM2-ZCRT_PGM =
ZSDSSDC026-ZCRT_PGM .
ZSDSV_ETAX_DTYM2-ZUPD_DATE =
ZSDSSDC026-ZUPD_DATE .
ZSDSV_ETAX_DTYM2-ZUPD_TIME =
ZSDSSDC026-ZUPD_TIME .
ZSDSV_ETAX_DTYM2-ZUPD_USER =
ZSDSSDC026-ZUPD_USER .
ZSDSV_ETAX_DTYM2-ZUPD_PGM =
ZSDSSDC026-ZUPD_PGM .
<VIM_TOTAL_STRUC> = ZSDSV_ETAX_DTYM2.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZSDSV_ETAX_DTYM2 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZSDSV_ETAX_DTYM2.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZSDSV_ETAX_DTYM2-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZSDSSDC026 WHERE
  BLART = ZSDSV_ETAX_DTYM2-BLART AND
  MWSKZ = ZSDSV_ETAX_DTYM2-MWSKZ .
    IF SY-SUBRC = 0.
    DELETE ZSDSSDC026 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZSDSSDC026 WHERE
  BLART = ZSDSV_ETAX_DTYM2-BLART AND
  MWSKZ = ZSDSV_ETAX_DTYM2-MWSKZ .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZSDSSDC026.
    ENDIF.
ZSDSSDC026-MANDT =
ZSDSV_ETAX_DTYM2-MANDT .
ZSDSSDC026-BLART =
ZSDSV_ETAX_DTYM2-BLART .
ZSDSSDC026-MWSKZ =
ZSDSV_ETAX_DTYM2-MWSKZ .
ZSDSSDC026-DOCTY =
ZSDSV_ETAX_DTYM2-DOCTY .
ZSDSSDC026-ZDEL_FLG =
ZSDSV_ETAX_DTYM2-ZDEL_FLG .
ZSDSSDC026-ZCRT_DATE =
ZSDSV_ETAX_DTYM2-ZCRT_DATE .
ZSDSSDC026-ZCRT_TIME =
ZSDSV_ETAX_DTYM2-ZCRT_TIME .
ZSDSSDC026-ZCRT_USER =
ZSDSV_ETAX_DTYM2-ZCRT_USER .
ZSDSSDC026-ZCRT_PGM =
ZSDSV_ETAX_DTYM2-ZCRT_PGM .
ZSDSSDC026-ZUPD_DATE =
ZSDSV_ETAX_DTYM2-ZUPD_DATE .
ZSDSSDC026-ZUPD_TIME =
ZSDSV_ETAX_DTYM2-ZUPD_TIME .
ZSDSSDC026-ZUPD_USER =
ZSDSV_ETAX_DTYM2-ZUPD_USER .
ZSDSSDC026-ZUPD_PGM =
ZSDSV_ETAX_DTYM2-ZUPD_PGM .
    IF SY-SUBRC = 0.
    UPDATE ZSDSSDC026 ##WARN_OK.
    ELSE.
    INSERT ZSDSSDC026 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZSDSV_ETAX_DTYM2-UPD_FLAG,
STATUS_ZSDSV_ETAX_DTYM2-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZSDSV_ETAX_DTYM2.
  SELECT SINGLE * FROM ZSDSSDC026 WHERE
BLART = ZSDSV_ETAX_DTYM2-BLART AND
MWSKZ = ZSDSV_ETAX_DTYM2-MWSKZ .
ZSDSV_ETAX_DTYM2-MANDT =
ZSDSSDC026-MANDT .
ZSDSV_ETAX_DTYM2-BLART =
ZSDSSDC026-BLART .
ZSDSV_ETAX_DTYM2-MWSKZ =
ZSDSSDC026-MWSKZ .
ZSDSV_ETAX_DTYM2-DOCTY =
ZSDSSDC026-DOCTY .
ZSDSV_ETAX_DTYM2-ZDEL_FLG =
ZSDSSDC026-ZDEL_FLG .
ZSDSV_ETAX_DTYM2-ZCRT_DATE =
ZSDSSDC026-ZCRT_DATE .
ZSDSV_ETAX_DTYM2-ZCRT_TIME =
ZSDSSDC026-ZCRT_TIME .
ZSDSV_ETAX_DTYM2-ZCRT_USER =
ZSDSSDC026-ZCRT_USER .
ZSDSV_ETAX_DTYM2-ZCRT_PGM =
ZSDSSDC026-ZCRT_PGM .
ZSDSV_ETAX_DTYM2-ZUPD_DATE =
ZSDSSDC026-ZUPD_DATE .
ZSDSV_ETAX_DTYM2-ZUPD_TIME =
ZSDSSDC026-ZUPD_TIME .
ZSDSV_ETAX_DTYM2-ZUPD_USER =
ZSDSSDC026-ZUPD_USER .
ZSDSV_ETAX_DTYM2-ZUPD_PGM =
ZSDSSDC026-ZUPD_PGM .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZSDSV_ETAX_DTYM2 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZSDSV_ETAX_DTYM2-BLART TO
ZSDSSDC026-BLART .
MOVE ZSDSV_ETAX_DTYM2-MWSKZ TO
ZSDSSDC026-MWSKZ .
MOVE ZSDSV_ETAX_DTYM2-MANDT TO
ZSDSSDC026-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZSDSSDC026'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZSDSSDC026 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZSDSSDC026'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
