*&---------------------------------------------------------------------*
*& Include          ZSDSSDR0090_SELECTION
*&---------------------------------------------------------------------*
*-----------------------------------------------------------------------
* P A R A M E T E R S   &   S E L E C T - O P T I O N S
*-----------------------------------------------------------------------
SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-H01.

  PARAMETERS : P_BUKRS TYPE BUKRS OBLIGATORY DEFAULT '1000'.

  SELECT-OPTIONS : S_VBELN FOR VBAP-VBELN OBLIGATORY,
                   S_POSNR FOR VBAP-POSNR,
                   S_EDATU FOR VBEP-EDATU OBLIGATORY.

SELECTION-SCREEN END OF BLOCK B1.

SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME TITLE TEXT-H02.
  PARAMETERS : R_BLOC RADIOBUTTON GROUP TYP,
               R_ALL  RADIOBUTTON GROUP TYP DEFAULT 'X'.
SELECTION-SCREEN END OF BLOCK B2.

SELECTION-SCREEN BEGIN OF BLOCK B3 WITH FRAME TITLE TEXT-H03.
  PARAMETERS : P_LANGU TYPE  SYLANGU DEFAULT 'E'.   "Print Language
SELECTION-SCREEN END OF BLOCK B3.

*SELECTION-SCREEN BEGIN OF BLOCK b4 WITH FRAME TITLE TEXT-h04.
*  PARAMETERS: r_header RADIOBUTTON GROUP opt DEFAULT 'X' MODIF ID mo1,
*              r_detail RADIOBUTTON GROUP opt MODIF ID mo1.
*
*
*SELECTION-SCREEN END OF BLOCK b4.
*
*SELECTION-SCREEN BEGIN OF BLOCK b5 WITH FRAME TITLE TEXT-h05.
*  SELECT-OPTIONS s_matnr FOR vbap-matnr NO INTERVALS.
*
*
*SELECTION-SCREEN END OF BLOCK b5.

*PARAMETERS : P_RESE AS CHECKBOX DEFAULT 'X'.

*PARAMETERS: r1 RADIOBUTTON GROUP log DEFAULT 'X' MODIF ID mod,
*            r2 RADIOBUTTON GROUP log MODIF ID mod,
*            r3 RADIOBUTTON GROUP log MODIF ID mod.
