*&---------------------------------------------------------------------*
*& Include          ZSDSSDR0230_TOP
*&---------------------------------------------------------------------*
*----------------------------------------------------------------------*
* TABLES
*----------------------------------------------------------------------*
TABLES:
  VBAK,
  VBAP,
  VBEP,
  VBKD,
  VBPA.
*----------------------------------------------------------------------*
* TYPES
*----------------------------------------------------------------------*
TYPES:
  BEGIN OF TS_SO,
    VBELN_MAIN     TYPE VBAK-VBELN,
    VBELN          TYPE VBAK-VBELN,
    POSNR          TYPE VBAP-POSNR,
    ETENR          TYPE VBEP-ETENR,
    VBTYP          TYPE VBAK-VBTYP,
    AUART          TYPE VBAK-AUART,
    VKORG          TYPE VBAK-VKORG,
    AUDAT          TYPE VBAK-AUDAT,
    KVGR1          TYPE VBAK-KVGR1,
    KVGR2          TYPE VBAK-KVGR2,
    AUGRU          TYPE VBAK-AUGRU,
    ERNAM          TYPE VBAK-ERNAM,
    BNAME          TYPE VBAK-BNAME,
    FKSAK          TYPE VBAK-FKSAK,
    LFSTK          TYPE VBAK-LFSTK,
    SPSTG          TYPE VBAK-SPSTG,
    GBSTK          TYPE VBAK-GBSTK,
    CMGST          TYPE VBAK-CMGST,
    ABSTK          TYPE VBAK-ABSTK,
    VKGRP          TYPE VBAK-VKGRP,
    VKBUR          TYPE VBAK-VKBUR,
    KUNNR          TYPE VBAK-KUNNR,
    CMPS_CM        TYPE VBAK-CMPS_CM,
    KNUMV          TYPE VBAK-KNUMV,
    ZZPOB          TYPE VBAK-ZZPOB,
    UEPOS          TYPE VBAP-UEPOS,
    ERDAT          TYPE VBAP-ERDAT,
    MATNR          TYPE VBAP-MATNR,
    KWMENG         TYPE VBAP-KWMENG,
    VRKME          TYPE VBAP-VRKME,
    KLMENG         TYPE VBAP-KLMENG,
    MEINS          TYPE VBAP-MEINS,
    WERKS          TYPE VBAP-WERKS,
    LGORT          TYPE VBAP-LGORT,
    PRODH          TYPE VBAP-PRODH,
    MVGR1          TYPE VBAP-MVGR1,
    KZWI3          TYPE VBAP-KZWI3,
    MWSBP          TYPE VBAP-MWSBP,
    KZWI1          TYPE VBAP-KZWI1,
    KZWI5          TYPE VBAP-KZWI5,
    PS_PSP_PNR     TYPE VBAP-PS_PSP_PNR,
    PSPHI          TYPE PROJ-PSPNR,
    ZZ1_LOB_SO_SDI TYPE VBAP-ZZ1_LOB_SO_SDI,
    UPMAT          TYPE VBAP-UPMAT,
    ABGRU          TYPE VBAP-ABGRU,
    WAERK          TYPE VBAP-WAERK,
    LFGSA          TYPE VBAP-LFGSA,
    VBEP_VBELN     TYPE VBEP-VBELN,
    LIFSP          TYPE VBEP-LIFSP,
    EDATU          TYPE VBEP-EDATU,
    BMENG          TYPE VBEP-BMENG,
    WMENG          TYPE VBEP-WMENG,
    PRSDT          TYPE VBKD-PRSDT,
    BSTKD          TYPE VBKD-BSTKD,
    BSTKD_E        TYPE VBKD-BSTKD_E,
    POSEX_E        TYPE VBKD-POSEX_E,
    ZTERM          TYPE VBKD-ZTERM,
  END OF TS_SO,
  TT_SO TYPE SORTED TABLE OF TS_SO WITH NON-UNIQUE KEY VBELN_MAIN VBELN POSNR ETENR,
  BEGIN OF TS_VBFA_AFT,
    VBELV   TYPE VBFA-VBELV,
    POSNV   TYPE VBFA-POSNV,
    VBTYP_V TYPE VBFA-VBTYP_V,
    VBELN   TYPE VBFA-VBELN,
    POSNN   TYPE VBFA-POSNN,
    VBTYP_N TYPE VBFA-VBTYP_N,
  END OF TS_VBFA_AFT,
  TT_VBFA_AFT TYPE SORTED TABLE OF TS_VBFA_AFT WITH NON-UNIQUE KEY VBELV POSNV VBTYP_V VBTYP_N,
  BEGIN OF TS_DO,
    VBELN TYPE LIKP-VBELN,
    WADAT TYPE LIKP-WADAT,
    ERDAT TYPE LIKP-ERDAT,
    ERZET TYPE LIKP-ERZET,
    BLDAT TYPE LIKP-BLDAT,
  END OF TS_DO,
  TT_DO TYPE SORTED TABLE OF TS_DO WITH NON-UNIQUE KEY VBELN WADAT,
  BEGIN OF TS_VBFA_BF,
    VBELN   TYPE VBFA-VBELN,
    POSNN   TYPE VBFA-POSNN,
    VBTYP_N TYPE VBFA-VBTYP_N,
    VBELV   TYPE VBFA-VBELV,
    POSNV   TYPE VBFA-POSNV,
    VBTYP_V TYPE VBFA-VBTYP_V,
  END OF TS_VBFA_BF,
  TT_VBFA_BF TYPE SORTED TABLE OF TS_VBFA_BF WITH NON-UNIQUE KEY VBELN POSNN,
  BEGIN OF TS_T001L,
    WERKS TYPE T001L-WERKS,
    LGORT TYPE T001L-LGORT,
    LGOBE TYPE T001L-LGOBE,
  END OF TS_T001L,
  TT_T001L TYPE SORTED TABLE OF TS_T001L WITH NON-UNIQUE KEY WERKS LGORT,
  BEGIN OF TS_MVKE,
    MATNR TYPE MVKE-MATNR,
    VKORG TYPE MVKE-VKORG,
    PRODH TYPE MVKE-PRODH,
  END OF TS_MVKE,
  TT_MVKE TYPE SORTED TABLE OF TS_MVKE WITH NON-UNIQUE KEY MATNR VKORG,
  BEGIN OF TS_TVV1T,
    KVGR1 TYPE TVV1T-KVGR1,
    BEZEI TYPE TVV1T-BEZEI,
  END OF TS_TVV1T,
  TT_TVV1T TYPE SORTED TABLE OF TS_TVV1T WITH NON-UNIQUE KEY KVGR1,
  BEGIN OF TS_TVV2T,
    KVGR2 TYPE TVV2T-KVGR2,
    BEZEI TYPE TVV2T-BEZEI,
  END OF TS_TVV2T,
  TT_TVV2T TYPE SORTED TABLE OF TS_TVV2T WITH NON-UNIQUE KEY KVGR2,
  BEGIN OF TS_ZSDSFIT036,
    KUNNR        TYPE ZSDSFIT036-KUNNR,
    PSPHI        TYPE ZSDSFIT036-PSPHI,
    STARTDATE    TYPE ZSDSFIT036-STARTDATE,
    ENDDATE      TYPE ZSDSFIT036-ENDDATE,
    SEQ          TYPE ZSDSFIT036-SEQ,
    CREDIT_LIMIT TYPE ZSDSFIT036-CREDIT_LIMIT,
  END OF TS_ZSDSFIT036,
  TT_ZSDSFIT036 TYPE SORTED TABLE OF TS_ZSDSFIT036 WITH NON-UNIQUE KEY KUNNR PSPHI STARTDATE ENDDATE,
  BEGIN OF TS_UKMBP_CMS_SGM,
    PARTNER      TYPE UKMBP_CMS_SGM-PARTNER,
    CREDIT_LIMIT TYPE UKMBP_CMS_SGM-CREDIT_LIMIT,
  END OF TS_UKMBP_CMS_SGM,
  TT_UKMBP_CMS_SGM TYPE SORTED TABLE OF TS_UKMBP_CMS_SGM WITH NON-UNIQUE KEY PARTNER,
  BEGIN OF TS_VBPA,
    VBELN      TYPE VBPA-VBELN,
    POSNR      TYPE VBPA-POSNR,
    PARVW      TYPE VBPA-PARVW,
    KUNNR      TYPE VBPA-KUNNR,
    PERNR      TYPE VBPA-PERNR,
    ADRNR      TYPE VBPA-ADRNR,
    NATION     TYPE ADRC-NATION,
    NAME1      TYPE ADRC-NAME1,
    NAME2      TYPE ADRC-NAME2,
    NAME3      TYPE ADRC-NAME3,
    NAME4      TYPE ADRC-NAME4,
    STREET     TYPE ADRC-STREET,
    STR_SUPPL3 TYPE ADRC-STR_SUPPL3,
    LOCATION   TYPE ADRC-LOCATION,
    STR_SUPPL1 TYPE ADRC-STR_SUPPL1,
    STR_SUPPL2 TYPE ADRC-STR_SUPPL2,
    CITY2      TYPE ADRC-CITY2,
    CITY1      TYPE ADRC-CITY1,
    POST_CODE1 TYPE ADRC-POST_CODE1,
  END OF TS_VBPA,
  TT_VBPA TYPE SORTED TABLE OF TS_VBPA WITH NON-UNIQUE KEY VBELN POSNR PARVW NATION,
  BEGIN OF TS_CHLOG,
    OBJECTID  TYPE CDHDR-OBJECTID,
    CHANGENR  TYPE CDHDR-CHANGENR,
    USERNAME  TYPE CDHDR-USERNAME,
    UDATE     TYPE CDHDR-UDATE,
    UTIME     TYPE CDHDR-UTIME,
    TCODE     TYPE CDHDR-TCODE,
    FNAME     TYPE CDPOS-FNAME,
    VALUE_NEW TYPE CDPOS-VALUE_NEW,
    VALUE_OLD TYPE CDPOS-VALUE_OLD,
  END OF TS_CHLOG,
  TT_CHLOG      TYPE SORTED TABLE OF TS_CHLOG WITH NON-UNIQUE KEY OBJECTID,
  TT_ZSDSSDT009 TYPE SORTED TABLE OF ZSDSSDT009 WITH NON-UNIQUE KEY VBELN POSNR ETENR,
  BEGIN OF TS_PRCD_ELEMENTS,
    KNUMV TYPE PRCD_ELEMENTS-KNUMV,
    KPOSN TYPE PRCD_ELEMENTS-KPOSN,
    STUNR TYPE PRCD_ELEMENTS-STUNR,
    ZAEHK TYPE PRCD_ELEMENTS-ZAEHK,
    KSCHL TYPE PRCD_ELEMENTS-KSCHL,
    KBETR TYPE PRCD_ELEMENTS-KBETR,
  END OF TS_PRCD_ELEMENTS,
  TT_PRCD_ELEMENTS TYPE SORTED TABLE OF TS_PRCD_ELEMENTS WITH NON-UNIQUE KEY KNUMV,
  BEGIN OF TS_TVAUT,
    AUGRU TYPE TVAUT-AUGRU,
    BEZEI TYPE TVAUT-BEZEI,
  END OF TS_TVAUT,
  TT_TVAUT TYPE SORTED TABLE OF TS_TVAUT WITH NON-UNIQUE KEY AUGRU,
  BEGIN OF TS_QT,
    VBELN TYPE VBAK-VBELN,
    ERDAT TYPE VBAK-ERDAT,
  END OF TS_QT,
  TT_QT TYPE SORTED TABLE OF TS_QT WITH NON-UNIQUE KEY VBELN,
  BEGIN OF TS_TVAGT,
    ABGRU TYPE TVAGT-ABGRU,
    BEZEI TYPE TVAGT-BEZEI,
  END OF TS_TVAGT,
  TT_TVAGT TYPE SORTED TABLE OF TS_TVAGT WITH NON-UNIQUE KEY ABGRU,
  BEGIN OF TS_TVGRT,
    VKGRP TYPE TVGRT-VKGRP,
    BEZEI TYPE TVGRT-BEZEI,
  END OF TS_TVGRT,
  TT_TVGRT TYPE SORTED TABLE OF TS_TVGRT WITH NON-UNIQUE KEY VKGRP,
  BEGIN OF TS_TVKBT,
    VKBUR TYPE TVKBT-VKBUR,
    BEZEI TYPE TVKBT-BEZEI,
  END OF TS_TVKBT,
  TT_TVKBT TYPE SORTED TABLE OF TS_TVKBT WITH NON-UNIQUE KEY VKBUR,
  BEGIN OF TS_PA0002,
    PERNR TYPE PA0002-PERNR,
    BEGDA TYPE PA0002-BEGDA,
    ENDDA TYPE PA0002-ENDDA,
    VORNA TYPE PA0002-VORNA,
    NACHN TYPE PA0002-NACHN,
  END OF TS_PA0002,
  TT_PA0002 TYPE SORTED TABLE OF TS_PA0002 WITH NON-UNIQUE KEY PERNR,
  BEGIN OF TS_INV,
    VBELN TYPE VBRK-VBELN,
    FKDAT TYPE VBRK-FKDAT,
    XBLNR TYPE VBRK-XBLNR,
    BELNR TYPE VBRK-BELNR,
    VBTYP TYPE VBRK-VBTYP,
  END OF TS_INV,
  TT_INV TYPE SORTED TABLE OF TS_INV WITH NON-UNIQUE KEY VBELN,
  BEGIN OF TS_T247,
    MNR TYPE T247-MNR,
    LTX TYPE T247-LTX,
  END OF TS_T247,
  TT_T247 TYPE SORTED TABLE OF TS_T247 WITH NON-UNIQUE KEY MNR,
  BEGIN OF TS_T052U,
    ZTERM TYPE T052U-ZTERM,
    TEXT1 TYPE T052U-TEXT1,
  END OF TS_T052U,
  TT_T052U TYPE SORTED TABLE OF TS_T052U WITH NON-UNIQUE KEY ZTERM,
  BEGIN OF TS_PROJ,
    PSPNR TYPE PRPS-PSPNR,
    POST1 TYPE PRPS-POST1,
  END OF TS_PROJ,
  TT_PROJ TYPE SORTED TABLE OF TS_PROJ WITH NON-UNIQUE KEY PSPNR,
  BEGIN OF TS_ZSDSSDT010,
    VBELN TYPE ZSDSSDT010-VBELN,
    POSNR TYPE ZSDSSDT010-POSNR,
    ETENR TYPE ZSDSSDT010-ETENR,
    DMBTR TYPE ZSDSSDT010-DMBTR,
    WAERS TYPE ZSDSSDT010-WAERS,
    BELNR TYPE ZSDSSDT010-BELNR,
  END OF TS_ZSDSSDT010,
  TT_ZSDSSDT010 TYPE SORTED TABLE OF TS_ZSDSSDT010  WITH NON-UNIQUE KEY VBELN POSNR ETENR,
  TT_DD07T      TYPE SORTED TABLE OF DD07T WITH NON-UNIQUE KEY DOMNAME DOMVALUE_L,
  BEGIN OF TS_INV_BY_REF,
    VGBEL TYPE VBRP-VGBEL,
    VGPOS TYPE VBRP-VGPOS,
    VGTYP TYPE VBRP-VGTYP,
    VBELN TYPE VBRP-VBELN,
    FKDAT TYPE VBRK-FKDAT,
    XBLNR TYPE VBRK-XBLNR,
    BELNR TYPE VBRK-BELNR,
  END OF TS_INV_BY_REF,
  TT_INV_BY_REF TYPE SORTED TABLE OF TS_INV_BY_REF WITH NON-UNIQUE KEY VGBEL VGPOS,
  BEGIN OF TS_DATA,
    VBELN_QT        TYPE VBFA-VBELV, " Q/T No.
    VBELN_SO        TYPE VBAK-VBELN, " S/O No.
    VBELN_DO        TYPE VBFA-VBELN, " D/O No.
    VBELN_IV        TYPE VBFA-VBELN, " Inv. No.
    LIFSP           TYPE TEXT20, " Delivery block
    AUART           TYPE VBAK-AUART, "Order Type
    POSNR           TYPE VBAP-POSNR, " Item
    UEPOS           TYPE VBAP-UEPOS, " H-Item
    ETENR           TYPE VBEP-ETENR, " Schedule Line
    EDATU           TYPE VBEP-EDATU, " First Deli. Date
    ERDAT           TYPE VBAP-ERDAT, " Item Created Date
    MATNR           TYPE VBAP-MATNR, " Material No.
    WMENG           TYPE VBEP-WMENG, " Qty.
    BMENG           TYPE VBEP-BMENG, " Confirm Qty.
    VRKME           TYPE VBAP-VRKME, " UOM
    MEINS           TYPE VBAP-MEINS, " Base Unit of Measure
    LGOBE           TYPE T001L-LGOBE, " Storage Location
    PRODH_MAT       TYPE MVKE-PRODH, " Material Prodh.
    PRODH           TYPE VBAP-PRODH, " Prod. Hierarchy
    PRODH1          TYPE VBAP-PRODH, " Prodh. Lv.1
    PRODH2          TYPE VBAP-PRODH, " Prodh. Lv.2
    PRODH3          TYPE VBAP-PRODH, " Prodh. Lv.3
    MVGR1           TYPE VBAP-MVGR1, " Material group1
    AUDAT           TYPE VBAK-AUDAT, " Create Date
    KVGR1           TYPE VBAK-KVGR1, " Cust. Grp1
    KVGR1_TX        TYPE TVV1T-BEZEI, " Cust. Grp1 Description
    KVGR2           TYPE VBAK-KVGR2, " Cust. Grp2
    KVGR2_TX        TYPE TVV2T-BEZEI, " Cust. Grp2 Description
    CREDIT_LIMIT    TYPE ZSDSFIT036-CREDIT_LIMIT, " Credit Limit
    CREDIT_CURRENCY TYPE UKMCRED_SGM0C-CURRENCY, " Credit Currency
    CMGST_TX        TYPE DD07T-DDTEXT, "Credit Status text
    CMGST_USR       TYPE CDHDR-USERNAME, "Credit Status Name
    CMGST_DATE      TYPE CDHDR-UDATE,
    CMGST_TIME      TYPE CDHDR-UTIME,
    BILLTO          TYPE VBPA-KUNNR, " Bill to
    BILLTO_NAME_EN  TYPE TEXT120,    " Bill NAME1-NAME4
    BILLTO_NAME_TH  TYPE TEXT120,    " Bill NAME1-NAME4
    BILLTO_CITY1    TYPE ADRC-CITY1,
    BILLTO_STREET   TYPE ADRC-STREET,
    WAERK           TYPE VBAP-WAERK, " SD Document Currency
    AMT_BOM         TYPE VBAP-KZWI3, " Amount Of BOM
    TOTAL_BOM       TYPE VBAP-KZWI3, " Total Amount Of BOM ( VBAP-KZWI3 + VBAP-MWSBP )
    PRICE_UNIT      TYPE VBAP-KZWI1, " Price/Unit (VBAP-KZWI1 /  VBAP-KWMENG)
    NETPRICE_UNIT   TYPE VBAP-KZWI3, " Net Price/Unit (VBAP-KZWI3 /  VBAP-KWMENG)
    NET_AMT         TYPE VBAP-KZWI3, " Net Amount
    TOTAL_AMT       TYPE VBAP-KZWI3, " Total Amount ( VBAP-KZWI3 +  VBAP-MWSBP )
    TAX_AMT         TYPE VBAP-MWSBP, " Tax Amount
    HEAD_DISC       TYPE VBAP-KZWI5, " Header Discount %
    TAX_AMT_ITEM    TYPE VBAP-MWSBP, " Item Tax Amount
    CSH_DISC        TYPE PRCD_ELEMENTS-KBETR, " Cash Discount % ( PRCD_ELEMENTS-KSCHL = “ZDH1”)
    ERDAT_DO        TYPE LIKP-ERDAT, " Created Date D/O
    ERZET_DO        TYPE LIKP-ERZET, " Created Time D/O
    BLDAT_DO        TYPE LIKP-BLDAT, " D/O. Date
    CO_APPV_STAT    TYPE ZSDSSDT009-CO_APPV_STAT, " H. CRED Status
    CO_APPV_BY      TYPE ZSDSSDT009-CO_APPV_BY, " H. CRED Name
    CO_APPV_DATE    TYPE ZSDSSDT009-CO_APPV_DATE, " H. CRED Date
    CO_APPV_TIME    TYPE ZSDSSDT009-CO_APPV_TIME, " H. CRED Time
    MGR_APPV_STAT   TYPE ZSDSSDT009-MGR_APPV_STAT, " MGR Status
    WAITING_APPV    TYPE TEXT50,  "MGR Status text
    MGR_APPV_BY     TYPE ZSDSSDT009-MGR_APPV_BY, " MGR Name
    MGR_APPV_DATE   TYPE ZSDSSDT009-MGR_APPV_DATE, " MGR Date
    MGR_APPV_TIME   TYPE ZSDSSDT009-MGR_APPV_TIME, " MGR Time
    AUGRU_TX        TYPE TVAUT-BEZEI, " Order Reason
    BSTKD           TYPE VBKD-BSTKD, " Main P/O No.
    REASON          TYPE TLINE-TDLINE, "Reason (Text ID : ZH01)
    BSTKD_E         TYPE VBKD-BSTKD_E, " Sub P/O No.
    POSEX_E         TYPE VBKD-POSEX_E, " PO item
    ERDAT_QT        TYPE VBAK-ERDAT, " Q/T Created Date
    ABGRU           TYPE VBAP-ABGRU, "Rejection status
    ABGRU_TX        TYPE TVAGT-BEZEI , " Reason for Reject
    REQUEST_REMARK  TYPE TLINE-TDLINE, " Request Remark (Text ID : ZH10)
    VKGRP           TYPE VBAK-VKGRP, " Sales Group
    VKGRP_TX        TYPE TVGRT-BEZEI, " Sales Group Desc.
    PERNR           TYPE VBPA-PERNR, " Sales Emp.
    PERNR_NAME      TYPE TEXT100, " Sales Name
    VKBUR           TYPE VBAK-VKBUR, " Sales Office
    VKBUR_TX        TYPE TVKBT-BEZEI, " Sales Office Desc.
    SHIPTO_H_ADR    TYPE TLINE-TDLINE, "Ship to address H
    SHIPTO_I_ADR    TYPE TLINE-TDLINE, "Ship to address I
    SHIPTO          TYPE VBPA-KUNNR, " Ship to Code
    SHIPTO_NAME_EN  TYPE TEXT120,    " Bill NAME1-NAME4
    SHIPTO_NAME_TH  TYPE TEXT120,    " Bill NAME1-NAME4
    ERNAM           TYPE VBAK-ERNAM, " S/O Created By
    BNAME           TYPE VBAK-BNAME, " Web Number
    ZZ1_LOB_SO_SDI  TYPE VBAP-ZZ1_LOB_SO_SDI, " LOB
    PS_PSP_PNR      TYPE VBAP-PS_PSP_PNR, "WBS
    PSPHI           TYPE PRPS-PSPHI, "Cost Sheet No.
    POST1           TYPE PROJ-POST1,  " Cost Sheet Desc
    MONTH           TYPE T247-LTX,   " Month (VBEP-EDATU)
    YEAR            TYPE NUM4, " Year (VBEP-EDATU)
    UPMAT           TYPE VBAP-UPMAT, " UP Material
    FKDAT           TYPE VBRK-FKDAT, " Inv. Date
    XBLNR           TYPE VBRK-XBLNR, " Ref. Tax number
    BELNR           TYPE BKPF-BELNR, " Ref. FI document no.
    CM_NO           TYPE TLINE-TDLINE,    " Text ID : ZH04/VBBK
    ADV_DMBTR       TYPE ZSDSSDT010-DMBTR, " Advance Receipt
    ADV_BELNR       TYPE ZSDSSDT010-BELNR, " Advance Doc.
    ZTERM           TYPE VBKD-ZTERM, " Payment Term
    ZTERM_TX        TYPE T052U-TEXT1, " Payment Term Desc.
    FKSAK_TX        TYPE DD07T-DDTEXT, " Bill.stat.order-rel.
    LFSTK_TX        TYPE DD07T-DDTEXT, " Delivery status
    SPSTG_TX        TYPE DD07T-DDTEXT, " Overall blkd status
    GBSTK_TX        TYPE DD07T-DDTEXT, " Overall status
    INV_REMARK      TYPE TLINE-TDLINE,    " Invoice Remark ( ZH09)
    ITEM_REMARK     TYPE TLINE-TDLINE, " Item Remark
    LAND_NO         TYPE TLINE-TDLINE, " Land No ( ZH11 )
    ZZPOB           TYPE VBAK-ZZPOB,   "POB
    INV_REF         TYPE DD07T-DDTEXT, "Invoice Ref
    RUNNO           TYPE NUM5,         "Running number group by Sales Order
    BNAME_QT        TYPE VBAK-BNAME,
    IHREZ           TYPE VBKD-IHREZ,
    DESCRIPTION     TYPE FARR_C_EVNT_TY_T-DESCRIPTION,
    OBJECT_ID       TYPE CRMS4D_SERV_H-OBJECT_ID,
    PO_NUMBER_SOLD  TYPE CRMS4D_SERV_H-PO_NUMBER_SOLD,
  END OF TS_DATA,
  TT_DATA TYPE STANDARD TABLE OF TS_DATA.
*----------------------------------------------------------------------*
* CONSTANTS
*----------------------------------------------------------------------*
CONSTANTS:
  GC_TCODE TYPE  SY-TCODE  VALUE 'ZSDSSD019',
  BEGIN OF GC_VBTYP,
    QUOT     TYPE VBAK-VBTYP VALUE 'B',
    SO       TYPE VBAK-VBTYP VALUE 'C',
    RT       TYPE VBAK-VBTYP VALUE 'H',
    DO       TYPE VBAK-VBTYP VALUE 'J',
    CN_REQ   TYPE VBAK-VBTYP VALUE 'K',
    DN_REQ   TYPE VBAK-VBTYP VALUE 'L',
    INV      TYPE VBAK-VBTYP VALUE 'M',
    INV_CANC TYPE VBAK-VBTYP VALUE 'N',
    CN       TYPE VBAK-VBTYP VALUE 'O',
    DN       TYPE VBAK-VBTYP VALUE 'P',
    CN_CANC  TYPE VBAK-VBTYP VALUE 'S',
    RT_DO    TYPE VBAK-VBTYP VALUE 'T',
  END OF GC_VBTYP,
  BEGIN OF GC_PARVW,
    BILL_TO TYPE VBPA-PARVW VALUE 'RE',
    SALES   TYPE VBPA-PARVW VALUE 'VE',
    SHIP_TO TYPE VBPA-PARVW VALUE 'WE',
  END OF GC_PARVW,
  BEGIN OF GC_KSCHL,
    CASH_DISCOUNT TYPE PRCD_ELEMENTS-KSCHL VALUE 'ZDH1',
  END OF GC_KSCHL,
  GC_CREDIT_SGMNT    TYPE UKMBP_CMS_SGM-CREDIT_SGMNT VALUE '1000',
  GC_OBJECTCLAS_SALE TYPE CDHDR-OBJECTCLAS VALUE 'VERKBELEG',
  GC_TRUE            TYPE FLAG VALUE 'X'.
*----------------------------------------------------------------------*
* INTERNAL TABLE
*----------------------------------------------------------------------*
DATA: GT_DATA TYPE TT_DATA ##NEEDED.
*----------------------------------------------------------------------*
* RANAGES
*----------------------------------------------------------------------*
DATA: GR_PSTYV TYPE RANGE OF VBAP-PSTYV ##NEEDED.
*----------------------------------------------------------------------*
* ALV DECLARATION
*----------------------------------------------------------------------*
DEFINE MC_SHOW_PROGRESS.
  IF SY-BATCH IS INITIAL.
*   Show progress online
    CALL FUNCTION 'SAPGUI_PROGRESS_INDICATOR'
      EXPORTING
        PERCENTAGE = &1 ##NUMBER_OK
        TEXT       = &2.
  ELSE.
*   Show message step in background
    MESSAGE I000(38) WITH &2 SPACE SPACE SPACE.
  ENDIF.
END-OF-DEFINITION.
DEFINE %FCAT.
  <L_FCAT>-SCRTEXT_S = <L_FCAT>-SCRTEXT_M =
  <L_FCAT>-SCRTEXT_L = <L_FCAT>-COLTEXT =
  <L_FCAT>-SELTEXT   = <L_FCAT>-TOOLTIP =
  <L_FCAT>-REPTEXT   = &1.
END-OF-DEFINITION.

DATA:   GF_EDIT    TYPE  CHAR1 ##NEEDED.
CONSTANTS:
  GC_HEADER_HEIGHT_1 TYPE  I                VALUE 0,
  GC_ALV_HEIGHT_1    TYPE  I                VALUE 100.
*----------------------------------------------------------------------*
* SELECTION-SCREEN
*----------------------------------------------------------------------*
SELECTION-SCREEN BEGIN OF BLOCK BLK1 WITH FRAME TITLE TEXT-S01.
  SELECT-OPTIONS:
    S_VKORG FOR VBAK-VKORG NO-EXTENSION NO INTERVALS DEFAULT '1000' OBLIGATORY,
    S_VTWEG FOR VBAK-VTWEG,
    S_SPART FOR VBAK-SPART,
    S_VKBUR FOR VBAK-VKBUR,
    S_VKGRP FOR VBAK-VKGRP OBLIGATORY,
    S_KUNNR FOR VBAK-KUNNR,
    S_AUART FOR VBAK-AUART,
    S_AUDAT FOR VBAK-AUDAT,
    S_ERDAT FOR VBAP-ERDAT,
    S_EDATU FOR VBEP-EDATU OBLIGATORY,
    S_VBELN FOR VBAK-VBELN,
    S_QT    FOR VBAK-VBELN,
    S_ABGRU FOR VBAP-ABGRU,
    S_MATNR FOR VBAP-MATNR,
    S_LGORT FOR VBAP-LGORT,
    S_AUFNR FOR VBAP-AUFNR,
    S_PRODH FOR VBAP-PRODH,
    S_PAPH1 FOR VBAP-PRODH,
    S_PAPH2 FOR VBAP-PRODH,
    S_PAPH3 FOR VBAP-PRODH,
    S_PERNR FOR VBPA-PERNR,
    S_BNAME FOR VBAK-BNAME,
    S_BSTKD FOR VBKD-BSTKD,
    S_KVGR2 FOR VBAK-KVGR2,
    S_ZZPOB FOR VBAK-ZZPOB.
SELECTION-SCREEN END OF BLOCK BLK1.
