*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZSDSV_ETAX_DISCM................................*
FORM GET_DATA_ZSDSV_ETAX_DISCM.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZSDSSDC018 WHERE
(VIM_WHERETAB) .
    CLEAR ZSDSV_ETAX_DISCM .
ZSDSV_ETAX_DISCM-MANDT =
ZSDSSDC018-MANDT .
ZSDSV_ETAX_DISCM-KSCHL =
ZSDSSDC018-KSCHL .
ZSDSV_ETAX_DISCM-DISC_CD =
ZSDSSDC018-DISC_CD .
ZSDSV_ETAX_DISCM-ZDEL_FLG =
ZSDSSDC018-ZDEL_FLG .
ZSDSV_ETAX_DISCM-ZCRT_DATE =
ZSDSSDC018-ZCRT_DATE .
ZSDSV_ETAX_DISCM-ZCRT_TIME =
ZSDSSDC018-ZCRT_TIME .
ZSDSV_ETAX_DISCM-ZCRT_USER =
ZSDSSDC018-ZCRT_USER .
ZSDSV_ETAX_DISCM-ZCRT_PGM =
ZSDSSDC018-ZCRT_PGM .
ZSDSV_ETAX_DISCM-ZUPD_DATE =
ZSDSSDC018-ZUPD_DATE .
ZSDSV_ETAX_DISCM-ZUPD_TIME =
ZSDSSDC018-ZUPD_TIME .
ZSDSV_ETAX_DISCM-ZUPD_USER =
ZSDSSDC018-ZUPD_USER .
ZSDSV_ETAX_DISCM-ZUPD_PGM =
ZSDSSDC018-ZUPD_PGM .
<VIM_TOTAL_STRUC> = ZSDSV_ETAX_DISCM.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZSDSV_ETAX_DISCM .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZSDSV_ETAX_DISCM.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZSDSV_ETAX_DISCM-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZSDSSDC018 WHERE
  KSCHL = ZSDSV_ETAX_DISCM-KSCHL .
    IF SY-SUBRC = 0.
    DELETE ZSDSSDC018 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZSDSSDC018 WHERE
  KSCHL = ZSDSV_ETAX_DISCM-KSCHL .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZSDSSDC018.
    ENDIF.
ZSDSSDC018-MANDT =
ZSDSV_ETAX_DISCM-MANDT .
ZSDSSDC018-KSCHL =
ZSDSV_ETAX_DISCM-KSCHL .
ZSDSSDC018-DISC_CD =
ZSDSV_ETAX_DISCM-DISC_CD .
ZSDSSDC018-ZDEL_FLG =
ZSDSV_ETAX_DISCM-ZDEL_FLG .
ZSDSSDC018-ZCRT_DATE =
ZSDSV_ETAX_DISCM-ZCRT_DATE .
ZSDSSDC018-ZCRT_TIME =
ZSDSV_ETAX_DISCM-ZCRT_TIME .
ZSDSSDC018-ZCRT_USER =
ZSDSV_ETAX_DISCM-ZCRT_USER .
ZSDSSDC018-ZCRT_PGM =
ZSDSV_ETAX_DISCM-ZCRT_PGM .
ZSDSSDC018-ZUPD_DATE =
ZSDSV_ETAX_DISCM-ZUPD_DATE .
ZSDSSDC018-ZUPD_TIME =
ZSDSV_ETAX_DISCM-ZUPD_TIME .
ZSDSSDC018-ZUPD_USER =
ZSDSV_ETAX_DISCM-ZUPD_USER .
ZSDSSDC018-ZUPD_PGM =
ZSDSV_ETAX_DISCM-ZUPD_PGM .
    IF SY-SUBRC = 0.
    UPDATE ZSDSSDC018 ##WARN_OK.
    ELSE.
    INSERT ZSDSSDC018 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZSDSV_ETAX_DISCM-UPD_FLAG,
STATUS_ZSDSV_ETAX_DISCM-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZSDSV_ETAX_DISCM.
  SELECT SINGLE * FROM ZSDSSDC018 WHERE
KSCHL = ZSDSV_ETAX_DISCM-KSCHL .
ZSDSV_ETAX_DISCM-MANDT =
ZSDSSDC018-MANDT .
ZSDSV_ETAX_DISCM-KSCHL =
ZSDSSDC018-KSCHL .
ZSDSV_ETAX_DISCM-DISC_CD =
ZSDSSDC018-DISC_CD .
ZSDSV_ETAX_DISCM-ZDEL_FLG =
ZSDSSDC018-ZDEL_FLG .
ZSDSV_ETAX_DISCM-ZCRT_DATE =
ZSDSSDC018-ZCRT_DATE .
ZSDSV_ETAX_DISCM-ZCRT_TIME =
ZSDSSDC018-ZCRT_TIME .
ZSDSV_ETAX_DISCM-ZCRT_USER =
ZSDSSDC018-ZCRT_USER .
ZSDSV_ETAX_DISCM-ZCRT_PGM =
ZSDSSDC018-ZCRT_PGM .
ZSDSV_ETAX_DISCM-ZUPD_DATE =
ZSDSSDC018-ZUPD_DATE .
ZSDSV_ETAX_DISCM-ZUPD_TIME =
ZSDSSDC018-ZUPD_TIME .
ZSDSV_ETAX_DISCM-ZUPD_USER =
ZSDSSDC018-ZUPD_USER .
ZSDSV_ETAX_DISCM-ZUPD_PGM =
ZSDSSDC018-ZUPD_PGM .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZSDSV_ETAX_DISCM USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZSDSV_ETAX_DISCM-KSCHL TO
ZSDSSDC018-KSCHL .
MOVE ZSDSV_ETAX_DISCM-MANDT TO
ZSDSSDC018-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZSDSSDC018'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZSDSSDC018 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZSDSSDC018'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
