*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZSDSV_ETAX_DISC.................................*
FORM GET_DATA_ZSDSV_ETAX_DISC.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZSDSSDC016 WHERE
(VIM_WHERETAB) .
    CLEAR ZSDSV_ETAX_DISC .
ZSDSV_ETAX_DISC-MANDT =
ZSDSSDC016-MANDT .
ZSDSV_ETAX_DISC-DISC_CD =
ZSDSSDC016-DISC_CD .
ZSDSV_ETAX_DISC-DESCP_TH =
ZSDSSDC016-DESCP_TH .
ZSDSV_ETAX_DISC-DESCP_EN =
ZSDSSDC016-DESCP_EN .
ZSDSV_ETAX_DISC-DISC_TY =
ZSDSSDC016-DISC_TY .
ZSDSV_ETAX_DISC-ZDEL_FLG =
ZSDSSDC016-ZDEL_FLG .
ZSDSV_ETAX_DISC-ZCRT_DATE =
ZSDSSDC016-ZCRT_DATE .
ZSDSV_ETAX_DISC-ZCRT_TIME =
ZSDSSDC016-ZCRT_TIME .
ZSDSV_ETAX_DISC-ZCRT_USER =
ZSDSSDC016-ZCRT_USER .
ZSDSV_ETAX_DISC-ZCRT_PGM =
ZSDSSDC016-ZCRT_PGM .
ZSDSV_ETAX_DISC-ZUPD_DATE =
ZSDSSDC016-ZUPD_DATE .
ZSDSV_ETAX_DISC-ZUPD_TIME =
ZSDSSDC016-ZUPD_TIME .
ZSDSV_ETAX_DISC-ZUPD_USER =
ZSDSSDC016-ZUPD_USER .
ZSDSV_ETAX_DISC-ZUPD_PGM =
ZSDSSDC016-ZUPD_PGM .
<VIM_TOTAL_STRUC> = ZSDSV_ETAX_DISC.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZSDSV_ETAX_DISC .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZSDSV_ETAX_DISC.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZSDSV_ETAX_DISC-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZSDSSDC016 WHERE
  DISC_CD = ZSDSV_ETAX_DISC-DISC_CD .
    IF SY-SUBRC = 0.
    DELETE ZSDSSDC016 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZSDSSDC016 WHERE
  DISC_CD = ZSDSV_ETAX_DISC-DISC_CD .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZSDSSDC016.
    ENDIF.
ZSDSSDC016-MANDT =
ZSDSV_ETAX_DISC-MANDT .
ZSDSSDC016-DISC_CD =
ZSDSV_ETAX_DISC-DISC_CD .
ZSDSSDC016-DESCP_TH =
ZSDSV_ETAX_DISC-DESCP_TH .
ZSDSSDC016-DESCP_EN =
ZSDSV_ETAX_DISC-DESCP_EN .
ZSDSSDC016-DISC_TY =
ZSDSV_ETAX_DISC-DISC_TY .
ZSDSSDC016-ZDEL_FLG =
ZSDSV_ETAX_DISC-ZDEL_FLG .
ZSDSSDC016-ZCRT_DATE =
ZSDSV_ETAX_DISC-ZCRT_DATE .
ZSDSSDC016-ZCRT_TIME =
ZSDSV_ETAX_DISC-ZCRT_TIME .
ZSDSSDC016-ZCRT_USER =
ZSDSV_ETAX_DISC-ZCRT_USER .
ZSDSSDC016-ZCRT_PGM =
ZSDSV_ETAX_DISC-ZCRT_PGM .
ZSDSSDC016-ZUPD_DATE =
ZSDSV_ETAX_DISC-ZUPD_DATE .
ZSDSSDC016-ZUPD_TIME =
ZSDSV_ETAX_DISC-ZUPD_TIME .
ZSDSSDC016-ZUPD_USER =
ZSDSV_ETAX_DISC-ZUPD_USER .
ZSDSSDC016-ZUPD_PGM =
ZSDSV_ETAX_DISC-ZUPD_PGM .
    IF SY-SUBRC = 0.
    UPDATE ZSDSSDC016 ##WARN_OK.
    ELSE.
    INSERT ZSDSSDC016 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZSDSV_ETAX_DISC-UPD_FLAG,
STATUS_ZSDSV_ETAX_DISC-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZSDSV_ETAX_DISC.
  SELECT SINGLE * FROM ZSDSSDC016 WHERE
DISC_CD = ZSDSV_ETAX_DISC-DISC_CD .
ZSDSV_ETAX_DISC-MANDT =
ZSDSSDC016-MANDT .
ZSDSV_ETAX_DISC-DISC_CD =
ZSDSSDC016-DISC_CD .
ZSDSV_ETAX_DISC-DESCP_TH =
ZSDSSDC016-DESCP_TH .
ZSDSV_ETAX_DISC-DESCP_EN =
ZSDSSDC016-DESCP_EN .
ZSDSV_ETAX_DISC-DISC_TY =
ZSDSSDC016-DISC_TY .
ZSDSV_ETAX_DISC-ZDEL_FLG =
ZSDSSDC016-ZDEL_FLG .
ZSDSV_ETAX_DISC-ZCRT_DATE =
ZSDSSDC016-ZCRT_DATE .
ZSDSV_ETAX_DISC-ZCRT_TIME =
ZSDSSDC016-ZCRT_TIME .
ZSDSV_ETAX_DISC-ZCRT_USER =
ZSDSSDC016-ZCRT_USER .
ZSDSV_ETAX_DISC-ZCRT_PGM =
ZSDSSDC016-ZCRT_PGM .
ZSDSV_ETAX_DISC-ZUPD_DATE =
ZSDSSDC016-ZUPD_DATE .
ZSDSV_ETAX_DISC-ZUPD_TIME =
ZSDSSDC016-ZUPD_TIME .
ZSDSV_ETAX_DISC-ZUPD_USER =
ZSDSSDC016-ZUPD_USER .
ZSDSV_ETAX_DISC-ZUPD_PGM =
ZSDSSDC016-ZUPD_PGM .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZSDSV_ETAX_DISC USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZSDSV_ETAX_DISC-DISC_CD TO
ZSDSSDC016-DISC_CD .
MOVE ZSDSV_ETAX_DISC-MANDT TO
ZSDSSDC016-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZSDSSDC016'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZSDSSDC016 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZSDSSDC016'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
