"Name: \PR:SAPMV45A\FO:USEREXIT_CHECK_VBEP\SE:BEGIN\EI
ENHANCEMENT 0 ZSDS_SD_SO_USEREXIT1.
* SDS User Exit Implementation
  DATA: LF_CHECK_VBEP_ERROR TYPE FLAG.

  ZCL_SDSSD_SALESORDER_ENH=>USEREXIT_CHECK_VBEP(
        EXPORTING IS_TRTYP = T180-TRTYP
                  IS_VBAK  = VBAK
                  IS_VBEP  = VBEP
                  IT_XVBEP = XVBEP[]
                  IT_YVBEP = YVBEP[]
                  IT_XVBAP = XVBAP[]
         CHANGING
                  CF_FCODE = FCODE
                  CF_ERROR = LF_CHECK_VBEP_ERROR ).

  IF LF_CHECK_VBEP_ERROR EQ 'X'.
    MESSAGE ID SY-MSGID TYPE 'S' NUMBER SY-MSGNO
      WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4 DISPLAY LIKE SY-MSGTY.
    EXIT.
  ENDIF.
ENDENHANCEMENT.
