*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZSDSV_ETAX_DOCTY................................*
FORM GET_DATA_ZSDSV_ETAX_DOCTY.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZSDSSDC014 WHERE
(VIM_WHERETAB) .
    CLEAR ZSDSV_ETAX_DOCTY .
ZSDSV_ETAX_DOCTY-MANDT =
ZSDSSDC014-MANDT .
ZSDSV_ETAX_DOCTY-DOCTY =
ZSDSSDC014-DOCTY .
ZSDSV_ETAX_DOCTY-DESCP_TH =
ZSDSSDC014-DESCP_TH .
ZSDSV_ETAX_DOCTY-DESCP_EN =
ZSDSSDC014-DESCP_EN .
ZSDSV_ETAX_DOCTY-DCGRP =
ZSDSSDC014-DCGRP .
ZSDSV_ETAX_DOCTY-ZDEL_FLG =
ZSDSSDC014-ZDEL_FLG .
ZSDSV_ETAX_DOCTY-ZCRT_DATE =
ZSDSSDC014-ZCRT_DATE .
ZSDSV_ETAX_DOCTY-ZCRT_TIME =
ZSDSSDC014-ZCRT_TIME .
ZSDSV_ETAX_DOCTY-ZCRT_USER =
ZSDSSDC014-ZCRT_USER .
ZSDSV_ETAX_DOCTY-ZCRT_PGM =
ZSDSSDC014-ZCRT_PGM .
ZSDSV_ETAX_DOCTY-ZUPD_DATE =
ZSDSSDC014-ZUPD_DATE .
ZSDSV_ETAX_DOCTY-ZUPD_TIME =
ZSDSSDC014-ZUPD_TIME .
ZSDSV_ETAX_DOCTY-ZUPD_USER =
ZSDSSDC014-ZUPD_USER .
ZSDSV_ETAX_DOCTY-ZUPD_PGM =
ZSDSSDC014-ZUPD_PGM .
<VIM_TOTAL_STRUC> = ZSDSV_ETAX_DOCTY.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZSDSV_ETAX_DOCTY .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZSDSV_ETAX_DOCTY.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZSDSV_ETAX_DOCTY-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZSDSSDC014 WHERE
  DOCTY = ZSDSV_ETAX_DOCTY-DOCTY .
    IF SY-SUBRC = 0.
    DELETE ZSDSSDC014 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZSDSSDC014 WHERE
  DOCTY = ZSDSV_ETAX_DOCTY-DOCTY .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZSDSSDC014.
    ENDIF.
ZSDSSDC014-MANDT =
ZSDSV_ETAX_DOCTY-MANDT .
ZSDSSDC014-DOCTY =
ZSDSV_ETAX_DOCTY-DOCTY .
ZSDSSDC014-DESCP_TH =
ZSDSV_ETAX_DOCTY-DESCP_TH .
ZSDSSDC014-DESCP_EN =
ZSDSV_ETAX_DOCTY-DESCP_EN .
ZSDSSDC014-DCGRP =
ZSDSV_ETAX_DOCTY-DCGRP .
ZSDSSDC014-ZDEL_FLG =
ZSDSV_ETAX_DOCTY-ZDEL_FLG .
ZSDSSDC014-ZCRT_DATE =
ZSDSV_ETAX_DOCTY-ZCRT_DATE .
ZSDSSDC014-ZCRT_TIME =
ZSDSV_ETAX_DOCTY-ZCRT_TIME .
ZSDSSDC014-ZCRT_USER =
ZSDSV_ETAX_DOCTY-ZCRT_USER .
ZSDSSDC014-ZCRT_PGM =
ZSDSV_ETAX_DOCTY-ZCRT_PGM .
ZSDSSDC014-ZUPD_DATE =
ZSDSV_ETAX_DOCTY-ZUPD_DATE .
ZSDSSDC014-ZUPD_TIME =
ZSDSV_ETAX_DOCTY-ZUPD_TIME .
ZSDSSDC014-ZUPD_USER =
ZSDSV_ETAX_DOCTY-ZUPD_USER .
ZSDSSDC014-ZUPD_PGM =
ZSDSV_ETAX_DOCTY-ZUPD_PGM .
    IF SY-SUBRC = 0.
    UPDATE ZSDSSDC014 ##WARN_OK.
    ELSE.
    INSERT ZSDSSDC014 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZSDSV_ETAX_DOCTY-UPD_FLAG,
STATUS_ZSDSV_ETAX_DOCTY-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZSDSV_ETAX_DOCTY.
  SELECT SINGLE * FROM ZSDSSDC014 WHERE
DOCTY = ZSDSV_ETAX_DOCTY-DOCTY .
ZSDSV_ETAX_DOCTY-MANDT =
ZSDSSDC014-MANDT .
ZSDSV_ETAX_DOCTY-DOCTY =
ZSDSSDC014-DOCTY .
ZSDSV_ETAX_DOCTY-DESCP_TH =
ZSDSSDC014-DESCP_TH .
ZSDSV_ETAX_DOCTY-DESCP_EN =
ZSDSSDC014-DESCP_EN .
ZSDSV_ETAX_DOCTY-DCGRP =
ZSDSSDC014-DCGRP .
ZSDSV_ETAX_DOCTY-ZDEL_FLG =
ZSDSSDC014-ZDEL_FLG .
ZSDSV_ETAX_DOCTY-ZCRT_DATE =
ZSDSSDC014-ZCRT_DATE .
ZSDSV_ETAX_DOCTY-ZCRT_TIME =
ZSDSSDC014-ZCRT_TIME .
ZSDSV_ETAX_DOCTY-ZCRT_USER =
ZSDSSDC014-ZCRT_USER .
ZSDSV_ETAX_DOCTY-ZCRT_PGM =
ZSDSSDC014-ZCRT_PGM .
ZSDSV_ETAX_DOCTY-ZUPD_DATE =
ZSDSSDC014-ZUPD_DATE .
ZSDSV_ETAX_DOCTY-ZUPD_TIME =
ZSDSSDC014-ZUPD_TIME .
ZSDSV_ETAX_DOCTY-ZUPD_USER =
ZSDSSDC014-ZUPD_USER .
ZSDSV_ETAX_DOCTY-ZUPD_PGM =
ZSDSSDC014-ZUPD_PGM .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZSDSV_ETAX_DOCTY USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZSDSV_ETAX_DOCTY-DOCTY TO
ZSDSSDC014-DOCTY .
MOVE ZSDSV_ETAX_DOCTY-MANDT TO
ZSDSSDC014-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZSDSSDC014'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZSDSSDC014 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZSDSSDC014'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
