"Name: \PR:SAPMV45A\FO:USEREXIT_FIELD_MODIFICATION\SE:END\EI
ENHANCEMENT 0 ZSDS_SD_SO_USEREXIT1.
* SDS User Exit Implementation
  ZCL_SDSSD_SALESORDER_ENH=>USEREXIT_FIELD_MODIFICATION(
        EXPORTING IS_T180 = T180
                  IS_VBAK = VBAK
        CHANGING  CS_SCREEN = SCREEN ).

  IF SY-TCODE EQ 'VA01' OR
     SY-TCODE EQ 'VA02'.
    IF ZCL_SDSCA_UTIL_SDS=>INITIAL_FLAG IS INITIAL.
      ZCL_SDSCA_UTIL_SDS=>CHECK_SDS( EXPORTING LV_MANDT = SY-MANDT
                                     IMPORTING LV_SDS   = ZCL_SDSCA_UTIL_SDS=>IS_SDS ).
      IF ZCL_SDSCA_UTIL_SDS=>IS_SDS EQ ABAP_TRUE.
        ZCL_SDSCA_UTIL_SDS=>USER_PARAM = ZCL_SDSCA_UTIL_SDS=>GET_USER_PARAMETER( 'LAG' ).
      ENDIF.
      ZCL_SDSCA_UTIL_SDS=>INITIAL_FLAG = ABAP_TRUE.
    ENDIF.
    IF ZCL_SDSCA_UTIL_SDS=>IS_SDS EQ ABAP_TRUE.
      IF ZCL_SDSCA_UTIL_SDS=>USER_PARAM IS NOT INITIAL AND
         XVBAP[] IS NOT INITIAL.
        LOOP AT XVBAP ASSIGNING FIELD-SYMBOL(<LFS_VBAP>) WHERE LGORT IS INITIAL
                                                           AND MATKL NE 'SP-TRANS'
                                                           AND MATKL NE 'FG-TRANS'.
          <LFS_VBAP>-LGORT = ZCL_SDSCA_UTIL_SDS=>USER_PARAM.
        ENDLOOP.
      ENDIF.
    ENDIF.
  ENDIF.

ENDENHANCEMENT.
