"Name: \PR:SAPMV45A\FO:USEREXIT_SAVE_DOCUMENT_PREPARE\SE:END\EI
ENHANCEMENT 0 ZSDS_SD_SO_USEREXIT1.
* SDS User Exit Implementation
  DATA: LF_FAIL TYPE FLAG.

  ZCL_SDSSD_SALESORDER_ENH=>USEREXIT_SAVE_DOCUMENT_PREPARE(
        EXPORTING
                  IS_TRTYP  = T180-TRTYP
        CHANGING
                  CS_VBAK   = VBAK
                  CT_XVBKD  = XVBKD[]
                  CT_YVBKD  = YVBKD[]
                  CT_XVBAP  = XVBAP[]
                  CT_YVBAP  = YVBAP[]
                  CT_XVBEP  = XVBEP[]
                  CT_YVBEP  = YVBEP[]
                  CF_FCODE  = FCODE
                  CF_ERROR  = LF_FAIL ).

  IF LF_FAIL EQ 'X'.
*   Display message on GUI
    IF SY-TCODE IS NOT INITIAL.
      GF_EXIT_SAVE_DOCUMENT_PREPARE = 'X'.
*      MESSAGE ID SY-MSGID TYPE 'S' NUMBER SY-MSGNO
*        WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4 DISPLAY LIKE SY-MSGTY.
      MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
        WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
    ELSE.
*   Display message on Fiori
      MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
        WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
    ENDIF.
  ELSEIF LF_FAIL EQ 'W'.
*   Display message on Fiori
    IF SY-MSGTY IS NOT INITIAL.
      MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
        WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
    ENDIF.
  ENDIF.
ENDENHANCEMENT.
