*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZSDSV_ETAX_PRVN.................................*
FORM GET_DATA_ZSDSV_ETAX_PRVN.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZSDSSDC022 WHERE
(VIM_WHERETAB) .
    CLEAR ZSDSV_ETAX_PRVN .
ZSDSV_ETAX_PRVN-MANDT =
ZSDSSDC022-MANDT .
ZSDSV_ETAX_PRVN-PROVINCE_CD =
ZSDSSDC022-PROVINCE_CD .
ZSDSV_ETAX_PRVN-PROVINCE_TX =
ZSDSSDC022-PROVINCE_TX .
ZSDSV_ETAX_PRVN-ZDEL_FLG =
ZSDSSDC022-ZDEL_FLG .
ZSDSV_ETAX_PRVN-ZCRT_DATE =
ZSDSSDC022-ZCRT_DATE .
ZSDSV_ETAX_PRVN-ZCRT_TIME =
ZSDSSDC022-ZCRT_TIME .
ZSDSV_ETAX_PRVN-ZCRT_USER =
ZSDSSDC022-ZCRT_USER .
ZSDSV_ETAX_PRVN-ZCRT_PGM =
ZSDSSDC022-ZCRT_PGM .
ZSDSV_ETAX_PRVN-ZUPD_DATE =
ZSDSSDC022-ZUPD_DATE .
ZSDSV_ETAX_PRVN-ZUPD_TIME =
ZSDSSDC022-ZUPD_TIME .
ZSDSV_ETAX_PRVN-ZUPD_USER =
ZSDSSDC022-ZUPD_USER .
ZSDSV_ETAX_PRVN-ZUPD_PGM =
ZSDSSDC022-ZUPD_PGM .
<VIM_TOTAL_STRUC> = ZSDSV_ETAX_PRVN.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZSDSV_ETAX_PRVN .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZSDSV_ETAX_PRVN.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZSDSV_ETAX_PRVN-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZSDSSDC022 WHERE
  PROVINCE_CD = ZSDSV_ETAX_PRVN-PROVINCE_CD .
    IF SY-SUBRC = 0.
    DELETE ZSDSSDC022 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZSDSSDC022 WHERE
  PROVINCE_CD = ZSDSV_ETAX_PRVN-PROVINCE_CD .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZSDSSDC022.
    ENDIF.
ZSDSSDC022-MANDT =
ZSDSV_ETAX_PRVN-MANDT .
ZSDSSDC022-PROVINCE_CD =
ZSDSV_ETAX_PRVN-PROVINCE_CD .
ZSDSSDC022-PROVINCE_TX =
ZSDSV_ETAX_PRVN-PROVINCE_TX .
ZSDSSDC022-ZDEL_FLG =
ZSDSV_ETAX_PRVN-ZDEL_FLG .
ZSDSSDC022-ZCRT_DATE =
ZSDSV_ETAX_PRVN-ZCRT_DATE .
ZSDSSDC022-ZCRT_TIME =
ZSDSV_ETAX_PRVN-ZCRT_TIME .
ZSDSSDC022-ZCRT_USER =
ZSDSV_ETAX_PRVN-ZCRT_USER .
ZSDSSDC022-ZCRT_PGM =
ZSDSV_ETAX_PRVN-ZCRT_PGM .
ZSDSSDC022-ZUPD_DATE =
ZSDSV_ETAX_PRVN-ZUPD_DATE .
ZSDSSDC022-ZUPD_TIME =
ZSDSV_ETAX_PRVN-ZUPD_TIME .
ZSDSSDC022-ZUPD_USER =
ZSDSV_ETAX_PRVN-ZUPD_USER .
ZSDSSDC022-ZUPD_PGM =
ZSDSV_ETAX_PRVN-ZUPD_PGM .
    IF SY-SUBRC = 0.
    UPDATE ZSDSSDC022 ##WARN_OK.
    ELSE.
    INSERT ZSDSSDC022 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZSDSV_ETAX_PRVN-UPD_FLAG,
STATUS_ZSDSV_ETAX_PRVN-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZSDSV_ETAX_PRVN.
  SELECT SINGLE * FROM ZSDSSDC022 WHERE
PROVINCE_CD = ZSDSV_ETAX_PRVN-PROVINCE_CD .
ZSDSV_ETAX_PRVN-MANDT =
ZSDSSDC022-MANDT .
ZSDSV_ETAX_PRVN-PROVINCE_CD =
ZSDSSDC022-PROVINCE_CD .
ZSDSV_ETAX_PRVN-PROVINCE_TX =
ZSDSSDC022-PROVINCE_TX .
ZSDSV_ETAX_PRVN-ZDEL_FLG =
ZSDSSDC022-ZDEL_FLG .
ZSDSV_ETAX_PRVN-ZCRT_DATE =
ZSDSSDC022-ZCRT_DATE .
ZSDSV_ETAX_PRVN-ZCRT_TIME =
ZSDSSDC022-ZCRT_TIME .
ZSDSV_ETAX_PRVN-ZCRT_USER =
ZSDSSDC022-ZCRT_USER .
ZSDSV_ETAX_PRVN-ZCRT_PGM =
ZSDSSDC022-ZCRT_PGM .
ZSDSV_ETAX_PRVN-ZUPD_DATE =
ZSDSSDC022-ZUPD_DATE .
ZSDSV_ETAX_PRVN-ZUPD_TIME =
ZSDSSDC022-ZUPD_TIME .
ZSDSV_ETAX_PRVN-ZUPD_USER =
ZSDSSDC022-ZUPD_USER .
ZSDSV_ETAX_PRVN-ZUPD_PGM =
ZSDSSDC022-ZUPD_PGM .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZSDSV_ETAX_PRVN USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZSDSV_ETAX_PRVN-PROVINCE_CD TO
ZSDSSDC022-PROVINCE_CD .
MOVE ZSDSV_ETAX_PRVN-MANDT TO
ZSDSSDC022-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZSDSSDC022'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZSDSSDC022 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZSDSSDC022'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
