"Name: \PR:SAPMV45A\FO:USEREXIT_MOVE_FIELD_TO_VBAKKOM\SE:END\EI
ENHANCEMENT 0 ZSDS_SD_MOVE_CUSTOM_VBAK.
  VBAK-ZZPOB        = US_VBAKKOM-ZZPOB.
  VBAK-ZZWARRANTY_L = US_VBAKKOM-ZZWARRANTY_L.
  VBAK-ZZRUNNING    = US_VBAKKOM-ZZRUNNING.
ENDENHANCEMENT.
