*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZSDSV_ETAX_DTRC.................................*
FORM GET_DATA_ZSDSV_ETAX_DTRC.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZSDSSDC023 WHERE
(VIM_WHERETAB) .
    CLEAR ZSDSV_ETAX_DTRC .
ZSDSV_ETAX_DTRC-MANDT =
ZSDSSDC023-MANDT .
ZSDSV_ETAX_DTRC-PROVINCE_CD =
ZSDSSDC023-PROVINCE_CD .
ZSDSV_ETAX_DTRC-DISTRICT_CD =
ZSDSSDC023-DISTRICT_CD .
ZSDSV_ETAX_DTRC-DISTRICT_TX =
ZSDSSDC023-DISTRICT_TX .
ZSDSV_ETAX_DTRC-ZDEL_FLG =
ZSDSSDC023-ZDEL_FLG .
ZSDSV_ETAX_DTRC-ZCRT_DATE =
ZSDSSDC023-ZCRT_DATE .
ZSDSV_ETAX_DTRC-ZCRT_TIME =
ZSDSSDC023-ZCRT_TIME .
ZSDSV_ETAX_DTRC-ZCRT_USER =
ZSDSSDC023-ZCRT_USER .
ZSDSV_ETAX_DTRC-ZCRT_PGM =
ZSDSSDC023-ZCRT_PGM .
ZSDSV_ETAX_DTRC-ZUPD_DATE =
ZSDSSDC023-ZUPD_DATE .
ZSDSV_ETAX_DTRC-ZUPD_TIME =
ZSDSSDC023-ZUPD_TIME .
ZSDSV_ETAX_DTRC-ZUPD_USER =
ZSDSSDC023-ZUPD_USER .
ZSDSV_ETAX_DTRC-ZUPD_PGM =
ZSDSSDC023-ZUPD_PGM .
<VIM_TOTAL_STRUC> = ZSDSV_ETAX_DTRC.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZSDSV_ETAX_DTRC .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZSDSV_ETAX_DTRC.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZSDSV_ETAX_DTRC-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZSDSSDC023 WHERE
  PROVINCE_CD = ZSDSV_ETAX_DTRC-PROVINCE_CD AND
  DISTRICT_CD = ZSDSV_ETAX_DTRC-DISTRICT_CD .
    IF SY-SUBRC = 0.
    DELETE ZSDSSDC023 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZSDSSDC023 WHERE
  PROVINCE_CD = ZSDSV_ETAX_DTRC-PROVINCE_CD AND
  DISTRICT_CD = ZSDSV_ETAX_DTRC-DISTRICT_CD .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZSDSSDC023.
    ENDIF.
ZSDSSDC023-MANDT =
ZSDSV_ETAX_DTRC-MANDT .
ZSDSSDC023-PROVINCE_CD =
ZSDSV_ETAX_DTRC-PROVINCE_CD .
ZSDSSDC023-DISTRICT_CD =
ZSDSV_ETAX_DTRC-DISTRICT_CD .
ZSDSSDC023-DISTRICT_TX =
ZSDSV_ETAX_DTRC-DISTRICT_TX .
ZSDSSDC023-ZDEL_FLG =
ZSDSV_ETAX_DTRC-ZDEL_FLG .
ZSDSSDC023-ZCRT_DATE =
ZSDSV_ETAX_DTRC-ZCRT_DATE .
ZSDSSDC023-ZCRT_TIME =
ZSDSV_ETAX_DTRC-ZCRT_TIME .
ZSDSSDC023-ZCRT_USER =
ZSDSV_ETAX_DTRC-ZCRT_USER .
ZSDSSDC023-ZCRT_PGM =
ZSDSV_ETAX_DTRC-ZCRT_PGM .
ZSDSSDC023-ZUPD_DATE =
ZSDSV_ETAX_DTRC-ZUPD_DATE .
ZSDSSDC023-ZUPD_TIME =
ZSDSV_ETAX_DTRC-ZUPD_TIME .
ZSDSSDC023-ZUPD_USER =
ZSDSV_ETAX_DTRC-ZUPD_USER .
ZSDSSDC023-ZUPD_PGM =
ZSDSV_ETAX_DTRC-ZUPD_PGM .
    IF SY-SUBRC = 0.
    UPDATE ZSDSSDC023 ##WARN_OK.
    ELSE.
    INSERT ZSDSSDC023 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZSDSV_ETAX_DTRC-UPD_FLAG,
STATUS_ZSDSV_ETAX_DTRC-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZSDSV_ETAX_DTRC.
  SELECT SINGLE * FROM ZSDSSDC023 WHERE
PROVINCE_CD = ZSDSV_ETAX_DTRC-PROVINCE_CD AND
DISTRICT_CD = ZSDSV_ETAX_DTRC-DISTRICT_CD .
ZSDSV_ETAX_DTRC-MANDT =
ZSDSSDC023-MANDT .
ZSDSV_ETAX_DTRC-PROVINCE_CD =
ZSDSSDC023-PROVINCE_CD .
ZSDSV_ETAX_DTRC-DISTRICT_CD =
ZSDSSDC023-DISTRICT_CD .
ZSDSV_ETAX_DTRC-DISTRICT_TX =
ZSDSSDC023-DISTRICT_TX .
ZSDSV_ETAX_DTRC-ZDEL_FLG =
ZSDSSDC023-ZDEL_FLG .
ZSDSV_ETAX_DTRC-ZCRT_DATE =
ZSDSSDC023-ZCRT_DATE .
ZSDSV_ETAX_DTRC-ZCRT_TIME =
ZSDSSDC023-ZCRT_TIME .
ZSDSV_ETAX_DTRC-ZCRT_USER =
ZSDSSDC023-ZCRT_USER .
ZSDSV_ETAX_DTRC-ZCRT_PGM =
ZSDSSDC023-ZCRT_PGM .
ZSDSV_ETAX_DTRC-ZUPD_DATE =
ZSDSSDC023-ZUPD_DATE .
ZSDSV_ETAX_DTRC-ZUPD_TIME =
ZSDSSDC023-ZUPD_TIME .
ZSDSV_ETAX_DTRC-ZUPD_USER =
ZSDSSDC023-ZUPD_USER .
ZSDSV_ETAX_DTRC-ZUPD_PGM =
ZSDSSDC023-ZUPD_PGM .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZSDSV_ETAX_DTRC USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZSDSV_ETAX_DTRC-PROVINCE_CD TO
ZSDSSDC023-PROVINCE_CD .
MOVE ZSDSV_ETAX_DTRC-DISTRICT_CD TO
ZSDSSDC023-DISTRICT_CD .
MOVE ZSDSV_ETAX_DTRC-MANDT TO
ZSDSSDC023-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZSDSSDC023'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZSDSSDC023 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZSDSSDC023'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
