*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZSDSV_ETAX_DTYM1................................*
FORM GET_DATA_ZSDSV_ETAX_DTYM1.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZSDSSDC017 WHERE
(VIM_WHERETAB) .
    CLEAR ZSDSV_ETAX_DTYM1 .
ZSDSV_ETAX_DTYM1-MANDT =
ZSDSSDC017-MANDT .
ZSDSV_ETAX_DTYM1-FKART =
ZSDSSDC017-FKART .
ZSDSV_ETAX_DTYM1-DOCTY =
ZSDSSDC017-DOCTY .
ZSDSV_ETAX_DTYM1-ZDEL_FLG =
ZSDSSDC017-ZDEL_FLG .
ZSDSV_ETAX_DTYM1-ZCRT_DATE =
ZSDSSDC017-ZCRT_DATE .
ZSDSV_ETAX_DTYM1-ZCRT_TIME =
ZSDSSDC017-ZCRT_TIME .
ZSDSV_ETAX_DTYM1-ZCRT_USER =
ZSDSSDC017-ZCRT_USER .
ZSDSV_ETAX_DTYM1-ZCRT_PGM =
ZSDSSDC017-ZCRT_PGM .
ZSDSV_ETAX_DTYM1-ZUPD_DATE =
ZSDSSDC017-ZUPD_DATE .
ZSDSV_ETAX_DTYM1-ZUPD_TIME =
ZSDSSDC017-ZUPD_TIME .
ZSDSV_ETAX_DTYM1-ZUPD_USER =
ZSDSSDC017-ZUPD_USER .
ZSDSV_ETAX_DTYM1-ZUPD_PGM =
ZSDSSDC017-ZUPD_PGM .
<VIM_TOTAL_STRUC> = ZSDSV_ETAX_DTYM1.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZSDSV_ETAX_DTYM1 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZSDSV_ETAX_DTYM1.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZSDSV_ETAX_DTYM1-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZSDSSDC017 WHERE
  FKART = ZSDSV_ETAX_DTYM1-FKART .
    IF SY-SUBRC = 0.
    DELETE ZSDSSDC017 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZSDSSDC017 WHERE
  FKART = ZSDSV_ETAX_DTYM1-FKART .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZSDSSDC017.
    ENDIF.
ZSDSSDC017-MANDT =
ZSDSV_ETAX_DTYM1-MANDT .
ZSDSSDC017-FKART =
ZSDSV_ETAX_DTYM1-FKART .
ZSDSSDC017-DOCTY =
ZSDSV_ETAX_DTYM1-DOCTY .
ZSDSSDC017-ZDEL_FLG =
ZSDSV_ETAX_DTYM1-ZDEL_FLG .
ZSDSSDC017-ZCRT_DATE =
ZSDSV_ETAX_DTYM1-ZCRT_DATE .
ZSDSSDC017-ZCRT_TIME =
ZSDSV_ETAX_DTYM1-ZCRT_TIME .
ZSDSSDC017-ZCRT_USER =
ZSDSV_ETAX_DTYM1-ZCRT_USER .
ZSDSSDC017-ZCRT_PGM =
ZSDSV_ETAX_DTYM1-ZCRT_PGM .
ZSDSSDC017-ZUPD_DATE =
ZSDSV_ETAX_DTYM1-ZUPD_DATE .
ZSDSSDC017-ZUPD_TIME =
ZSDSV_ETAX_DTYM1-ZUPD_TIME .
ZSDSSDC017-ZUPD_USER =
ZSDSV_ETAX_DTYM1-ZUPD_USER .
ZSDSSDC017-ZUPD_PGM =
ZSDSV_ETAX_DTYM1-ZUPD_PGM .
    IF SY-SUBRC = 0.
    UPDATE ZSDSSDC017 ##WARN_OK.
    ELSE.
    INSERT ZSDSSDC017 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZSDSV_ETAX_DTYM1-UPD_FLAG,
STATUS_ZSDSV_ETAX_DTYM1-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZSDSV_ETAX_DTYM1.
  SELECT SINGLE * FROM ZSDSSDC017 WHERE
FKART = ZSDSV_ETAX_DTYM1-FKART .
ZSDSV_ETAX_DTYM1-MANDT =
ZSDSSDC017-MANDT .
ZSDSV_ETAX_DTYM1-FKART =
ZSDSSDC017-FKART .
ZSDSV_ETAX_DTYM1-DOCTY =
ZSDSSDC017-DOCTY .
ZSDSV_ETAX_DTYM1-ZDEL_FLG =
ZSDSSDC017-ZDEL_FLG .
ZSDSV_ETAX_DTYM1-ZCRT_DATE =
ZSDSSDC017-ZCRT_DATE .
ZSDSV_ETAX_DTYM1-ZCRT_TIME =
ZSDSSDC017-ZCRT_TIME .
ZSDSV_ETAX_DTYM1-ZCRT_USER =
ZSDSSDC017-ZCRT_USER .
ZSDSV_ETAX_DTYM1-ZCRT_PGM =
ZSDSSDC017-ZCRT_PGM .
ZSDSV_ETAX_DTYM1-ZUPD_DATE =
ZSDSSDC017-ZUPD_DATE .
ZSDSV_ETAX_DTYM1-ZUPD_TIME =
ZSDSSDC017-ZUPD_TIME .
ZSDSV_ETAX_DTYM1-ZUPD_USER =
ZSDSSDC017-ZUPD_USER .
ZSDSV_ETAX_DTYM1-ZUPD_PGM =
ZSDSSDC017-ZUPD_PGM .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZSDSV_ETAX_DTYM1 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZSDSV_ETAX_DTYM1-FKART TO
ZSDSSDC017-FKART .
MOVE ZSDSV_ETAX_DTYM1-MANDT TO
ZSDSSDC017-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZSDSSDC017'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZSDSSDC017 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZSDSSDC017'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
