FUNCTION-POOL ZSDSFI07.                     "MESSAGE-ID ..

CONSTANTS:
  BEGIN OF GC_DOCTYP,
    INV TYPE VBAK-VBTYP VALUE 'M',
    DEL TYPE VBAK-VBTYP VALUE 'J',
  END OF GC_DOCTYP.

* INCLUDE LZSDSFI07D...                      " Local class definition
* --- Global --- *
DATA: GW_VBRK TYPE VBRK,
      GW_VBRP TYPE VBRP,
      GW_LIKP TYPE LIKP,
      GW_LIPS TYPE LIPS,
      GV_SUBRC TYPE SY-SUBRC,
      GV_MSG   TYPE BAPIRET2-MESSAGE.
* --- Z_SD_CM01 --- *

* --- Z_SD_CM02 --- *
DATA: GV_BUSOBJ TYPE BAPIUSW01-OBJTYPE,
      GW_TVAK   TYPE TVAK.

DATA: GT_RETURN TYPE STANDARD TABLE OF BAPIRET2,
      GW_RETURN LIKE LINE OF GT_RETURN,
      GW_ORDER_HEADER_IN  TYPE BAPISDHD1,
      GW_ORDER_HEADER_INX TYPE BAPISDHD1X,
      GT_ORDER_ITEMS_IN   TYPE STANDARD TABLE OF BAPISDITM,
      GW_ORDER_ITEMS_IN   LIKE LINE OF GT_ORDER_ITEMS_IN,
      GT_ORDER_ITEMS_INX  TYPE STANDARD TABLE OF BAPISDITMX,
      GW_ORDER_ITEMS_INX  LIKE LINE OF GT_ORDER_ITEMS_INX,
      GT_ORDER_PARTNERS   TYPE STANDARD TABLE OF BAPIPARNR,
      GW_ORDER_PARTNERS   LIKE LINE OF GT_ORDER_PARTNERS,
      GT_ORDER_PARTNER_ADDR   TYPE STANDARD TABLE OF BAPIADDR1,
      GW_ORDER_PARTNER_ADDR   LIKE LINE OF GT_ORDER_PARTNER_ADDR,
      GT_ORDER_SCHEDULES_IN   TYPE STANDARD TABLE OF BAPISCHDL,
      GW_ORDER_SCHEDULES_IN   LIKE LINE OF GT_ORDER_SCHEDULES_IN,
      GT_ORDER_SCHEDULES_INX  TYPE STANDARD TABLE OF BAPISCHDLX,
      GW_ORDER_SCHEDULES_INX  LIKE LINE OF GT_ORDER_SCHEDULES_INX,
      GT_ORDER_CONDITIONS_IN  TYPE STANDARD TABLE OF BAPICOND,
      GW_ORDER_CONDITIONS_IN  LIKE LINE OF GT_ORDER_CONDITIONS_IN,
      GT_ORDER_CONDITIONS_INX  TYPE STANDARD TABLE OF BAPICONDX,
      GW_ORDER_CONDITIONS_INX  LIKE LINE OF GT_ORDER_CONDITIONS_INX,
      GT_ORDER_TEXT        TYPE STANDARD TABLE OF BAPISDTEXT,
      GW_ORDER_TEXT        LIKE LINE OF GT_ORDER_TEXT,
      GT_EXTENSIONIN       TYPE STANDARD TABLE OF BAPIPAREX,
      GW_EXTENSIONIN       LIKE LINE OF GT_EXTENSIONIN,
      LOGIC_SWITCH         TYPE BAPISDLS,
      GV_VBELN             TYPE VBAK-VBELN,
      GV_ADDR_LINK         TYPE BAPIPARNR-ADDR_LINK.

*DATA: GW_HEADER     TYPE ZSD_CM02_H,
*      GT_ITEM       TYPE STANDARD TABLE OF ZSD_CM02_I,
*      GW_ITEM       LIKE LINE OF GT_ITEM,
*      GT_TEXT       TYPE STANDARD TABLE OF ZSD_CM02_T,
*      GW_TEXT       LIKE LINE OF GT_TEXT.

DATA: GV_NON_VAL. "For non value case

* --- Z_SD_CM03 --- *
TABLES: VBFA.

DATA:   GT_DOCFLOW    TYPE TDT_DOCFLOW,
        GT_VBFA       TYPE STANDARD TABLE OF VBFA,
        GW_DOCFLOW    LIKE LINE OF GT_DOCFLOW,
        GW_VBFA       LIKE LINE OF GT_VBFA,
        GW_VBKD       TYPE VBKD,
        GW_VBAK       TYPE VBAK,
        GW_VBPA       TYPE VBPA.
*        GW_ZSD_CM03_H TYPE ZSD_CM03_H,
*        GW_HEADER03   TYPE ZSD_CM03_H.

RANGES: GR_VBTYP    FOR VBFA-VBTYP_N.
