*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZSDSV_ZSDSSDC013................................*
FORM GET_DATA_ZSDSV_ZSDSSDC013.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZSDSSDC013 WHERE
(VIM_WHERETAB) .
    CLEAR ZSDSV_ZSDSSDC013 .
ZSDSV_ZSDSSDC013-MANDT =
ZSDSSDC013-MANDT .
ZSDSV_ZSDSSDC013-VKGRP =
ZSDSSDC013-VKGRP .
ZSDSV_ZSDSSDC013-RUNNING =
ZSDSSDC013-RUNNING .
ZSDSV_ZSDSSDC013-QUOTAGRP =
ZSDSSDC013-QUOTAGRP .
ZSDSV_ZSDSSDC013-QUOTAGRP_DESC =
ZSDSSDC013-QUOTAGRP_DESC .
ZSDSV_ZSDSSDC013-ZDEL_FLG =
ZSDSSDC013-ZDEL_FLG .
ZSDSV_ZSDSSDC013-ZCRT_DATE =
ZSDSSDC013-ZCRT_DATE .
ZSDSV_ZSDSSDC013-ZCRT_TIME =
ZSDSSDC013-ZCRT_TIME .
ZSDSV_ZSDSSDC013-ZCRT_USER =
ZSDSSDC013-ZCRT_USER .
ZSDSV_ZSDSSDC013-ZCRT_PGM =
ZSDSSDC013-ZCRT_PGM .
ZSDSV_ZSDSSDC013-ZUPD_DATE =
ZSDSSDC013-ZUPD_DATE .
ZSDSV_ZSDSSDC013-ZUPD_TIME =
ZSDSSDC013-ZUPD_TIME .
ZSDSV_ZSDSSDC013-ZUPD_USER =
ZSDSSDC013-ZUPD_USER .
ZSDSV_ZSDSSDC013-ZUPD_PGM =
ZSDSSDC013-ZUPD_PGM .
<VIM_TOTAL_STRUC> = ZSDSV_ZSDSSDC013.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZSDSV_ZSDSSDC013 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZSDSV_ZSDSSDC013.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZSDSV_ZSDSSDC013-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZSDSSDC013 WHERE
  VKGRP = ZSDSV_ZSDSSDC013-VKGRP AND
  RUNNING = ZSDSV_ZSDSSDC013-RUNNING .
    IF SY-SUBRC = 0.
    DELETE ZSDSSDC013 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZSDSSDC013 WHERE
  VKGRP = ZSDSV_ZSDSSDC013-VKGRP AND
  RUNNING = ZSDSV_ZSDSSDC013-RUNNING .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZSDSSDC013.
    ENDIF.
ZSDSSDC013-MANDT =
ZSDSV_ZSDSSDC013-MANDT .
ZSDSSDC013-VKGRP =
ZSDSV_ZSDSSDC013-VKGRP .
ZSDSSDC013-RUNNING =
ZSDSV_ZSDSSDC013-RUNNING .
ZSDSSDC013-QUOTAGRP =
ZSDSV_ZSDSSDC013-QUOTAGRP .
ZSDSSDC013-QUOTAGRP_DESC =
ZSDSV_ZSDSSDC013-QUOTAGRP_DESC .
ZSDSSDC013-ZDEL_FLG =
ZSDSV_ZSDSSDC013-ZDEL_FLG .
ZSDSSDC013-ZCRT_DATE =
ZSDSV_ZSDSSDC013-ZCRT_DATE .
ZSDSSDC013-ZCRT_TIME =
ZSDSV_ZSDSSDC013-ZCRT_TIME .
ZSDSSDC013-ZCRT_USER =
ZSDSV_ZSDSSDC013-ZCRT_USER .
ZSDSSDC013-ZCRT_PGM =
ZSDSV_ZSDSSDC013-ZCRT_PGM .
ZSDSSDC013-ZUPD_DATE =
ZSDSV_ZSDSSDC013-ZUPD_DATE .
ZSDSSDC013-ZUPD_TIME =
ZSDSV_ZSDSSDC013-ZUPD_TIME .
ZSDSSDC013-ZUPD_USER =
ZSDSV_ZSDSSDC013-ZUPD_USER .
ZSDSSDC013-ZUPD_PGM =
ZSDSV_ZSDSSDC013-ZUPD_PGM .
    IF SY-SUBRC = 0.
    UPDATE ZSDSSDC013 ##WARN_OK.
    ELSE.
    INSERT ZSDSSDC013 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZSDSV_ZSDSSDC013-UPD_FLAG,
STATUS_ZSDSV_ZSDSSDC013-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZSDSV_ZSDSSDC013.
  SELECT SINGLE * FROM ZSDSSDC013 WHERE
VKGRP = ZSDSV_ZSDSSDC013-VKGRP AND
RUNNING = ZSDSV_ZSDSSDC013-RUNNING .
ZSDSV_ZSDSSDC013-MANDT =
ZSDSSDC013-MANDT .
ZSDSV_ZSDSSDC013-VKGRP =
ZSDSSDC013-VKGRP .
ZSDSV_ZSDSSDC013-RUNNING =
ZSDSSDC013-RUNNING .
ZSDSV_ZSDSSDC013-QUOTAGRP =
ZSDSSDC013-QUOTAGRP .
ZSDSV_ZSDSSDC013-QUOTAGRP_DESC =
ZSDSSDC013-QUOTAGRP_DESC .
ZSDSV_ZSDSSDC013-ZDEL_FLG =
ZSDSSDC013-ZDEL_FLG .
ZSDSV_ZSDSSDC013-ZCRT_DATE =
ZSDSSDC013-ZCRT_DATE .
ZSDSV_ZSDSSDC013-ZCRT_TIME =
ZSDSSDC013-ZCRT_TIME .
ZSDSV_ZSDSSDC013-ZCRT_USER =
ZSDSSDC013-ZCRT_USER .
ZSDSV_ZSDSSDC013-ZCRT_PGM =
ZSDSSDC013-ZCRT_PGM .
ZSDSV_ZSDSSDC013-ZUPD_DATE =
ZSDSSDC013-ZUPD_DATE .
ZSDSV_ZSDSSDC013-ZUPD_TIME =
ZSDSSDC013-ZUPD_TIME .
ZSDSV_ZSDSSDC013-ZUPD_USER =
ZSDSSDC013-ZUPD_USER .
ZSDSV_ZSDSSDC013-ZUPD_PGM =
ZSDSSDC013-ZUPD_PGM .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZSDSV_ZSDSSDC013 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZSDSV_ZSDSSDC013-VKGRP TO
ZSDSSDC013-VKGRP .
MOVE ZSDSV_ZSDSSDC013-RUNNING TO
ZSDSSDC013-RUNNING .
MOVE ZSDSV_ZSDSSDC013-MANDT TO
ZSDSSDC013-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZSDSSDC013'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZSDSSDC013 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZSDSSDC013'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
