*"* use this source file for the definition and implementation of
*"* local helper classes, interface definitions and type
*"* declarations
CLASS LCL_DATA DEFINITION.
  PUBLIC SECTION.
    METHODS :
      CONSTRUCKTOR.

    CLASS-METHODS :
      PHYSICAL_COUNT CHANGING C_DATA TYPE ZSDSMMS061,
      PHYSICAL_ASSET CHANGING C_DATA TYPE ZSDSFIS181.

ENDCLASS.
CLASS LCL_DATA IMPLEMENTATION.
  METHOD CONSTRUCKTOR.

  ENDMETHOD.
  METHOD PHYSICAL_COUNT.
    DATA : I_INPUT TYPE	ZSDSMMT025,
           I_MODE	 TYPE	CHAR10.

    DATA : T_OUTPUT TYPE ZSDSMMS059.

    DATA : T_SEARCH TYPE ZSDSFIS142_TT.

    DATA : E_MESTYPE TYPE  CHAR1,
           E_MESSAGE TYPE  CHAR255.

    I_MODE = C_DATA-I_MODE.
    MOVE-CORRESPONDING C_DATA TO I_INPUT.

    IF     C_DATA-I_PROCESS EQ 'SP'.
      CALL FUNCTION 'Z_SDSMM_PHYSICAL_COUNT_SP'
        EXPORTING
          I_INPUT   = I_INPUT
          I_MODE    = I_MODE
        IMPORTING
          E_MESTYPE = C_DATA-E_MESSTYP
          E_MESSAGE = C_DATA-E_MESSAGE
        TABLES
          T_SEARCH  = C_DATA-DATA_SEARCH
        CHANGING
          T_OUTPUT  = T_OUTPUT.

    ELSEIF C_DATA-I_PROCESS EQ 'FG'.
      CALL FUNCTION 'Z_SDSMM_PHYSICAL_COUNT_FG'
        EXPORTING
          I_INPUT   = I_INPUT
          I_MODE    = I_MODE
        IMPORTING
          E_MESTYPE = C_DATA-E_MESSTYP
          E_MESSAGE = C_DATA-E_MESSAGE
        TABLES
          T_SEARCH  = C_DATA-DATA_SEARCH
        CHANGING
          T_OUTPUT  = T_OUTPUT.
    ENDIF.

    IF I_MODE EQ 'GET'.
      C_DATA-E_MESSTYP   = T_OUTPUT-MESSTYP.
      C_DATA-E_MESSAGE   = T_OUTPUT-MESSAGE.
      C_DATA-DATA_RESULT = T_OUTPUT-DATA_TAB.
    ENDIF.

  ENDMETHOD.
  METHOD PHYSICAL_ASSET.

    DATA : I_INPUT TYPE  ZSDSFIT050,
           I_MODE  TYPE  CHAR10.

*    DATA : LV_ASSET TYPE ANLN1,
*           LV_SUBAT TYPE ANLN2.

    I_MODE = C_DATA-I_MODE.
    MOVE-CORRESPONDING C_DATA TO I_INPUT.

    CALL FUNCTION 'Z_SDSMM_PHYSICAL_COUNT_FIX'
      EXPORTING
        I_INPUT   = I_INPUT
        I_MODE    = I_MODE
      IMPORTING
        E_MESTYPE = C_DATA-E_MESTYPE
        E_MESSAGE = C_DATA-E_MESSAGE
        ET_RETURN = C_DATA-DATA_SEARCH
        ET_REPORT = C_DATA-DATA_REPORT
        E_SEARCH  = C_DATA-SEARF
        E_KOSTL   = C_DATA-KOSTL
        E_PERNR   = C_DATA-PERNR
        E_ASSET   = C_DATA-ANLN1 "LV_ASSET
        E_SUBST   = C_DATA-ANLN2."LV_SUBAT.

  ENDMETHOD.
ENDCLASS.
