CLASS ZCL_ZSDSMM_STOCK_NEW_DPC_EXT DEFINITION
  PUBLIC
  INHERITING FROM ZCL_ZSDSMM_STOCK_NEW_DPC
  CREATE PUBLIC .

  PUBLIC SECTION.

    CONSTANTS : BEGIN OF GC_CON,
                  SUM      TYPE C LENGTH 50 VALUE 'fgSumSet',
                  DETAIL   TYPE C LENGTH 50 VALUE 'fgDetailSet',
                  SPSUM    TYPE C LENGTH 50 VALUE 'spSumSet',
                  SPDETAIL TYPE C LENGTH 50 VALUE 'spDetailSet',
                END OF GC_CON .

    METHODS /IWBEP/IF_MGW_APPL_SRV_RUNTIME~CREATE_DEEP_ENTITY
        REDEFINITION .
    METHODS /IWBEP/IF_MGW_APPL_SRV_RUNTIME~GET_ENTITYSET
        REDEFINITION .
protected section.
private section.
ENDCLASS.



CLASS ZCL_ZSDSMM_STOCK_NEW_DPC_EXT IMPLEMENTATION.


  METHOD /IWBEP/IF_MGW_APPL_SRV_RUNTIME~CREATE_DEEP_ENTITY.
    DATA : LS_SUM    TYPE ZSDSMMS057,
           LS_DETAIL TYPE ZSDSMMS058.

    FIELD-SYMBOLS <LFS_DATA> TYPE ANY.

    IF IO_DATA_PROVIDER IS NOT INITIAL.
      IF     IV_ENTITY_SET_NAME EQ GC_CON-SUM.
        IO_DATA_PROVIDER->READ_ENTRY_DATA( IMPORTING ES_DATA = LS_SUM ).
        LCL_DATA=>GET_SUM_DATA( CHANGING C_DATA = LS_SUM ).
        ASSIGN LS_SUM TO <LFS_DATA>.
      ELSEIF IV_ENTITY_SET_NAME EQ GC_CON-DETAIL.
        IO_DATA_PROVIDER->READ_ENTRY_DATA( IMPORTING ES_DATA = LS_DETAIL ).
        LCL_DATA=>GET_SUM_DETAIL( CHANGING C_DATA = LS_DETAIL ).
        ASSIGN LS_DETAIL TO <LFS_DATA>.
      ELSEIF IV_ENTITY_SET_NAME EQ GC_CON-SPSUM.
        IO_DATA_PROVIDER->READ_ENTRY_DATA( IMPORTING ES_DATA = LS_SUM ).
        LCL_DATA=>GET_SUM_DATA_SP( CHANGING C_DATA = LS_SUM ).
        ASSIGN LS_SUM TO <LFS_DATA>.
      ELSEIF IV_ENTITY_SET_NAME EQ GC_CON-SPDETAIL.
        IO_DATA_PROVIDER->READ_ENTRY_DATA( IMPORTING ES_DATA = LS_DETAIL ).
        LCL_DATA=>GET_SUM_DETAIL_SP( CHANGING C_DATA = LS_DETAIL ).
        ASSIGN LS_DETAIL TO <LFS_DATA>.
      ENDIF.

      COPY_DATA_TO_REF(
           EXPORTING
           IS_DATA =  <LFS_DATA>
           CHANGING
           CR_DATA = ER_DEEP_ENTITY
           ).
    ENDIF.
  ENDMETHOD.


  method /IWBEP/IF_MGW_APPL_SRV_RUNTIME~GET_ENTITYSET.
**TRY.
*CALL METHOD SUPER->/IWBEP/IF_MGW_APPL_SRV_RUNTIME~GET_ENTITYSET
**  EXPORTING
**    IV_ENTITY_NAME           =
**    IV_ENTITY_SET_NAME       =
**    IV_SOURCE_NAME           =
**    IT_FILTER_SELECT_OPTIONS =
**    IT_ORDER                 =
**    IS_PAGING                =
**    IT_NAVIGATION_PATH       =
**    IT_KEY_TAB               =
**    IV_FILTER_STRING         =
**    IV_SEARCH_STRING         =
**    IO_TECH_REQUEST_CONTEXT  =
**  IMPORTING
**    ER_ENTITYSET             =
**    ES_RESPONSE_CONTEXT      =
*    .
**  CATCH /IWBEP/CX_MGW_BUSI_EXCEPTION.
**  CATCH /IWBEP/CX_MGW_TECH_EXCEPTION.
**ENDTRY.
  endmethod.
ENDCLASS.
