CLASS ZCL_ZSDSMM_RESERV_VAN_MPC_EXT DEFINITION
  PUBLIC
  INHERITING FROM ZCL_ZSDSMM_RESERV_VAN_MPC
  CREATE PUBLIC .

  PUBLIC SECTION.

    TYPES:
      BEGIN OF TS_RESERVATIONDEEP.
        INCLUDE TYPE TS_RESERVATION.
    TYPES: RESERVATIONITEMSET TYPE STANDARD TABLE OF TS_RESERVATIONITEM WITH DEFAULT KEY,
        RESPONSESET             TYPE STANDARD TABLE OF TS_RESPONSE WITH DEFAULT KEY,
      END OF TS_RESERVATIONDEEP .

    METHODS DEFINE
        REDEFINITION .
protected section.
private section.
ENDCLASS.



CLASS ZCL_ZSDSMM_RESERV_VAN_MPC_EXT IMPLEMENTATION.


  METHOD DEFINE.
    DATA LO_ENTITY_TYPE TYPE REF TO /IWBEP/IF_MGW_ODATA_ENTITY_TYP.

    SUPER->DEFINE( ).
*   Header Entity Name
    LO_ENTITY_TYPE = MODEL->GET_ENTITY_TYPE( IV_ENTITY_NAME = 'Reservation' ).

*   MPC_EXT Deep Structure Name
    LO_ENTITY_TYPE->BIND_STRUCTURE( IV_STRUCTURE_NAME = 'ZCL_ZSDSMM_RESERV_VAN_MPC_EXT=>TS_RESERVATIONDEEP' ).

  ENDMETHOD.
ENDCLASS.
