*"* use this source file for the definition and implementation of
*"* local helper classes, interface definitions and type
*"* declarations
CLASS LCL_DATA DEFINITION.
  PUBLIC SECTION.
    METHODS :
      CONSTRUCTOR.

    CLASS-METHODS :
      GET_SUM_DATA CHANGING C_DATA TYPE ZSDSMMS057,
      GET_SUM_DATA_SP CHANGING C_DATA TYPE ZSDSMMS057,
      GET_SUM_DETAIL CHANGING C_DATA TYPE ZSDSMMS058,
      GET_SUM_DETAIL_SP CHANGING C_DATA TYPE ZSDSMMS058.

ENDCLASS.
CLASS LCL_DATA IMPLEMENTATION.
  METHOD CONSTRUCTOR.

  ENDMETHOD.
  METHOD GET_SUM_DATA.
    DATA LCL_STOCK TYPE REF TO ZCL_SDSMM_AVAILABLE_STOCK_NEW.

    DATA : LS_SELECTION TYPE ZSDSMMS056.

    IF LCL_STOCK IS NOT BOUND.
      CREATE OBJECT LCL_STOCK.
    ENDIF.

    LS_SELECTION-PH1 = C_DATA-SELECTION_PH1.
    LS_SELECTION-PH2 = C_DATA-SELECTION_PH2.
    LS_SELECTION-PH3 = C_DATA-SELECTION_PH3.
    LS_SELECTION-MATNR = C_DATA-SELECTION_MAT.

    C_DATA-SUM_DATA = LCL_STOCK->FG( I_WERKS          = C_DATA-WERKS
                                     I_DATA_SELECTION = LS_SELECTION ).

  ENDMETHOD.
  METHOD GET_SUM_DATA_SP.
    DATA LCL_STOCK TYPE REF TO ZCL_SDSMM_AVAILABLE_STOCK_NEW.

    DATA : LS_SELECTION TYPE ZSDSMMS056.

    IF LCL_STOCK IS NOT BOUND.
      CREATE OBJECT LCL_STOCK.
    ENDIF.

    LS_SELECTION-PH1 = C_DATA-SELECTION_PH1.
    LS_SELECTION-PH2 = C_DATA-SELECTION_PH2.
    LS_SELECTION-PH3 = C_DATA-SELECTION_PH3.
    LS_SELECTION-MATNR = C_DATA-SELECTION_MAT.

    C_DATA-SUM_DATA = LCL_STOCK->SP( I_WERKS          = C_DATA-WERKS
                                     I_DATA_SELECTION = LS_SELECTION ).

  ENDMETHOD.
  METHOD GET_SUM_DETAIL.
    DATA LCL_STOCK TYPE REF TO ZCL_SDSMM_AVAILABLE_STOCK_NEW.

    DATA : LS_SELECTION TYPE ZSDSMMS049.

    IF LCL_STOCK IS NOT BOUND.
      CREATE OBJECT LCL_STOCK.
    ENDIF.

    LS_SELECTION-PH1   = C_DATA-SELECTION_PH1.
    LS_SELECTION-PH2   = C_DATA-SELECTION_PH2.
    LS_SELECTION-PH3   = C_DATA-SELECTION_PH3.
    LS_SELECTION-LGORT = C_DATA-SELECTION_LOCATION.
    LS_SELECTION-MATNR = C_DATA-SELECTION_MAT.

    C_DATA-DETAIL_DATA = LCL_STOCK->FG_DETAIL( I_WERKS          = C_DATA-WERKS
                                               I_DATA_SELECTION = LS_SELECTION ).

  ENDMETHOD.
  METHOD GET_SUM_DETAIL_SP.
    DATA LCL_STOCK TYPE REF TO ZCL_SDSMM_AVAILABLE_STOCK_NEW.

    DATA : LS_SELECTION TYPE ZSDSMMS049.

    IF LCL_STOCK IS NOT BOUND.
      CREATE OBJECT LCL_STOCK.
    ENDIF.

    LS_SELECTION-PH1   = C_DATA-SELECTION_PH1.
    LS_SELECTION-PH2   = C_DATA-SELECTION_PH2.
    LS_SELECTION-PH3   = C_DATA-SELECTION_PH3.
    LS_SELECTION-LGORT = C_DATA-SELECTION_LOCATION.
    LS_SELECTION-MATNR = C_DATA-SELECTION_MAT.

    C_DATA-DETAIL_DATA = LCL_STOCK->SP_DETAIL( I_WERKS          = C_DATA-WERKS
                                               I_DATA_SELECTION = LS_SELECTION ).

  ENDMETHOD.
ENDCLASS.
