CLASS ZCL_ZSDSMM_PHYSICAL_CO_DPC_EXT DEFINITION
  PUBLIC
  INHERITING FROM ZCL_ZSDSMM_PHYSICAL_CO_DPC
  CREATE PUBLIC .

  PUBLIC SECTION.

    CONSTANTS : BEGIN OF GC_CON,
                  PHYSICAL_COUNT TYPE C LENGTH 20 VALUE 'dataPhysicalCountSet',
                  PHYSICAL_ASSET TYPE C LENGTH 20 VALUE 'dataPhysicalAssetSet',
                END OF GC_CON.

    METHODS /IWBEP/IF_MGW_APPL_SRV_RUNTIME~CREATE_DEEP_ENTITY
        REDEFINITION .
protected section.

  methods DATAPHYSICALCOUN_GET_ENTITYSET
    redefinition .
private section.
ENDCLASS.



CLASS ZCL_ZSDSMM_PHYSICAL_CO_DPC_EXT IMPLEMENTATION.


  METHOD /IWBEP/IF_MGW_APPL_SRV_RUNTIME~CREATE_DEEP_ENTITY.
    DATA : LS_DATA  TYPE ZSDSMMS061,
           LS_ASSET TYPE ZSDSFIS181.

    FIELD-SYMBOLS <LFS_DATA> TYPE ANY.

    IF IO_DATA_PROVIDER IS NOT INITIAL.
      IF     IV_ENTITY_SET_NAME EQ GC_CON-PHYSICAL_COUNT.
        IO_DATA_PROVIDER->READ_ENTRY_DATA( IMPORTING ES_DATA = LS_DATA ).
        LCL_DATA=>PHYSICAL_COUNT( CHANGING C_DATA = LS_DATA ).
        ASSIGN LS_DATA TO <LFS_DATA>.
      ELSEIF IV_ENTITY_SET_NAME EQ GC_CON-PHYSICAL_ASSET.
        IO_DATA_PROVIDER->READ_ENTRY_DATA( IMPORTING ES_DATA = LS_ASSET ).
        LCL_DATA=>PHYSICAL_ASSET( CHANGING C_DATA = LS_ASSET ).
        ASSIGN LS_ASSET TO <LFS_DATA>.
      ENDIF.

      COPY_DATA_TO_REF(
           EXPORTING
           IS_DATA = <LFS_DATA>
           CHANGING
           CR_DATA = ER_DEEP_ENTITY
           ).
    ENDIF.
  ENDMETHOD.


  method DATAPHYSICALCOUN_GET_ENTITYSET.
**TRY.
*CALL METHOD SUPER->DATAPHYSICALCOUN_GET_ENTITYSET
*  EXPORTING
*    IV_ENTITY_NAME           =
*    IV_ENTITY_SET_NAME       =
*    IV_SOURCE_NAME           =
*    IT_FILTER_SELECT_OPTIONS =
*    IS_PAGING                =
*    IT_KEY_TAB               =
*    IT_NAVIGATION_PATH       =
*    IT_ORDER                 =
*    IV_FILTER_STRING         =
*    IV_SEARCH_STRING         =
**    IO_TECH_REQUEST_CONTEXT  =
**  IMPORTING
**    ET_ENTITYSET             =
**    ES_RESPONSE_CONTEXT      =
*    .
**  CATCH /IWBEP/CX_MGW_BUSI_EXCEPTION.
**  CATCH /IWBEP/CX_MGW_TECH_EXCEPTION.
**ENDTRY.
  endmethod.
ENDCLASS.
