class ZCL_ZSDSMM_STOCK_DPC_EXT definition
  public
  inheriting from ZCL_ZSDSMM_STOCK_DPC
  create public .

public section.
protected section.

  methods AVAILABLESTOCKSE_GET_ENTITY
    redefinition .
  methods AVAILABLESTOCKSE_GET_ENTITYSET
    redefinition .
private section.
ENDCLASS.



CLASS ZCL_ZSDSMM_STOCK_DPC_EXT IMPLEMENTATION.


  method AVAILABLESTOCKSE_GET_ENTITY.
**TRY.
*CALL METHOD SUPER->AVAILABLESTOCKSE_GET_ENTITY
*  EXPORTING
*    IV_ENTITY_NAME          =
*    IV_ENTITY_SET_NAME      =
*    IV_SOURCE_NAME          =
*    IT_KEY_TAB              =
**    IO_REQUEST_OBJECT       =
**    IO_TECH_REQUEST_CONTEXT =
*    IT_NAVIGATION_PATH      =
**  IMPORTING
**    ER_ENTITY               =
**    ES_RESPONSE_CONTEXT     =
*    .
**  CATCH /IWBEP/CX_MGW_BUSI_EXCEPTION.
**  CATCH /IWBEP/CX_MGW_TECH_EXCEPTION.
**ENDTRY.
  endmethod.


  METHOD AVAILABLESTOCKSE_GET_ENTITYSET.
**TRY.
*CALL METHOD SUPER->AVAILABLESTOCKSE_GET_ENTITYSET
*  EXPORTING
*    IV_ENTITY_NAME           =
*    IV_ENTITY_SET_NAME       =
*    IV_SOURCE_NAME           =
*    IT_FILTER_SELECT_OPTIONS =
*    IS_PAGING                =
*    IT_KEY_TAB               =
*    IT_NAVIGATION_PATH       =
*    IT_ORDER                 =
*    IV_FILTER_STRING         =
*    IV_SEARCH_STRING         =
**    IO_TECH_REQUEST_CONTEXT  =
**  IMPORTING
**    ET_ENTITYSET             =
**    ES_RESPONSE_CONTEXT      =
*    .
**  CATCH /IWBEP/CX_MGW_BUSI_EXCEPTION.
**  CATCH /IWBEP/CX_MGW_TECH_EXCEPTION.
**ENDTRY.

* et_entityset





    DATA:
      LF_MATNR  TYPE MATNR,
      LS_ENTITY TYPE ZCL_ZSDSMM_STOCK_MPC=>TS_AVAILABLESTOCK,

      LT_RESULT TYPE ZSDSMMS026_TT.

    READ TABLE IT_FILTER_SELECT_OPTIONS INTO DATA(LS_FILTER)
      WITH KEY PROPERTY = 'MaterialNo' .
    IF SY-SUBRC IS INITIAL.
      READ TABLE LS_FILTER-SELECT_OPTIONS INTO DATA(LS_SELECT_OPTIONS) INDEX 1 .
      IF SY-SUBRC = 0 .
        LF_MATNR  = LS_SELECT_OPTIONS-LOW .
      ENDIF.
    ENDIF.

    CALL METHOD ZCL_SDSMM_AVAILABLE_STOCK=>AVAILABLE_STOCK_PROCESS
      EXPORTING
        IF_MATNR  = LF_MATNR
      IMPORTING
        ET_RESULT = LT_RESULT.

    LOOP AT LT_RESULT INTO DATA(LS_RESULT) .
      MOVE-CORRESPONDING LS_RESULT TO LS_ENTITY.
      APPEND LS_ENTITY TO ET_ENTITYSET .
    ENDLOOP.
  ENDMETHOD.
ENDCLASS.
