FUNCTION-POOL ZSDSMM03.                     "MESSAGE-ID ..

* INCLUDE LZSDSMM03D...                      " Local class definition

TYPES : BEGIN OF GY_OBJK,
  OBKNR TYPE OBJK-OBKNR,
  SERNR TYPE OBJK-SERNR,
  MATNR TYPE OBJK-MATNR,
END OF GY_OBJK.

TYPES : BEGIN OF GY_MARA,
  MATNR TYPE MARA-MATNR,
  PRDHA TYPE MARA-PRDHA,
END OF GY_MARA.

TYPES : BEGIN OF GY_SER01,
 OBKNR   TYPE SER01-OBKNR,
 LIEF_NR TYPE SER01-LIEF_NR,
 POSNR   TYPE SER01-POSNR,
 VBTYP   TYPE SER01-VBTYP,
END OF GY_SER01.

TYPES : BEGIN OF GY_VBFA,
  VBELV TYPE VBFA-VBELV,
  POSNV TYPE VBFA-POSNV,
  VBELN TYPE VBFA-VBELN,
  POSNN TYPE VBFA-POSNN,
END OF GY_VBFA.

TYPES : BEGIN OF GY_VBRK,
  VBELN TYPE VBRK-VBELN,
  FKDAT TYPE VBRK-FKDAT,
  ZUONR TYPE VBRK-ZUONR,
  POSNR TYPE VBRP-POSNR,
  PRCTR TYPE VBRP-PRCTR,
END OF GY_VBRK.

TYPES : BEGIN OF GY_VBAK,
  VBELN TYPE VBAK-VBELN,
  KUNNR TYPE VBAK-KUNNR,
  VKBUR TYPE VBAK-VKBUR,
  VKGRP TYPE VBAK-VKGRP,
END OF GY_VBAK.

TYPES : BEGIN OF GY_KNA1,
  KUNNR TYPE KNA1-KUNNR,
  NAME1 TYPE ADRC-NAME1,
  NAME2 TYPE ADRC-NAME2,
  NAME3 TYPE ADRC-NAME3,
  NAME4 TYPE ADRC-NAME4,
END OF GY_KNA1.

TYPES : BEGIN OF GY_SERIAL_MAT,
  SERNR TYPE OBJK-SERNR,
  MATNR TYPE OBJK-MATNR,
END OF GY_SERIAL_MAT.

*&---------------------------------------------------------------------*
*  VARIABLE
*&---------------------------------------------------------------------*
DATA : GT_OBJK TYPE TABLE OF GY_OBJK,
       GS_OBJK TYPE GY_OBJK.

DATA : GT_MARA TYPE TABLE OF GY_MARA,
       GS_MARA TYPE GY_MARA.

DATA : GT_SER01 TYPE TABLE OF GY_SER01,
       GS_SER01 TYPE GY_SER01.

DATA : GT_VBFA TYPE TABLE OF GY_VBFA,
       GS_VBFA TYPE GY_VBFA.

DATA : GT_VBRK TYPE TABLE OF GY_VBRK,
       GS_VBRK TYPE GY_VBRK.

DATA : GT_VBAK TYPE TABLE OF GY_VBAK,
       GS_VBAK TYPE GY_VBAK.

DATA : GT_KNA1 TYPE TABLE OF GY_KNA1,
       GS_KNA1 TYPE GY_KNA1.

DATA : GT_SERIAL_MAT TYPE TABLE OF GY_SERIAL_MAT,
       GS_SERIAL_MAT TYPE GY_SERIAL_MAT.         "MESSAGE-ID ..


DATA : GV_MATNR TYPE OBJK-MATNR,
       GV_SERNR TYPE OBJK-SERNR.
