*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZSDSV_INSURANCE.................................*
FORM GET_DATA_ZSDSV_INSURANCE.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZSDSMMT008 WHERE
(VIM_WHERETAB) .
    CLEAR ZSDSV_INSURANCE .
ZSDSV_INSURANCE-MANDT =
ZSDSMMT008-MANDT .
ZSDSV_INSURANCE-CODE =
ZSDSMMT008-CODE .
ZSDSV_INSURANCE-SEQUENCE =
ZSDSMMT008-SEQUENCE .
ZSDSV_INSURANCE-INS_PERCENT =
ZSDSMMT008-INS_PERCENT .
ZSDSV_INSURANCE-ZDEL_FLG =
ZSDSMMT008-ZDEL_FLG .
ZSDSV_INSURANCE-ZCRT_DATE =
ZSDSMMT008-ZCRT_DATE .
ZSDSV_INSURANCE-ZCRT_TIME =
ZSDSMMT008-ZCRT_TIME .
ZSDSV_INSURANCE-ZCRT_USER =
ZSDSMMT008-ZCRT_USER .
ZSDSV_INSURANCE-ZCRT_PGM =
ZSDSMMT008-ZCRT_PGM .
ZSDSV_INSURANCE-ZUPD_DATE =
ZSDSMMT008-ZUPD_DATE .
ZSDSV_INSURANCE-ZUPD_TIME =
ZSDSMMT008-ZUPD_TIME .
ZSDSV_INSURANCE-ZUPD_USER =
ZSDSMMT008-ZUPD_USER .
ZSDSV_INSURANCE-ZUPD_PGM =
ZSDSMMT008-ZUPD_PGM .
    SELECT SINGLE * FROM T173 WHERE
VSART = ZSDSMMT008-CODE .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T173T WHERE
VSART = T173-VSART AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZSDSV_INSURANCE-BEZEI =
T173T-BEZEI .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = ZSDSV_INSURANCE.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZSDSV_INSURANCE .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZSDSV_INSURANCE.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZSDSV_INSURANCE-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZSDSMMT008 WHERE
  CODE = ZSDSV_INSURANCE-CODE AND
  SEQUENCE = ZSDSV_INSURANCE-SEQUENCE .
    IF SY-SUBRC = 0.
    DELETE ZSDSMMT008 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZSDSMMT008 WHERE
  CODE = ZSDSV_INSURANCE-CODE AND
  SEQUENCE = ZSDSV_INSURANCE-SEQUENCE .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZSDSMMT008.
    ENDIF.
ZSDSMMT008-MANDT =
ZSDSV_INSURANCE-MANDT .
ZSDSMMT008-CODE =
ZSDSV_INSURANCE-CODE .
ZSDSMMT008-SEQUENCE =
ZSDSV_INSURANCE-SEQUENCE .
ZSDSMMT008-INS_PERCENT =
ZSDSV_INSURANCE-INS_PERCENT .
ZSDSMMT008-ZDEL_FLG =
ZSDSV_INSURANCE-ZDEL_FLG .
ZSDSMMT008-ZCRT_DATE =
ZSDSV_INSURANCE-ZCRT_DATE .
ZSDSMMT008-ZCRT_TIME =
ZSDSV_INSURANCE-ZCRT_TIME .
ZSDSMMT008-ZCRT_USER =
ZSDSV_INSURANCE-ZCRT_USER .
ZSDSMMT008-ZCRT_PGM =
ZSDSV_INSURANCE-ZCRT_PGM .
ZSDSMMT008-ZUPD_DATE =
ZSDSV_INSURANCE-ZUPD_DATE .
ZSDSMMT008-ZUPD_TIME =
ZSDSV_INSURANCE-ZUPD_TIME .
ZSDSMMT008-ZUPD_USER =
ZSDSV_INSURANCE-ZUPD_USER .
ZSDSMMT008-ZUPD_PGM =
ZSDSV_INSURANCE-ZUPD_PGM .
    IF SY-SUBRC = 0.
    UPDATE ZSDSMMT008 ##WARN_OK.
    ELSE.
    INSERT ZSDSMMT008 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZSDSV_INSURANCE-UPD_FLAG,
STATUS_ZSDSV_INSURANCE-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZSDSV_INSURANCE.
  SELECT SINGLE * FROM ZSDSMMT008 WHERE
CODE = ZSDSV_INSURANCE-CODE AND
SEQUENCE = ZSDSV_INSURANCE-SEQUENCE .
ZSDSV_INSURANCE-MANDT =
ZSDSMMT008-MANDT .
ZSDSV_INSURANCE-CODE =
ZSDSMMT008-CODE .
ZSDSV_INSURANCE-SEQUENCE =
ZSDSMMT008-SEQUENCE .
ZSDSV_INSURANCE-INS_PERCENT =
ZSDSMMT008-INS_PERCENT .
ZSDSV_INSURANCE-ZDEL_FLG =
ZSDSMMT008-ZDEL_FLG .
ZSDSV_INSURANCE-ZCRT_DATE =
ZSDSMMT008-ZCRT_DATE .
ZSDSV_INSURANCE-ZCRT_TIME =
ZSDSMMT008-ZCRT_TIME .
ZSDSV_INSURANCE-ZCRT_USER =
ZSDSMMT008-ZCRT_USER .
ZSDSV_INSURANCE-ZCRT_PGM =
ZSDSMMT008-ZCRT_PGM .
ZSDSV_INSURANCE-ZUPD_DATE =
ZSDSMMT008-ZUPD_DATE .
ZSDSV_INSURANCE-ZUPD_TIME =
ZSDSMMT008-ZUPD_TIME .
ZSDSV_INSURANCE-ZUPD_USER =
ZSDSMMT008-ZUPD_USER .
ZSDSV_INSURANCE-ZUPD_PGM =
ZSDSMMT008-ZUPD_PGM .
    SELECT SINGLE * FROM T173 WHERE
VSART = ZSDSMMT008-CODE .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T173T WHERE
VSART = T173-VSART AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZSDSV_INSURANCE-BEZEI =
T173T-BEZEI .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZSDSV_INSURANCE-BEZEI .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZSDSV_INSURANCE-BEZEI .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZSDSV_INSURANCE USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZSDSV_INSURANCE-CODE TO
ZSDSMMT008-CODE .
MOVE ZSDSV_INSURANCE-SEQUENCE TO
ZSDSMMT008-SEQUENCE .
MOVE ZSDSV_INSURANCE-MANDT TO
ZSDSMMT008-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZSDSMMT008'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZSDSMMT008 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZSDSMMT008'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZSDSV_INSURANCE USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZSDSMMT008-MANDT =
ZSDSV_INSURANCE-MANDT .
ZSDSMMT008-CODE =
ZSDSV_INSURANCE-CODE .
ZSDSMMT008-SEQUENCE =
ZSDSV_INSURANCE-SEQUENCE .
ZSDSMMT008-INS_PERCENT =
ZSDSV_INSURANCE-INS_PERCENT .
ZSDSMMT008-ZDEL_FLG =
ZSDSV_INSURANCE-ZDEL_FLG .
ZSDSMMT008-ZCRT_DATE =
ZSDSV_INSURANCE-ZCRT_DATE .
ZSDSMMT008-ZCRT_TIME =
ZSDSV_INSURANCE-ZCRT_TIME .
ZSDSMMT008-ZCRT_USER =
ZSDSV_INSURANCE-ZCRT_USER .
ZSDSMMT008-ZCRT_PGM =
ZSDSV_INSURANCE-ZCRT_PGM .
ZSDSMMT008-ZUPD_DATE =
ZSDSV_INSURANCE-ZUPD_DATE .
ZSDSMMT008-ZUPD_TIME =
ZSDSV_INSURANCE-ZUPD_TIME .
ZSDSMMT008-ZUPD_USER =
ZSDSV_INSURANCE-ZUPD_USER .
ZSDSMMT008-ZUPD_PGM =
ZSDSV_INSURANCE-ZUPD_PGM .
    SELECT SINGLE * FROM T173 WHERE
VSART = ZSDSMMT008-CODE .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T173T WHERE
VSART = T173-VSART AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZSDSV_INSURANCE-BEZEI =
T173T-BEZEI .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZSDSV_INSURANCE-BEZEI .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZSDSV_INSURANCE-BEZEI .
    ENDIF.
ENDFORM.
