FUNCTION-POOL ZSDSMM06.                     "MESSAGE-ID ..

TYPE-POOLS : TRUXS.

TYPES: BEGIN OF GTY_OUT.
        INCLUDE STRUCTURE ZSDSMMS012.
TYPES: END OF GTY_OUT.

TYPES : BEGIN OF GY_T024X,
  LABOR TYPE T024X-LABOR,
  LBTXT TYPE T024X-LBTXT,
END OF GY_T024X.

DATA: GT_MVKE  TYPE STANDARD TABLE OF MVKE,
      GS_MVKE LIKE LINE OF GT_MVKE,
      GT_MBEW  TYPE STANDARD TABLE OF MBEW,
      GS_MBEW LIKE LINE OF GT_MBEW,
      GT_MARC  TYPE STANDARD TABLE OF MARC,
      GS_MARC LIKE LINE OF GT_MARC,
      GT_OUT   TYPE STANDARD TABLE OF GTY_OUT,
      GS_OUT  LIKE LINE OF GT_OUT,
      GT_MARA  TYPE SORTED TABLE OF MARA WITH UNIQUE KEY MATNR,
      GS_MARA LIKE LINE OF GT_MARA,
      GT_MAKT  TYPE STANDARD TABLE OF MAKT,
      GS_MAKT LIKE LINE OF GT_MAKT,
      GT_CABN  TYPE STANDARD TABLE OF CABN,
      GS_CABN LIKE LINE OF GT_CABN,
      GT_AUSP  TYPE STANDARD TABLE OF AUSP,
      GS_AUSP LIKE LINE OF GT_AUSP.

DATA: GT_MAST  TYPE STANDARD TABLE OF MAST,
      GS_MAST LIKE LINE OF GT_MAST,
      GT_STKO  TYPE STANDARD TABLE OF STKO,     "WCH181113 Fix alternative BOM
      GS_STKO LIKE LINE OF GT_STKO,            "WCH181113 Fix alternative BOM
      GT_STAS  TYPE STANDARD TABLE OF STAS,     "WCH181113 Fix alternative BOM
      GS_STAS LIKE LINE OF GT_STAS,            "WCH181113 Fix alternative BOM
      GT_STPO  TYPE STANDARD TABLE OF STPO,
      GS_STPO LIKE LINE OF GT_STPO.
*DATA: GT_ZTCS_MA_PRODUCT  TYPE STANDARD TABLE OF ZTCS_MA_PRODUCT,
*      GS_ZTCS_MA_PRODUCT  LIKE LINE OF GT_ZTCS_MA_PRODUCT.
DATA: GT_MARD   TYPE STANDARD TABLE OF MARD,
      GS_MARD  LIKE LINE OF GT_MARD.


DATA : GT_T024X TYPE TABLE OF GY_T024X,
       GS_T024X TYPE GY_T024X.
DATA : GT_ZDSMMC013 TYPE TABLE OF ZDSMMC013,
       GS_ZDSMMC013 TYPE  ZDSMMC013,
       GT_ZDSMMC002 TYPE TABLE OF ZDSMMC002,
       GS_ZDSMMC002 TYPE  ZDSMMC002,
       GT_ZDSMMC010 TYPE TABLE OF ZDSMMC010,
       GS_ZDSMMC010 TYPE  ZDSMMC010,
       GT_ZDSMMC009 TYPE TABLE OF ZDSMMC009,
       GS_ZDSMMC009 TYPE  ZDSMMC009,
       GT_ZDSMMC028 TYPE TABLE OF ZDSMMC028,
       GS_ZDSMMC028 TYPE  ZDSMMC028,
       GT_ZDSMMC015 TYPE TABLE OF ZDSMMC015,
       GS_ZDSMMC015 TYPE  ZDSMMC015,
       GT_ZDSMMC001 TYPE TABLE OF ZDSMMC001,
       GS_ZDSMMC001 TYPE  ZDSMMC001.


RANGES: GR_WERKS FOR MARC-WERKS,
        GR_ATNAM FOR CABN-ATNAM.
