*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZSDSV_AVG_CLEAR.................................*
FORM GET_DATA_ZSDSV_AVG_CLEAR.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZSDSMMT009 WHERE
(VIM_WHERETAB) .
    CLEAR ZSDSV_AVG_CLEAR .
ZSDSV_AVG_CLEAR-MANDT =
ZSDSMMT009-MANDT .
ZSDSV_AVG_CLEAR-CODE =
ZSDSMMT009-CODE .
ZSDSV_AVG_CLEAR-IHREZ =
ZSDSMMT009-IHREZ .
ZSDSV_AVG_CLEAR-VOL_OPTION =
ZSDSMMT009-VOL_OPTION .
ZSDSV_AVG_CLEAR-VOLUME =
ZSDSMMT009-VOLUME .
ZSDSV_AVG_CLEAR-AVG_CLEAR =
ZSDSMMT009-AVG_CLEAR .
ZSDSV_AVG_CLEAR-ZDEL_FLG =
ZSDSMMT009-ZDEL_FLG .
ZSDSV_AVG_CLEAR-ZCRT_DATE =
ZSDSMMT009-ZCRT_DATE .
ZSDSV_AVG_CLEAR-ZCRT_TIME =
ZSDSMMT009-ZCRT_TIME .
ZSDSV_AVG_CLEAR-ZCRT_USER =
ZSDSMMT009-ZCRT_USER .
ZSDSV_AVG_CLEAR-ZCRT_PGM =
ZSDSMMT009-ZCRT_PGM .
ZSDSV_AVG_CLEAR-ZUPD_DATE =
ZSDSMMT009-ZUPD_DATE .
ZSDSV_AVG_CLEAR-ZUPD_TIME =
ZSDSMMT009-ZUPD_TIME .
ZSDSV_AVG_CLEAR-ZUPD_USER =
ZSDSMMT009-ZUPD_USER .
ZSDSV_AVG_CLEAR-ZUPD_PGM =
ZSDSMMT009-ZUPD_PGM .
    SELECT SINGLE * FROM T173 WHERE
VSART = ZSDSMMT009-CODE .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T173T WHERE
VSART = T173-VSART AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZSDSV_AVG_CLEAR-BEZEI =
T173T-BEZEI .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = ZSDSV_AVG_CLEAR.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZSDSV_AVG_CLEAR .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZSDSV_AVG_CLEAR.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZSDSV_AVG_CLEAR-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZSDSMMT009 WHERE
  CODE = ZSDSV_AVG_CLEAR-CODE AND
  IHREZ = ZSDSV_AVG_CLEAR-IHREZ AND
  VOL_OPTION = ZSDSV_AVG_CLEAR-VOL_OPTION AND
  VOLUME = ZSDSV_AVG_CLEAR-VOLUME .
    IF SY-SUBRC = 0.
    DELETE ZSDSMMT009 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZSDSMMT009 WHERE
  CODE = ZSDSV_AVG_CLEAR-CODE AND
  IHREZ = ZSDSV_AVG_CLEAR-IHREZ AND
  VOL_OPTION = ZSDSV_AVG_CLEAR-VOL_OPTION AND
  VOLUME = ZSDSV_AVG_CLEAR-VOLUME .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZSDSMMT009.
    ENDIF.
ZSDSMMT009-MANDT =
ZSDSV_AVG_CLEAR-MANDT .
ZSDSMMT009-CODE =
ZSDSV_AVG_CLEAR-CODE .
ZSDSMMT009-IHREZ =
ZSDSV_AVG_CLEAR-IHREZ .
ZSDSMMT009-VOL_OPTION =
ZSDSV_AVG_CLEAR-VOL_OPTION .
ZSDSMMT009-VOLUME =
ZSDSV_AVG_CLEAR-VOLUME .
ZSDSMMT009-AVG_CLEAR =
ZSDSV_AVG_CLEAR-AVG_CLEAR .
ZSDSMMT009-ZDEL_FLG =
ZSDSV_AVG_CLEAR-ZDEL_FLG .
ZSDSMMT009-ZCRT_DATE =
ZSDSV_AVG_CLEAR-ZCRT_DATE .
ZSDSMMT009-ZCRT_TIME =
ZSDSV_AVG_CLEAR-ZCRT_TIME .
ZSDSMMT009-ZCRT_USER =
ZSDSV_AVG_CLEAR-ZCRT_USER .
ZSDSMMT009-ZCRT_PGM =
ZSDSV_AVG_CLEAR-ZCRT_PGM .
ZSDSMMT009-ZUPD_DATE =
ZSDSV_AVG_CLEAR-ZUPD_DATE .
ZSDSMMT009-ZUPD_TIME =
ZSDSV_AVG_CLEAR-ZUPD_TIME .
ZSDSMMT009-ZUPD_USER =
ZSDSV_AVG_CLEAR-ZUPD_USER .
ZSDSMMT009-ZUPD_PGM =
ZSDSV_AVG_CLEAR-ZUPD_PGM .
    IF SY-SUBRC = 0.
    UPDATE ZSDSMMT009 ##WARN_OK.
    ELSE.
    INSERT ZSDSMMT009 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZSDSV_AVG_CLEAR-UPD_FLAG,
STATUS_ZSDSV_AVG_CLEAR-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZSDSV_AVG_CLEAR.
  SELECT SINGLE * FROM ZSDSMMT009 WHERE
CODE = ZSDSV_AVG_CLEAR-CODE AND
IHREZ = ZSDSV_AVG_CLEAR-IHREZ AND
VOL_OPTION = ZSDSV_AVG_CLEAR-VOL_OPTION AND
VOLUME = ZSDSV_AVG_CLEAR-VOLUME .
ZSDSV_AVG_CLEAR-MANDT =
ZSDSMMT009-MANDT .
ZSDSV_AVG_CLEAR-CODE =
ZSDSMMT009-CODE .
ZSDSV_AVG_CLEAR-IHREZ =
ZSDSMMT009-IHREZ .
ZSDSV_AVG_CLEAR-VOL_OPTION =
ZSDSMMT009-VOL_OPTION .
ZSDSV_AVG_CLEAR-VOLUME =
ZSDSMMT009-VOLUME .
ZSDSV_AVG_CLEAR-AVG_CLEAR =
ZSDSMMT009-AVG_CLEAR .
ZSDSV_AVG_CLEAR-ZDEL_FLG =
ZSDSMMT009-ZDEL_FLG .
ZSDSV_AVG_CLEAR-ZCRT_DATE =
ZSDSMMT009-ZCRT_DATE .
ZSDSV_AVG_CLEAR-ZCRT_TIME =
ZSDSMMT009-ZCRT_TIME .
ZSDSV_AVG_CLEAR-ZCRT_USER =
ZSDSMMT009-ZCRT_USER .
ZSDSV_AVG_CLEAR-ZCRT_PGM =
ZSDSMMT009-ZCRT_PGM .
ZSDSV_AVG_CLEAR-ZUPD_DATE =
ZSDSMMT009-ZUPD_DATE .
ZSDSV_AVG_CLEAR-ZUPD_TIME =
ZSDSMMT009-ZUPD_TIME .
ZSDSV_AVG_CLEAR-ZUPD_USER =
ZSDSMMT009-ZUPD_USER .
ZSDSV_AVG_CLEAR-ZUPD_PGM =
ZSDSMMT009-ZUPD_PGM .
    SELECT SINGLE * FROM T173 WHERE
VSART = ZSDSMMT009-CODE .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T173T WHERE
VSART = T173-VSART AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZSDSV_AVG_CLEAR-BEZEI =
T173T-BEZEI .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZSDSV_AVG_CLEAR-BEZEI .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZSDSV_AVG_CLEAR-BEZEI .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZSDSV_AVG_CLEAR USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZSDSV_AVG_CLEAR-CODE TO
ZSDSMMT009-CODE .
MOVE ZSDSV_AVG_CLEAR-IHREZ TO
ZSDSMMT009-IHREZ .
MOVE ZSDSV_AVG_CLEAR-VOL_OPTION TO
ZSDSMMT009-VOL_OPTION .
MOVE ZSDSV_AVG_CLEAR-VOLUME TO
ZSDSMMT009-VOLUME .
MOVE ZSDSV_AVG_CLEAR-MANDT TO
ZSDSMMT009-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZSDSMMT009'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZSDSMMT009 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZSDSMMT009'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZSDSV_AVG_CLEAR USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZSDSMMT009-MANDT =
ZSDSV_AVG_CLEAR-MANDT .
ZSDSMMT009-CODE =
ZSDSV_AVG_CLEAR-CODE .
ZSDSMMT009-IHREZ =
ZSDSV_AVG_CLEAR-IHREZ .
ZSDSMMT009-VOL_OPTION =
ZSDSV_AVG_CLEAR-VOL_OPTION .
ZSDSMMT009-VOLUME =
ZSDSV_AVG_CLEAR-VOLUME .
ZSDSMMT009-AVG_CLEAR =
ZSDSV_AVG_CLEAR-AVG_CLEAR .
ZSDSMMT009-ZDEL_FLG =
ZSDSV_AVG_CLEAR-ZDEL_FLG .
ZSDSMMT009-ZCRT_DATE =
ZSDSV_AVG_CLEAR-ZCRT_DATE .
ZSDSMMT009-ZCRT_TIME =
ZSDSV_AVG_CLEAR-ZCRT_TIME .
ZSDSMMT009-ZCRT_USER =
ZSDSV_AVG_CLEAR-ZCRT_USER .
ZSDSMMT009-ZCRT_PGM =
ZSDSV_AVG_CLEAR-ZCRT_PGM .
ZSDSMMT009-ZUPD_DATE =
ZSDSV_AVG_CLEAR-ZUPD_DATE .
ZSDSMMT009-ZUPD_TIME =
ZSDSV_AVG_CLEAR-ZUPD_TIME .
ZSDSMMT009-ZUPD_USER =
ZSDSV_AVG_CLEAR-ZUPD_USER .
ZSDSMMT009-ZUPD_PGM =
ZSDSV_AVG_CLEAR-ZUPD_PGM .
    SELECT SINGLE * FROM T173 WHERE
VSART = ZSDSMMT009-CODE .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T173T WHERE
VSART = T173-VSART AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZSDSV_AVG_CLEAR-BEZEI =
T173T-BEZEI .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZSDSV_AVG_CLEAR-BEZEI .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZSDSV_AVG_CLEAR-BEZEI .
    ENDIF.
ENDFORM.
