*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZSDSV_IMP_DUTY..................................*
FORM GET_DATA_ZSDSV_IMP_DUTY.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZSDSMMT012 WHERE
(VIM_WHERETAB) .
    CLEAR ZSDSV_IMP_DUTY .
ZSDSV_IMP_DUTY-MANDT =
ZSDSMMT012-MANDT .
ZSDSV_IMP_DUTY-MATNR =
ZSDSMMT012-MATNR .
ZSDSV_IMP_DUTY-DUTY_PERCENT =
ZSDSMMT012-DUTY_PERCENT .
ZSDSV_IMP_DUTY-ZERO_FLG =
ZSDSMMT012-ZERO_FLG .
ZSDSV_IMP_DUTY-ZDEL_FLG =
ZSDSMMT012-ZDEL_FLG .
ZSDSV_IMP_DUTY-ZCRT_DATE =
ZSDSMMT012-ZCRT_DATE .
ZSDSV_IMP_DUTY-ZCRT_TIME =
ZSDSMMT012-ZCRT_TIME .
ZSDSV_IMP_DUTY-ZCRT_USER =
ZSDSMMT012-ZCRT_USER .
ZSDSV_IMP_DUTY-ZCRT_PGM =
ZSDSMMT012-ZCRT_PGM .
ZSDSV_IMP_DUTY-ZUPD_DATE =
ZSDSMMT012-ZUPD_DATE .
ZSDSV_IMP_DUTY-ZUPD_TIME =
ZSDSMMT012-ZUPD_TIME .
ZSDSV_IMP_DUTY-ZUPD_USER =
ZSDSMMT012-ZUPD_USER .
ZSDSV_IMP_DUTY-ZUPD_PGM =
ZSDSMMT012-ZUPD_PGM .
    SELECT SINGLE * FROM MARA WHERE
MATNR = ZSDSMMT012-MATNR .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM MAKT WHERE
MATNR = MARA-MATNR AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZSDSV_IMP_DUTY-MAKTX =
MAKT-MAKTX .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = ZSDSV_IMP_DUTY.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZSDSV_IMP_DUTY .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZSDSV_IMP_DUTY.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZSDSV_IMP_DUTY-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZSDSMMT012 WHERE
  MATNR = ZSDSV_IMP_DUTY-MATNR .
    IF SY-SUBRC = 0.
    DELETE ZSDSMMT012 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZSDSMMT012 WHERE
  MATNR = ZSDSV_IMP_DUTY-MATNR .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZSDSMMT012.
    ENDIF.
ZSDSMMT012-MANDT =
ZSDSV_IMP_DUTY-MANDT .
ZSDSMMT012-MATNR =
ZSDSV_IMP_DUTY-MATNR .
ZSDSMMT012-DUTY_PERCENT =
ZSDSV_IMP_DUTY-DUTY_PERCENT .
ZSDSMMT012-ZERO_FLG =
ZSDSV_IMP_DUTY-ZERO_FLG .
ZSDSMMT012-ZDEL_FLG =
ZSDSV_IMP_DUTY-ZDEL_FLG .
ZSDSMMT012-ZCRT_DATE =
ZSDSV_IMP_DUTY-ZCRT_DATE .
ZSDSMMT012-ZCRT_TIME =
ZSDSV_IMP_DUTY-ZCRT_TIME .
ZSDSMMT012-ZCRT_USER =
ZSDSV_IMP_DUTY-ZCRT_USER .
ZSDSMMT012-ZCRT_PGM =
ZSDSV_IMP_DUTY-ZCRT_PGM .
ZSDSMMT012-ZUPD_DATE =
ZSDSV_IMP_DUTY-ZUPD_DATE .
ZSDSMMT012-ZUPD_TIME =
ZSDSV_IMP_DUTY-ZUPD_TIME .
ZSDSMMT012-ZUPD_USER =
ZSDSV_IMP_DUTY-ZUPD_USER .
ZSDSMMT012-ZUPD_PGM =
ZSDSV_IMP_DUTY-ZUPD_PGM .
    IF SY-SUBRC = 0.
    UPDATE ZSDSMMT012 ##WARN_OK.
    ELSE.
    INSERT ZSDSMMT012 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZSDSV_IMP_DUTY-UPD_FLAG,
STATUS_ZSDSV_IMP_DUTY-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZSDSV_IMP_DUTY.
  SELECT SINGLE * FROM ZSDSMMT012 WHERE
MATNR = ZSDSV_IMP_DUTY-MATNR .
ZSDSV_IMP_DUTY-MANDT =
ZSDSMMT012-MANDT .
ZSDSV_IMP_DUTY-MATNR =
ZSDSMMT012-MATNR .
ZSDSV_IMP_DUTY-DUTY_PERCENT =
ZSDSMMT012-DUTY_PERCENT .
ZSDSV_IMP_DUTY-ZERO_FLG =
ZSDSMMT012-ZERO_FLG .
ZSDSV_IMP_DUTY-ZDEL_FLG =
ZSDSMMT012-ZDEL_FLG .
ZSDSV_IMP_DUTY-ZCRT_DATE =
ZSDSMMT012-ZCRT_DATE .
ZSDSV_IMP_DUTY-ZCRT_TIME =
ZSDSMMT012-ZCRT_TIME .
ZSDSV_IMP_DUTY-ZCRT_USER =
ZSDSMMT012-ZCRT_USER .
ZSDSV_IMP_DUTY-ZCRT_PGM =
ZSDSMMT012-ZCRT_PGM .
ZSDSV_IMP_DUTY-ZUPD_DATE =
ZSDSMMT012-ZUPD_DATE .
ZSDSV_IMP_DUTY-ZUPD_TIME =
ZSDSMMT012-ZUPD_TIME .
ZSDSV_IMP_DUTY-ZUPD_USER =
ZSDSMMT012-ZUPD_USER .
ZSDSV_IMP_DUTY-ZUPD_PGM =
ZSDSMMT012-ZUPD_PGM .
    SELECT SINGLE * FROM MARA WHERE
MATNR = ZSDSMMT012-MATNR .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM MAKT WHERE
MATNR = MARA-MATNR AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZSDSV_IMP_DUTY-MAKTX =
MAKT-MAKTX .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZSDSV_IMP_DUTY-MAKTX .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZSDSV_IMP_DUTY-MAKTX .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZSDSV_IMP_DUTY USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZSDSV_IMP_DUTY-MATNR TO
ZSDSMMT012-MATNR .
MOVE ZSDSV_IMP_DUTY-MANDT TO
ZSDSMMT012-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZSDSMMT012'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZSDSMMT012 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZSDSMMT012'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZSDSV_IMP_DUTY USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZSDSMMT012-MANDT =
ZSDSV_IMP_DUTY-MANDT .
ZSDSMMT012-MATNR =
ZSDSV_IMP_DUTY-MATNR .
ZSDSMMT012-DUTY_PERCENT =
ZSDSV_IMP_DUTY-DUTY_PERCENT .
ZSDSMMT012-ZERO_FLG =
ZSDSV_IMP_DUTY-ZERO_FLG .
ZSDSMMT012-ZDEL_FLG =
ZSDSV_IMP_DUTY-ZDEL_FLG .
ZSDSMMT012-ZCRT_DATE =
ZSDSV_IMP_DUTY-ZCRT_DATE .
ZSDSMMT012-ZCRT_TIME =
ZSDSV_IMP_DUTY-ZCRT_TIME .
ZSDSMMT012-ZCRT_USER =
ZSDSV_IMP_DUTY-ZCRT_USER .
ZSDSMMT012-ZCRT_PGM =
ZSDSV_IMP_DUTY-ZCRT_PGM .
ZSDSMMT012-ZUPD_DATE =
ZSDSV_IMP_DUTY-ZUPD_DATE .
ZSDSMMT012-ZUPD_TIME =
ZSDSV_IMP_DUTY-ZUPD_TIME .
ZSDSMMT012-ZUPD_USER =
ZSDSV_IMP_DUTY-ZUPD_USER .
ZSDSMMT012-ZUPD_PGM =
ZSDSV_IMP_DUTY-ZUPD_PGM .
    SELECT SINGLE * FROM MARA WHERE
MATNR = ZSDSMMT012-MATNR .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM MAKT WHERE
MATNR = MARA-MATNR AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZSDSV_IMP_DUTY-MAKTX =
MAKT-MAKTX .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZSDSV_IMP_DUTY-MAKTX .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZSDSV_IMP_DUTY-MAKTX .
    ENDIF.
ENDFORM.
