*&---------------------------------------------------------------------*
*& Report ZSDSMMR0750
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZSDSMMR0750.
TABLES: SSCRFIELDS.
DATA: MARKFIELD.
INCLUDE: <LIST>.
*&------------------------------------------------------------
* To create screen and together icon on the screen.
*&------------------------------------------------------------
SELECTION-SCREEN: BEGIN OF BLOCK MAIN WITH  FRAME TITLE TEXT-001,SKIP,
BEGIN OF BLOCK REP1  WITH  FRAME TITLE TEXT-C01,
PUSHBUTTON /15(60)  REP01 USER-COMMAND REP01,
END OF BLOCK REP1,

BEGIN OF BLOCK REP2  WITH  FRAME TITLE TEXT-C02,
PUSHBUTTON /15(60)  REP02 USER-COMMAND REP02,
END OF BLOCK REP2,

BEGIN OF BLOCK REP3  WITH  FRAME TITLE TEXT-C03,
PUSHBUTTON /15(60)  REP03 USER-COMMAND REP03,
END OF BLOCK REP3,

BEGIN OF BLOCK REP4  WITH  FRAME TITLE TEXT-C04,
PUSHBUTTON /15(60)  REP04 USER-COMMAND REP04,
END OF BLOCK REP4,

*BEGIN OF BLOCK REP5  WITH  FRAME TITLE TEXT-C05,
*PUSHBUTTON /15(60)  REP05 USER-COMMAND REP05,
*END OF BLOCK REP5,
**
*BEGIN OF BLOCK REP6  WITH  FRAME TITLE TEXT-C06,
*PUSHBUTTON /15(60)  REP06 USER-COMMAND REP06,
*END OF BLOCK REP6,
**
*BEGIN OF BLOCK REP7  WITH  FRAME TITLE TEXT-C07,
*PUSHBUTTON /15(60)  REP07 USER-COMMAND REP7,
*END OF BLOCK REP7,
*
*BEGIN OF BLOCK REP8  WITH  FRAME TITLE TEXT-C08,
*PUSHBUTTON /15(60)  REP08 USER-COMMAND REP8,
*END OF BLOCK REP8,

END OF BLOCK MAIN.

INITIALIZATION.
*  WRITE: icon_activity AS ICON TO rep01 NO-GAP,
*         icon_sap      AS ICON TO rep02 NO-GAP.

  CONCATENATE: REP01  TEXT-B01 INTO REP01,
               REP02  TEXT-B02 INTO REP02,
               REP03  TEXT-B03 INTO REP03,
               REP04  TEXT-B04 INTO REP04.
*               REP05  TEXT-B05 INTO REP05,
*               REP06  TEXT-B06 INTO REP06.
*               REP07  TEXT-B07 INTO REP07,
*               REP08  TEXT-B08 INTO REP08.
*               REP09  TEXT-009 INTO REP09,
*               REP10  TEXT-010 INTO REP10,
*               REP11  TEXT-011 INTO REP11,
*               REP12  TEXT-012 INTO REP12.

AT SELECTION-SCREEN.
  CASE SSCRFIELDS-UCOMM.
    WHEN 'REP01'.
      CLEAR SSCRFIELDS-UCOMM.
      CALL TRANSACTION 'ZSDSMM055'.
    WHEN 'REP02'.
      CLEAR SSCRFIELDS-UCOMM.
      CALL TRANSACTION 'ZSDSMM056'.
    WHEN 'REP03'.
      CLEAR SSCRFIELDS-UCOMM.
      CALL TRANSACTION 'ZSDSMM057'.
    WHEN 'REP04'.
      CLEAR SSCRFIELDS-UCOMM.
      CALL TRANSACTION 'ZSDSMM058'.
    WHEN 'REP05'.
*      CLEAR SSCRFIELDS-UCOMM.
*      CALL TRANSACTION 'ZSDSMM031'.
    WHEN 'REP06'.
*      CLEAR SSCRFIELDS-UCOMM.
*      CALL TRANSACTION 'ZSDSMM041'.
    WHEN 'REP07'.
      CLEAR SSCRFIELDS-UCOMM.

    WHEN 'REP08'.
      CLEAR SSCRFIELDS-UCOMM.

  ENDCASE.
