*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZSDSV_AVG_PRICE.................................*
FORM GET_DATA_ZSDSV_AVG_PRICE.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZSDSMMT010 WHERE
(VIM_WHERETAB) .
    CLEAR ZSDSV_AVG_PRICE .
ZSDSV_AVG_PRICE-MANDT =
ZSDSMMT010-MANDT .
ZSDSV_AVG_PRICE-CODE =
ZSDSMMT010-CODE .
ZSDSV_AVG_PRICE-IHREZ =
ZSDSMMT010-IHREZ .
ZSDSV_AVG_PRICE-AVG_GROSS =
ZSDSMMT010-AVG_GROSS .
ZSDSV_AVG_PRICE-AVG_VOLUME =
ZSDSMMT010-AVG_VOLUME .
ZSDSV_AVG_PRICE-ZDEL_FLG =
ZSDSMMT010-ZDEL_FLG .
ZSDSV_AVG_PRICE-ZCRT_DATE =
ZSDSMMT010-ZCRT_DATE .
ZSDSV_AVG_PRICE-ZCRT_TIME =
ZSDSMMT010-ZCRT_TIME .
ZSDSV_AVG_PRICE-ZCRT_USER =
ZSDSMMT010-ZCRT_USER .
ZSDSV_AVG_PRICE-ZCRT_PGM =
ZSDSMMT010-ZCRT_PGM .
ZSDSV_AVG_PRICE-ZUPD_DATE =
ZSDSMMT010-ZUPD_DATE .
ZSDSV_AVG_PRICE-ZUPD_TIME =
ZSDSMMT010-ZUPD_TIME .
ZSDSV_AVG_PRICE-ZUPD_USER =
ZSDSMMT010-ZUPD_USER .
ZSDSV_AVG_PRICE-ZUPD_PGM =
ZSDSMMT010-ZUPD_PGM .
    SELECT SINGLE * FROM T173 WHERE
VSART = ZSDSMMT010-CODE .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T173T WHERE
VSART = T173-VSART AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZSDSV_AVG_PRICE-BEZEI =
T173T-BEZEI .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = ZSDSV_AVG_PRICE.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZSDSV_AVG_PRICE .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZSDSV_AVG_PRICE.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZSDSV_AVG_PRICE-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZSDSMMT010 WHERE
  CODE = ZSDSV_AVG_PRICE-CODE AND
  IHREZ = ZSDSV_AVG_PRICE-IHREZ .
    IF SY-SUBRC = 0.
    DELETE ZSDSMMT010 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZSDSMMT010 WHERE
  CODE = ZSDSV_AVG_PRICE-CODE AND
  IHREZ = ZSDSV_AVG_PRICE-IHREZ .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZSDSMMT010.
    ENDIF.
ZSDSMMT010-MANDT =
ZSDSV_AVG_PRICE-MANDT .
ZSDSMMT010-CODE =
ZSDSV_AVG_PRICE-CODE .
ZSDSMMT010-IHREZ =
ZSDSV_AVG_PRICE-IHREZ .
ZSDSMMT010-AVG_GROSS =
ZSDSV_AVG_PRICE-AVG_GROSS .
ZSDSMMT010-AVG_VOLUME =
ZSDSV_AVG_PRICE-AVG_VOLUME .
ZSDSMMT010-ZDEL_FLG =
ZSDSV_AVG_PRICE-ZDEL_FLG .
ZSDSMMT010-ZCRT_DATE =
ZSDSV_AVG_PRICE-ZCRT_DATE .
ZSDSMMT010-ZCRT_TIME =
ZSDSV_AVG_PRICE-ZCRT_TIME .
ZSDSMMT010-ZCRT_USER =
ZSDSV_AVG_PRICE-ZCRT_USER .
ZSDSMMT010-ZCRT_PGM =
ZSDSV_AVG_PRICE-ZCRT_PGM .
ZSDSMMT010-ZUPD_DATE =
ZSDSV_AVG_PRICE-ZUPD_DATE .
ZSDSMMT010-ZUPD_TIME =
ZSDSV_AVG_PRICE-ZUPD_TIME .
ZSDSMMT010-ZUPD_USER =
ZSDSV_AVG_PRICE-ZUPD_USER .
ZSDSMMT010-ZUPD_PGM =
ZSDSV_AVG_PRICE-ZUPD_PGM .
    IF SY-SUBRC = 0.
    UPDATE ZSDSMMT010 ##WARN_OK.
    ELSE.
    INSERT ZSDSMMT010 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZSDSV_AVG_PRICE-UPD_FLAG,
STATUS_ZSDSV_AVG_PRICE-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZSDSV_AVG_PRICE.
  SELECT SINGLE * FROM ZSDSMMT010 WHERE
CODE = ZSDSV_AVG_PRICE-CODE AND
IHREZ = ZSDSV_AVG_PRICE-IHREZ .
ZSDSV_AVG_PRICE-MANDT =
ZSDSMMT010-MANDT .
ZSDSV_AVG_PRICE-CODE =
ZSDSMMT010-CODE .
ZSDSV_AVG_PRICE-IHREZ =
ZSDSMMT010-IHREZ .
ZSDSV_AVG_PRICE-AVG_GROSS =
ZSDSMMT010-AVG_GROSS .
ZSDSV_AVG_PRICE-AVG_VOLUME =
ZSDSMMT010-AVG_VOLUME .
ZSDSV_AVG_PRICE-ZDEL_FLG =
ZSDSMMT010-ZDEL_FLG .
ZSDSV_AVG_PRICE-ZCRT_DATE =
ZSDSMMT010-ZCRT_DATE .
ZSDSV_AVG_PRICE-ZCRT_TIME =
ZSDSMMT010-ZCRT_TIME .
ZSDSV_AVG_PRICE-ZCRT_USER =
ZSDSMMT010-ZCRT_USER .
ZSDSV_AVG_PRICE-ZCRT_PGM =
ZSDSMMT010-ZCRT_PGM .
ZSDSV_AVG_PRICE-ZUPD_DATE =
ZSDSMMT010-ZUPD_DATE .
ZSDSV_AVG_PRICE-ZUPD_TIME =
ZSDSMMT010-ZUPD_TIME .
ZSDSV_AVG_PRICE-ZUPD_USER =
ZSDSMMT010-ZUPD_USER .
ZSDSV_AVG_PRICE-ZUPD_PGM =
ZSDSMMT010-ZUPD_PGM .
    SELECT SINGLE * FROM T173 WHERE
VSART = ZSDSMMT010-CODE .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T173T WHERE
VSART = T173-VSART AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZSDSV_AVG_PRICE-BEZEI =
T173T-BEZEI .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZSDSV_AVG_PRICE-BEZEI .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZSDSV_AVG_PRICE-BEZEI .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZSDSV_AVG_PRICE USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZSDSV_AVG_PRICE-CODE TO
ZSDSMMT010-CODE .
MOVE ZSDSV_AVG_PRICE-IHREZ TO
ZSDSMMT010-IHREZ .
MOVE ZSDSV_AVG_PRICE-MANDT TO
ZSDSMMT010-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZSDSMMT010'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZSDSMMT010 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZSDSMMT010'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZSDSV_AVG_PRICE USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZSDSMMT010-MANDT =
ZSDSV_AVG_PRICE-MANDT .
ZSDSMMT010-CODE =
ZSDSV_AVG_PRICE-CODE .
ZSDSMMT010-IHREZ =
ZSDSV_AVG_PRICE-IHREZ .
ZSDSMMT010-AVG_GROSS =
ZSDSV_AVG_PRICE-AVG_GROSS .
ZSDSMMT010-AVG_VOLUME =
ZSDSV_AVG_PRICE-AVG_VOLUME .
ZSDSMMT010-ZDEL_FLG =
ZSDSV_AVG_PRICE-ZDEL_FLG .
ZSDSMMT010-ZCRT_DATE =
ZSDSV_AVG_PRICE-ZCRT_DATE .
ZSDSMMT010-ZCRT_TIME =
ZSDSV_AVG_PRICE-ZCRT_TIME .
ZSDSMMT010-ZCRT_USER =
ZSDSV_AVG_PRICE-ZCRT_USER .
ZSDSMMT010-ZCRT_PGM =
ZSDSV_AVG_PRICE-ZCRT_PGM .
ZSDSMMT010-ZUPD_DATE =
ZSDSV_AVG_PRICE-ZUPD_DATE .
ZSDSMMT010-ZUPD_TIME =
ZSDSV_AVG_PRICE-ZUPD_TIME .
ZSDSMMT010-ZUPD_USER =
ZSDSV_AVG_PRICE-ZUPD_USER .
ZSDSMMT010-ZUPD_PGM =
ZSDSV_AVG_PRICE-ZUPD_PGM .
    SELECT SINGLE * FROM T173 WHERE
VSART = ZSDSMMT010-CODE .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM T173T WHERE
VSART = T173-VSART AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZSDSV_AVG_PRICE-BEZEI =
T173T-BEZEI .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZSDSV_AVG_PRICE-BEZEI .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZSDSV_AVG_PRICE-BEZEI .
    ENDIF.
ENDFORM.
