FUNCTION Z_SDSMM_REJECT_PR.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(I_WEBNO) TYPE  CHAR20 OPTIONAL
*"  EXPORTING
*"     VALUE(E_OUTPUT) TYPE  CHAR1
*"     VALUE(E_MESSAGE) TYPE  CHAR255
*"     VALUE(E_MESSTYP) TYPE  BAPIRET2-TYPE
*"----------------------------------------------------------------------

  DATA : BEGIN OF LS_DATA,
           BANFN TYPE EBAN-BANFN,
         END OF LS_DATA.

  DATA: LT_DATA  LIKE STANDARD TABLE OF LS_DATA WITH EMPTY KEY,
        LT_COMP  LIKE STANDARD TABLE OF LS_DATA WITH EMPTY KEY,
        LV_PO    TYPE STRING.

  SELECT BANFN
    FROM ZSDSMMT006
    INTO TABLE LT_DATA
    WHERE WEBNO EQ I_WEBNO
      AND FLAGD EQ SPACE.
  IF LT_DATA[] IS NOT INITIAL.
    SELECT EKPO~EBELN,
           EKPO~EBELP,
           EKPO~BANFN
      FROM EKPO
      INTO TABLE @DATA(LT_EKPO)
      FOR ALL ENTRIES IN @LT_DATA
      WHERE BANFN EQ @LT_DATA-BANFN
        AND LOEKZ NE 'L'.
    IF SY-SUBRC = 0.
      SORT LT_EKPO BY EBELN.
      DELETE ADJACENT DUPLICATES FROM LT_EKPO COMPARING EBELN.
      LOOP AT LT_EKPO INTO DATA(LS_EKPO).
        IF SY-TABIX = 1.
          E_OUTPUT = LS_EKPO-BANFN.
          LV_PO    = LS_EKPO-EBELN.
        ELSE.
          CONCATENATE LV_PO
                      ', '
                      LS_EKPO-EBELN
                      INTO LV_PO.
        ENDIF.
      ENDLOOP.
      E_MESSAGE = TEXT-E03.
      REPLACE ALL OCCURRENCES OF '&1' IN E_MESSAGE WITH LV_PO.
      E_MESSTYP = GC_CONSTANT-E.
      EXIT.
    ELSE.
      LT_COMP = LCL_DATA=>DELETE_ITEM_PR( LT_DATA ).
      LOOP AT LT_COMP INTO LS_DATA.
        LCL_DATA=>UPDATE_ZSDSMMT006_REJECT( LS_DATA-BANFN ).
      ENDLOOP.
    ENDIF.
  ENDIF.

  E_OUTPUT  = GS_DATA-GV_PR_SAP.
  E_MESSAGE = GS_DATA-GV_MESSAGE.

ENDFUNCTION.
