*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZSDSV_DELIVERYTO................................*
FORM GET_DATA_ZSDSV_DELIVERYTO.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZSDSMMT017 WHERE
(VIM_WHERETAB) .
    CLEAR ZSDSV_DELIVERYTO .
ZSDSV_DELIVERYTO-MANDT =
ZSDSMMT017-MANDT .
ZSDSV_DELIVERYTO-BWART =
ZSDSMMT017-BWART .
ZSDSV_DELIVERYTO-MVT_TYPE_CATEGORY =
ZSDSMMT017-MVT_TYPE_CATEGORY .
ZSDSV_DELIVERYTO-ISSUE_SLOC =
ZSDSMMT017-ISSUE_SLOC .
ZSDSV_DELIVERYTO-RECV_SLOC =
ZSDSMMT017-RECV_SLOC .
ZSDSV_DELIVERYTO-COND_DOC_TYPE =
ZSDSMMT017-COND_DOC_TYPE .
ZSDSV_DELIVERYTO-DELIVERY_TO =
ZSDSMMT017-DELIVERY_TO .
ZSDSV_DELIVERYTO-SENT_SALESFORCE =
ZSDSMMT017-SENT_SALESFORCE .
ZSDSV_DELIVERYTO-SENT_SONY =
ZSDSMMT017-SENT_SONY .
ZSDSV_DELIVERYTO-PREFIX_FILENAME =
ZSDSMMT017-PREFIX_FILENAME .
<VIM_TOTAL_STRUC> = ZSDSV_DELIVERYTO.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZSDSV_DELIVERYTO .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZSDSV_DELIVERYTO.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZSDSV_DELIVERYTO-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZSDSMMT017 WHERE
  BWART = ZSDSV_DELIVERYTO-BWART AND
  MVT_TYPE_CATEGORY = ZSDSV_DELIVERYTO-MVT_TYPE_CATEGORY AND
  ISSUE_SLOC = ZSDSV_DELIVERYTO-ISSUE_SLOC AND
  RECV_SLOC = ZSDSV_DELIVERYTO-RECV_SLOC .
    IF SY-SUBRC = 0.
    DELETE ZSDSMMT017 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZSDSMMT017 WHERE
  BWART = ZSDSV_DELIVERYTO-BWART AND
  MVT_TYPE_CATEGORY = ZSDSV_DELIVERYTO-MVT_TYPE_CATEGORY AND
  ISSUE_SLOC = ZSDSV_DELIVERYTO-ISSUE_SLOC AND
  RECV_SLOC = ZSDSV_DELIVERYTO-RECV_SLOC .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZSDSMMT017.
    ENDIF.
ZSDSMMT017-MANDT =
ZSDSV_DELIVERYTO-MANDT .
ZSDSMMT017-BWART =
ZSDSV_DELIVERYTO-BWART .
ZSDSMMT017-MVT_TYPE_CATEGORY =
ZSDSV_DELIVERYTO-MVT_TYPE_CATEGORY .
ZSDSMMT017-ISSUE_SLOC =
ZSDSV_DELIVERYTO-ISSUE_SLOC .
ZSDSMMT017-RECV_SLOC =
ZSDSV_DELIVERYTO-RECV_SLOC .
ZSDSMMT017-COND_DOC_TYPE =
ZSDSV_DELIVERYTO-COND_DOC_TYPE .
ZSDSMMT017-DELIVERY_TO =
ZSDSV_DELIVERYTO-DELIVERY_TO .
ZSDSMMT017-SENT_SALESFORCE =
ZSDSV_DELIVERYTO-SENT_SALESFORCE .
ZSDSMMT017-SENT_SONY =
ZSDSV_DELIVERYTO-SENT_SONY .
ZSDSMMT017-PREFIX_FILENAME =
ZSDSV_DELIVERYTO-PREFIX_FILENAME .
    IF SY-SUBRC = 0.
    UPDATE ZSDSMMT017 ##WARN_OK.
    ELSE.
    INSERT ZSDSMMT017 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZSDSV_DELIVERYTO-UPD_FLAG,
STATUS_ZSDSV_DELIVERYTO-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZSDSV_DELIVERYTO.
  SELECT SINGLE * FROM ZSDSMMT017 WHERE
BWART = ZSDSV_DELIVERYTO-BWART AND
MVT_TYPE_CATEGORY = ZSDSV_DELIVERYTO-MVT_TYPE_CATEGORY AND
ISSUE_SLOC = ZSDSV_DELIVERYTO-ISSUE_SLOC AND
RECV_SLOC = ZSDSV_DELIVERYTO-RECV_SLOC .
ZSDSV_DELIVERYTO-MANDT =
ZSDSMMT017-MANDT .
ZSDSV_DELIVERYTO-BWART =
ZSDSMMT017-BWART .
ZSDSV_DELIVERYTO-MVT_TYPE_CATEGORY =
ZSDSMMT017-MVT_TYPE_CATEGORY .
ZSDSV_DELIVERYTO-ISSUE_SLOC =
ZSDSMMT017-ISSUE_SLOC .
ZSDSV_DELIVERYTO-RECV_SLOC =
ZSDSMMT017-RECV_SLOC .
ZSDSV_DELIVERYTO-COND_DOC_TYPE =
ZSDSMMT017-COND_DOC_TYPE .
ZSDSV_DELIVERYTO-DELIVERY_TO =
ZSDSMMT017-DELIVERY_TO .
ZSDSV_DELIVERYTO-SENT_SALESFORCE =
ZSDSMMT017-SENT_SALESFORCE .
ZSDSV_DELIVERYTO-SENT_SONY =
ZSDSMMT017-SENT_SONY .
ZSDSV_DELIVERYTO-PREFIX_FILENAME =
ZSDSMMT017-PREFIX_FILENAME .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZSDSV_DELIVERYTO USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZSDSV_DELIVERYTO-BWART TO
ZSDSMMT017-BWART .
MOVE ZSDSV_DELIVERYTO-MVT_TYPE_CATEGORY TO
ZSDSMMT017-MVT_TYPE_CATEGORY .
MOVE ZSDSV_DELIVERYTO-ISSUE_SLOC TO
ZSDSMMT017-ISSUE_SLOC .
MOVE ZSDSV_DELIVERYTO-RECV_SLOC TO
ZSDSMMT017-RECV_SLOC .
MOVE ZSDSV_DELIVERYTO-MANDT TO
ZSDSMMT017-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZSDSMMT017'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZSDSMMT017 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZSDSMMT017'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
