*-----------------------------------------------------------------------
*  Program ID         : ZSDSFIR0120
*  Creation Date      : 29.03.2023
*  Author             : Jakarin S.
*  Add-on ID          : ZFIARE026
*  Description        : Program print incoming request with and w/o sale order
*  Purpose            :
*  Copied from        : ZAR_MSBILL_CRED SAP ECC6
*  Restriction        :
*-----------------------------------------------------------------------
*  CHANGE HISTORY
*-----------------------------------------------------------------------
*  Date        Task #      Programmer  Description
*-----------------------------------------------------------------------
*  DD.MM.YYYY  TR no.      ABAP Name   Detail
*-----------------------------------------------------------------------
REPORT ZSDSFIR0120 MESSAGE-ID ZSDSFi01.
TYPE-POOLS: SLIS,VRM.
TABLES: SSCRFIELDS,VBAK,VBAP,KONV,ZSDSFIT006,ZSDSFIT007,KNA1,ADRC.

DATA: MARKFIELD,
      S_VTWEG  LIKE VBAK-VTWEG.
INCLUDE: <LIST>.

TYPES : BEGIN OF TYP_HEADER.
        INCLUDE STRUCTURE ZSDSFIT006.
TYPES : END OF TYP_HEADER.

TYPES : BEGIN OF TYP_DETAIL_DB.
        INCLUDE STRUCTURE ZSDSFIT007.
TYPES : END OF TYP_DETAIL_DB.


TYPES : BEGIN OF TYP_DETAIL.
        INCLUDE STRUCTURE ZSDSFIT007.
TYPES : AUART TYPE VBAK-AUART,
   KNUMV TYPE VBAK-KNUMV,
   MEINH TYPE MARM-MEINH,
   KWMENG_O TYPE VBAP-KWMENG,
   SEL(1) TYPE C,
   ADD(1) TYPE C,
END OF TYP_DETAIL.



TYPES : BEGIN OF TYP_VBAK,
        VBELN  TYPE VBAK-VBELN,
        KUNNR TYPE VBAK-KUNNR,
        NAME1 TYPE ADRC-NAME1,
        NAME2 TYPE ADRC-NAME2,
        ZTERM TYPE VBKD-ZTERM,
        BSTKD TYPE VBKD-BSTKD,
        T052U TYPE T052U-TEXT1,
        AUFNR TYPE AUFK-AUFNR,
        KTEXT TYPE AUFK-KTEXT,
     END OF TYP_VBAK.

TYPES : BEGIN OF TYP_KONV,
        KNUMV TYPE VBAK-KNUMV,
        KPOSN TYPE KONV-KPOSN,
        KSCHL TYPE KONV-KSCHL,
        KWERT TYPE KONV-KWERT,
  END OF TYP_KONV.

TYPES : BEGIN OF TYP_VBAP,
        VBELN TYPE VBAP-VBELN,
        POSNR TYPE VBAP-POSNR,
        MATNR TYPE VBAP-MATNR,
        KWMENG TYPE VBAP-KWMENG,
        NETPR TYPE VBAP-NETPR,
        NETWR TYPE VBAP-NETWR,
  END OF TYP_VBAP.

TYPES : BEGIN OF TYP_APV.
        INCLUDE STRUCTURE ZSDSFIT008.
TYPES : END OF TYP_APV.

TYPES : BEGIN OF TYP_VBAK_ATME.
        INCLUDE STRUCTURE ZSDSFIT009.
TYPES : END OF TYP_VBAK_ATME.

TYPES : BEGIN OF TYP_VBAP_ATME.
        INCLUDE STRUCTURE ZSDSFIT010.
TYPES : END OF TYP_VBAP_ATME.

TYPES : BEGIN OF TYP_KONV_ATME.
        INCLUDE STRUCTURE ZSDSFIT011.
TYPES : END OF TYP_KONV_ATME.

DATA : I_VBAK_ATME TYPE STANDARD TABLE OF TYP_VBAK_ATME,
       W_VBAK_ATME LIKE LINE OF I_VBAK_ATME,
       I_VBAP_ATME TYPE STANDARD TABLE OF TYP_VBAP_ATME,
       W_VBAP_ATME LIKE LINE OF I_VBAP_ATME,
       I_KONV_ATME TYPE STANDARD TABLE OF TYP_KONV_ATME,
       W_KONV_ATME LIKE LINE OF I_KONV_ATME.

DATA : I_HEADER TYPE STANDARD TABLE OF  TYP_HEADER,
       I_HEADER_CHG TYPE STANDARD TABLE OF  TYP_HEADER,
       I_HEADER_ADD TYPE STANDARD TABLE OF  TYP_HEADER,
       I_HEADER_DEL TYPE STANDARD TABLE OF  TYP_HEADER,
       W_HEADER LIKE LINE OF I_HEADER,
       W_HEADER_CHG LIKE LINE OF I_HEADER,
       W_HEADER_ADD LIKE LINE OF I_HEADER,
       I_DETAIL TYPE STANDARD TABLE OF TYP_DETAIL,
       I_DETAIL_200 TYPE STANDARD TABLE OF TYP_DETAIL,
       I_DETAIL_OLD TYPE STANDARD TABLE OF TYP_DETAIL,
       I_DETAIL_CHG TYPE STANDARD TABLE OF TYP_DETAIL,
       I_DETAIL_ADD TYPE STANDARD TABLE OF TYP_DETAIL,
       I_DETAIL_DEL TYPE STANDARD TABLE OF TYP_DETAIL,
       W_DETAIL LIKE LINE OF I_DETAIL,
       W_DETAIL_200 LIKE LINE OF I_DETAIL_200,
       W_DETAIL_OLD LIKE LINE OF I_DETAIL_OLD,
       W_DETAIL_CHG LIKE LINE OF I_DETAIL_CHG,
       W_DETAIL_ADD LIKE LINE OF I_DETAIL_ADD,
       I_VBAK TYPE STANDARD TABLE OF TYP_VBAK,
       W_VBAK LIKE LINE OF I_VBAK,
       I_KONV TYPE STANDARD TABLE OF TYP_KONV,
       W_KONV LIKE LINE OF I_KONV,
       I_VBAP TYPE STANDARD TABLE OF TYP_VBAP,
       W_VBAP LIKE LINE OF I_VBAP,
       I_APV TYPE STANDARD TABLE OF TYP_APV,
       W_APV LIKE LINE OF I_APV,
       I_DETAIL_DB TYPE STANDARD TABLE OF TYP_DETAIL_DB,
       W_DETAIL_DB LIKE LINE OF I_DETAIL_DB.



** Control
CONTROLS : TC_DETAIL TYPE TABLEVIEW USING SCREEN '0100',
           TC_DETAIL_200 TYPE TABLEVIEW USING SCREEN '0200'.

DATA :

LST_DOCTYPE TYPE ZSDSFIT006-DOCTYPE,
TXT_DOCNR TYPE ZSDSFIT006-DOCNR,
TXT_DOCDATE TYPE ZSDSFIT006-DOCDATE,
TXT_TOPIC TYPE ZSDSFIT006-TOPIC,
TXT_VBELN TYPE ZSDSFIT006-VBELN,
TXT_ATTEND TYPE ZSDSFIT006-ATTEND,
TXT_KUNNR TYPE VBAK-KUNNR,
TXT_NAME1 TYPE ZSDSFIT006-NAME1,
TXT_ZTERM TYPE VBKD-ZTERM,
TXT_PMNT_DESC TYPE T052U-TEXT1,
TXT_PMNT_TYP TYPE ZSDSFIT006-PMNTTYP,
TXT_BSTKD TYPE VBKD-BSTKD,
TXT_AUFNR TYPE AUFK-AUFNR,
LST_MGRNR TYPE ZSDSFIT006-MGRNR,
TXT_KTEXT TYPE AUFK-KTEXT,
TXT_MNAME(40) TYPE C,
TXT_POS TYPE ZSDSFIT006-POSDESC,
TXT_PRCNT TYPE ZSDSFIT006-PRCNT,
CHK_VAT TYPE C VALUE 'X',
CHK_WHT TYPE C,
TXT_VAT TYPE ZSDSFIT006-VAT,
TXT_WHT TYPE ZSDSFIT006-WHTAX,
TXT_TOTAL_QTY TYPE VBAP-KWMENG,
TXT_TOTAL_AMT1 TYPE VBAP-NETWR,
TXT_ADV TYPE VBAP-NETWR,
TXT_TOTAL_AMT2 TYPE VBAP-NETWR,
TXT_AMT_INC_VAT TYPE VBAP-NETWR,
TXT_AMT_INC_WHT TYPE VBAP-NETWR,
TXT_GRANDTOTAL TYPE VBAP-NETWR,
TXT_EDATU TYPE VBEP-EDATU,

* Old v
LST_DOCTYPE_O TYPE ZSDSFIT006-DOCTYPE,
TXT_DOCDATE_O TYPE ZSDSFIT006-DOCDATE,
TXT_TOPIC_O TYPE ZSDSFIT006-TOPIC,
TXT_VBELN_O TYPE ZSDSFIT006-VBELN,
TXT_ATTEND_O TYPE ZSDSFIT006-ATTEND,
TXT_KUNNR_O TYPE VBAK-KUNNR,
TXT_NAME1_O TYPE ZSDSFIT006-NAME1,
TXT_ZTERM_O TYPE VBKD-ZTERM,
TXT_PMNT_DESC_O TYPE T052U-TEXT1,
TXT_PMNT_TYP_O TYPE ZSDSFIT006-PMNTTYP,
TXT_BSTKD_O TYPE VBKD-BSTKD,
TXT_AUFNR_O TYPE AUFK-AUFNR,
LST_MGRNR_O TYPE ZSDSFIT006-MGRNR,
TXT_KTEXT_O TYPE AUFK-KTEXT,
TXT_MNAME_O(40) TYPE C,
TXT_POS_O TYPE ZSDSFIT006-POSDESC,
TXT_PRCNT_O TYPE ZSDSFIT006-PRCNT,
TXT_VAT_O TYPE ZSDSFIT006-VAT,
TXT_WHT_O TYPE ZSDSFIT006-WHTAX,
TXT_TOTAL_QTY_O TYPE VBAP-KWMENG,
TXT_TOTAL_AMT1_O TYPE VBAP-NETWR,
TXT_ADV_O TYPE VBAP-NETWR,
TXT_TOTAL_AMT2_O TYPE VBAP-NETWR,
TXT_AMT_INC_VAT_O TYPE VBAP-NETWR,
TXT_AMT_INC_WHT_O TYPE VBAP-NETWR,
TXT_GRANDTOTAL_O TYPE VBAP-NETWR,
TXT_EDATU_O TYPE VBEP-EDATU
.

DATA: NAME  TYPE VRM_ID,
      LIST  TYPE VRM_VALUES,
      VALUE LIKE LINE OF LIST,
      OREF TYPE REF TO CX_ROOT,
      GV_MESSAGE TYPE STRING,
      GV_ANSWER(1) TYPE C,
      TXT_ERDAT TYPE ZSDSFIT006-ERDAT,
      TXT_ERTIM TYPE ZSDSFIT006-ERTIM,
      TXT_ERNAM TYPE ZSDSFIT006-ERNAM,
      R_FIELD(1) TYPE N,
      CP_POSNR TYPE VBAP-POSNR,
      GV_CORRECT(1) TYPE C,
      GV_POSNR TYPE VBAP-POSNR.



FIELD-SYMBOLS : <FSH> LIKE LINE OF I_HEADER,
                <FSD> LIKE LINE OF I_DETAIL.


INCLUDE ZSDSFIR0120_STATUS.
INCLUDE ZSDSFIR0120_COMMAND.

*&------------------------------------------------------------
* To create screen and together icon on the screen.
*&------------------------------------------------------------
SELECTION-SCREEN: BEGIN OF BLOCK MAIN WITH  FRAME TITLE TEXT-001,SKIP,
                  BEGIN OF BLOCK REP  WITH  FRAME TITLE TEXT-005,
                  PUSHBUTTON /10(50)  REP01 USER-COMMAND REP01,SKIP,
                  PUSHBUTTON /10(50)  REP02 USER-COMMAND REP02,SKIP,
                  END OF BLOCK REP,
                  END OF BLOCK MAIN.
SELECTION-SCREEN FUNCTION KEY 1.

INITIALIZATION.

*  CONCATENATE: '@6A@'(003) ' Test One Screen'(002) INTO sscrfields-functxt_01.
*  WRITE: icon_positive AS ICON TO rep01 NO-GAP,
*         icon_negative AS ICON TO rep02 NO-GAP.

  CONCATENATE: REP01  '+:+:+   Convert from SO/QT   +:+:+'   INTO REP01,
               REP02  '+:+:+   User key in     +:+:+'  INTO REP02.

*Approve Name
  PERFORM F_ASSIGN_MANAGER.



AT SELECTION-SCREEN.

  CASE SSCRFIELDS-UCOMM.
    WHEN 'REP01'.
      CLEAR SSCRFIELDS-UCOMM.
      CLEAR : I_DETAIL[].
      CALL SCREEN 0100.
    WHEN 'REP02'.
      CLEAR SSCRFIELDS-UCOMM.
      CLEAR : I_DETAIL_200[].
      CALL SCREEN 0200.
  ENDCASE.

  INCLUDE ZSDSFIR0120_PAI.
  INCLUDE ZSDSFIR0120_PBO.
  INCLUDE ZSDSFIR0120_SUBRUTINE.
