*&---------------------------------------------------------------------*
*& Report ZSDSFIR0140
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZSDSFIR0140 NO STANDARD PAGE HEADING.

TYPE-POOLS: SLIS,VRM.
TABLES: SSCRFIELDS,VBAK,VBAP,KONV,ZSDSFIT006,ZSDSFIT007.

DATA: MARKFIELD,
      S_VTWEG  LIKE VBAK-VTWEG.
INCLUDE: <LIST>.

TYPES : BEGIN OF TYP_HEADER.
        INCLUDE STRUCTURE ZSDSFIT006.
TYPES : END OF TYP_HEADER.

TYPES : BEGIN OF TYP_DETAIL_DB.
        INCLUDE STRUCTURE ZSDSFIT007.
TYPES : END OF TYP_DETAIL_DB.


TYPES : BEGIN OF TYP_DETAIL.
        INCLUDE STRUCTURE ZSDSFIT007.
TYPES : AUART TYPE VBAK-AUART,
       KNUMV TYPE VBAK-KNUMV,
       MEINH TYPE MARM-MEINH,
       KWMENG_O TYPE VBAP-KWMENG,
       SEL(1) TYPE C,
       ADD(1) TYPE C,
       FULL_SET(1) TYPE C,
       UMREZ TYPE MARM-UMREZ,
       UMREN TYPE  MARM-UMREN,
    END OF TYP_DETAIL.

TYPES : BEGIN OF TYP_VBAK,
        VBELN  TYPE VBAK-VBELN,
        KUNNR TYPE VBAK-KUNNR,
        NAME1 TYPE ZSDSFIT006-NAME1,
        ZTERM TYPE VBKD-ZTERM,
        BSTKD TYPE VBKD-BSTKD,
        T052U TYPE T052U-TEXT1,
        AUFNR TYPE AUFK-AUFNR,
        KTEXT TYPE AUFK-KTEXT,
     END OF TYP_VBAK.

TYPES : BEGIN OF TYP_KONV,
        KNUMV TYPE VBAK-KNUMV,
        KPOSN TYPE KONV-KPOSN,
        KSCHL TYPE KONV-KSCHL,
        KWERT TYPE KONV-KWERT,
  END OF TYP_KONV.

TYPES : BEGIN OF TYP_VBAP,
        VBELN TYPE VBAP-VBELN,
        POSNR TYPE VBAP-POSNR,
        MATNR TYPE VBAP-MATNR,
        KWMENG TYPE VBAP-KWMENG,
        NETPR TYPE VBAP-NETPR,
        NETWR TYPE VBAP-NETWR,
  END OF TYP_VBAP.

TYPES : BEGIN OF TYP_APV.
        INCLUDE STRUCTURE ZSDSFIT008.
TYPES : END OF TYP_APV.

TYPES : BEGIN OF TYP_VBAK_ATME.
        INCLUDE STRUCTURE ZSDSFIT009.
TYPES : END OF TYP_VBAK_ATME.

TYPES : BEGIN OF TYP_VBAP_ATME.
        INCLUDE STRUCTURE ZSDSFIT010.
TYPES : END OF TYP_VBAP_ATME.

TYPES : BEGIN OF TYP_KONV_ATME.
        INCLUDE STRUCTURE ZSDSFIT011.
TYPES : END OF TYP_KONV_ATME.

DATA : I_VBAK_ATME TYPE STANDARD TABLE OF TYP_VBAK_ATME,
       W_VBAK_ATME LIKE LINE OF I_VBAK_ATME,
       I_VBAP_ATME TYPE STANDARD TABLE OF TYP_VBAP_ATME,
       W_VBAP_ATME LIKE LINE OF I_VBAP_ATME,
       I_KONV_ATME TYPE STANDARD TABLE OF TYP_KONV_ATME,
       W_KONV_ATME LIKE LINE OF I_KONV_ATME.

DATA : I_HEADER TYPE STANDARD TABLE OF  TYP_HEADER,
       W_HEADER LIKE LINE OF I_HEADER,
       I_DETAIL TYPE STANDARD TABLE OF TYP_DETAIL,
       I_DETAIL_ADD TYPE STANDARD TABLE OF TYP_DETAIL,
       I_DETAIL_OLD TYPE STANDARD TABLE OF TYP_DETAIL,
       I_DETAIL_200 TYPE STANDARD TABLE OF TYP_DETAIL,
       I_DETAIL_DEL TYPE STANDARD TABLE OF TYP_DETAIL,
       W_DETAIL LIKE LINE OF I_DETAIL,
       W_DETAIL_OLD LIKE LINE OF I_DETAIL_OLD,
       W_DETAIL_ADD LIKE LINE OF I_DETAIL_ADD,
       W_DETAIL_200 LIKE LINE OF I_DETAIL_200,
       I_VBAK TYPE STANDARD TABLE OF TYP_VBAK,
       W_VBAK LIKE LINE OF I_VBAK,
       I_KONV TYPE STANDARD TABLE OF TYP_KONV,
       W_KONV LIKE LINE OF I_KONV,
       I_VBAP TYPE STANDARD TABLE OF TYP_VBAP,
       I_VBAP_POP TYPE STANDARD TABLE OF TYP_DETAIL,
       W_VBAP LIKE LINE OF I_VBAP,
       W_VBAP_POP LIKE LINE OF I_VBAP_POP,
       I_APV TYPE STANDARD TABLE OF TYP_APV,
       W_APV LIKE LINE OF I_APV,
       I_DETAIL_DB TYPE STANDARD TABLE OF TYP_DETAIL_DB,
       I_DETAIL_DB_NEW TYPE STANDARD TABLE OF TYP_DETAIL_DB,
       W_DETAIL_DB LIKE LINE OF I_DETAIL_DB.

** Control
CONTROLS : TC_DETAIL TYPE TABLEVIEW USING SCREEN '0100',
           TC_DETAIL_200 TYPE TABLEVIEW USING SCREEN '0200',
           TC_VBAP_300 TYPE TABLEVIEW USING SCREEN '0300'.
DATA :

LST_DOCTYPE TYPE ZSDSFIT006-DOCTYPE,
TXT_DOCNR TYPE ZSDSFIT006-DOCNR,
TXT_DOCDATE TYPE ZSDSFIT006-DOCDATE,
TXT_TOPIC TYPE ZSDSFIT006-TOPIC,
TXT_VBELN TYPE ZSDSFIT006-VBELN,
TXT_ATTEND TYPE ZSDSFIT006-ATTEND,
TXT_KUNNR TYPE VBAK-KUNNR,
TXT_NAME1 TYPE ZSDSFIT006-NAME1,
TXT_ZTERM TYPE VBKD-ZTERM,
TXT_PMNT_DESC TYPE T052U-TEXT1,
TXT_PMNT_TYP TYPE ZSDSFIT006-PMNTTYP,
TXT_BSTKD TYPE VBKD-BSTKD,
TXT_AUFNR TYPE AUFK-AUFNR,
LST_MGRNR TYPE ZSDSFIT006-MGRNR,
TXT_KTEXT TYPE AUFK-KTEXT,
TXT_MNAME(40) TYPE C,
TXT_POS TYPE ZSDSFIT006-POSDESC,
TXT_PRCNT TYPE ZSDSFIT006-PRCNT,
CHK_VAT TYPE C VALUE 'X',
CHK_WHT TYPE C,
TXT_VAT TYPE ZSDSFIT006-VAT,
TXT_WHT TYPE ZSDSFIT006-WHTAX,
TXT_TOTAL_QTY TYPE VBAP-KWMENG,
TXT_TOTAL_AMT1 TYPE VBAP-NETWR,
TXT_ADV TYPE ZSDSFIT006-KWERT,
TXT_TOTAL_AMT2 TYPE VBAP-NETWR,
TXT_AMT_INC_VAT TYPE VBAP-NETWR,
TXT_AMT_INC_WHT TYPE VBAP-NETWR,
TXT_GRANDTOTAL TYPE VBAP-NETWR,
TXT_REFTYPE TYPE ZSDSFIT006-REFTYPE,
TXT_EDATU TYPE VBEP-EDATU,

* Old v
LST_DOCTYPE_O TYPE ZSDSFIT006-DOCTYPE,
TXT_DOCDATE_O TYPE ZSDSFIT006-DOCDATE,
TXT_TOPIC_O TYPE ZSDSFIT006-TOPIC,
TXT_VBELN_O TYPE ZSDSFIT006-VBELN,
TXT_ATTEND_O TYPE ZSDSFIT006-ATTEND,
TXT_KUNNR_O TYPE VBAK-KUNNR,
TXT_NAME1_O TYPE ZSDSFIT006-NAME1,
TXT_ZTERM_O TYPE VBKD-ZTERM,
TXT_PMNT_DESC_O TYPE T052U-TEXT1,
TXT_PMNT_TYP_O TYPE ZSDSFIT006-PMNTTYP,
TXT_BSTKD_O TYPE VBKD-BSTKD,
TXT_AUFNR_O TYPE AUFK-AUFNR,
LST_MGRNR_O TYPE ZSDSFIT006-MGRNR,
TXT_KTEXT_O TYPE AUFK-KTEXT,
TXT_MNAME_O(40) TYPE C,
TXT_POS_O TYPE ZSDSFIT006-POSDESC,
TXT_PRCNT_O TYPE ZSDSFIT006-PRCNT,
TXT_VAT_O TYPE ZSDSFIT006-VAT,
TXT_WHT_O TYPE ZSDSFIT006-WHTAX,
TXT_TOTAL_QTY_O TYPE VBAP-KWMENG,
TXT_TOTAL_AMT1_O TYPE VBAP-NETWR,
TXT_ADV_O TYPE ZSDSFIT006-KWERT,
TXT_TOTAL_AMT2_O TYPE VBAP-NETWR,
TXT_AMT_INC_VAT_O TYPE VBAP-NETWR,
TXT_AMT_INC_WHT_O TYPE VBAP-NETWR,
TXT_GRANDTOTAL_O TYPE VBAP-NETWR,
TXT_EDATU_O TYPE VBEP-EDATU.

DATA: NAME  TYPE VRM_ID,
      LIST  TYPE VRM_VALUES,
      VALUE LIKE LINE OF LIST,
      OREF TYPE REF TO CX_ROOT,
      GV_MESSAGE TYPE STRING,
      GV_ANSWER(1) TYPE C,
*      txt_erdat TYPE ZSDSFIT006-erdat,
*      txt_ertim TYPE ZSDSFIT006-ertim,
*      txt_ernam TYPE ZSDSFIT006-ernam,
      TXT_AEDAT TYPE ZSDSFIT006-AEDAT,
      TXT_AETIM TYPE ZSDSFIT006-AETIM,
      TXT_AENAM TYPE ZSDSFIT006-AENAM,
      R_FIELD(1) TYPE N,
      FIRST_INITIAL TYPE C,
      GV_CORRECT TYPE C,
      GV_POSNR TYPE VBAP-POSNR,
      CP_POSNR TYPE VBAP-POSNR.

DATA: G_CONTAINER  TYPE SCRFNAME VALUE 'CC_CONTAINER_GRID',
      G_CONTAINER_POP  TYPE SCRFNAME VALUE 'CC_CONTAINER_GRID_POP',
      G_CUSTOM_CONTAINER TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      G_GRID       TYPE REF TO CL_GUI_ALV_GRID,
      G_GRID_POP    TYPE REF TO CL_GUI_ALV_GRID,
      GS_ALV       TYPE LVC_S_STBL,
      GW_FIELDCAT  TYPE TABLE OF LVC_S_FCAT WITH HEADER LINE,
      GW_FIELDCAT_POP TYPE TABLE OF LVC_S_FCAT WITH HEADER LINE,
      GWA_FIELDCAT_POP TYPE LVC_S_FCAT,
      LS_VARIANT   TYPE DISVARIANT,
      LSA_LAYOUT   TYPE LVC_S_LAYO,
      LS_LAYOUT    TYPE SLIS_LAYOUT_ALV,
      I_SORT       TYPE STANDARD TABLE OF LVC_S_SORT INITIAL SIZE 0,
      I_SORT_POP   TYPE STANDARD TABLE OF LVC_S_SORT INITIAL SIZE 0,
      WA_SORT      TYPE LVC_S_SORT.


FIELD-SYMBOLS : <FSH> LIKE LINE OF I_HEADER,
                <FSD> LIKE LINE OF I_DETAIL.

INCLUDE ZSDSFIR0140_SUBRUTINE.
*Selection Screen.
SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-B01.
PARAMETERS : P_DOCNR TYPE ZSDSFIT006-DOCNR OBLIGATORY MODIF ID CHG.
SELECTION-SCREEN END OF BLOCK B1.

INITIALIZATION.
*Approve Name
  PERFORM F_ASSIGN_MANAGER.

AT SELECTION-SCREEN OUTPUT.
  CLEAR : I_HEADER[],I_DETAIL[],I_DETAIL_200[].
  IF P_DOCNR IS NOT INITIAL.
    PERFORM F_GET_DATA
                TABLES
                   I_HEADER
                   I_DETAIL
                   I_VBAP
                   I_KONV
                   I_DETAIL_OLD
                USING
                   P_DOCNR.


    IF I_HEADER[] IS NOT INITIAL.
      READ TABLE I_HEADER INTO W_HEADER INDEX 1.
      CHECK SY-SUBRC EQ 0.
      CASE W_HEADER-REFTYPE.
        WHEN 'QT' OR 'SO'. "Reference
          FIRST_INITIAL = 'X'.
          CALL SCREEN 100.
        WHEN 'UE'. " User key in
          I_DETAIL_200[] = I_DETAIL[].
          FIRST_INITIAL = 'X'.
          CALL SCREEN 200.
      ENDCASE.
    ELSE.
      MESSAGE S000(38) WITH 'Data not found' DISPLAY LIKE 'E'.
      EXIT.
    ENDIF.

  ENDIF.



START-OF-SELECTION.
  CLEAR : I_HEADER[],I_DETAIL[],I_DETAIL_200[].
  PERFORM F_GET_DATA
              TABLES
                 I_HEADER
                 I_DETAIL
                 I_VBAP
                 I_KONV
                 I_DETAIL_OLD
              USING
                 P_DOCNR.

END-OF-SELECTION.

  IF I_HEADER[] IS NOT INITIAL.
    READ TABLE I_HEADER INTO W_HEADER INDEX 1.
    CHECK SY-SUBRC EQ 0.

    CASE W_HEADER-REFTYPE.
      WHEN 'QT' OR 'SO'. "Reference
        FIRST_INITIAL = 'X'.
        CALL SCREEN 100.
      WHEN 'UE'. " User key in
        I_DETAIL_200[] = I_DETAIL[].
        FIRST_INITIAL = 'X'.
        CALL SCREEN 200.
    ENDCASE.
  ELSE.
    MESSAGE S000(38) WITH 'Data not found' DISPLAY LIKE 'E'.
    EXIT.
  ENDIF.

  INCLUDE ZSDSFIR0140_PBO.
  INCLUDE ZSDSFIR0140_PAI.
