*-----------------------------------------------------------------------
*  Program ID         : ZSDSFIR0120
*  Creation Date      : 29.03.2023
*  Author             : Jakarin S.
*  Add-on ID          : ZFIARE026
*  Description        : List of letter of billing document
*  Purpose            :
*  Copied from        : ZAR_MSBILL_CRED_REP SAP ECC6
*  Restriction        :
*-----------------------------------------------------------------------
*  CHANGE HISTORY
*-----------------------------------------------------------------------
*  Date        Task #      Programmer  Description
*-----------------------------------------------------------------------
*  DD.MM.YYYY  TR no.      ABAP Name   Detail
*-----------------------------------------------------------------------
REPORT ZSDSFIR0150 NO STANDARD PAGE HEADING.
TYPE-POOLS : VRM,SLIS.
TABLES : VBAK,VBAP,KONV,ZSDSFIT006,ZSDSFIT007,AUFK.


TYPES : BEGIN OF TYP_HEADER,
          DOCNR TYPE ZSDSFIT006-DOCNR,
          VBELN TYPE ZSDSFIT006-VBELN,
          KUNNR TYPE ZSDSFIT006-KUNNR,
          NAME1 TYPE ZSDSFIT006-NAME1,
          BSTKD TYPE ZSDSFIT006-BSTKD,
          AUFNR TYPE ZSDSFIT006-AUFNR,
          KTEXT TYPE ZSDSFIT006-KTEXT,
          DOCTYPE TYPE ZSDSFIT006-DOCTYPE,
          DDTEXT TYPE DD07T-DDTEXT,
          REFTYPE TYPE ZSDSFIT006-REFTYPE,
          PMNTTYP TYPE ZSDSFIT006-PMNTTYP,
          NETWR TYPE ZSDSFIT007-NETWR,
          VAT_AMT TYPE ZSDSFIT007-NETWR,
          WHT_AMT TYPE ZSDSFIT007-NETWR,
          PRCNT TYPE ZSDSFIT006-PRCNT,
          VAT TYPE ZSDSFIT006-VAT,
          WHTAX TYPE ZSDSFIT006-WHTAX,
          DOCDATE TYPE ZSDSFIT006-DOCDATE,
          POSDESC TYPE ZSDSFIT006-POSDESC,
          TOPIC TYPE ZSDSFIT006-TOPIC,
          ATTEND TYPE ZSDSFIT006-ATTEND,
          ZTERM TYPE ZSDSFIT006-ZTERM,
          TEXT1 TYPE T052U-TEXT1,
          ERNAM TYPE ZSDSFIT006-ERNAM,
          ERDAT TYPE ZSDSFIT006-ERDAT,
          ERTIM TYPE ZSDSFIT006-ERTIM,
          AENAM TYPE ZSDSFIT006-AENAM,
          AEDAT TYPE ZSDSFIT006-AEDAT,
          AETIM TYPE ZSDSFIT006-AETIM,
        END OF TYP_HEADER.

TYPES : BEGIN OF TYP_OUTPUT,
            DOCNR TYPE ZSDSFIT006-DOCNR,
            VBELN TYPE ZSDSFIT006-VBELN,
            KUNNR TYPE ZSDSFIT006-KUNNR,
            NAME1 TYPE ZSDSFIT006-NAME1,
            BSTKD TYPE ZSDSFIT006-BSTKD,
            AUFNR TYPE ZSDSFIT006-AUFNR,
            KTEXT TYPE ZSDSFIT006-KTEXT,
            DOCTYPE TYPE ZSDSFIT006-DOCTYPE,
            DDTEXT TYPE DD07T-DDTEXT,
            REFTYPE TYPE ZSDSFIT006-REFTYPE,
            PMNTTYP TYPE ZSDSFIT006-PMNTTYP,
            NETWR TYPE ZSDSFIT007-NETWR,
            VAT_AMT TYPE ZSDSFIT007-NETWR,
            WHT_AMT TYPE ZSDSFIT007-NETWR,
            G_NETWR TYPE ZSDSFIT007-NETWR,
            PRCNT TYPE ZSDSFIT006-PRCNT,
            VAT TYPE ZSDSFIT006-VAT,
            WHTAX TYPE ZSDSFIT006-WHTAX,
            DOCDATE TYPE ZSDSFIT006-DOCDATE,
*            posdesc TYPE ZSDSFIT006-posdesc,
            TOPIC TYPE ZSDSFIT006-TOPIC,
            ATTEND TYPE ZSDSFIT006-ATTEND,
            ZTERM TYPE ZSDSFIT006-ZTERM,
            TEXT1 TYPE T052U-TEXT1,
            ERNAM TYPE ZSDSFIT006-ERNAM,
            ERNAM_TXT(100) TYPE C,
            ERDAT TYPE ZSDSFIT006-ERDAT,
            ERTIM TYPE ZSDSFIT006-ERTIM,
            AENAM TYPE ZSDSFIT006-AENAM,
            AENAM_TXT(100) TYPE C,
            AEDAT TYPE ZSDSFIT006-AEDAT,
            AETIM TYPE ZSDSFIT006-AETIM,
*            pernr TYPE ZSDSFIT008-pernr,
*            vorna TYPE ZSDSFIT008-vorna,
*            nachn TYPE ZSDSFIT008-nachn,
  END OF TYP_OUTPUT.

TYPES : BEGIN OF TYP_CFG.
        INCLUDE STRUCTURE ZSDSFIT008.
TYPES : END OF TYP_CFG.


DATA : IT_HEADER TYPE TABLE OF TYP_HEADER,
       W_HEADER LIKE LINE OF IT_HEADER,
       IT_OUTPUT TYPE TABLE OF TYP_OUTPUT,
       W_OUTPUT LIKE LINE OF IT_OUTPUT,
       IT_CFG TYPE TABLE OF TYP_CFG,
       W_CFG LIKE LINE OF IT_CFG.

DATA: GR_TABLE   TYPE REF TO CL_SALV_TABLE,
      GR_DISPLAY TYPE REF TO CL_SALV_DISPLAY_SETTINGS,
      GR_COLUMNS  TYPE REF TO CL_SALV_COLUMNS_TABLE,
      GR_COLUMN  TYPE REF TO CL_SALV_COLUMN,
      GR_AGGRS TYPE REF TO CL_SALV_AGGREGATIONS,
      GR_SORT TYPE REF TO CL_SALV_SORTS,
      GR_SORT_COLUMN TYPE REF TO CL_SALV_SORT, "column sort
      GR_EVENTS TYPE REF TO CL_SALV_EVENTS_TABLE,
      GR_FUNCTIONS TYPE REF TO CL_SALV_FUNCTIONS_LIST,
      GR_LAYOUT  TYPE REF TO CL_SALV_LAYOUT,
      G_VARIANT TYPE SLIS_VARI,
      GR_KEY    TYPE SALV_S_LAYOUT_KEY,
      GR_SELECTIONS TYPE REF TO CL_SALV_SELECTIONS,
      WA_ALV TYPE TYP_HEADER,
      LV_ROWS TYPE I,
      LV_SRWS(6) TYPE C.




*Selection Screen.
SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-B01.
SELECT-OPTIONS: S_DOCDAT FOR ZSDSFIT006-DOCDATE OBLIGATORY MODIF ID DSP,
                S_DOCNR FOR ZSDSFIT006-DOCNR  MODIF ID DSP,
                S_VBELN FOR ZSDSFIT006-VBELN  MODIF ID DSP,
                S_KUNNR FOR ZSDSFIT006-KUNNR MODIF ID DSP,
                S_AUFNR FOR AUFK-AUFNR MODIF ID DSP.
PARAMETERS : P_NAME1 TYPE ZSDSFIT006-NAME1 MODIF ID DSP.
SELECT-OPTIONS: S_BSTKD FOR ZSDSFIT006-BSTKD MODIF ID DSP,
                S_ERDAT FOR ZSDSFIT006-ERDAT MODIF ID DSP,
                S_TYPE FOR ZSDSFIT006-DOCTYPE MODIF ID DSP,
                S_ERNAM FOR ZSDSFIT006-ERNAM MODIF ID DSP.

SELECTION-SCREEN END OF BLOCK B1.


INITIALIZATION.

AT SELECTION-SCREEN OUTPUT.



START-OF-SELECTION.
  PERFORM F_GET_DATA TABLES IT_HEADER IT_OUTPUT.

END-OF-SELECTION.
  PERFORM F_DISPLAY_ALV.

  INCLUDE ZSDSFIR0150_SUBRUTINE.
