*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZSDSV_AVAIL_SLOC................................*
FORM GET_DATA_ZSDSV_AVAIL_SLOC.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZSDSMMC002 WHERE
(VIM_WHERETAB) .
    CLEAR ZSDSV_AVAIL_SLOC .
ZSDSV_AVAIL_SLOC-MANDT =
ZSDSMMC002-MANDT .
ZSDSV_AVAIL_SLOC-WERKS =
ZSDSMMC002-WERKS .
ZSDSV_AVAIL_SLOC-MTART =
ZSDSMMC002-MTART .
ZSDSV_AVAIL_SLOC-LGORT =
ZSDSMMC002-LGORT .
ZSDSV_AVAIL_SLOC-ZDEL_FLG =
ZSDSMMC002-ZDEL_FLG .
ZSDSV_AVAIL_SLOC-ZCRT_DATE =
ZSDSMMC002-ZCRT_DATE .
ZSDSV_AVAIL_SLOC-ZCRT_TIME =
ZSDSMMC002-ZCRT_TIME .
ZSDSV_AVAIL_SLOC-ZCRT_USER =
ZSDSMMC002-ZCRT_USER .
ZSDSV_AVAIL_SLOC-ZCRT_PGM =
ZSDSMMC002-ZCRT_PGM .
ZSDSV_AVAIL_SLOC-ZUPD_DATE =
ZSDSMMC002-ZUPD_DATE .
ZSDSV_AVAIL_SLOC-ZUPD_TIME =
ZSDSMMC002-ZUPD_TIME .
ZSDSV_AVAIL_SLOC-ZUPD_USER =
ZSDSMMC002-ZUPD_USER .
ZSDSV_AVAIL_SLOC-ZUPD_PGM =
ZSDSMMC002-ZUPD_PGM .
<VIM_TOTAL_STRUC> = ZSDSV_AVAIL_SLOC.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZSDSV_AVAIL_SLOC .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZSDSV_AVAIL_SLOC.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZSDSV_AVAIL_SLOC-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZSDSMMC002 WHERE
  WERKS = ZSDSV_AVAIL_SLOC-WERKS AND
  MTART = ZSDSV_AVAIL_SLOC-MTART AND
  LGORT = ZSDSV_AVAIL_SLOC-LGORT .
    IF SY-SUBRC = 0.
    DELETE ZSDSMMC002 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZSDSMMC002 WHERE
  WERKS = ZSDSV_AVAIL_SLOC-WERKS AND
  MTART = ZSDSV_AVAIL_SLOC-MTART AND
  LGORT = ZSDSV_AVAIL_SLOC-LGORT .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZSDSMMC002.
    ENDIF.
ZSDSMMC002-MANDT =
ZSDSV_AVAIL_SLOC-MANDT .
ZSDSMMC002-WERKS =
ZSDSV_AVAIL_SLOC-WERKS .
ZSDSMMC002-MTART =
ZSDSV_AVAIL_SLOC-MTART .
ZSDSMMC002-LGORT =
ZSDSV_AVAIL_SLOC-LGORT .
ZSDSMMC002-ZDEL_FLG =
ZSDSV_AVAIL_SLOC-ZDEL_FLG .
ZSDSMMC002-ZCRT_DATE =
ZSDSV_AVAIL_SLOC-ZCRT_DATE .
ZSDSMMC002-ZCRT_TIME =
ZSDSV_AVAIL_SLOC-ZCRT_TIME .
ZSDSMMC002-ZCRT_USER =
ZSDSV_AVAIL_SLOC-ZCRT_USER .
ZSDSMMC002-ZCRT_PGM =
ZSDSV_AVAIL_SLOC-ZCRT_PGM .
ZSDSMMC002-ZUPD_DATE =
ZSDSV_AVAIL_SLOC-ZUPD_DATE .
ZSDSMMC002-ZUPD_TIME =
ZSDSV_AVAIL_SLOC-ZUPD_TIME .
ZSDSMMC002-ZUPD_USER =
ZSDSV_AVAIL_SLOC-ZUPD_USER .
ZSDSMMC002-ZUPD_PGM =
ZSDSV_AVAIL_SLOC-ZUPD_PGM .
    IF SY-SUBRC = 0.
    UPDATE ZSDSMMC002 ##WARN_OK.
    ELSE.
    INSERT ZSDSMMC002 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZSDSV_AVAIL_SLOC-UPD_FLAG,
STATUS_ZSDSV_AVAIL_SLOC-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZSDSV_AVAIL_SLOC.
  SELECT SINGLE * FROM ZSDSMMC002 WHERE
WERKS = ZSDSV_AVAIL_SLOC-WERKS AND
MTART = ZSDSV_AVAIL_SLOC-MTART AND
LGORT = ZSDSV_AVAIL_SLOC-LGORT .
ZSDSV_AVAIL_SLOC-MANDT =
ZSDSMMC002-MANDT .
ZSDSV_AVAIL_SLOC-WERKS =
ZSDSMMC002-WERKS .
ZSDSV_AVAIL_SLOC-MTART =
ZSDSMMC002-MTART .
ZSDSV_AVAIL_SLOC-LGORT =
ZSDSMMC002-LGORT .
ZSDSV_AVAIL_SLOC-ZDEL_FLG =
ZSDSMMC002-ZDEL_FLG .
ZSDSV_AVAIL_SLOC-ZCRT_DATE =
ZSDSMMC002-ZCRT_DATE .
ZSDSV_AVAIL_SLOC-ZCRT_TIME =
ZSDSMMC002-ZCRT_TIME .
ZSDSV_AVAIL_SLOC-ZCRT_USER =
ZSDSMMC002-ZCRT_USER .
ZSDSV_AVAIL_SLOC-ZCRT_PGM =
ZSDSMMC002-ZCRT_PGM .
ZSDSV_AVAIL_SLOC-ZUPD_DATE =
ZSDSMMC002-ZUPD_DATE .
ZSDSV_AVAIL_SLOC-ZUPD_TIME =
ZSDSMMC002-ZUPD_TIME .
ZSDSV_AVAIL_SLOC-ZUPD_USER =
ZSDSMMC002-ZUPD_USER .
ZSDSV_AVAIL_SLOC-ZUPD_PGM =
ZSDSMMC002-ZUPD_PGM .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZSDSV_AVAIL_SLOC USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZSDSV_AVAIL_SLOC-WERKS TO
ZSDSMMC002-WERKS .
MOVE ZSDSV_AVAIL_SLOC-MTART TO
ZSDSMMC002-MTART .
MOVE ZSDSV_AVAIL_SLOC-LGORT TO
ZSDSMMC002-LGORT .
MOVE ZSDSV_AVAIL_SLOC-MANDT TO
ZSDSMMC002-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZSDSMMC002'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZSDSMMC002 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZSDSMMC002'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
