*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZSDSV_UNL_PRICE.................................*
FORM GET_DATA_ZSDSV_UNL_PRICE.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZSDSMMT011 WHERE
(VIM_WHERETAB) .
    CLEAR ZSDSV_UNL_PRICE .
ZSDSV_UNL_PRICE-MANDT =
ZSDSMMT011-MANDT .
ZSDSV_UNL_PRICE-MTART =
ZSDSMMT011-MTART .
ZSDSV_UNL_PRICE-PRODH =
ZSDSMMT011-PRODH .
ZSDSV_UNL_PRICE-ZZ1_DES_PT_C =
ZSDSMMT011-ZZ1_DES_PT_C .
ZSDSV_UNL_PRICE-PRICE_VOLUME =
ZSDSMMT011-PRICE_VOLUME .
ZSDSV_UNL_PRICE-ZDEL_FLG =
ZSDSMMT011-ZDEL_FLG .
ZSDSV_UNL_PRICE-ZCRT_DATE =
ZSDSMMT011-ZCRT_DATE .
ZSDSV_UNL_PRICE-ZCRT_TIME =
ZSDSMMT011-ZCRT_TIME .
ZSDSV_UNL_PRICE-ZCRT_USER =
ZSDSMMT011-ZCRT_USER .
ZSDSV_UNL_PRICE-ZCRT_PGM =
ZSDSMMT011-ZCRT_PGM .
ZSDSV_UNL_PRICE-ZUPD_DATE =
ZSDSMMT011-ZUPD_DATE .
ZSDSV_UNL_PRICE-ZUPD_TIME =
ZSDSMMT011-ZUPD_TIME .
ZSDSV_UNL_PRICE-ZUPD_USER =
ZSDSMMT011-ZUPD_USER .
ZSDSV_UNL_PRICE-ZUPD_PGM =
ZSDSMMT011-ZUPD_PGM .
    SELECT * FROM ZDSCAC006 WHERE
ZZ1_DES_PT_C = ZSDSMMT011-ZZ1_DES_PT_C .
ZSDSV_UNL_PRICE-DES_PT_N =
ZDSCAC006-DES_PT_N .
      EXIT.
    ENDSELECT.
<VIM_TOTAL_STRUC> = ZSDSV_UNL_PRICE.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZSDSV_UNL_PRICE .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZSDSV_UNL_PRICE.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZSDSV_UNL_PRICE-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZSDSMMT011 WHERE
  MTART = ZSDSV_UNL_PRICE-MTART AND
  PRODH = ZSDSV_UNL_PRICE-PRODH AND
  ZZ1_DES_PT_C = ZSDSV_UNL_PRICE-ZZ1_DES_PT_C .
    IF SY-SUBRC = 0.
    DELETE ZSDSMMT011 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZSDSMMT011 WHERE
  MTART = ZSDSV_UNL_PRICE-MTART AND
  PRODH = ZSDSV_UNL_PRICE-PRODH AND
  ZZ1_DES_PT_C = ZSDSV_UNL_PRICE-ZZ1_DES_PT_C .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZSDSMMT011.
    ENDIF.
ZSDSMMT011-MANDT =
ZSDSV_UNL_PRICE-MANDT .
ZSDSMMT011-MTART =
ZSDSV_UNL_PRICE-MTART .
ZSDSMMT011-PRODH =
ZSDSV_UNL_PRICE-PRODH .
ZSDSMMT011-ZZ1_DES_PT_C =
ZSDSV_UNL_PRICE-ZZ1_DES_PT_C .
ZSDSMMT011-PRICE_VOLUME =
ZSDSV_UNL_PRICE-PRICE_VOLUME .
ZSDSMMT011-ZDEL_FLG =
ZSDSV_UNL_PRICE-ZDEL_FLG .
ZSDSMMT011-ZCRT_DATE =
ZSDSV_UNL_PRICE-ZCRT_DATE .
ZSDSMMT011-ZCRT_TIME =
ZSDSV_UNL_PRICE-ZCRT_TIME .
ZSDSMMT011-ZCRT_USER =
ZSDSV_UNL_PRICE-ZCRT_USER .
ZSDSMMT011-ZCRT_PGM =
ZSDSV_UNL_PRICE-ZCRT_PGM .
ZSDSMMT011-ZUPD_DATE =
ZSDSV_UNL_PRICE-ZUPD_DATE .
ZSDSMMT011-ZUPD_TIME =
ZSDSV_UNL_PRICE-ZUPD_TIME .
ZSDSMMT011-ZUPD_USER =
ZSDSV_UNL_PRICE-ZUPD_USER .
ZSDSMMT011-ZUPD_PGM =
ZSDSV_UNL_PRICE-ZUPD_PGM .
    IF SY-SUBRC = 0.
    UPDATE ZSDSMMT011 ##WARN_OK.
    ELSE.
    INSERT ZSDSMMT011 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZSDSV_UNL_PRICE-UPD_FLAG,
STATUS_ZSDSV_UNL_PRICE-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZSDSV_UNL_PRICE.
  SELECT SINGLE * FROM ZSDSMMT011 WHERE
MTART = ZSDSV_UNL_PRICE-MTART AND
PRODH = ZSDSV_UNL_PRICE-PRODH AND
ZZ1_DES_PT_C = ZSDSV_UNL_PRICE-ZZ1_DES_PT_C .
ZSDSV_UNL_PRICE-MANDT =
ZSDSMMT011-MANDT .
ZSDSV_UNL_PRICE-MTART =
ZSDSMMT011-MTART .
ZSDSV_UNL_PRICE-PRODH =
ZSDSMMT011-PRODH .
ZSDSV_UNL_PRICE-ZZ1_DES_PT_C =
ZSDSMMT011-ZZ1_DES_PT_C .
ZSDSV_UNL_PRICE-PRICE_VOLUME =
ZSDSMMT011-PRICE_VOLUME .
ZSDSV_UNL_PRICE-ZDEL_FLG =
ZSDSMMT011-ZDEL_FLG .
ZSDSV_UNL_PRICE-ZCRT_DATE =
ZSDSMMT011-ZCRT_DATE .
ZSDSV_UNL_PRICE-ZCRT_TIME =
ZSDSMMT011-ZCRT_TIME .
ZSDSV_UNL_PRICE-ZCRT_USER =
ZSDSMMT011-ZCRT_USER .
ZSDSV_UNL_PRICE-ZCRT_PGM =
ZSDSMMT011-ZCRT_PGM .
ZSDSV_UNL_PRICE-ZUPD_DATE =
ZSDSMMT011-ZUPD_DATE .
ZSDSV_UNL_PRICE-ZUPD_TIME =
ZSDSMMT011-ZUPD_TIME .
ZSDSV_UNL_PRICE-ZUPD_USER =
ZSDSMMT011-ZUPD_USER .
ZSDSV_UNL_PRICE-ZUPD_PGM =
ZSDSMMT011-ZUPD_PGM .
    SELECT * FROM ZDSCAC006 WHERE
ZZ1_DES_PT_C = ZSDSMMT011-ZZ1_DES_PT_C .
ZSDSV_UNL_PRICE-DES_PT_N =
ZDSCAC006-DES_PT_N .
      EXIT.
    ENDSELECT.
    IF SY-SUBRC NE 0.
      CLEAR SY-SUBRC.
      CLEAR ZSDSV_UNL_PRICE-DES_PT_N .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZSDSV_UNL_PRICE USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZSDSV_UNL_PRICE-MTART TO
ZSDSMMT011-MTART .
MOVE ZSDSV_UNL_PRICE-PRODH TO
ZSDSMMT011-PRODH .
MOVE ZSDSV_UNL_PRICE-ZZ1_DES_PT_C TO
ZSDSMMT011-ZZ1_DES_PT_C .
MOVE ZSDSV_UNL_PRICE-MANDT TO
ZSDSMMT011-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZSDSMMT011'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZSDSMMT011 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZSDSMMT011'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZSDSV_UNL_PRICE USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZSDSMMT011-MANDT =
ZSDSV_UNL_PRICE-MANDT .
ZSDSMMT011-MTART =
ZSDSV_UNL_PRICE-MTART .
ZSDSMMT011-PRODH =
ZSDSV_UNL_PRICE-PRODH .
ZSDSMMT011-ZZ1_DES_PT_C =
ZSDSV_UNL_PRICE-ZZ1_DES_PT_C .
ZSDSMMT011-PRICE_VOLUME =
ZSDSV_UNL_PRICE-PRICE_VOLUME .
ZSDSMMT011-ZDEL_FLG =
ZSDSV_UNL_PRICE-ZDEL_FLG .
ZSDSMMT011-ZCRT_DATE =
ZSDSV_UNL_PRICE-ZCRT_DATE .
ZSDSMMT011-ZCRT_TIME =
ZSDSV_UNL_PRICE-ZCRT_TIME .
ZSDSMMT011-ZCRT_USER =
ZSDSV_UNL_PRICE-ZCRT_USER .
ZSDSMMT011-ZCRT_PGM =
ZSDSV_UNL_PRICE-ZCRT_PGM .
ZSDSMMT011-ZUPD_DATE =
ZSDSV_UNL_PRICE-ZUPD_DATE .
ZSDSMMT011-ZUPD_TIME =
ZSDSV_UNL_PRICE-ZUPD_TIME .
ZSDSMMT011-ZUPD_USER =
ZSDSV_UNL_PRICE-ZUPD_USER .
ZSDSMMT011-ZUPD_PGM =
ZSDSV_UNL_PRICE-ZUPD_PGM .
    SELECT * FROM ZDSCAC006 WHERE
ZZ1_DES_PT_C = ZSDSMMT011-ZZ1_DES_PT_C .
ZSDSV_UNL_PRICE-DES_PT_N =
ZDSCAC006-DES_PT_N .
      EXIT.
    ENDSELECT.
    IF SY-SUBRC NE 0.
      CLEAR SY-SUBRC.
      CLEAR ZSDSV_UNL_PRICE-DES_PT_N .
    ENDIF.
ENDFORM.
