*&---------------------------------------------------------------------*
*& Report ZSDSFIR0160
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZSDSFIR0160 NO STANDARD PAGE HEADING.

TYPE-POOLS : SLIS,VRM.
TABLES : VBAK,VBAP,VBKD,KONV,ZSDSFIT006.
TABLES : TNAPR,                         "Programs & Forms
        ITCPO,                         "Communicationarea for Spool
        ARC_PARAMS,                    "Archive parameters
        TOA_DARA,                      "Archive parameters
        ADDR_KEY.                      "Adressnumber for ADDRESS

TYPES : BEGIN OF TYP_HEADER.
        INCLUDE STRUCTURE ZSDSFIT006.
TYPES :
        TXT_DATE(100) TYPE C,
        TXT_PAYMENT(100) TYPE C,
        TXT_PROJECT(100) TYPE C,
        TXT_PO(100) TYPE C,
        VORNA TYPE ZSDSFIT008-VORNA,
        NACHN TYPE ZSDSFIT008-NACHN,
        PERNR TYPE ZSDSFIT008-PERNR, "ADD BY APHAI 29.09.2015
        END OF TYP_HEADER.

TYPES : BEGIN OF TYP_DETAIL.
        INCLUDE STRUCTURE ZSDSFIT007.
TYPES : TXT_KWMENG(10) TYPE N,
        MEINH TYPE MARM-MEINH,
        END OF TYP_DETAIL.

TYPES : BEGIN OF TYP_SUMMARY,
        DOCNR TYPE ZSDSFIT006-DOCNR,
        TOT_QTY TYPE VBAP-KWMENG, "total quantity
        TOT_AMT1 TYPE VBAP-NETWR, " total amount 1
        TOT_ADV TYPE VBAP-NETWR, " advance reciept
        TOT_AMT2 TYPE VBAP-NETWR, " total amount after minus advance reciept
        TOT_VAT TYPE VBAP-NETWR, " vat
        TOT_WHT TYPE VBAP-NETWR, " with holding tax
        NET_AMT TYPE VBAP-NETWR, " Net amount
        NET_AMT_TXT TYPE CHAR255, " Net amount text
        END OF TYP_SUMMARY.

TYPES : BEGIN OF TYP_KONV,
        KNUMV TYPE VBAK-KNUMV,
        KPOSN TYPE KONV-KPOSN,
        KSCHL TYPE KONV-KSCHL,
        KWERT TYPE KONV-KWERT,
  END OF TYP_KONV.

TYPES : BEGIN OF TYP_VBAP,
        VBELN TYPE VBAP-VBELN,
        POSNR TYPE VBAP-POSNR,
        MATNR TYPE VBAP-MATNR,
        KWMENG TYPE VBAP-KWMENG,
        NETPR TYPE VBAP-NETPR,
        NETWR TYPE VBAP-NETWR,
  END OF TYP_VBAP.

TYPES : BEGIN OF TYP_FOOT,
        DOCNR TYPE ZSDSFIT006-DOCNR,
        LIST_TYPE TYPE CHAR4,
        LIST_TEXT TYPE CHAR255,
        LIST_TEXT2 TYPE CHAR255,
        VALUE TYPE VBAP-NETWR,
        VALUE_TXT TYPE CHAR17,
        SORT TYPE I,
        END OF TYP_FOOT.

TYPES : BEGIN OF TYP_FOOT_TOTAL,
        DOCNR TYPE ZSDSFIT006-DOCNR,
        TOT_QTY(4) TYPE N,
        TOT_AMT1 TYPE VBAP-NETWR,
        SORT TYPE I,
        END OF TYP_FOOT_TOTAL.

TYPES : BEGIN OF TYP_CONFIG,
        PERNR TYPE ZSDSFIT008-PERNR,
        BNAME TYPE ZSDSFIT008-BNAME,
      END OF TYP_CONFIG.

DATA : I_HEADER TYPE STANDARD TABLE OF TYP_HEADER,
       W_HEADER TYPE TYP_HEADER,
       I_DETAIL TYPE STANDARD TABLE OF TYP_DETAIL,
       W_DETAIL TYPE TYP_DETAIL,
       I_SUMMARY TYPE STANDARD TABLE OF TYP_SUMMARY,
       W_SUMMARY TYPE TYP_SUMMARY,
       I_VBAP TYPE STANDARD TABLE OF TYP_VBAP,
       W_VBAP TYPE TYP_VBAP,
       I_KONV TYPE STANDARD TABLE OF TYP_KONV,
       W_KONV TYPE TYP_KONV,
       I_FOOT TYPE TABLE OF TYP_FOOT,
       W_FOOT LIKE LINE OF I_FOOT,
       I_FOOT_TOTAL TYPE TABLE OF TYP_FOOT_TOTAL,
       W_FOOT_TOTAL LIKE LINE OF I_FOOT_TOTAL,
       I_CONF TYPE TABLE OF TYP_CONFIG,
       W_CONF LIKE LINE OF I_CONF.

CONSTANTS :  GC_YES       TYPE C    VALUE 'X',
             GC_X         TYPE C    VALUE 'X',
             GC_REPID     TYPE REPID      VALUE 'ZSDSFIR0160',
             C_LANGU_TH   LIKE SYST-LANGU VALUE '2',
             GC_FORM_NAME TYPE TDSFNAME   VALUE 'ZSDSFI005'.

DATA:     GV_FORMNAME  TYPE TDSFNAME,
          GV_FM_NAME   TYPE RS38L_FNAM,
          T_OUTPUT_INFO  TYPE SSFCRESCL,
          GWA_CONTROL_PARAMETERS TYPE SSFCTRLOP,
          GWA_OUTPUT_OPTIONS TYPE SSFCOMPOP.
*Selection Screen.
SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-B01.
SELECT-OPTIONS: S_DOCNR FOR ZSDSFIT006-DOCNR  MODIF ID DSP,
                S_VBELN FOR ZSDSFIT006-VBELN  MODIF ID DSP,
                S_DOCDAT FOR ZSDSFIT006-DOCDATE  MODIF ID DSP,
                S_ERDAT FOR ZSDSFIT006-ERDAT MODIF ID DSP.
SELECTION-SCREEN END OF BLOCK B1.

INITIALIZATION.

AT SELECTION-SCREEN OUTPUT.

AT SELECTION-SCREEN.

START-OF-SELECTION.

  IF S_DOCNR[] IS INITIAL AND
     S_VBELN[] IS INITIAL AND
     S_DOCDAT[] IS INITIAL AND
     S_ERDAT[] IS INITIAL.
    MESSAGE I000(38) WITH 'Please input at least one selection criteria!' DISPLAY LIKE 'E'.
    EXIT.
  ENDIF.

  PERFORM F_GET_DATA TABLES I_HEADER
                            I_DETAIL
                            I_SUMMARY.

END-OF-SELECTION.

  IF I_HEADER[] IS NOT INITIAL.
    PERFORM F_PRINT_FORM.
  ELSE.
    MESSAGE I000(38) WITH 'Letter of billing not found' DISPLAY LIKE 'I'.
  ENDIF.

  INCLUDE ZSDSFIR0160_SUBRUTINE.
