*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZSDSV_YOUR_REFER................................*
FORM GET_DATA_ZSDSV_YOUR_REFER.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZSDSMMT023 WHERE
(VIM_WHERETAB) .
    CLEAR ZSDSV_YOUR_REFER .
ZSDSV_YOUR_REFER-MANDT =
ZSDSMMT023-MANDT .
ZSDSV_YOUR_REFER-IHREZ =
ZSDSMMT023-IHREZ .
ZSDSV_YOUR_REFER-ZDEL_FLG =
ZSDSMMT023-ZDEL_FLG .
ZSDSV_YOUR_REFER-ZCRT_DATE =
ZSDSMMT023-ZCRT_DATE .
ZSDSV_YOUR_REFER-ZCRT_TIME =
ZSDSMMT023-ZCRT_TIME .
ZSDSV_YOUR_REFER-ZCRT_USER =
ZSDSMMT023-ZCRT_USER .
ZSDSV_YOUR_REFER-ZCRT_PGM =
ZSDSMMT023-ZCRT_PGM .
ZSDSV_YOUR_REFER-ZUPD_DATE =
ZSDSMMT023-ZUPD_DATE .
ZSDSV_YOUR_REFER-ZUPD_TIME =
ZSDSMMT023-ZUPD_TIME .
ZSDSV_YOUR_REFER-ZUPD_USER =
ZSDSMMT023-ZUPD_USER .
ZSDSV_YOUR_REFER-ZUPD_PGM =
ZSDSMMT023-ZUPD_PGM .
<VIM_TOTAL_STRUC> = ZSDSV_YOUR_REFER.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZSDSV_YOUR_REFER .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZSDSV_YOUR_REFER.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZSDSV_YOUR_REFER-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZSDSMMT023 WHERE
  IHREZ = ZSDSV_YOUR_REFER-IHREZ .
    IF SY-SUBRC = 0.
    DELETE ZSDSMMT023 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZSDSMMT023 WHERE
  IHREZ = ZSDSV_YOUR_REFER-IHREZ .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZSDSMMT023.
    ENDIF.
ZSDSMMT023-MANDT =
ZSDSV_YOUR_REFER-MANDT .
ZSDSMMT023-IHREZ =
ZSDSV_YOUR_REFER-IHREZ .
ZSDSMMT023-ZDEL_FLG =
ZSDSV_YOUR_REFER-ZDEL_FLG .
ZSDSMMT023-ZCRT_DATE =
ZSDSV_YOUR_REFER-ZCRT_DATE .
ZSDSMMT023-ZCRT_TIME =
ZSDSV_YOUR_REFER-ZCRT_TIME .
ZSDSMMT023-ZCRT_USER =
ZSDSV_YOUR_REFER-ZCRT_USER .
ZSDSMMT023-ZCRT_PGM =
ZSDSV_YOUR_REFER-ZCRT_PGM .
ZSDSMMT023-ZUPD_DATE =
ZSDSV_YOUR_REFER-ZUPD_DATE .
ZSDSMMT023-ZUPD_TIME =
ZSDSV_YOUR_REFER-ZUPD_TIME .
ZSDSMMT023-ZUPD_USER =
ZSDSV_YOUR_REFER-ZUPD_USER .
ZSDSMMT023-ZUPD_PGM =
ZSDSV_YOUR_REFER-ZUPD_PGM .
    IF SY-SUBRC = 0.
    UPDATE ZSDSMMT023 ##WARN_OK.
    ELSE.
    INSERT ZSDSMMT023 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZSDSV_YOUR_REFER-UPD_FLAG,
STATUS_ZSDSV_YOUR_REFER-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZSDSV_YOUR_REFER.
  SELECT SINGLE * FROM ZSDSMMT023 WHERE
IHREZ = ZSDSV_YOUR_REFER-IHREZ .
ZSDSV_YOUR_REFER-MANDT =
ZSDSMMT023-MANDT .
ZSDSV_YOUR_REFER-IHREZ =
ZSDSMMT023-IHREZ .
ZSDSV_YOUR_REFER-ZDEL_FLG =
ZSDSMMT023-ZDEL_FLG .
ZSDSV_YOUR_REFER-ZCRT_DATE =
ZSDSMMT023-ZCRT_DATE .
ZSDSV_YOUR_REFER-ZCRT_TIME =
ZSDSMMT023-ZCRT_TIME .
ZSDSV_YOUR_REFER-ZCRT_USER =
ZSDSMMT023-ZCRT_USER .
ZSDSV_YOUR_REFER-ZCRT_PGM =
ZSDSMMT023-ZCRT_PGM .
ZSDSV_YOUR_REFER-ZUPD_DATE =
ZSDSMMT023-ZUPD_DATE .
ZSDSV_YOUR_REFER-ZUPD_TIME =
ZSDSMMT023-ZUPD_TIME .
ZSDSV_YOUR_REFER-ZUPD_USER =
ZSDSMMT023-ZUPD_USER .
ZSDSV_YOUR_REFER-ZUPD_PGM =
ZSDSMMT023-ZUPD_PGM .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZSDSV_YOUR_REFER USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZSDSV_YOUR_REFER-IHREZ TO
ZSDSMMT023-IHREZ .
MOVE ZSDSV_YOUR_REFER-MANDT TO
ZSDSMMT023-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZSDSMMT023'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZSDSMMT023 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZSDSMMT023'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
