FUNCTION-POOL ZSDSMM07.                     "MESSAGE-ID ..

TYPE-POOLS : TRUXS.

DATA: GT_BOM_DETAIL TYPE STANDARD TABLE OF ZSDSMMS013,
      GS_BOM_DETAIL LIKE LINE OF GT_BOM_DETAIL,
      GT_MAST       TYPE STANDARD TABLE OF MAST,
      GS_MAST       LIKE LINE OF GT_MAST,
      GT_STKO       TYPE STANDARD TABLE OF STKO,     "WCH181113 Fix alternative BOM
      GS_STKO       LIKE LINE OF GT_STKO,            "WCH181113 Fix alternative BOM
      GT_STAS       TYPE STANDARD TABLE OF STAS,     "WCH181113 Fix alternative BOM
      GS_STAS       LIKE LINE OF GT_STAS,            "WCH181113 Fix alternative BOM
      GT_STPO       TYPE STANDARD TABLE OF STPO,
      GS_STPO       LIKE LINE OF GT_STPO,
      GT_MAKT       TYPE STANDARD TABLE OF MAKT,
      GS_MAKT       LIKE LINE OF GT_MAKT,
      GT_MARA       TYPE STANDARD TABLE OF MARA,
      GS_MARA       LIKE LINE OF GT_MARA,
      GT_CABN       TYPE STANDARD TABLE OF CABN,
      GS_CABN       LIKE LINE OF GT_CABN,
      GT_AUSP       TYPE STANDARD TABLE OF AUSP,
      GS_AUSP       LIKE LINE OF GT_AUSP.

RANGES: GR_ATNAM FOR CABN-ATNAM.
