"Name: \PR:SAPL2012\EX:MOVE_EXTENTIONIN_01\EI
ENHANCEMENT 0 ZSDS_PO_EXTENSIONIN.

DATA: LS_POHEADER TYPE ZSDSMMS037,
      LS_POITEM   TYPE ZSDSMMS038.
LOOP AT EXTENSIONIN.
  MOVE EXTENSIONIN TO WA_EXTENSIONIN.
  SHIFT WA_EXTENSIONIN BY C_LENSTRUC PLACES.
  CASE EXTENSIONIN-STRUCTURE.
    WHEN 'PO_Header'.
      CLEAR L_CONTAINER.
      MOVE WA_EXTENSIONIN TO L_CONTAINER.
      PERFORM MOVE_CONTAINER_IN USING L_CONTAINER 'ZSDSMMS037' LR_PAREX
                                CHANGING LS_POHEADER.
      CHECK NOT LS_POHEADER IS INITIAL.
      TRY.                                                  "#EC *
          MOVE-CORRESPONDING LS_POHEADER TO EXS_POHEADER.   "#EC *
        CATCH CX_ROOT.                                      "#EC *
          MESSAGE E051(MMPUR_BASE) WITH 'EXTENSIONIN' 'ZSDSMMS037' "1946529 "n_1974311
                                   INTO GL_DUMMY.
          MMPUR_MESSAGE_ENACO_FORCED SY-MSGTY SY-MSGID SY-MSGNO
                               SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
      ENDTRY.

      IF LS_POHEADER-ZZ_JTEPA IS NOT INITIAL.
        EXS_POHEADERX-ZZ_JTEPA = 'X'.
      ENDIF.
      IF LS_POHEADER-ZZ1_DIVCD_PO IS NOT INITIAL.
        EXS_POHEADERX-ZZ1_DIVCD_PO = 'X'.
      ENDIF.
      IF LS_POHEADER-ZZ1_DLV_MODE IS NOT INITIAL.
        EXS_POHEADERX-ZZ1_DLV_MODE = 'X'.
      ENDIF.
      IF LS_POHEADER-ZZ1_PRJ_C_PO IS NOT INITIAL.
        EXS_POHEADERX-ZZ1_PRJ_C_PO = 'X'.
      ENDIF.

    WHEN 'PO_Item'.
      CLEAR L_CONTAINER.
      MOVE WA_EXTENSIONIN TO L_CONTAINER.
      PERFORM MOVE_CONTAINER_IN USING L_CONTAINER 'ZSDSMMS038' LR_PAREX
                                CHANGING LS_POITEM.
      CHECK NOT LS_POITEM IS INITIAL.
      TRY.                                                  "#EC *
          MOVE-CORRESPONDING LS_POITEM TO CHT_POITEM.       "#EC *
        CATCH CX_ROOT.                                      "#EC *
          MESSAGE E051(MMPUR_BASE) WITH 'EXTENSIONIN' 'ZSDSMMS038' "1946529 "n_1974311
                                   INTO GL_DUMMY.
          MMPUR_MESSAGE_ENACO_FORCED SY-MSGTY SY-MSGID SY-MSGNO
                               SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
      ENDTRY.

      IF LS_POITEM-ZZ1_LOB_PO_PDI IS NOT INITIAL.
        CHT_POITEMX-ZZ1_LOB_PO_PDI = 'X'.
      ENDIF.
      IF LS_POITEM-ZZ1_DES_PT_C_PO IS NOT INITIAL.
        CHT_POITEMX-ZZ1_DES_PT_C_PO = 'X'.
      ENDIF.
  ENDCASE.

ENDLOOP.
ENDENHANCEMENT.
