class ZCL_SDSFI_CO_IETAX_SERVICE definition
  public
  inheriting from CL_PROXY_CLIENT
  final
  create public .

public section.

  methods CHECK_STATUS_RD_SENT
    importing
      !INPUT type ZSDSFIS061
    exporting
      !OUTPUT type ZSDSFIS072
    raising
      CX_AI_SYSTEM_FAULT
      CX_AI_APPLICATION_FAULT .
  methods CONSTRUCTOR
    importing
      !LOGICAL_PORT_NAME type PRX_LOGICAL_PORT_NAME optional
    raising
      CX_AI_SYSTEM_FAULT .
  methods SIGN_DOCUMENT
    importing
      !INPUT type ZSDSFIS065
    exporting
      !OUTPUT type ZSDSFIS067 .
protected section.
private section.
ENDCLASS.



CLASS ZCL_SDSFI_CO_IETAX_SERVICE IMPLEMENTATION.


  METHOD CHECK_STATUS_RD_SENT.
    DATA:
      LS_PARMBIND TYPE ABAP_PARMBIND,
      LT_PARMBIND TYPE ABAP_PARMBIND_TAB.

    LS_PARMBIND-NAME = 'INPUT'.
    LS_PARMBIND-KIND = CL_ABAP_OBJECTDESCR=>IMPORTING.
    GET REFERENCE OF INPUT INTO LS_PARMBIND-VALUE.
    INSERT LS_PARMBIND INTO TABLE LT_PARMBIND.

    LS_PARMBIND-NAME = 'OUTPUT'.
    LS_PARMBIND-KIND = CL_ABAP_OBJECTDESCR=>EXPORTING.
    GET REFERENCE OF OUTPUT INTO LS_PARMBIND-VALUE.
    INSERT LS_PARMBIND INTO TABLE LT_PARMBIND.

    IF_PROXY_CLIENT~EXECUTE(
      EXPORTING
        METHOD_NAME = 'CHECK_STATUS_RD_SENT'
      CHANGING
        PARMBIND_TAB = LT_PARMBIND
    ).
  ENDMETHOD.


  METHOD CONSTRUCTOR.

  SUPER->CONSTRUCTOR(
    CLASS_NAME          = 'ZCL_SDSFI_CO_IETAX_SERVICE'
    LOGICAL_PORT_NAME   = LOGICAL_PORT_NAME
  ).

  ENDMETHOD.


  method SIGN_DOCUMENT.
  endmethod.
ENDCLASS.
