class ZCL_IM_SDS_SETTLEMENT_1 definition
  public
  final
  create public .

public section.

  interfaces IF_EX_K_SETTLEMENT_1 .
protected section.
private section.
ENDCLASS.



CLASS ZCL_IM_SDS_SETTLEMENT_1 IMPLEMENTATION.


  METHOD IF_EX_K_SETTLEMENT_1~RW_CHANGE.

    DATA : LS_DATA_FIELD TYPE SETTLE_RW_CHANGE_CHECK.

    FIELD-SYMBOLS : <FS_BLDAT>       TYPE ANY,
                    <FS_BUDAT>       TYPE ANY,
                    <lft_DATA_CHECK> TYPE SETTLE_RW_CHANGE_CHECK_T.

*    FIELD-SYMBOLS : <FS>        TYPE ANY,
*                    <FST>       TYPE ANY TABLE,
*                    <LFT_ACCIT> TYPE SETTLE_ACCIT_T.

    FIELD-SYMBOLS : <FST_CK> TYPE ANY TABLE,
                    <FS_CK>  TYPE COBK.

    FIELD-SYMBOLS : <LFS_DATA_CHECK> TYPE ACCIT.
    DATA : LS_DATA_CHECK TYPE SETTLE_RW_CHANGE_CHECK.

    ZCL_SDSCA_UTIL_SDS=>CHECK_SDS( EXPORTING LV_MANDT = SY-MANDT
                                   IMPORTING LV_SDS   = DATA(LV_SDS) ).
    IF LV_SDS EQ ABAP_TRUE.

      ASSIGN ('(SAPLKO77)AK-BLDAT') TO <FS_BLDAT>.

      ASSIGN ('(SAPLKO77)AK-BUDAT') TO <FS_BUDAT>.
      IF <FS_BLDAT> IS ASSIGNED AND
         <FS_BUDAT> IS ASSIGNED.
        <FS_BLDAT> = <FS_BUDAT>.
      ENDIF.

      IF <FS_BUDAT> IS ASSIGNED.
        ASSIGN ('(SAPLKO77)CK[]') TO <FST_CK>.

        LOOP AT <FST_CK> ASSIGNING <FS_CK>.
          <FS_CK>-BLDAT = <FS_BUDAT>.
        ENDLOOP.
      ENDIF.



*      IF <FST> IS ASSIGNED.
*        LOOP AT <LFT_ACCIT> ASSIGNING <LFS_DATA_CHECK>.
*          <LFS_DATA_CHECK>-BLDAT = <LFS_DATA_CHECK>-BUDAT.
*          <LFS_DATA_CHECK>-WWERT = <LFS_DATA_CHECK>-BUDAT.
*          <LFS_DATA_CHECK>-VALUT = <LFS_DATA_CHECK>-BUDAT.
*        ENDLOOP.
*      ENDIF.


      CLEAR : ET_ACCIT.
      ASSIGN ('(SAPLKO77)GD_RW_CHANGE_CHECK') TO <lft_DATA_CHECK>.
      LS_DATA_CHECK-SLGVO = 'AB'.
      LS_DATA_CHECK-FDNAM = 'BLDAT'.
      APPEND LS_DATA_CHECK TO <lft_DATA_CHECK>.

      LS_DATA_CHECK-SLGVO = 'AB'.
      LS_DATA_CHECK-FDNAM = 'WWERT'.
      APPEND LS_DATA_CHECK TO <lft_DATA_CHECK>.

      LS_DATA_CHECK-SLGVO = 'AB'.
      LS_DATA_CHECK-FDNAM = 'VALUT'.
      APPEND LS_DATA_CHECK TO <lft_DATA_CHECK>.

      LS_DATA_FIELD-SLGVO = 'AB'.
      LS_DATA_FIELD-FDNAM = 'BLDAT'.
      APPEND LS_DATA_FIELD TO ET_RW_CHANGE_CHECK.

      LS_DATA_FIELD-SLGVO = 'AB'.
      LS_DATA_FIELD-FDNAM = 'WWERT'.
      APPEND LS_DATA_FIELD TO ET_RW_CHANGE_CHECK.

      LS_DATA_FIELD-SLGVO = 'AB'.
      LS_DATA_FIELD-FDNAM = 'VALUT'.
      APPEND LS_DATA_FIELD TO ET_RW_CHANGE_CHECK.

      LOOP AT IT_ACCIT INTO DATA(LS_DATA).
        LS_DATA-BLDAT = LS_DATA-BUDAT.
        LS_DATA-WWERT = LS_DATA-BUDAT.
        LS_DATA-VALUT = LS_DATA-BUDAT.



        APPEND LS_DATA TO ET_ACCIT.
      ENDLOOP.
    ENDIF.
  ENDMETHOD.
ENDCLASS.
