class ZCL_ZSDSPS_PROJECT_INF_DPC_EXT definition
  public
  inheriting from ZCL_ZSDSPS_PROJECT_INF_DPC
  create public .

public section.

  constants:
    BEGIN OF GC_CON,
        WBS_INFO   TYPE C LENGTH 10 VALUE 'wbsInfoSet',
        WBS_DETIAL TYPE C LENGTH 12 VALUE 'wbsDetialSet',
      END OF GC_CON .

  methods /IWBEP/IF_MGW_APPL_SRV_RUNTIME~CREATE_DEEP_ENTITY
    redefinition .
  methods /IWBEP/IF_MGW_APPL_SRV_RUNTIME~GET_ENTITYSET
    redefinition .
protected section.
private section.
ENDCLASS.



CLASS ZCL_ZSDSPS_PROJECT_INF_DPC_EXT IMPLEMENTATION.


  METHOD /IWBEP/IF_MGW_APPL_SRV_RUNTIME~CREATE_DEEP_ENTITY.

    DATA : LS_WBS_INFO   TYPE ZSDSFIS188,
           LS_WBS_DETAIL TYPE ZSDSFIS189.

    FIELD-SYMBOLS <LFS_DATA> TYPE ANY.

    IF IO_DATA_PROVIDER IS NOT INITIAL.
      IF     IV_ENTITY_SET_NAME EQ GC_CON-WBS_INFO.
        IO_DATA_PROVIDER->READ_ENTRY_DATA( IMPORTING ES_DATA = LS_WBS_INFO ).
        LCL_DATA=>GET_WBS_INFO( CHANGING CT_DATA = LS_WBS_INFO ).
        ASSIGN LS_WBS_INFO TO <LFS_DATA>.
      ELSEIF IV_ENTITY_SET_NAME EQ GC_CON-WBS_DETIAL.
        IO_DATA_PROVIDER->READ_ENTRY_DATA( IMPORTING ES_DATA = LS_WBS_DETAIL ).
        LCL_DATA=>GET_WBS_DETAIL( CHANGING CT_DATA = LS_WBS_DETAIL ).
        ASSIGN LS_WBS_DETAIL TO <LFS_DATA>.
      ENDIF.

      COPY_DATA_TO_REF(
           EXPORTING
           IS_DATA = <LFS_DATA>
           CHANGING
           CR_DATA = ER_DEEP_ENTITY
           ).
    ENDIF.

  ENDMETHOD.


  method /IWBEP/IF_MGW_APPL_SRV_RUNTIME~GET_ENTITYSET.
**TRY.
*CALL METHOD SUPER->/IWBEP/IF_MGW_APPL_SRV_RUNTIME~GET_ENTITYSET
**  EXPORTING
**    IV_ENTITY_NAME           =
**    IV_ENTITY_SET_NAME       =
**    IV_SOURCE_NAME           =
**    IT_FILTER_SELECT_OPTIONS =
**    IT_ORDER                 =
**    IS_PAGING                =
**    IT_NAVIGATION_PATH       =
**    IT_KEY_TAB               =
**    IV_FILTER_STRING         =
**    IV_SEARCH_STRING         =
**    IO_TECH_REQUEST_CONTEXT  =
**  IMPORTING
**    ER_ENTITYSET             =
**    ES_RESPONSE_CONTEXT      =
*    .
**  CATCH /IWBEP/CX_MGW_BUSI_EXCEPTION.
**  CATCH /IWBEP/CX_MGW_TECH_EXCEPTION.
**ENDTRY.
  endmethod.
ENDCLASS.
