INTERFACE ZIF_SDSFI_CUSTOMER_CREDIT_TYPE
  PUBLIC .
*-----------------------------------------------------------------------
*  CHANGE HISTORY
*-----------------------------------------------------------------------
*  Date        Task #      Programmer  Description
*-----------------------------------------------------------------------
*  05.06.2025  420000624   ThanapongC. - Add Special GL for Adv.Receive
*-----------------------------------------------------------------------
  TYPES:
    BEGIN OF TS_GENC,
      RT_VBTYP         TYPE SHP_VBTYP_RANGE_T,
      RT_GBSTK         TYPE SHP_GBSTK_RANGE_T,
      RT_CMGST         TYPE SHP_CMGST_RANGE_T,
      RT_BLART         TYPE WSGM_T_GM_TR_DOC_TYPE,
      RT_SPECIAL_GL    TYPE FIAPPT_T_GL_RANGE,
      RT_BLART_BILLING TYPE WSGM_T_GM_TR_DOC_TYPE,
      RT_BLART_OTHERS  TYPE WSGM_T_GM_TR_DOC_TYPE,
      RT_AUART_PROJ    TYPE SACO_AUART_RANGES_TAB,
      RT_FKART_PROJ    TYPE RANGE OF VBRK-FKART,
      RT_ZTERM_EXCLUDE TYPE RANGE OF VBKD-ZTERM,
      RT_ZTERM_CRDT    TYPE RANGE OF KNVV-ZTERM,

      BEGIN OF SPECIAL_GL,
        AR_INVOICE       TYPE UMSKZ,
        DOWN_PATMENT     TYPE UMSKZ,
        ADV_RECEIVE      TYPE UMSKZ,
        ADV_RECEIVE_01   TYPE UMSKZ,                        "+420000624
        POST_DATE_CHEQUE TYPE UMSKZ,
        AVAL             TYPE UMSKZ,
        DLC              TYPE UMSKZ,
        BANK_GUARANTEE   TYPE UMSKZ,
        CREDIT_INSURANCE TYPE UMSKZ,
        CHQ_RETURN       TYPE UMSKZ,
        RETENTION        TYPE UMSKZ,
      END OF SPECIAL_GL,

    END OF TS_GENC .
  TYPES:
    BEGIN OF TS_PARTNER_KEY,
      PARTNER TYPE BUT000-PARTNER,
    END OF TS_PARTNER_KEY .
  TYPES:
    TT_PARTNER_KEY TYPE HASHED TABLE OF TS_PARTNER_KEY
                                WITH UNIQUE KEY PARTNER .
  TYPES:
    BEGIN OF TS_VBELN_KEY,
      VBELN TYPE VBELN,
    END OF TS_VBELN_KEY .
  TYPES:
    TT_VBELN_KEY TYPE HASHED TABLE OF TS_VBELN_KEY
                      WITH UNIQUE KEY VBELN .
  TYPES:
    BEGIN OF TS_PSPNR,
      PSPNR TYPE PROJ-PSPNR,
      PSPID TYPE PROJ-PSPID,
    END OF TS_PSPNR .
  TYPES:
    TT_PSPNR TYPE HASHED TABLE OF TS_PSPNR
                        WITH UNIQUE KEY PSPNR .
  TYPES:
    BEGIN OF TS_PARTNER_NAME,
      PARTNER    TYPE BUT000-PARTNER,
      PARTNER_TX TYPE C LENGTH 160,
    END OF TS_PARTNER_NAME .
  TYPES:
    TT_PARTNER_NAME TYPE HASHED TABLE OF TS_PARTNER_NAME
                         WITH UNIQUE KEY PARTNER .

  TYPES: BEGIN OF TS_KNB1,
           KUNNR TYPE KNB1-KUNNR,
           BUKRS TYPE KNB1-BUKRS,
           BUSAB TYPE KNB1-BUSAB,
         END OF TS_KNB1.
  TYPES TT_KNB1 TYPE HASHED TABLE OF TS_KNB1
                     WITH UNIQUE KEY KUNNR
                                     BUKRS.

  TYPES: BEGIN OF TS_T001S,
           BUKRS TYPE T001S-BUKRS,
           BUSAB TYPE T001S-BUSAB,
           SNAME TYPE T001S-SNAME,
         END OF TS_T001S.
  TYPES TT_T001S TYPE HASHED TABLE OF TS_T001S
                      WITH UNIQUE KEY BUKRS
                                      BUSAB.

  TYPES:
    BEGIN OF TS_CMS_SGM,
      PARTNER      TYPE UKMBP_CMS_SGM-PARTNER,
      CREDIT_SGMNT TYPE UKMBP_CMS_SGM-CREDIT_SGMNT,
      CREDIT_LIMIT TYPE UKMBP_CMS_SGM-CREDIT_LIMIT,
      XBLOCKED     TYPE UKMBP_CMS_SGM-XBLOCKED,
      RISK_CLASS   TYPE UKMBP_CMS-RISK_CLASS,
      ZTERM        TYPE KNVV-ZTERM,
      BUSAB        TYPE KNB1-BUSAB,
      BUSAB_TX     TYPE T001S-SNAME,
    END OF TS_CMS_SGM .
  TYPES:
    TT_CMS_SGM TYPE STANDARD TABLE OF TS_CMS_SGM
                    WITH DEFAULT KEY .
  TYPES:
    BEGIN OF TS_WBS_CRDT,
      KUNNR        TYPE ZSDSFIT036-KUNNR,
      PSPID        TYPE PROJ-PSPID,                         "+420000174
      PSPHI        TYPE ZSDSFIT036-PSPHI,
      CREDIT_LIMIT TYPE ZSDSFIT036-CREDIT_LIMIT,
      ZTERM        TYPE ZSDSFIT036-ZTERM,
      STARTDATE    TYPE ZSDSFIT036-STARTDATE,
      ENDDATE      TYPE ZSDSFIT036-ENDDATE,
      STATUS       TYPE ZSDSDE_WBS_CRDT_STATUS,             "+420000174
      SEQ          TYPE ZSDSFIT036-SEQ,
      PSPHI_TX     TYPE PROJ-POST1,
      BUSAB        TYPE KNB1-BUSAB,
      BUSAB_TX     TYPE T001S-SNAME,
    END OF TS_WBS_CRDT .
  TYPES:
    TT_WBS_CRDT TYPE STANDARD TABLE OF TS_WBS_CRDT
                     WITH DEFAULT KEY .

  TYPES: BEGIN OF TS_CRDT_MGMT.
           INCLUDE TYPE TS_WBS_CRDT.
  TYPES:   CREDIT_SGMNT TYPE UKMBP_CMS_SGM-CREDIT_SGMNT,
           XBLOCKED     TYPE UKMBP_CMS_SGM-XBLOCKED,
           RISK_CLASS   TYPE UKMBP_CMS-RISK_CLASS,
         END OF TS_CRDT_MGMT.
  TYPES TT_CRDT_MGMT TYPE STANDARD TABLE OF TS_CRDT_MGMT
                          WITH EMPTY KEY.

  TYPES: BEGIN OF TS_PARTNER_CUST,
           PARTNER TYPE BUT000-PARTNER,
           ZTERM   TYPE TS_WBS_CRDT-ZTERM,
         END OF TS_PARTNER_CUST .
  TYPES:
    TT_PARTNER_CUST TYPE HASHED TABLE OF TS_PARTNER_CUST
                         WITH UNIQUE KEY PARTNER.

  TYPES:BEGIN OF TS_PARTNER_WBS,
          PARTNER TYPE BUT000-PARTNER,
          PSPHI   TYPE PRPS-PSPHI,
          ZTERM   TYPE TS_WBS_CRDT-ZTERM,
        END OF TS_PARTNER_WBS .
  TYPES:
    TT_PARTNER_WBS TYPE HASHED TABLE OF TS_PARTNER_WBS
                        WITH UNIQUE KEY PARTNER
                                        PSPHI.

  TYPES: BEGIN OF TS_BILL_CYCLE,
           KUNNR TYPE ZSDSFIC024-KUNNR,
           ZDAYS TYPE ZSDSFIC024-ZDAYS,
         END OF TS_BILL_CYCLE.
  TYPES TT_BILL_CYCLE TYPE HASHED TABLE OF TS_BILL_CYCLE
                           WITH UNIQUE KEY KUNNR.

  TYPES:
    BEGIN OF TS_RISK_CLST,
      RISK_CLASS    TYPE UKM_RISK_CL0T-RISK_CLASS,
      RISK_CLASS_TX TYPE UKM_RISK_CL0T-RISK_CLASS_TXT,
    END OF TS_RISK_CLST .
  TYPES:
    TT_RISK_CLST TYPE HASHED TABLE OF TS_RISK_CLST
                            WITH UNIQUE KEY RISK_CLASS .
  TYPES:
    BEGIN OF TS_VBKD,
      VBELN TYPE VBKD-VBELN,
      POSNR TYPE VBKD-POSNR,
      ZTERM TYPE VBKD-ZTERM,
    END OF TS_VBKD .
  TYPES:
    TT_VBKD TYPE SORTED TABLE OF TS_VBKD
                 WITH UNIQUE KEY VBELN .

  TYPES:
    BEGIN OF TS_VKORG,
      VKORG TYPE VBRK-VKORG,
    END OF TS_VKORG .
  TYPES:
    TT_VKORG TYPE HASHED TABLE OF TS_VKORG
                  WITH UNIQUE KEY VKORG.
  TYPES:
    BEGIN OF TS_TVKOT,
      VKORG TYPE TVKOT-VKORG,
      VTEXT TYPE TVKOT-VTEXT,
    END OF TS_TVKOT .
  TYPES:
    TT_TVKOT  TYPE HASHED TABLE OF TS_TVKOT
                   WITH UNIQUE KEY VKORG .

  TYPES:
    BEGIN OF TS_VTWEG,
      VTWEG TYPE VBRK-VTWEG,
    END OF TS_VTWEG .
  TYPES:
    TT_VTWEG TYPE HASHED TABLE OF TS_VTWEG
                  WITH UNIQUE KEY VTWEG .

  TYPES:
    BEGIN OF TS_TVTWT,
      VTWEG TYPE TVTWT-VTWEG,
      VTEXT TYPE TVTWT-VTEXT,
    END OF TS_TVTWT .
  TYPES:
    TT_TVTWT TYPE HASHED TABLE OF TS_TVTWT
                  WITH UNIQUE KEY VTWEG .

  TYPES:
    BEGIN OF TS_SPART,
      SPART TYPE TSPAT-SPART,
    END OF TS_SPART .
  TYPES:
    TT_SPART TYPE HASHED TABLE OF TS_SPART
                  WITH UNIQUE KEY SPART .

  TYPES:
    BEGIN OF TS_TSPAT,
      SPART TYPE TSPAT-SPART,
      VTEXT TYPE TSPAT-VTEXT,
    END OF TS_TSPAT .
  TYPES:
    TT_TSPAT TYPE HASHED TABLE OF TS_TSPAT
                  WITH UNIQUE KEY SPART .

  TYPES:
    BEGIN OF TS_VKGRP,
      VKGRP TYPE TVGRT-VKGRP,
    END OF TS_VKGRP .
  TYPES:
    TT_VKGRP TYPE HASHED TABLE OF TS_VKGRP
                  WITH UNIQUE KEY VKGRP .
  TYPES:
    BEGIN OF TS_TVGRT,
      VKGRP TYPE TVGRT-VKGRP,
      BEZEI TYPE TVGRT-BEZEI,
    END OF TS_TVGRT .
  TYPES:
    TT_TVGRT TYPE HASHED TABLE OF TS_TVGRT
                  WITH UNIQUE KEY VKGRP .

  TYPES:
    BEGIN OF TS_VKBUR,
      VKBUR TYPE TVKBT-VKBUR,
    END OF TS_VKBUR .
  TYPES:
    TT_VKBUR TYPE HASHED TABLE OF TS_VKBUR
                  WITH UNIQUE KEY VKBUR .

  TYPES:
    BEGIN OF TS_TVKBT,
      VKBUR TYPE TVKBT-VKBUR,
      BEZEI TYPE TVKBT-BEZEI,
    END OF TS_TVKBT .
  TYPES:
    TT_TVKBT TYPE SORTED TABLE OF TS_TVKBT
                  WITH UNIQUE KEY VKBUR.

  TYPES: BEGIN OF TY_VBELN,
           VBELN TYPE VBPA-VBELN,
         END OF TY_VBELN.
  TYPES TT_VBELN TYPE HASHED TABLE OF TY_VBELN
                     WITH UNIQUE KEY VBELN.

  TYPES: BEGIN OF TY_VBPA,
           VBELN TYPE VBPA-VBELN,
           POSNR TYPE VBPA-POSNR,
           PARVW TYPE VBPA-PARVW,
           PERNR TYPE VBPA-PERNR,
           VORNA TYPE PA0002-VORNA,
         END OF TY_VBPA.
  TYPES TT_VBPA TYPE SORTED TABLE OF TY_VBPA
                     WITH UNIQUE KEY VBELN
                                     POSNR
                                     PARVW.
  TYPES:
    BEGIN OF TS_PERNR,
      PERNR TYPE PA0002-PERNR,
    END OF TS_PERNR .
  TYPES:
    TT_PERNR TYPE HASHED TABLE OF TS_PERNR
                              WITH UNIQUE KEY PERNR .
  TYPES:
    BEGIN OF TS_PA0002,
      PERNR TYPE PA0002-PERNR,
      VORNA TYPE PA0002-VORNA,
    END OF TS_PA0002 .
  TYPES:
    TT_PA0002 TYPE HASHED TABLE OF TS_PA0002
                   WITH UNIQUE KEY PERNR .

  TYPES:
    BEGIN OF TS_DOC,
      KUNNR       TYPE BSID_VIEW-KUNNR,
      PSPID       TYPE ZSDSFIS103-PSPID,
      DOC_TYPE    TYPE ZSDSFIS103-DOC_TYPE,
      DOC_NO      TYPE ZSDSFIS103-DOC_NO,
      DOC_DATE    TYPE ZSDSFIS103-DOC_DATE,
      REF_DOC     TYPE ZSDSFIS103-REF_DOC,
      ZTERM       TYPE ZSDSFIS103-ZTERM,
      NET_DUEDATE TYPE ZSDSFIS103-NET_DUEDATE,
      AMOUNT      TYPE ZSDSFIS103-AMOUNT,
      ZFBDT       TYPE BSID_VIEW-ZFBDT,
      ZBD1T       TYPE BSID_VIEW-ZBD1T,
      ZBD2T       TYPE BSID_VIEW-ZBD2T,
      ZBD3T       TYPE BSID_VIEW-ZBD3T,
      SHKZG       TYPE BSID_VIEW-SHKZG,
      REBZG       TYPE BSID_VIEW-REBZG,
      REBZJ       TYPE BSID_VIEW-REBZJ,                     "+420000174
      KOART       TYPE BSEG-KOART,
      WAERS       TYPE BSID_VIEW-WAERS,
      BLART       TYPE BSID_VIEW-BLART,
      GJAHR       TYPE BSID_VIEW-GJAHR,
      BUKRS       TYPE BSID_VIEW-BUKRS,
      VKORG       TYPE VBAK-VKORG,
      VTWEG       TYPE VBAK-VTWEG,
      SPART       TYPE VBAK-SPART,
      VKGRP       TYPE VBAK-VKGRP,
      VKBUR       TYPE VBAK-VKBUR,
      SALE_PERNR  TYPE VBPA-PERNR,
    END OF TS_DOC .
  TYPES:
    TT_DOC TYPE STANDARD TABLE OF TS_DOC
                WITH DEFAULT KEY.

  TYPES TT_RESULT TYPE ZSDSFIS102_TT .
  TYPES:
    TT_CREDIT_LIMIT_RANGE TYPE RANGE OF UKM_CREDIT_LIMIT,
    TT_BUSAB_RANGE        TYPE RANGE OF KNB1-BUSAB,
    TT_WBSSTAT_RANGE      TYPE RANGE OF ZSDSFIS101-STATUS.

ENDINTERFACE.
