*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZSDSV_ZSDSFIC027................................*
FORM GET_DATA_ZSDSV_ZSDSFIC027.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZSDSFIC027 WHERE
(VIM_WHERETAB) .
    CLEAR ZSDSV_ZSDSFIC027 .
ZSDSV_ZSDSFIC027-MANDT =
ZSDSFIC027-MANDT .
ZSDSV_ZSDSFIC027-PIC_PERNR =
ZSDSFIC027-PIC_PERNR .
ZSDSV_ZSDSFIC027-SEQNO =
ZSDSFIC027-SEQNO .
ZSDSV_ZSDSFIC027-FR_KUNNR =
ZSDSFIC027-FR_KUNNR .
ZSDSV_ZSDSFIC027-TO_KUNNR =
ZSDSFIC027-TO_KUNNR .
ZSDSV_ZSDSFIC027-BUKRS =
ZSDSFIC027-BUKRS .
ZSDSV_ZSDSFIC027-VKORG =
ZSDSFIC027-VKORG .
ZSDSV_ZSDSFIC027-FR_VTWEG =
ZSDSFIC027-FR_VTWEG .
ZSDSV_ZSDSFIC027-TO_VTWEG =
ZSDSFIC027-TO_VTWEG .
ZSDSV_ZSDSFIC027-FR_SPART =
ZSDSFIC027-FR_SPART .
ZSDSV_ZSDSFIC027-TO_SPART =
ZSDSFIC027-TO_SPART .
ZSDSV_ZSDSFIC027-VKBUR =
ZSDSFIC027-VKBUR .
ZSDSV_ZSDSFIC027-FR_VKGRP =
ZSDSFIC027-FR_VKGRP .
ZSDSV_ZSDSFIC027-TO_VKGRP =
ZSDSFIC027-TO_VKGRP .
ZSDSV_ZSDSFIC027-FR_BUSAB =
ZSDSFIC027-FR_BUSAB .
ZSDSV_ZSDSFIC027-TO_BUSAB =
ZSDSFIC027-TO_BUSAB .
ZSDSV_ZSDSFIC027-ZCRT_DATE =
ZSDSFIC027-ZCRT_DATE .
ZSDSV_ZSDSFIC027-ZCRT_TIME =
ZSDSFIC027-ZCRT_TIME .
ZSDSV_ZSDSFIC027-ZCRT_USER =
ZSDSFIC027-ZCRT_USER .
ZSDSV_ZSDSFIC027-ZUPD_DATE =
ZSDSFIC027-ZUPD_DATE .
ZSDSV_ZSDSFIC027-ZUPD_TIME =
ZSDSFIC027-ZUPD_TIME .
ZSDSV_ZSDSFIC027-ZUPD_USER =
ZSDSFIC027-ZUPD_USER .
    SELECT * FROM PA0002 WHERE
PERNR = ZSDSFIC027-PIC_PERNR .
ZSDSV_ZSDSFIC027-VORNA =
PA0002-VORNA .
ZSDSV_ZSDSFIC027-NACHN =
PA0002-NACHN .
      EXIT.
    ENDSELECT.
<VIM_TOTAL_STRUC> = ZSDSV_ZSDSFIC027.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZSDSV_ZSDSFIC027 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZSDSV_ZSDSFIC027.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZSDSV_ZSDSFIC027-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZSDSFIC027 WHERE
  PIC_PERNR = ZSDSV_ZSDSFIC027-PIC_PERNR AND
  SEQNO = ZSDSV_ZSDSFIC027-SEQNO .
    IF SY-SUBRC = 0.
    DELETE ZSDSFIC027 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZSDSFIC027 WHERE
  PIC_PERNR = ZSDSV_ZSDSFIC027-PIC_PERNR AND
  SEQNO = ZSDSV_ZSDSFIC027-SEQNO .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZSDSFIC027.
    ENDIF.
ZSDSFIC027-MANDT =
ZSDSV_ZSDSFIC027-MANDT .
ZSDSFIC027-PIC_PERNR =
ZSDSV_ZSDSFIC027-PIC_PERNR .
ZSDSFIC027-SEQNO =
ZSDSV_ZSDSFIC027-SEQNO .
ZSDSFIC027-FR_KUNNR =
ZSDSV_ZSDSFIC027-FR_KUNNR .
ZSDSFIC027-TO_KUNNR =
ZSDSV_ZSDSFIC027-TO_KUNNR .
ZSDSFIC027-BUKRS =
ZSDSV_ZSDSFIC027-BUKRS .
ZSDSFIC027-VKORG =
ZSDSV_ZSDSFIC027-VKORG .
ZSDSFIC027-FR_VTWEG =
ZSDSV_ZSDSFIC027-FR_VTWEG .
ZSDSFIC027-TO_VTWEG =
ZSDSV_ZSDSFIC027-TO_VTWEG .
ZSDSFIC027-FR_SPART =
ZSDSV_ZSDSFIC027-FR_SPART .
ZSDSFIC027-TO_SPART =
ZSDSV_ZSDSFIC027-TO_SPART .
ZSDSFIC027-VKBUR =
ZSDSV_ZSDSFIC027-VKBUR .
ZSDSFIC027-FR_VKGRP =
ZSDSV_ZSDSFIC027-FR_VKGRP .
ZSDSFIC027-TO_VKGRP =
ZSDSV_ZSDSFIC027-TO_VKGRP .
ZSDSFIC027-FR_BUSAB =
ZSDSV_ZSDSFIC027-FR_BUSAB .
ZSDSFIC027-TO_BUSAB =
ZSDSV_ZSDSFIC027-TO_BUSAB .
ZSDSFIC027-ZCRT_DATE =
ZSDSV_ZSDSFIC027-ZCRT_DATE .
ZSDSFIC027-ZCRT_TIME =
ZSDSV_ZSDSFIC027-ZCRT_TIME .
ZSDSFIC027-ZCRT_USER =
ZSDSV_ZSDSFIC027-ZCRT_USER .
ZSDSFIC027-ZUPD_DATE =
ZSDSV_ZSDSFIC027-ZUPD_DATE .
ZSDSFIC027-ZUPD_TIME =
ZSDSV_ZSDSFIC027-ZUPD_TIME .
ZSDSFIC027-ZUPD_USER =
ZSDSV_ZSDSFIC027-ZUPD_USER .
    IF SY-SUBRC = 0.
    UPDATE ZSDSFIC027 ##WARN_OK.
    ELSE.
    INSERT ZSDSFIC027 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZSDSV_ZSDSFIC027-UPD_FLAG,
STATUS_ZSDSV_ZSDSFIC027-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZSDSV_ZSDSFIC027.
  SELECT SINGLE * FROM ZSDSFIC027 WHERE
PIC_PERNR = ZSDSV_ZSDSFIC027-PIC_PERNR AND
SEQNO = ZSDSV_ZSDSFIC027-SEQNO .
ZSDSV_ZSDSFIC027-MANDT =
ZSDSFIC027-MANDT .
ZSDSV_ZSDSFIC027-PIC_PERNR =
ZSDSFIC027-PIC_PERNR .
ZSDSV_ZSDSFIC027-SEQNO =
ZSDSFIC027-SEQNO .
ZSDSV_ZSDSFIC027-FR_KUNNR =
ZSDSFIC027-FR_KUNNR .
ZSDSV_ZSDSFIC027-TO_KUNNR =
ZSDSFIC027-TO_KUNNR .
ZSDSV_ZSDSFIC027-BUKRS =
ZSDSFIC027-BUKRS .
ZSDSV_ZSDSFIC027-VKORG =
ZSDSFIC027-VKORG .
ZSDSV_ZSDSFIC027-FR_VTWEG =
ZSDSFIC027-FR_VTWEG .
ZSDSV_ZSDSFIC027-TO_VTWEG =
ZSDSFIC027-TO_VTWEG .
ZSDSV_ZSDSFIC027-FR_SPART =
ZSDSFIC027-FR_SPART .
ZSDSV_ZSDSFIC027-TO_SPART =
ZSDSFIC027-TO_SPART .
ZSDSV_ZSDSFIC027-VKBUR =
ZSDSFIC027-VKBUR .
ZSDSV_ZSDSFIC027-FR_VKGRP =
ZSDSFIC027-FR_VKGRP .
ZSDSV_ZSDSFIC027-TO_VKGRP =
ZSDSFIC027-TO_VKGRP .
ZSDSV_ZSDSFIC027-FR_BUSAB =
ZSDSFIC027-FR_BUSAB .
ZSDSV_ZSDSFIC027-TO_BUSAB =
ZSDSFIC027-TO_BUSAB .
ZSDSV_ZSDSFIC027-ZCRT_DATE =
ZSDSFIC027-ZCRT_DATE .
ZSDSV_ZSDSFIC027-ZCRT_TIME =
ZSDSFIC027-ZCRT_TIME .
ZSDSV_ZSDSFIC027-ZCRT_USER =
ZSDSFIC027-ZCRT_USER .
ZSDSV_ZSDSFIC027-ZUPD_DATE =
ZSDSFIC027-ZUPD_DATE .
ZSDSV_ZSDSFIC027-ZUPD_TIME =
ZSDSFIC027-ZUPD_TIME .
ZSDSV_ZSDSFIC027-ZUPD_USER =
ZSDSFIC027-ZUPD_USER .
    SELECT * FROM PA0002 WHERE
PERNR = ZSDSFIC027-PIC_PERNR .
ZSDSV_ZSDSFIC027-VORNA =
PA0002-VORNA .
ZSDSV_ZSDSFIC027-NACHN =
PA0002-NACHN .
      EXIT.
    ENDSELECT.
    IF SY-SUBRC NE 0.
      CLEAR SY-SUBRC.
      CLEAR ZSDSV_ZSDSFIC027-VORNA .
      CLEAR ZSDSV_ZSDSFIC027-NACHN .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZSDSV_ZSDSFIC027 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZSDSV_ZSDSFIC027-PIC_PERNR TO
ZSDSFIC027-PIC_PERNR .
MOVE ZSDSV_ZSDSFIC027-SEQNO TO
ZSDSFIC027-SEQNO .
MOVE ZSDSV_ZSDSFIC027-MANDT TO
ZSDSFIC027-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZSDSFIC027'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZSDSFIC027 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZSDSFIC027'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZSDSV_ZSDSFIC027 USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZSDSFIC027-MANDT =
ZSDSV_ZSDSFIC027-MANDT .
ZSDSFIC027-PIC_PERNR =
ZSDSV_ZSDSFIC027-PIC_PERNR .
ZSDSFIC027-SEQNO =
ZSDSV_ZSDSFIC027-SEQNO .
ZSDSFIC027-FR_KUNNR =
ZSDSV_ZSDSFIC027-FR_KUNNR .
ZSDSFIC027-TO_KUNNR =
ZSDSV_ZSDSFIC027-TO_KUNNR .
ZSDSFIC027-BUKRS =
ZSDSV_ZSDSFIC027-BUKRS .
ZSDSFIC027-VKORG =
ZSDSV_ZSDSFIC027-VKORG .
ZSDSFIC027-FR_VTWEG =
ZSDSV_ZSDSFIC027-FR_VTWEG .
ZSDSFIC027-TO_VTWEG =
ZSDSV_ZSDSFIC027-TO_VTWEG .
ZSDSFIC027-FR_SPART =
ZSDSV_ZSDSFIC027-FR_SPART .
ZSDSFIC027-TO_SPART =
ZSDSV_ZSDSFIC027-TO_SPART .
ZSDSFIC027-VKBUR =
ZSDSV_ZSDSFIC027-VKBUR .
ZSDSFIC027-FR_VKGRP =
ZSDSV_ZSDSFIC027-FR_VKGRP .
ZSDSFIC027-TO_VKGRP =
ZSDSV_ZSDSFIC027-TO_VKGRP .
ZSDSFIC027-FR_BUSAB =
ZSDSV_ZSDSFIC027-FR_BUSAB .
ZSDSFIC027-TO_BUSAB =
ZSDSV_ZSDSFIC027-TO_BUSAB .
ZSDSFIC027-ZCRT_DATE =
ZSDSV_ZSDSFIC027-ZCRT_DATE .
ZSDSFIC027-ZCRT_TIME =
ZSDSV_ZSDSFIC027-ZCRT_TIME .
ZSDSFIC027-ZCRT_USER =
ZSDSV_ZSDSFIC027-ZCRT_USER .
ZSDSFIC027-ZUPD_DATE =
ZSDSV_ZSDSFIC027-ZUPD_DATE .
ZSDSFIC027-ZUPD_TIME =
ZSDSV_ZSDSFIC027-ZUPD_TIME .
ZSDSFIC027-ZUPD_USER =
ZSDSV_ZSDSFIC027-ZUPD_USER .
    SELECT * FROM PA0002 WHERE
PERNR = ZSDSFIC027-PIC_PERNR .
ZSDSV_ZSDSFIC027-VORNA =
PA0002-VORNA .
ZSDSV_ZSDSFIC027-NACHN =
PA0002-NACHN .
      EXIT.
    ENDSELECT.
    IF SY-SUBRC NE 0.
      CLEAR SY-SUBRC.
      CLEAR ZSDSV_ZSDSFIC027-VORNA .
      CLEAR ZSDSV_ZSDSFIC027-NACHN .
    ENDIF.
ENDFORM.
