FUNCTION Z_SDSFI_INTERFACE_00001030.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(I_BKDF) LIKE  BKDF STRUCTURE  BKDF
*"     VALUE(I_UF05A) LIKE  UF05A STRUCTURE  UF05A
*"     VALUE(I_XVBUP) LIKE  OFIWA-XVBUP DEFAULT 'X'
*"  TABLES
*"      T_AUSZ1 STRUCTURE  AUSZ1 OPTIONAL
*"      T_AUSZ2 STRUCTURE  AUSZ2 OPTIONAL
*"      T_AUSZ3 STRUCTURE  AUSZ_CLR OPTIONAL
*"      T_BKP1 STRUCTURE  BKP1
*"      T_BKPF STRUCTURE  BKPF
*"      T_BSEC STRUCTURE  BSEC
*"      T_BSED STRUCTURE  BSED
*"      T_BSEG STRUCTURE  BSEG
*"      T_BSET STRUCTURE  BSET
*"      T_BSEU STRUCTURE  BSEU
*"----------------------------------------------------------------------
  DATA : LV_CHECK_SDS LIKE ABAP_TRUE.
  PERFORM CHECK_SDS CHANGING LV_CHECK_SDS.
  CHECK LV_CHECK_SDS EQ ABAP_TRUE AND SY-TCODE = 'FB08'.

  READ TABLE T_BKPF INTO DATA(LS_BKPF) INDEX 1.
  IF SY-SUBRC = 0 AND LS_BKPF-BLART = 'SX'.
    SELECT SINGLE *
      FROM ZSDSFIT060
      INTO @DATA(LS_FIT060)
      WHERE JV_DOCNO = @LS_BKPF-XBLNR.
    IF SY-SUBRC = 0.
      LS_FIT060-ZDEL_FLG = ABAP_TRUE.

      "Update table
      MODIFY ZSDSFIT060 FROM LS_FIT060.

      "update to K2
      DATA(LCL_JV_PROCESS) = NEW ZCL_SDSFI_JV_CHECK( ).
      LCL_JV_PROCESS->GS_FIT060 = LS_FIT060.
      LCL_JV_PROCESS->GS_FIT060-POSTED = 'A'.

      "Start Process
      LCL_JV_PROCESS->START_PROCESS( ).
    ENDIF.
  ENDIF.

ENDFUNCTION.
