*&---------------------------------------------------------------------*
*& Include          ZSDSFIR0180_TOPZ
*&---------------------------------------------------------------------*
TYPE-POOLS: ABAP,
            SLIS,
            ICON.

*&--------------------------------------------------------------------*
*& TABLES
*&--------------------------------------------------------------------*
TABLES : BKPF,BSEG,VBRK.

*&--------------------------------------------------------------------*
*& TYPES
*&--------------------------------------------------------------------*
TYPES : BEGIN OF GTY_MESSG.
          INCLUDE STRUCTURE ZSDSFIS021.
TYPES : END OF GTY_MESSG.

TYPES : BEGIN OF GTY_ADDFIELDS,
          DOCUMENT_NO      TYPE ZSDSFIT014-DOCUMENT_NO,
          RD_DOC_TYPE_DESC TYPE ZSDSFIC005-RD_DOC_TYP_DS_TH,
        END OF GTY_ADDFIELDS.

TYPES : BEGIN OF GTY_DOC_PARTNER.
          INCLUDE STRUCTURE ZSDSFIT018.
          INCLUDE TYPE GTY_ADDFIELDS.
TYPES:    RD_PARTNER_DESC TYPE ZSDSFIC018-RD_PARTNER_DESC.
TYPES : END OF GTY_DOC_PARTNER.

TYPES : BEGIN OF GTY_DOC_H_VAT.
          INCLUDE STRUCTURE ZSDSFIT017.
          INCLUDE TYPE GTY_ADDFIELDS.
TYPES:    VAT_RATE_TXT TYPE C LENGTH 21,
          KUNNR        TYPE ZSDSFIT014-KUNNR,
          KUNNR_NAME   TYPE ZSDSFIT014-KUNNR_NAME.
TYPES : END OF GTY_DOC_H_VAT.

TYPES : BEGIN OF GTY_DOC_H_REF.
          INCLUDE STRUCTURE ZSDSFIT016.
          INCLUDE TYPE GTY_ADDFIELDS.
TYPES:    KUNNR                TYPE ZSDSFIT014-KUNNR,
          KUNNR_NAME           TYPE ZSDSFIT014-KUNNR_NAME,
          REF_RD_DOC_TYPE_DESC TYPE ZSDSFIC005-RD_DOC_TYP_DS_TH.
TYPES : END OF GTY_DOC_H_REF.

TYPES : BEGIN OF GTY_DOC_ITEM.
          INCLUDE STRUCTURE ZSDSFIT015.
          INCLUDE TYPE GTY_ADDFIELDS.
TYPES:    KUNNR            TYPE ZSDSFIT014-KUNNR,
          KUNNR_NAME       TYPE ZSDSFIT014-KUNNR_NAME,
          LINK_DISC_CHARGE TYPE C LENGTH 10.
TYPES : END OF GTY_DOC_ITEM.

TYPES : BEGIN OF GTY_DOC_DISCHG.
          INCLUDE STRUCTURE ZSDSFIT013.
          INCLUDE TYPE GTY_ADDFIELDS.
TYPES:
          CHARGE_AMT_ALV TYPE ZSDSFIT013-CHARGE_AMT.
TYPES: KUNNR      TYPE ZSDSFIT014-KUNNR,
       KUNNR_NAME TYPE ZSDSFIT014-KUNNR_NAME,
       SAP_CURR   TYPE ZSDSFIT014-SAP_CURR.
TYPES : END OF GTY_DOC_DISCHG.

TYPES : BEGIN OF GTY_HEAD,
          SEL_CB            TYPE CHAR1,
          MAIL_CB           TYPE CHAR1,
          ICON              TYPE ICON-ID,
          MESSG             TYPE STRING,
          E_MAIL            TYPE ZSDSFIC001-E_MAIL,
          ERNAM             TYPE BKPF-USNAM,                          "INS CH11
          CPUDT             TYPE BKPF-CPUDT.                          "INS CH11
          INCLUDE STRUCTURE ZSDSFIT014.
TYPES :

          CANCEL            TYPE C LENGTH 30,
          RD_DOC_TYPE_DESC  TYPE ZSDSFIC005-RD_DOC_TYP_DS_TH,
          SAP_DOC_TYPE_DESC TYPE TEXT40,
          LINK_PARTNER      TYPE C LENGTH 10,
          LINK_REPLACE_DOC  TYPE C LENGTH 3,
*  rd_doc_resn_desc  TYPE ZSDSFIC004-rd_doc_resn_desc,
          LINK_REF_DOC      TYPE C LENGTH 10,
          TAX_CODE          TYPE ZSDSFIT017-TAX_CODE,
          VAT_RATE          TYPE ZSDSFIT017-VAT_RATE,
          GROSS_AMT         TYPE ZSDSFIT017-NET_AMT_BF_VAT,
          RD_VAT_TYPE       TYPE ZSDSFIC014-RD_VAT_TYPE,
          LINK_DISC_CHARGE  TYPE C LENGTH 10,
          LINK_VAT          TYPE C LENGTH 10,
          IT_MESSG          TYPE TABLE OF GTY_MESSG WITH NON-UNIQUE DEFAULT KEY,
          IT_ITEM           TYPE TABLE OF GTY_DOC_ITEM WITH NON-UNIQUE DEFAULT KEY,
          IT_CHARGE         TYPE TABLE OF GTY_DOC_DISCHG WITH NON-UNIQUE DEFAULT KEY,
          IT_PARTNER        TYPE TABLE OF GTY_DOC_PARTNER WITH NON-UNIQUE DEFAULT KEY,
          IT_H_VAT          TYPE TABLE OF GTY_DOC_H_VAT WITH NON-UNIQUE DEFAULT KEY,
          IT_H_REF          TYPE TABLE OF GTY_DOC_H_REF WITH NON-UNIQUE DEFAULT KEY,
          IT_PDF            TYPE ZSDSFIS022_TT,
          WA_AL11           TYPE ZSDSFIS024,
          X_PDF             TYPE FLAG,
          SAPOBJECTID       TYPE SAEOBJID,
          DONE              TYPE FLAG,
          STYL              TYPE LVC_T_STYL.
TYPES : END OF GTY_HEAD.

TYPES : BEGIN OF GTY_EMAIL,
          KUNNR        TYPE ZSDSFIC001-KUNNR,
          RUNNO        TYPE ZSDSFIC001-RUNNO,
          E_MAIL       TYPE ZSDSFIC001-E_MAIL,
          MOBILE_PHONE TYPE ZSDSFIC001-MOBILE_PHONE,
          RD_DOC_TYPE  TYPE ZSDSFIC001-RD_DOC_TYPE,
          SAP_DOC_TYPE TYPE ZSDSFIC001-SAP_DOC_TYPE,
          BUKRS        TYPE ZSDSFIC001-BUKRS,
          VKORG        TYPE ZSDSFIC001-VKORG.
TYPES : END OF GTY_EMAIL.

TYPES: BEGIN OF GTY_BILL,
         BUKRS               TYPE VBRK-BUKRS,
         GJAHR               TYPE VBRK-GJAHR,
         VBELN               TYPE VBRK-VBELN,
         FKDAT               TYPE VBRK-FKDAT,
         KUNNR               TYPE VBRK-KUNRG,
         BUPLA               TYPE VBRK-BUPLA,
         FKART               TYPE VBRK-FKART,
         ERNAM               TYPE VBRK-ERNAM,
         ERDAT               TYPE VBRK-ERDAT,
         ERZET               TYPE VBRK-ERZET,
         FKSTO               TYPE VBRK-FKSTO,
         POSNR               TYPE VBRP-POSNR,
         MWSK1               TYPE VBRP-MWSKZ,
         TAX_CODE            TYPE ZSDSFIC011-TAX_CODE,
         RD_DOC_TYPE         TYPE ZSDSFIC005-RD_DOC_TYPE,
         RD_DOC_TYPE_DESC_TH TYPE ZSDSFIC005-RD_DOC_TYP_DS_TH,
         RD_DOC_TYPE_DESC_EN TYPE ZSDSFIC005-RD_DOC_TYP_DS_EN,
         RD_DOC_TYPE_GRP     TYPE ZSDSFIC005-RD_DOC_TYPE_GRP,
         STATUS              TYPE ZSDSFIT014-STATUS,
         SAP_DOC_NO          TYPE ZSDSFIT014-SAP_DOC_NO,
         SAP_DOC_TYPE        TYPE ZSDSFIT014-SAP_DOC_TYPE,
         DOCUMENT_NO         TYPE ZSDSFIT014-DOCUMENT_NO,
         VKORG               TYPE VBRK-VKORG,
         VTWEG               TYPE VBRK-VTWEG,
         RFBSK               TYPE VBRK-RFBSK,
         KOART               TYPE BSEG-KOART, "INS by CH14
         AUGBL               TYPE BSEG-AUGBL, "INS by CH14
         AUGDT               TYPE BSEG-AUGDT. "INS by CH14
TYPES : END OF GTY_BILL.

TYPES: BEGIN OF GTY_BILL2,
         BUKRS               TYPE VBRK-BUKRS,
         GJAHR               TYPE VBRK-GJAHR,
         VBELN               TYPE VBRK-VBELN,
         BUPLA               TYPE VBRK-BUPLA,
         RD_DOC_TYPE         TYPE ZSDSFIC005-RD_DOC_TYPE,
         FKDAT               TYPE VBRK-FKDAT,
         KUNNR               TYPE VBRK-KUNRG,
         FKART               TYPE VBRK-FKART,
         ERNAM               TYPE VBRK-ERNAM,
         ERDAT               TYPE VBRK-ERDAT,
         ERZET               TYPE VBRK-ERZET,
         FKSTO               TYPE VBRK-FKSTO,
         POSNR               TYPE VBRP-POSNR,
         MWSK1               TYPE VBRP-MWSKZ,
         TAX_CODE            TYPE ZSDSFIC011-TAX_CODE,
         RD_DOC_TYPE_DESC_TH TYPE ZSDSFIC005-RD_DOC_TYP_DS_TH,
         RD_DOC_TYPE_DESC_EN TYPE ZSDSFIC005-RD_DOC_TYP_DS_EN,
         RD_DOC_TYPE_GRP     TYPE ZSDSFIC005-RD_DOC_TYPE_GRP,
         STATUS              TYPE ZSDSFIT014-STATUS,
         SAP_DOC_NO          TYPE ZSDSFIT014-SAP_DOC_NO,
         SAP_DOC_TYPE        TYPE ZSDSFIT014-SAP_DOC_TYPE,
         DOCUMENT_NO         TYPE ZSDSFIT014-DOCUMENT_NO,
         VKORG               TYPE VBRK-VKORG,
         VTWEG               TYPE VBRK-VTWEG,
         RFBSK               TYPE VBRK-RFBSK.
TYPES : END OF GTY_BILL2.

TYPES: BEGIN OF GTY_BSEG,
         BUKRS TYPE BSEG-BUKRS,
         BELNR TYPE BSEG-BELNR,
         GJAHR TYPE BSEG-GJAHR,
         BUZEI TYPE BSEG-BUZEI,
         KOART TYPE BSEG-KOART,
         AUGBL TYPE BSEG-AUGBL,
         AUGDT TYPE BSEG-AUGDT,
       END OF GTY_BSEG.

TYPES: BEGIN OF GTY_DOC_HEADER.
         INCLUDE STRUCTURE ZSDSFIT014.
TYPES : END OF GTY_DOC_HEADER.

TYPES: BEGIN OF GTY_MAP_DOC_SD,
         VKORG       TYPE ZSDSFIC011-VKORG,
         FKART       TYPE ZSDSFIC011-FKART,
         TAX_CODE    TYPE ZSDSFIC011-TAX_CODE,
         RD_DOC_TYPE TYPE ZSDSFIC011-RD_DOC_TYPE,
         RD_FLAG     TYPE ZSDSFIC011-RD_FLAG,
         EMAIL_FLAG  TYPE ZSDSFIC011-EMAIL_FLAG.
TYPES : END OF GTY_MAP_DOC_SD.

TYPES: BEGIN OF GTY_MAP_DOC_FI,
         BUKRS       TYPE ZSDSFIC009-BUKRS,
         BLART       TYPE ZSDSFIC009-BLART,
         TAX_CODE    TYPE ZSDSFIC009-TAX_CODE,
         RD_DOC_TYPE TYPE ZSDSFIC009-RD_DOC_TYPE,
         RD_FLAG     TYPE ZSDSFIC009-RD_FLAG,
         EMAIL_FLAG  TYPE ZSDSFIC009-EMAIL_FLAG.
TYPES : END OF GTY_MAP_DOC_FI.

TYPES: BEGIN OF GTY_MAP_DOC_RESN,
         SAP_RESN    TYPE ZSDSFIC010-SAP_RESN,
         RD_DOC_TYPE TYPE ZSDSFIC010-RD_DOC_TYPE,
         RD_DOC_RESN TYPE ZSDSFIC010-RD_DOC_RESN.
TYPES : END OF GTY_MAP_DOC_RESN.


TYPES: BEGIN OF GTY_RD_DOC_TYPE,
         RD_DOC_TYPE         TYPE ZSDSFIC005-RD_DOC_TYPE,
         RD_DOC_TYPE_DESC_TH TYPE ZSDSFIC005-RD_DOC_TYP_DS_TH,
         RD_DOC_TYPE_DESC_EN TYPE ZSDSFIC005-RD_DOC_TYP_DS_EN,
         RD_DOC_TYPE_GRP     TYPE ZSDSFIC005-RD_DOC_TYPE_GRP.
TYPES : END OF GTY_RD_DOC_TYPE.

TYPES: BEGIN OF GTY_RD_DOC_RESN,
         RD_DOC_RESN      TYPE ZSDSFIC004-RD_DOC_RESN,
         RD_DOC_RESN_DESC TYPE ZSDSFIC004-RD_DOC_RESN_DESC.
TYPES : END OF GTY_RD_DOC_RESN.

TYPES: BEGIN OF GTY_RD_PARTNER,
         RD_PARTNER      TYPE ZSDSFIC018-RD_PARTNER,
         RD_PARTNER_DESC TYPE ZSDSFIC018-RD_PARTNER_DESC,
         RD_PARTNER_TYPE TYPE ZSDSFIC018-RD_PARTNER_TYPE.
TYPES : END OF GTY_RD_PARTNER.

TYPES: BEGIN OF GTY_RD_SUB_DIST,
         SUB_DIST_CODE TYPE ZSDSFIC020-SUB_DIST_CODE,
         SUB_DIST_NAME TYPE ZSDSFIC020-SUB_DIST_NAME,
         DIST_CODE     TYPE ZSDSFIC020-DIST_CODE,
         PROVINCE_CODE TYPE ZSDSFIC020-PROVINCE_CODE.
TYPES : END OF GTY_RD_SUB_DIST.

TYPES: BEGIN OF GTY_RD_DISTRICT,
         DIST_CODE     TYPE ZSDSFIC017-DIST_CODE,
         DIST_NAME     TYPE ZSDSFIC017-DIST_NAME,
         PROVINCE_CODE TYPE ZSDSFIC017-PROVINCE_CODE.
TYPES : END OF GTY_RD_DISTRICT.

TYPES: BEGIN OF GTY_RD_PROVINCE,
         PROVINCE_CODE TYPE ZSDSFIC019-PROVINCE_CODE,
         PROVINCE_NAME TYPE ZSDSFIC019-PROVINCE_NAME.
TYPES : END OF GTY_RD_PROVINCE.

TYPES: BEGIN OF GTY_RD_UNIT,
         SAP_UNIT     TYPE ZSDSFIC021-SAP_UNIT,
         RD_UNIT_CODE TYPE ZSDSFIC021-RD_UNIT_CODE,
         RD_UNIT_NAME TYPE ZSDSFIC021-RD_UNIT_NAME.
TYPES : END OF GTY_RD_UNIT.

TYPES: BEGIN OF GTY_RD_DISCHG,
         RD_DISCHG         TYPE ZSDSFIC016-RD_DISCHG,
         RD_DISCHG_DESC_TH TYPE ZSDSFIC016-RD_DISCHG_DESC_T,
         RD_DISCHG_DESC_EN TYPE ZSDSFIC016-RD_DISCHG_DESC_E,
         RD_DISCHG_TYPE    TYPE ZSDSFIC016-RD_DISCHG_TYPE.
TYPES : END OF GTY_RD_DISCHG.

TYPES: BEGIN OF GTY_MAP_CURR,
         WAERK        TYPE ZSDSFIC007-WAERK,
         RD_CURR_CODE TYPE ZSDSFIC007-RD_CURR_CODE.
TYPES : END OF GTY_MAP_CURR.

TYPES: BEGIN OF GTY_MAP_VAT_TYPE,
         TAX_CODE    TYPE ZSDSFIC014-TAX_CODE,
         RD_VAT_TYPE TYPE ZSDSFIC014-RD_VAT_TYPE.
TYPES : END OF GTY_MAP_VAT_TYPE.

TYPES: BEGIN OF GTY_MAP_SCH_CTRY,
         CNTRY_CODE    TYPE ZSDSFIC013-CNTRY_CODE,
         RD_CNTRY_CODE TYPE ZSDSFIC013-RD_CNTRY_CODE.
TYPES : END OF GTY_MAP_SCH_CTRY.

TYPES: BEGIN OF GTY_MAP_DISCHG,
         SD_COND   TYPE ZSDSFIC008-SD_COND,
         SD_SUBT   TYPE ZSDSFIC008-SD_SUBT,
         FI_GL     TYPE ZSDSFIC008-FI_GL,
         RD_DISCHG TYPE ZSDSFIC008-RD_DISCHG.
TYPES : END OF GTY_MAP_DISCHG.

TYPES: BEGIN OF GTY_COMPANY_ADDR,
         BUKRS         TYPE ZSDSFIC003-BUKRS,
         BUPLA         TYPE ZSDSFIC003-BUPLA,
         HOME_NO       TYPE ZSDSFIC003-HOME_NO,
         SUB_DIST_CODE TYPE ZSDSFIC003-SUB_DIST_CODE,
         POSTAL        TYPE ZSDSFIC003-POSTAL,
         COUNTRY       TYPE ZSDSFIC003-COUNTRY,
         SCH_ID        TYPE ZSDSFIC003-SCH_ID.
TYPES : END OF GTY_COMPANY_ADDR.

TYPES: BEGIN OF GTY_TVFKT,
         FKART TYPE TVFKT-FKART,
         VTEXT TYPE TVFKT-VTEXT,
       END OF GTY_TVFKT.

TYPES: BEGIN OF GTY_T003T,
         BLART TYPE T003T-BLART,
         LTEXT TYPE T003T-LTEXT,
       END OF GTY_T003T.

TYPES: BEGIN OF GTY_VBRK,
         GJAHR  TYPE VBRK-GJAHR,
         VBELN  TYPE VBRK-VBELN,
         FKDAT  TYPE VBRK-FKDAT,
         BUKRS  TYPE VBRK-BUKRS,
         FKART  TYPE VBRK-FKART,
         MODULE TYPE C LENGTH 2,
       END OF GTY_VBRK.

TYPES: BEGIN OF GTY_PARAM,
         ID           TYPE ZSDSFIC015-ID,
         NAME         TYPE ZSDSFIC015-NAME,
         PARAM_EXT    TYPE ZSDSFIC015-PARAM_EXT,
         SEQUENCE     TYPE ZSDSFIC015-SEQUENCE,
         ENDDA        TYPE ZSDSFIC015-ENDDA,
         BEGDA        TYPE ZSDSFIC015-BEGDA,
         PARAM_SIGN   TYPE ZSDSFIC015-PARAM_SIGN,
         PARAM_OPTION TYPE ZSDSFIC015-PARAM_OPTION,
         LOW_VALUE    TYPE ZSDSFIC015-LOW_VALUE,
         HIGH_VALUE   TYPE ZSDSFIC015-HIGH_VALUE,
         COMMENTS     TYPE ZSDSFIC015-COMMENTS,
       END OF GTY_PARAM.

TYPES : BEGIN OF GTY_MSG_VX,
          MESSAGE_V1 TYPE BAPIRET2-MESSAGE_V1,
          MESSAGE_V2 TYPE BAPIRET2-MESSAGE_V2,
          MESSAGE_V3 TYPE BAPIRET2-MESSAGE_V3,
          MESSAGE_V4 TYPE BAPIRET2-MESSAGE_V4,
        END OF GTY_MSG_VX.

*>>> BEGIN OF INSERTION: <ETAX001> on 06.09.2020 <<<
*TYPES : BEGIN OF GTY_COLLECTOR,
*          BUKRS       TYPE ZTFIT_COLLECTOR-BUKRS,
*          BELNR       TYPE ZTFIT_COLLECTOR-BELNR,
*          GJAHR       TYPE ZTFIT_COLLECTOR-GJAHR,
*          RUN_ID      TYPE ZTFIT_COLLECTOR-RUN_ID,
*          WORK_DATE   TYPE ZTFIT_COLLECTOR-WORK_DATE,
*          PERNR       TYPE ZTFIT_COLLECTOR-PERNR,
*          ACTION_TYPE TYPE ZTFIT_COLLECTOR-ACTION_TYPE,
*          STATUS      TYPE ZTFIT_COLLECTOR-STATUS,
*          RECEIPT_NO  TYPE ZTFIT_COLLECTOR-RECEIPT_NO,
*          DELETE_FLAG TYPE ZTFIT_COLLECTOR-DELETE_FLAG,       "INS CH02
*        END OF GTY_COLLECTOR.

TYPES: BEGIN OF GTY_ONE_SD,
         VBELN      TYPE VBPA-VBELN,
         KUNNR      TYPE VBPA-KUNNR,
         ADRNR      TYPE VBPA-ADRNR,
         EMAIL      TYPE ADR6-SMTP_ADDR,
         TEL_NUMBER TYPE ADR2-TEL_NUMBER,
       END OF GTY_ONE_SD.
*>>> END OF INSERTION: <ETAX001> on 06.09.2020 <<

TYPES: GTTY_HEAD         TYPE TABLE OF GTY_HEAD,
       GTTY_BILL         TYPE TABLE OF GTY_BILL,
       GTTY_BILL2        TYPE TABLE OF GTY_BILL2, "INS: <ETAX001>
       GTTY_MESSG        TYPE TABLE OF GTY_MESSG WITH NON-UNIQUE DEFAULT KEY,
       GTTY_DOC_HEADER   TYPE SORTED TABLE OF GTY_DOC_HEADER WITH NON-UNIQUE KEY BUKRS SAP_DOC_NO GJAHR RD_DOC_TYPE MODULE_ETX,
       GTTY_DOC_ITEM     TYPE TABLE OF GTY_DOC_ITEM WITH NON-UNIQUE DEFAULT KEY,
       GTTY_DOC_PARTNER  TYPE TABLE OF GTY_DOC_PARTNER WITH NON-UNIQUE DEFAULT KEY,
       GTTY_DOC_H_VAT    TYPE TABLE OF GTY_DOC_H_VAT WITH NON-UNIQUE DEFAULT KEY,
       GTTY_DOC_H_REF    TYPE TABLE OF GTY_DOC_H_REF WITH NON-UNIQUE DEFAULT KEY,
       GTTY_DOC_DISCHG   TYPE TABLE OF GTY_DOC_DISCHG WITH NON-UNIQUE DEFAULT KEY,

       GTTY_MAP_DOC_SD   TYPE SORTED TABLE OF GTY_MAP_DOC_SD WITH NON-UNIQUE KEY VKORG FKART TAX_CODE,
       GTTY_MAP_DOC_FI   TYPE SORTED TABLE OF GTY_MAP_DOC_FI WITH NON-UNIQUE KEY BUKRS BLART TAX_CODE,
       GTTY_MAP_DOC_RESN TYPE SORTED TABLE OF GTY_MAP_DOC_RESN WITH UNIQUE KEY SAP_RESN RD_DOC_TYPE,
       GTTY_MAP_CURR     TYPE SORTED TABLE OF GTY_MAP_CURR WITH UNIQUE KEY WAERK,
       GTTY_MAP_VAT_TYPE TYPE SORTED TABLE OF GTY_MAP_VAT_TYPE WITH UNIQUE KEY TAX_CODE,
       GTTY_MAP_SCH_CTRY TYPE SORTED TABLE OF GTY_MAP_SCH_CTRY WITH UNIQUE KEY CNTRY_CODE,
       GTTY_MAP_DISCHG   TYPE SORTED TABLE OF GTY_MAP_DISCHG WITH NON-UNIQUE KEY SD_COND SD_SUBT FI_GL,

       GTTY_RD_DOC_TYPE  TYPE SORTED TABLE OF GTY_RD_DOC_TYPE WITH UNIQUE KEY RD_DOC_TYPE,
       GTTY_RD_DOC_RESN  TYPE SORTED TABLE OF GTY_RD_DOC_RESN WITH UNIQUE KEY RD_DOC_RESN,
       GTTY_RD_PARTNER   TYPE SORTED TABLE OF GTY_RD_PARTNER WITH UNIQUE KEY RD_PARTNER,
       GTTY_RD_SUB_DIST  TYPE SORTED TABLE OF GTY_RD_SUB_DIST WITH UNIQUE KEY SUB_DIST_CODE,
       GTTY_RD_DISTRICT  TYPE SORTED TABLE OF GTY_RD_DISTRICT WITH UNIQUE KEY DIST_CODE,
       GTTY_RD_PROVINCE  TYPE SORTED TABLE OF GTY_RD_PROVINCE WITH UNIQUE KEY PROVINCE_CODE,
       GTTY_RD_UNIT      TYPE SORTED TABLE OF GTY_RD_UNIT WITH UNIQUE KEY SAP_UNIT,
       GTTY_RD_DISCHG    TYPE SORTED TABLE OF GTY_RD_DISCHG WITH UNIQUE KEY RD_DISCHG,
       GTTY_COMPANY_ADDR TYPE SORTED TABLE OF GTY_COMPANY_ADDR WITH NON-UNIQUE KEY BUKRS BUPLA,

       GTTY_TVFKT        TYPE SORTED TABLE OF GTY_TVFKT WITH UNIQUE KEY FKART,
       GTTY_T003T        TYPE SORTED TABLE OF GTY_T003T WITH UNIQUE KEY BLART,
       GTTY_VBRK         TYPE TABLE OF GTY_VBRK,
       GTTY_PARAM        TYPE TABLE OF GTY_PARAM,
       GTTY_BSEG         TYPE TABLE OF GTY_BSEG,
*>>> BEGIN OF INSERTION: <ETAX001> on 06.09.2020 <<<
*       GTTY_COLLECTOR    TYPE TABLE OF GTY_COLLECTOR,
       GTTY_ONE_SD       TYPE TABLE OF GTY_ONE_SD.
*>>> END OF INSERTION: <ETAX001> on 06.09.2020 <<<
*&--------------------------------------------------------------------*
*& CONSTANTS
*&--------------------------------------------------------------------*
CONSTANTS : GC_ALPHA TYPE CHAR5  VALUE 'ALPHA',
            GC_GJAHR TYPE CHAR5  VALUE 'GJAHR'.

CONSTANTS: GC_YES    TYPE C LENGTH 3 VALUE 'Yes',
           GC_NO     TYPE C LENGTH 3 VALUE 'No',
           GC_DETAIL TYPE C LENGTH 10 VALUE 'Detail'.

*STRUCTURE
CONSTANTS: GC_DOC_HEADER  TYPE TABNAME VALUE 'ZSDSFIT014',
           GC_DOC_ITEM    TYPE TABNAME VALUE 'ZSDSFIT015',
           GC_DOC_DISCHG  TYPE TABNAME VALUE 'ZSDSFIT013',
           GC_DOC_PARTNER TYPE TABNAME VALUE 'ZSDSFIT018',
           GC_DOC_H_VAT   TYPE TABNAME VALUE 'ZSDSFIT017',
           GC_DOC_H_REF   TYPE TABNAME VALUE 'ZSDSFIT016'.

CONSTANTS:
  GC_ERROR   TYPE BAPI_MTYPE  VALUE 'E',
  GC_SUCCESS TYPE BAPI_MTYPE  VALUE 'S'.

*&--------------------------------------------------------------------*
*& INTERNAL TABLE
*&--------------------------------------------------------------------*
DATA : GT_HEAD       TYPE TABLE OF GTY_HEAD,
       GT_CHARGE     TYPE GTTY_DOC_DISCHG,
       GT_PDF_RESULT TYPE ZSDSFIS025_TT.

DATA : GT_SD          TYPE GTTY_BILL,
       GT_FI          TYPE GTTY_BILL,
       GT_SD_BSEG     TYPE GTTY_BSEG,
       GT_MAIL        TYPE TABLE OF GTY_EMAIL,
       GT_DOC_HEADER  TYPE GTTY_DOC_HEADER,
       GT_DOC_ITEM    TYPE GTTY_DOC_ITEM,
       GT_DOC_PARTNER TYPE GTTY_DOC_PARTNER,
       GT_DOC_H_VAT   TYPE GTTY_DOC_H_VAT,
       GT_DOC_H_REF   TYPE GTTY_DOC_H_REF,
       GT_DOC_DISCHG  TYPE GTTY_DOC_DISCHG.

DATA: GT_MAP_DOC_SD   TYPE GTTY_MAP_DOC_SD,
      GT_MAP_DOC_FI   TYPE GTTY_MAP_DOC_FI,
      GT_MAP_DOC_RESN TYPE GTTY_MAP_DOC_RESN,
      GT_MAP_CURR     TYPE GTTY_MAP_CURR,
      GT_MAP_VAT_TYPE TYPE GTTY_MAP_VAT_TYPE,
      GT_MAP_SCH_CTRY TYPE GTTY_MAP_SCH_CTRY,
      GT_MAP_DISCHG   TYPE GTTY_MAP_DISCHG.

DATA: GT_RD_DOC_TYPE  TYPE GTTY_RD_DOC_TYPE,
      GT_RD_DOC_RESN  TYPE GTTY_RD_DOC_RESN,
      GT_RD_PARTNER   TYPE GTTY_RD_PARTNER,
      GT_RD_SUB_DIST  TYPE GTTY_RD_SUB_DIST,
      GT_RD_DISTRICT  TYPE GTTY_RD_DISTRICT,
      GT_RD_PROVINCE  TYPE GTTY_RD_PROVINCE,
      GT_RD_UNIT      TYPE GTTY_RD_UNIT,
      GT_RD_DISCHG    TYPE GTTY_RD_DISCHG,
      GT_COMPANY_ADDR TYPE GTTY_COMPANY_ADDR.

DATA: GT_TVFKT   TYPE SORTED TABLE OF GTY_TVFKT WITH UNIQUE KEY FKART,
      GT_T003T   TYPE SORTED TABLE OF GTY_T003T WITH UNIQUE KEY BLART,
      GT_REF_DOC TYPE GTTY_VBRK.

DATA: GT_RD_SENT TYPE ZSDSFIS027_TT,
      GT_PARAM   TYPE GTTY_PARAM.
*      gt_text_table TYPE text_lh.    "Only FUNCTION 'READ_TEXT_TABLE' does exist on client system

*>>> BEGIN OF INSERTION: <ETAX001> on 06.09.2020 <<<
DATA: "GT_COLLECTOR TYPE GTTY_COLLECTOR,
      GT_ONE_SD    TYPE GTTY_ONE_SD.
*>>> END OF INSERTION: <ETAX001> on 06.09.2020 <<<

*&--------------------------------------------------------------------*
*& WORK AREA
*&--------------------------------------------------------------------*
DATA : GWA_FILE_PATH TYPE ZSDSFIS028.

*&--------------------------------------------------------------------*
*& VARIABLES
*&--------------------------------------------------------------------*
DATA : GV_COUNT               TYPE I,
       GV_COUNT_SUCCESS       TYPE I,
       GV_COUNT_ERROR         TYPE I,
       GV_SAP_DOC_NO          TYPE CHAR255,
       GV_RD_DOC_TYPE         TYPE CHAR255,
       GV_KUNNR               TYPE CHAR255,
       GV_DIS_DETAIL          TYPE FLAG,
       GV_READ_TEXT_TAB       TYPE ABAP_BOOL,
       GV_CHECK_COLLECTOR_ARC TYPE FLAG . "CH17 +

*&--------------------------------------------------------------------*
*& RANGES
*&--------------------------------------------------------------------*
DATA: GR_STATUS      TYPE RANGE OF ZSDSFIT014-STATUS,
      GR_RD_DCTYPGRP TYPE RANGE OF ZSDSFIC005-RD_DOC_TYPE_GRP,
      GR_KUNNR       TYPE RANGE OF ZSDSFIC001-KUNNR,
      GR_SAP_DOC_NO  TYPE RANGE OF ZSDSFIT014-SAP_DOC_NO,
      GR_FKART       TYPE RANGE OF TVFK-FKART,
      GR_BLART       TYPE RANGE OF T003T-BLART,
      GR_PO_KUNNR    TYPE RANGE OF KNA1-KUNNR ,             ">>>CH17+
      GR_DV_DOCTYPE  TYPE RANGE OF ZSDSFIC005-RD_DOC_TYPE . ">>>CH17+


*&--------------------------------------------------------------------*
*& MACRO
*&--------------------------------------------------------------------*
DEFINE M_MESSAGE.
  PERFORM THROW_MESSAGE USING &1  "p_msgty
                              &2  "p_msgno
                              &3  "p_msgid
                              &4  "p_msgtx
                              &5. "p_displ
END-OF-DEFINITION.

DEFINE M_ADD_FIELDCAT.
  CLEAR &1.
  &1-FIELDNAME = &3.
  &1-TABNAME   = &4.
  APPEND &1 TO &2.
END-OF-DEFINITION.

DEFINE %FCAT.

  IF &2 IS NOT INITIAL.
    &1-SCRTEXT_S = &1-SCRTEXT_M =
    &1-SCRTEXT_L = &1-COLTEXT =
    &1-SELTEXT   = &1-TOOLTIP =
    &1-REPTEXT   = &2.
  ENDIF.

  &1-CHECKBOX  = &3.
  &1-EDIT      = &4.
  &1-HOTSPOT   = &5.
  &1-TECH      = &6.
  &1-JUST      = &7.
  &1-CONVEXIT  = &8.
  &1-COL_POS   = &9.

END-OF-DEFINITION.
