*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZSDSV_ZSDSFIC029................................*
FORM GET_DATA_ZSDSV_ZSDSFIC029.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZSDSFIC029 WHERE
(VIM_WHERETAB) .
    CLEAR ZSDSV_ZSDSFIC029 .
ZSDSV_ZSDSFIC029-MANDT =
ZSDSFIC029-MANDT .
ZSDSV_ZSDSFIC029-APPROVER =
ZSDSFIC029-APPROVER .
ZSDSV_ZSDSFIC029-APPV_TYPE =
ZSDSFIC029-APPV_TYPE .
ZSDSV_ZSDSFIC029-SEQNO =
ZSDSFIC029-SEQNO .
ZSDSV_ZSDSFIC029-AUART =
ZSDSFIC029-AUART .
ZSDSV_ZSDSFIC029-VKORG =
ZSDSFIC029-VKORG .
ZSDSV_ZSDSFIC029-VTWEG =
ZSDSFIC029-VTWEG .
ZSDSV_ZSDSFIC029-SPART =
ZSDSFIC029-SPART .
ZSDSV_ZSDSFIC029-ZCRT_DATE =
ZSDSFIC029-ZCRT_DATE .
ZSDSV_ZSDSFIC029-ZCRT_TIME =
ZSDSFIC029-ZCRT_TIME .
ZSDSV_ZSDSFIC029-ZCRT_USER =
ZSDSFIC029-ZCRT_USER .
ZSDSV_ZSDSFIC029-ZUPD_DATE =
ZSDSFIC029-ZUPD_DATE .
ZSDSV_ZSDSFIC029-ZUPD_TIME =
ZSDSFIC029-ZUPD_TIME .
ZSDSV_ZSDSFIC029-ZUPD_USER =
ZSDSFIC029-ZUPD_USER .
    SELECT SINGLE * FROM USR21 WHERE
BNAME = ZSDSFIC029-APPROVER .
    IF SY-SUBRC EQ 0.
      SELECT * FROM ADRP WHERE
PERSNUMBER = USR21-PERSNUMBER .
ZSDSV_ZSDSFIC029-NAME_TEXT =
ADRP-NAME_TEXT .
        EXIT.
      ENDSELECT.
    ENDIF.
<VIM_TOTAL_STRUC> = ZSDSV_ZSDSFIC029.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZSDSV_ZSDSFIC029 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZSDSV_ZSDSFIC029.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZSDSV_ZSDSFIC029-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZSDSFIC029 WHERE
  APPROVER = ZSDSV_ZSDSFIC029-APPROVER AND
  APPV_TYPE = ZSDSV_ZSDSFIC029-APPV_TYPE AND
  SEQNO = ZSDSV_ZSDSFIC029-SEQNO .
    IF SY-SUBRC = 0.
    DELETE ZSDSFIC029 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZSDSFIC029 WHERE
  APPROVER = ZSDSV_ZSDSFIC029-APPROVER AND
  APPV_TYPE = ZSDSV_ZSDSFIC029-APPV_TYPE AND
  SEQNO = ZSDSV_ZSDSFIC029-SEQNO .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZSDSFIC029.
    ENDIF.
ZSDSFIC029-MANDT =
ZSDSV_ZSDSFIC029-MANDT .
ZSDSFIC029-APPROVER =
ZSDSV_ZSDSFIC029-APPROVER .
ZSDSFIC029-APPV_TYPE =
ZSDSV_ZSDSFIC029-APPV_TYPE .
ZSDSFIC029-SEQNO =
ZSDSV_ZSDSFIC029-SEQNO .
ZSDSFIC029-AUART =
ZSDSV_ZSDSFIC029-AUART .
ZSDSFIC029-VKORG =
ZSDSV_ZSDSFIC029-VKORG .
ZSDSFIC029-VTWEG =
ZSDSV_ZSDSFIC029-VTWEG .
ZSDSFIC029-SPART =
ZSDSV_ZSDSFIC029-SPART .
ZSDSFIC029-ZCRT_DATE =
ZSDSV_ZSDSFIC029-ZCRT_DATE .
ZSDSFIC029-ZCRT_TIME =
ZSDSV_ZSDSFIC029-ZCRT_TIME .
ZSDSFIC029-ZCRT_USER =
ZSDSV_ZSDSFIC029-ZCRT_USER .
ZSDSFIC029-ZUPD_DATE =
ZSDSV_ZSDSFIC029-ZUPD_DATE .
ZSDSFIC029-ZUPD_TIME =
ZSDSV_ZSDSFIC029-ZUPD_TIME .
ZSDSFIC029-ZUPD_USER =
ZSDSV_ZSDSFIC029-ZUPD_USER .
    IF SY-SUBRC = 0.
    UPDATE ZSDSFIC029 ##WARN_OK.
    ELSE.
    INSERT ZSDSFIC029 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZSDSV_ZSDSFIC029-UPD_FLAG,
STATUS_ZSDSV_ZSDSFIC029-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZSDSV_ZSDSFIC029.
  SELECT SINGLE * FROM ZSDSFIC029 WHERE
APPROVER = ZSDSV_ZSDSFIC029-APPROVER AND
APPV_TYPE = ZSDSV_ZSDSFIC029-APPV_TYPE AND
SEQNO = ZSDSV_ZSDSFIC029-SEQNO .
ZSDSV_ZSDSFIC029-MANDT =
ZSDSFIC029-MANDT .
ZSDSV_ZSDSFIC029-APPROVER =
ZSDSFIC029-APPROVER .
ZSDSV_ZSDSFIC029-APPV_TYPE =
ZSDSFIC029-APPV_TYPE .
ZSDSV_ZSDSFIC029-SEQNO =
ZSDSFIC029-SEQNO .
ZSDSV_ZSDSFIC029-AUART =
ZSDSFIC029-AUART .
ZSDSV_ZSDSFIC029-VKORG =
ZSDSFIC029-VKORG .
ZSDSV_ZSDSFIC029-VTWEG =
ZSDSFIC029-VTWEG .
ZSDSV_ZSDSFIC029-SPART =
ZSDSFIC029-SPART .
ZSDSV_ZSDSFIC029-ZCRT_DATE =
ZSDSFIC029-ZCRT_DATE .
ZSDSV_ZSDSFIC029-ZCRT_TIME =
ZSDSFIC029-ZCRT_TIME .
ZSDSV_ZSDSFIC029-ZCRT_USER =
ZSDSFIC029-ZCRT_USER .
ZSDSV_ZSDSFIC029-ZUPD_DATE =
ZSDSFIC029-ZUPD_DATE .
ZSDSV_ZSDSFIC029-ZUPD_TIME =
ZSDSFIC029-ZUPD_TIME .
ZSDSV_ZSDSFIC029-ZUPD_USER =
ZSDSFIC029-ZUPD_USER .
    SELECT SINGLE * FROM USR21 WHERE
BNAME = ZSDSFIC029-APPROVER .
    IF SY-SUBRC EQ 0.
      SELECT * FROM ADRP WHERE
PERSNUMBER = USR21-PERSNUMBER .
ZSDSV_ZSDSFIC029-NAME_TEXT =
ADRP-NAME_TEXT .
        EXIT.
      ENDSELECT.
      IF SY-SUBRC NE 0.
        CLEAR SY-SUBRC.
        CLEAR ZSDSV_ZSDSFIC029-NAME_TEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZSDSV_ZSDSFIC029-NAME_TEXT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZSDSV_ZSDSFIC029 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZSDSV_ZSDSFIC029-APPROVER TO
ZSDSFIC029-APPROVER .
MOVE ZSDSV_ZSDSFIC029-APPV_TYPE TO
ZSDSFIC029-APPV_TYPE .
MOVE ZSDSV_ZSDSFIC029-SEQNO TO
ZSDSFIC029-SEQNO .
MOVE ZSDSV_ZSDSFIC029-MANDT TO
ZSDSFIC029-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZSDSFIC029'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZSDSFIC029 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZSDSFIC029'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZSDSV_ZSDSFIC029 USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZSDSFIC029-MANDT =
ZSDSV_ZSDSFIC029-MANDT .
ZSDSFIC029-APPROVER =
ZSDSV_ZSDSFIC029-APPROVER .
ZSDSFIC029-APPV_TYPE =
ZSDSV_ZSDSFIC029-APPV_TYPE .
ZSDSFIC029-SEQNO =
ZSDSV_ZSDSFIC029-SEQNO .
ZSDSFIC029-AUART =
ZSDSV_ZSDSFIC029-AUART .
ZSDSFIC029-VKORG =
ZSDSV_ZSDSFIC029-VKORG .
ZSDSFIC029-VTWEG =
ZSDSV_ZSDSFIC029-VTWEG .
ZSDSFIC029-SPART =
ZSDSV_ZSDSFIC029-SPART .
ZSDSFIC029-ZCRT_DATE =
ZSDSV_ZSDSFIC029-ZCRT_DATE .
ZSDSFIC029-ZCRT_TIME =
ZSDSV_ZSDSFIC029-ZCRT_TIME .
ZSDSFIC029-ZCRT_USER =
ZSDSV_ZSDSFIC029-ZCRT_USER .
ZSDSFIC029-ZUPD_DATE =
ZSDSV_ZSDSFIC029-ZUPD_DATE .
ZSDSFIC029-ZUPD_TIME =
ZSDSV_ZSDSFIC029-ZUPD_TIME .
ZSDSFIC029-ZUPD_USER =
ZSDSV_ZSDSFIC029-ZUPD_USER .
    SELECT SINGLE * FROM USR21 WHERE
BNAME = ZSDSFIC029-APPROVER .
    IF SY-SUBRC EQ 0.
      SELECT * FROM ADRP WHERE
PERSNUMBER = USR21-PERSNUMBER .
ZSDSV_ZSDSFIC029-NAME_TEXT =
ADRP-NAME_TEXT .
        EXIT.
      ENDSELECT.
      IF SY-SUBRC NE 0.
        CLEAR SY-SUBRC.
        CLEAR ZSDSV_ZSDSFIC029-NAME_TEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZSDSV_ZSDSFIC029-NAME_TEXT .
    ENDIF.
ENDFORM.
