*&---------------------------------------------------------------------*
*& Include          ZSDSFIR0190_S01
*&---------------------------------------------------------------------*
SELECTION-SCREEN BEGIN OF BLOCK B01 WITH FRAME TITLE TEXT-B01.
  PARAMETERS : CB_SD AS CHECKBOX DEFAULT 'X',
               CB_FI AS CHECKBOX DEFAULT 'X' MODIF ID M01.
SELECTION-SCREEN END OF BLOCK B01.
*General Data Selection
SELECTION-SCREEN BEGIN OF BLOCK B02 WITH FRAME TITLE TEXT-B02.
  SELECT-OPTIONS: S_BUKRS FOR T001-BUKRS OBLIGATORY DEFAULT '1000',
                  S_GJAHR FOR BKPF-GJAHR DEFAULT SY-DATUM+0(4) OBLIGATORY,
                  S_BELNR FOR BKPF-BELNR,
                  S_BUPLA FOR BSEG-BUPLA,
                  S_RD_DTY FOR ZSDSFIT014-RD_DOC_TYPE MATCHCODE OBJECT ZSHETX_RD_DOC_TYPE,
                  S_FKART FOR VBRK-FKART,
                  S_BUDAT FOR BKPF-BUDAT DEFAULT SY-DATUM,
                  S_KUNNR FOR VBRK-KUNAG.
SELECTION-SCREEN END OF BLOCK B02.
*Document Reason
SELECTION-SCREEN BEGIN OF BLOCK B03 WITH FRAME TITLE TEXT-B03.
  SELECT-OPTIONS: S_RD_DRS FOR ZSDSFIT014-RD_DOC_RESN,
                  S_AUGRU FOR ZSDSFIT014-SAP_DOC_RESN MATCHCODE OBJECT H_TVAU.
SELECTION-SCREEN END OF BLOCK B03.
*Document Status
SELECTION-SCREEN BEGIN OF BLOCK B08 WITH FRAME TITLE TEXT-B08.
  PARAMETERS : P_NEW TYPE CHAR1 AS CHECKBOX DEFAULT 'X',
               P_TF  TYPE CHAR1 AS CHECKBOX DEFAULT 'X'.
  ">>>>>> BEGIN OF INSERTION: <CH12> 30.11.2020 10:19:47 >>>>>>
  SELECTION-SCREEN BEGIN OF LINE .
    POSITION 1.
    PARAMETERS  P_OBSLT TYPE CHAR1 AS CHECKBOX MODIF ID M02 DEFAULT 'X'.
    POSITION 3.
    SELECTION-SCREEN COMMENT 3(70) TEXT-OBS.
  SELECTION-SCREEN END OF LINE.
  "<<<<<< END OF INSERTION: <CH12> 30.11.2020 10:19:47  <<<<<<
SELECTION-SCREEN END OF BLOCK B08.
*Replacement Document
SELECTION-SCREEN BEGIN OF BLOCK B04 WITH FRAME TITLE TEXT-B04.
  PARAMETERS: CB_N_RPL AS CHECKBOX DEFAULT 'X',
              CB_RPL   AS CHECKBOX DEFAULT 'X'.
SELECTION-SCREEN END OF BLOCK B04.
*Cancelled Document
SELECTION-SCREEN BEGIN OF BLOCK B05 WITH FRAME TITLE TEXT-B05.
  SELECTION-SCREEN BEGIN OF LINE.
    PARAMETERS: CB_NORML AS CHECKBOX DEFAULT 'X'.
    SELECTION-SCREEN COMMENT 3(45) TEXT-S01.
  SELECTION-SCREEN END OF LINE.

*SELECTION-SCREEN BEGIN OF LINE.
*PARAMETERS: cb_cc_rd AS CHECKBOX DEFAULT 'X'.
*SELECTION-SCREEN COMMENT 3(45) TEXT-s02.
*SELECTION-SCREEN END OF LINE.

  SELECTION-SCREEN BEGIN OF LINE.
    PARAMETERS: CB_CNCL AS CHECKBOX DEFAULT 'X'.
*SELECTION-SCREEN COMMENT 3(45) TEXT-s03.
    SELECTION-SCREEN COMMENT 3(45) TEXT-S12.
  SELECTION-SCREEN END OF LINE.


SELECTION-SCREEN END OF BLOCK B05.


*>>> BEGIN OF INSERTION: <ETAX003> on 24.09.2020 <<<
SELECTION-SCREEN BEGIN OF BLOCK B10 WITH FRAME TITLE TEXT-B10.
  SELECTION-SCREEN BEGIN OF LINE.
    PARAMETERS: CB_RD AS CHECKBOX DEFAULT 'X'.
    SELECTION-SCREEN COMMENT 3(45) TEXT-S10.
  SELECTION-SCREEN END OF LINE.

  SELECTION-SCREEN BEGIN OF LINE.
    PARAMETERS: CB_NOTRD AS CHECKBOX DEFAULT 'X'.
    SELECTION-SCREEN COMMENT 3(45) TEXT-S11.
  SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK B10.
*>>> END OF INSERTION: <ETAX003> on 24.09.2020 <<<

*Transferring Information
SELECTION-SCREEN BEGIN OF BLOCK B06 WITH FRAME TITLE TEXT-B06.
  SELECT-OPTIONS: S_ETX_BY FOR ZSDSFIT014-ETAX_BY,
                  S_ETX_DT FOR ZSDSFIT014-ETAX_DATE.
SELECTION-SCREEN END OF BLOCK B06.

*>>> BOI CH01 >>>
*Printing Information
SELECTION-SCREEN BEGIN OF BLOCK B11 WITH FRAME TITLE TEXT-B11.
  SELECT-OPTIONS: S_PNT_BY FOR ZSDSFIT014-PRINT_USER,
                  S_PNT_DT FOR ZSDSFIT014-PRINT_DATE.
SELECTION-SCREEN END OF BLOCK B11.
*<<< EOI CH01 <<<

*Document Group
SELECTION-SCREEN BEGIN OF BLOCK B07 WITH FRAME TITLE TEXT-B07.
  PARAMETERS: CB_INV AS CHECKBOX DEFAULT 'X',
              CB_RCT AS CHECKBOX DEFAULT 'X',
              CB_TIV AS CHECKBOX DEFAULT 'X',
              CB_DCN AS CHECKBOX DEFAULT 'X'.
SELECTION-SCREEN END OF BLOCK B07.
**Document Status
*SELECTION-SCREEN BEGIN OF BLOCK b08 WITH FRAME TITLE TEXT-b08.
*SELECTION-SCREEN BEGIN OF LINE.
*PARAMETERS: cb_stat1 AS CHECKBOX DEFAULT 'X'.
*SELECTION-SCREEN COMMENT 3(45) TEXT-s04.
*SELECTION-SCREEN END OF LINE.
*SELECTION-SCREEN BEGIN OF LINE.
*PARAMETERS: cb_stat2 AS CHECKBOX DEFAULT 'X'.
*SELECTION-SCREEN COMMENT 3(45) TEXT-s05.
*SELECTION-SCREEN END OF LINE.
*
*SELECTION-SCREEN BEGIN OF LINE.
*PARAMETERS: cb_stat5 AS CHECKBOX DEFAULT 'X'.
*SELECTION-SCREEN COMMENT 3(45) TEXT-s06.
*SELECTION-SCREEN END OF LINE.
*
*SELECTION-SCREEN BEGIN OF LINE.
*PARAMETERS: cb_stat3 AS CHECKBOX DEFAULT 'X'.
*SELECTION-SCREEN COMMENT 3(45) TEXT-s07.
*SELECTION-SCREEN END OF LINE.
*
*SELECTION-SCREEN BEGIN OF LINE.
*PARAMETERS: cb_stat4 AS CHECKBOX DEFAULT 'X'.
*SELECTION-SCREEN COMMENT 3(45) TEXT-s08.
*SELECTION-SCREEN END OF LINE.
*
*SELECTION-SCREEN BEGIN OF LINE.
*PARAMETERS: cb_stat6 AS CHECKBOX DEFAULT 'X'.
*SELECTION-SCREEN COMMENT 3(45) TEXT-s09.
*SELECTION-SCREEN END OF LINE.
*SELECTION-SCREEN END OF BLOCK b08.

*Layout Control
SELECTION-SCREEN BEGIN OF BLOCK B09 WITH FRAME TITLE TEXT-B09.
  PARAMETERS: P_VARI TYPE DISVARIANT-VARIANT.
SELECTION-SCREEN END OF BLOCK B09.

*F4 Help for layout variant
AT SELECTION-SCREEN ON VALUE-REQUEST FOR P_VARI.

  PERFORM F4_VARIANT USING SY-REPID CHANGING P_VARI.
