FUNCTION-POOL ZSDSFI19.                     "MESSAGE-ID ..

* INCLUDE LZSDSFI19D...                      " Local class definition
DATA :
  GR_CUSTOM_CONT TYPE REF TO CL_GUI_CUSTOM_CONTAINER ##NEEDED,
  GR_TEXT_EDIT   TYPE REF TO CL_GUI_TEXTEDIT         ##NEEDED.
DATA:
  GT_TEXT     TYPE WCB_TDLINE_TAB      ##NEEDED,
  GT_OLD_TEXT TYPE  WCB_TDLINE_TAB     ##NEEDED.
DATA:
  GF_OKCODE TYPE SY-UCOMM              ##NEEDED.
