*&---------------------------------------------------------------------*
*& Include          ZSDSFIR0350_S01
*&---------------------------------------------------------------------*

*----------------------------------------------------------------------*
* SELECTION-SCREEN
*----------------------------------------------------------------------*
* Text-s01: Selection Criteria
SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-S01.
  PARAMETERS: P_BUKRS TYPE BKPF-BUKRS DEFAULT '1000'.
  SELECT-OPTIONS:
   S_HKONT FOR SKA1-SAKNR NO INTERVALS OBLIGATORY,
   S_BELNR FOR BKPF-BELNR,
   S_GJAHR FOR BKPF-GJAHR NO INTERVALS NO-EXTENSION DEFAULT SY-DATUM(4),
   S_SELEC FOR BKPF-BUDAT.
SELECTION-SCREEN END OF BLOCK B1.
SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME TITLE TEXT-S02.
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 1(50) TEXT-S03 FOR FIELD RB_FC1.
    PARAMETERS: RB_FC1 RADIOBUTTON GROUP RAD DEFAULT 'X'.
  SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN SKIP 1.
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 1(50) TEXT-S04 FOR FIELD RB_FC2.
    PARAMETERS: RB_FC2 RADIOBUTTON GROUP RAD.
  SELECTION-SCREEN END OF LINE.
  PARAMETERS: P_BUDAT TYPE BKPF-BUDAT DEFAULT SY-DATUM OBLIGATORY.
  PARAMETERS: P_BLART TYPE BKPF-BLART DEFAULT 'SB'.
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 11(20) TEXT-S06 FOR FIELD RB_M1.
    PARAMETERS: RB_M1 RADIOBUTTON GROUP MOD.
  SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 11(20) TEXT-S07 FOR FIELD RB_M2.
    PARAMETERS: RB_M2 RADIOBUTTON GROUP MOD.
  SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN SKIP 1.
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 1(50) TEXT-S05 FOR FIELD RB_FC3.
    PARAMETERS: RB_FC3 RADIOBUTTON GROUP RAD.
  SELECTION-SCREEN END OF LINE.
  SELECT-OPTIONS: S_BUDAT FOR BKPF-BUDAT.
  PARAMETERS: P_VAR TYPE DISVARIANT-VARIANT.
SELECTION-SCREEN END OF BLOCK B2.
