*&---------------------------------------------------------------------*
*& Include          ZSDSFIR0110_SELECTION
*&---------------------------------------------------------------------*
*-----------------------------------------------------------------------
* P A R A M E T E R S   &   S E L E C T - O P T I O N S
*-----------------------------------------------------------------------
* PARAMETERS:
* SELECT-OPTIONS:
SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-B01.

SELECTION-SCREEN BEGIN OF LINE.

SELECTION-SCREEN COMMENT 1(30) TEXT-T04.

PARAMETERS: P_MANUAL RADIOBUTTON GROUP RAD1 DEFAULT 'X' USER-COMMAND UCOM1 MODIF ID M01.
SELECTION-SCREEN COMMENT 35(25) TEXT-T02.
PARAMETERS: P_AUTO RADIOBUTTON GROUP RAD1 MODIF ID M02.
SELECTION-SCREEN COMMENT 64(25) TEXT-T03 .

SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(30) TEXT-T01 FOR FIELD P_DATE.
PARAMETERS: P_DATE TYPE SY-DATUM.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN SKIP.
SELECTION-SCREEN END OF BLOCK B1.

SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME TITLE TEXT-B02.
SELECT-OPTIONS S_FCURR FOR TCURR-FCURR NO INTERVALS OBLIGATORY.
SELECTION-SCREEN END OF BLOCK B2.

SELECTION-SCREEN BEGIN OF BLOCK B3 WITH FRAME TITLE TEXT-B03.
PARAMETERS : CB_B AS CHECKBOX DEFAULT 'X',
             CB_M AS CHECKBOX DEFAULT 'X',
             CB_G AS CHECKBOX DEFAULT 'X'.
SELECTION-SCREEN END OF BLOCK B3.

PARAMETERS : CB_K2 AS CHECKBOX DEFAULT 'X'.
