FUNCTION-POOL ZSDSFI02.                     "MESSAGE-ID ..

* INCLUDE LZSDSFI02D...                      " Local class definition


CONSTANTS:
  GC_TASK_INSERT TYPE BUS_EI_OBJECT_TASK       VALUE 'I',
  GC_TASK_UPDATE TYPE BUS_EI_OBJECT_TASK       VALUE 'U',
  GC_TASK_MODIFY TYPE BUS_EI_OBJECT_TASK       VALUE 'M',
  GC_TASK_DELETE TYPE BUS_EI_OBJECT_TASK       VALUE 'D',
  GC_SDS         TYPE EKKO-EKORG               VALUE '1000',
  GC_TAX_TH3     TYPE BAPIBUS1006TAX-TAXTYPE   VALUE 'TH3',
  GC_TH          TYPE LAND1                    VALUE 'TH',
  GC_HEADOFF     TYPE CHAR30                   VALUE 'Head Office/สำนักงานใหญ่',
  GC_VIP_TAX     TYPE BPTAXNUM                 VALUE '0000000000000',

  "Message type: S Success, E Error, W Warning, I Info, A Abort
  BEGIN OF GC_MSGTYP,
    ERROR TYPE BAPIRET2-TYPE VALUE 'E',
    ABORT TYPE BAPIRET2-TYPE VALUE 'A',
  END OF GC_MSGTYP,

  BEGIN OF GC_ROLE,
    CUSTOMER    TYPE BU_ROLE VALUE 'FLCU01',
    CUSTOMER_FI TYPE BU_ROLE VALUE 'FLCU00',
    VENDOR      TYPE BU_ROLE VALUE 'FLVN01',
    VENDOR_FI   TYPE BU_ROLE VALUE 'FLVN00',
    CREDIT      TYPE BU_ROLE VALUE 'UKM000',
    CONTACT_P   TYPE BU_ROLE VALUE 'CHM003',
  END OF GC_ROLE,

  BEGIN OF GC_SALES_AREA,
    VKORG TYPE VKORG VALUE '1000',  "Sales Org.
    VTWEG TYPE VTWEG VALUE '00',    "Distr. Channel
    SPART TYPE SPART VALUE '00',    "Division
  END OF GC_SALES_AREA,

  BEGIN OF GC_PARTNER_FN,
    S_EMP  TYPE PARVW VALUE 'VE',    "Sales  Emp.
    SHIPTO TYPE PARVW VALUE 'WE',    "Ship to
  END OF GC_PARTNER_FN,

  BEGIN OF GC_GROUP,
    NAF TYPE BU_GROUP VALUE 'Z010',
    DKI TYPE BU_GROUP VALUE 'Z030',
    EMP TYPE BU_GROUP VALUE 'Z050',
  END OF GC_GROUP.

"Work Area
DATA:
  GS_BP_EXTERN      TYPE BAPIBUS1006_HEAD-BPARTNER,
  GS_PARTN_CAT      TYPE BAPIBUS1006_HEAD-PARTN_CAT,
  GS_PARTN_GRP      TYPE BAPIBUS1006_HEAD-PARTN_GRP,
  GS_CENTRALDATA    TYPE BAPIBUS1006_CENTRAL,
  GS_CENTRAL_PERSON TYPE BAPIBUS1006_CENTRAL_PERSON,
  GS_CENTRAL_ORGAN  TYPE BAPIBUS1006_CENTRAL_ORGAN,
  GS_ADDRESS        TYPE BAPIBUS1006_ADDRESS.

"Table
DATA:
 GT_RETURN         TYPE STANDARD TABLE OF BAPIRET2.

DATA:
  GV_PARTNER       TYPE BU_PARTNER,
  GV_PARTNER_GUID  TYPE BAPIBUS1006_HEAD-PARTNGUID,   "but000-partner_guid,
  GV_EXT           TYPE BAPIBUS1006_HEAD-EXTERN_NO,
  GV_FLAG_ERR      TYPE CHAR01,      "Flag for check error.
  GV_LOCAL         TYPE CHAR01,
  GV_CUSTOMER_FLAG TYPE CHAR01,
  GV_VENDOR_FLAG   TYPE CHAR01.


DATA: GV_CONST TYPE CHAR01,
      GT_VTWEG TYPE STANDARD TABLE OF FAGL_R_S_SELOPT.
