*&---------------------------------------------------------------------*
*& Include          ZSDSMMR0350_SELECTION
*&---------------------------------------------------------------------*

*-----------------------------------------------------------------------
* P A R A M E T E R S   &   S E L E C T - O P T I O N S
*-----------------------------------------------------------------------
SELECTION-SCREEN BEGIN OF BLOCK BLOCK1 WITH FRAME TITLE TEXT-001.
PARAMETERS : P_NAME LIKE RLGRAP-FILENAME OBLIGATORY.
SELECTION-SCREEN END OF BLOCK BLOCK1.

SELECTION-SCREEN BEGIN OF BLOCK BLOCK2 WITH FRAME TITLE TEXT-002.
PARAMETERS : R1 RADIOBUTTON GROUP TXT DEFAULT 'X',
             R2 RADIOBUTTON GROUP TXT.
SELECTION-SCREEN END OF BLOCK BLOCK2.

SELECTION-SCREEN BEGIN OF BLOCK BLOCK5 WITH FRAME TITLE TEXT-003.
SELECT-OPTIONS: S_RECEI FOR SOMLRECI1-RECEIVER NO INTERVALS.
SELECTION-SCREEN END OF BLOCK BLOCK5.

SELECTION-SCREEN BEGIN OF BLOCK B4 WITH FRAME TITLE TEXT-004.
SELECTION-SCREEN COMMENT 3(41) TEXT-C04 FOR FIELD P_GI.
PARAMETERS: P_GI AS CHECKBOX DEFAULT SPACE.
SELECTION-SCREEN END OF BLOCK B4.
