*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZSDSV_COL_STATUS................................*
FORM GET_DATA_ZSDSV_COL_STATUS.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZSDSFIT038 WHERE
(VIM_WHERETAB) .
    CLEAR ZSDSV_COL_STATUS .
ZSDSV_COL_STATUS-MANDT =
ZSDSFIT038-MANDT .
ZSDSV_COL_STATUS-DATA_TYPE =
ZSDSFIT038-DATA_TYPE .
ZSDSV_COL_STATUS-BUKRS =
ZSDSFIT038-BUKRS .
ZSDSV_COL_STATUS-BELNR =
ZSDSFIT038-BELNR .
ZSDSV_COL_STATUS-GJAHR =
ZSDSFIT038-GJAHR .
ZSDSV_COL_STATUS-BUZEI =
ZSDSFIT038-BUZEI .
ZSDSV_COL_STATUS-SEQ =
ZSDSFIT038-SEQ .
ZSDSV_COL_STATUS-SUB_SEQ =
ZSDSFIT038-SUB_SEQ .
ZSDSV_COL_STATUS-VBELN_VF =
ZSDSFIT038-VBELN_VF .
ZSDSV_COL_STATUS-BILLPL_NO =
ZSDSFIT038-BILLPL_NO .
ZSDSV_COL_STATUS-BILLPL_DATE =
ZSDSFIT038-BILLPL_DATE .
ZSDSV_COL_STATUS-PERNR =
ZSDSFIT038-PERNR .
ZSDSV_COL_STATUS-WORK_DATE =
ZSDSFIT038-WORK_DATE .
ZSDSV_COL_STATUS-KUNNR =
ZSDSFIT038-KUNNR .
ZSDSV_COL_STATUS-UMSKZ =
ZSDSFIT038-UMSKZ .
ZSDSV_COL_STATUS-XBLNR =
ZSDSFIT038-XBLNR .
ZSDSV_COL_STATUS-BLDAT =
ZSDSFIT038-BLDAT .
ZSDSV_COL_STATUS-BUDAT =
ZSDSFIT038-BUDAT .
ZSDSV_COL_STATUS-FAEDT =
ZSDSFIT038-FAEDT .
ZSDSV_COL_STATUS-WRBTR =
ZSDSFIT038-WRBTR .
ZSDSV_COL_STATUS-WAERS =
ZSDSFIT038-WAERS .
ZSDSV_COL_STATUS-DEDUCT_AMT =
ZSDSFIT038-DEDUCT_AMT .
ZSDSV_COL_STATUS-PAYNO =
ZSDSFIT038-PAYNO .
ZSDSV_COL_STATUS-BRNCH =
ZSDSFIT038-BRNCH .
ZSDSV_COL_STATUS-BAL_AMT =
ZSDSFIT038-BAL_AMT .
ZSDSV_COL_STATUS-EXPS_AMT =
ZSDSFIT038-EXPS_AMT .
ZSDSV_COL_STATUS-AUFNR_EXPS =
ZSDSFIT038-AUFNR_EXPS .
ZSDSV_COL_STATUS-WHT_AMT =
ZSDSFIT038-WHT_AMT .
ZSDSV_COL_STATUS-FEE =
ZSDSFIT038-FEE .
ZSDSV_COL_STATUS-AUFNR_FEE =
ZSDSFIT038-AUFNR_FEE .
ZSDSV_COL_STATUS-RECEIVED_AMT =
ZSDSFIT038-RECEIVED_AMT .
ZSDSV_COL_STATUS-RETENTION =
ZSDSFIT038-RETENTION .
ZSDSV_COL_STATUS-INCOME_AMT =
ZSDSFIT038-INCOME_AMT .
ZSDSV_COL_STATUS-CASH_CON =
ZSDSFIT038-CASH_CON .
ZSDSV_COL_STATUS-ADV_AMT =
ZSDSFIT038-ADV_AMT .
ZSDSV_COL_STATUS-PAYIN_AMT =
ZSDSFIT038-PAYIN_AMT .
ZSDSV_COL_STATUS-REMAIN_AMT =
ZSDSFIT038-REMAIN_AMT .
ZSDSV_COL_STATUS-REMAIN_C_AMT =
ZSDSFIT038-REMAIN_C_AMT .
ZSDSV_COL_STATUS-KOSTL =
ZSDSFIT038-KOSTL .
ZSDSV_COL_STATUS-PRCTR =
ZSDSFIT038-PRCTR .
ZSDSV_COL_STATUS-HBKID =
ZSDSFIT038-HBKID .
ZSDSV_COL_STATUS-HKTID =
ZSDSFIT038-HKTID .
ZSDSV_COL_STATUS-PYMT_METHOD =
ZSDSFIT038-PYMT_METHOD .
ZSDSV_COL_STATUS-ACTION_TYPE =
ZSDSFIT038-ACTION_TYPE .
ZSDSV_COL_STATUS-STATUS =
ZSDSFIT038-STATUS .
ZSDSV_COL_STATUS-REMARK =
ZSDSFIT038-REMARK .
ZSDSV_COL_STATUS-PAYMENT_DATE =
ZSDSFIT038-PAYMENT_DATE .
ZSDSV_COL_STATUS-RECEIVED_DATE =
ZSDSFIT038-RECEIVED_DATE .
ZSDSV_COL_STATUS-RECEIPT_NO =
ZSDSFIT038-RECEIPT_NO .
ZSDSV_COL_STATUS-BANK_DATE =
ZSDSFIT038-BANK_DATE .
ZSDSV_COL_STATUS-CHEQUE_NO =
ZSDSFIT038-CHEQUE_NO .
ZSDSV_COL_STATUS-BANKN =
ZSDSFIT038-BANKN .
ZSDSV_COL_STATUS-BANKL =
ZSDSFIT038-BANKL .
ZSDSV_COL_STATUS-TRANF_NO =
ZSDSFIT038-TRANF_NO .
ZSDSV_COL_STATUS-BANKK =
ZSDSFIT038-BANKK .
ZSDSV_COL_STATUS-ZBANK_ITEM =
ZSDSFIT038-ZBANK_ITEM .
ZSDSV_COL_STATUS-VBELN =
ZSDSFIT038-VBELN .
ZSDSV_COL_STATUS-FKDAT =
ZSDSFIT038-FKDAT .
ZSDSV_COL_STATUS-CHEQUE_DATE =
ZSDSFIT038-CHEQUE_DATE .
ZSDSV_COL_STATUS-FOLLOW_DATE =
ZSDSFIT038-FOLLOW_DATE .
ZSDSV_COL_STATUS-PO_REF =
ZSDSFIT038-PO_REF .
ZSDSV_COL_STATUS-BILLPL_AMT =
ZSDSFIT038-BILLPL_AMT .
ZSDSV_COL_STATUS-DOCUMENT_STATUS =
ZSDSFIT038-DOCUMENT_STATUS .
ZSDSV_COL_STATUS-INV_STATUS =
ZSDSFIT038-INV_STATUS .
ZSDSV_COL_STATUS-REMARK_VENDOR =
ZSDSFIT038-REMARK_VENDOR .
ZSDSV_COL_STATUS-REASON_VENDOR =
ZSDSFIT038-REASON_VENDOR .
ZSDSV_COL_STATUS-BILLING_CYCLE =
ZSDSFIT038-BILLING_CYCLE .
ZSDSV_COL_STATUS-COLLECTION_CYCLE =
ZSDSFIT038-COLLECTION_CYCLE .
ZSDSV_COL_STATUS-AWB_NO =
ZSDSFIT038-AWB_NO .
ZSDSV_COL_STATUS-DELETE_FLAG =
ZSDSFIT038-DELETE_FLAG .
ZSDSV_COL_STATUS-DELETE_DATE =
ZSDSFIT038-DELETE_DATE .
ZSDSV_COL_STATUS-ERDAT =
ZSDSFIT038-ERDAT .
ZSDSV_COL_STATUS-ERZMT =
ZSDSFIT038-ERZMT .
ZSDSV_COL_STATUS-UPDATE_BY =
ZSDSFIT038-UPDATE_BY .
ZSDSV_COL_STATUS-UPDATE_ON =
ZSDSFIT038-UPDATE_ON .
ZSDSV_COL_STATUS-UPDATE_TIME =
ZSDSFIT038-UPDATE_TIME .
ZSDSV_COL_STATUS-ERNAM_HIST =
ZSDSFIT038-ERNAM_HIST .
ZSDSV_COL_STATUS-ERDAT_HIST =
ZSDSFIT038-ERDAT_HIST .
ZSDSV_COL_STATUS-ERZMT_HIST =
ZSDSFIT038-ERZMT_HIST .
<VIM_TOTAL_STRUC> = ZSDSV_COL_STATUS.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZSDSV_COL_STATUS .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZSDSV_COL_STATUS.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZSDSV_COL_STATUS-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZSDSFIT038 WHERE
  DATA_TYPE = ZSDSV_COL_STATUS-DATA_TYPE AND
  BUKRS = ZSDSV_COL_STATUS-BUKRS AND
  BELNR = ZSDSV_COL_STATUS-BELNR AND
  GJAHR = ZSDSV_COL_STATUS-GJAHR AND
  BUZEI = ZSDSV_COL_STATUS-BUZEI AND
  SEQ = ZSDSV_COL_STATUS-SEQ AND
  SUB_SEQ = ZSDSV_COL_STATUS-SUB_SEQ .
    IF SY-SUBRC = 0.
    DELETE ZSDSFIT038 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZSDSFIT038 WHERE
  DATA_TYPE = ZSDSV_COL_STATUS-DATA_TYPE AND
  BUKRS = ZSDSV_COL_STATUS-BUKRS AND
  BELNR = ZSDSV_COL_STATUS-BELNR AND
  GJAHR = ZSDSV_COL_STATUS-GJAHR AND
  BUZEI = ZSDSV_COL_STATUS-BUZEI AND
  SEQ = ZSDSV_COL_STATUS-SEQ AND
  SUB_SEQ = ZSDSV_COL_STATUS-SUB_SEQ .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZSDSFIT038.
    ENDIF.
ZSDSFIT038-MANDT =
ZSDSV_COL_STATUS-MANDT .
ZSDSFIT038-DATA_TYPE =
ZSDSV_COL_STATUS-DATA_TYPE .
ZSDSFIT038-BUKRS =
ZSDSV_COL_STATUS-BUKRS .
ZSDSFIT038-BELNR =
ZSDSV_COL_STATUS-BELNR .
ZSDSFIT038-GJAHR =
ZSDSV_COL_STATUS-GJAHR .
ZSDSFIT038-BUZEI =
ZSDSV_COL_STATUS-BUZEI .
ZSDSFIT038-SEQ =
ZSDSV_COL_STATUS-SEQ .
ZSDSFIT038-SUB_SEQ =
ZSDSV_COL_STATUS-SUB_SEQ .
ZSDSFIT038-VBELN_VF =
ZSDSV_COL_STATUS-VBELN_VF .
ZSDSFIT038-BILLPL_NO =
ZSDSV_COL_STATUS-BILLPL_NO .
ZSDSFIT038-BILLPL_DATE =
ZSDSV_COL_STATUS-BILLPL_DATE .
ZSDSFIT038-PERNR =
ZSDSV_COL_STATUS-PERNR .
ZSDSFIT038-WORK_DATE =
ZSDSV_COL_STATUS-WORK_DATE .
ZSDSFIT038-KUNNR =
ZSDSV_COL_STATUS-KUNNR .
ZSDSFIT038-UMSKZ =
ZSDSV_COL_STATUS-UMSKZ .
ZSDSFIT038-XBLNR =
ZSDSV_COL_STATUS-XBLNR .
ZSDSFIT038-BLDAT =
ZSDSV_COL_STATUS-BLDAT .
ZSDSFIT038-BUDAT =
ZSDSV_COL_STATUS-BUDAT .
ZSDSFIT038-FAEDT =
ZSDSV_COL_STATUS-FAEDT .
ZSDSFIT038-WRBTR =
ZSDSV_COL_STATUS-WRBTR .
ZSDSFIT038-WAERS =
ZSDSV_COL_STATUS-WAERS .
ZSDSFIT038-DEDUCT_AMT =
ZSDSV_COL_STATUS-DEDUCT_AMT .
ZSDSFIT038-PAYNO =
ZSDSV_COL_STATUS-PAYNO .
ZSDSFIT038-BRNCH =
ZSDSV_COL_STATUS-BRNCH .
ZSDSFIT038-BAL_AMT =
ZSDSV_COL_STATUS-BAL_AMT .
ZSDSFIT038-EXPS_AMT =
ZSDSV_COL_STATUS-EXPS_AMT .
ZSDSFIT038-AUFNR_EXPS =
ZSDSV_COL_STATUS-AUFNR_EXPS .
ZSDSFIT038-WHT_AMT =
ZSDSV_COL_STATUS-WHT_AMT .
ZSDSFIT038-FEE =
ZSDSV_COL_STATUS-FEE .
ZSDSFIT038-AUFNR_FEE =
ZSDSV_COL_STATUS-AUFNR_FEE .
ZSDSFIT038-RECEIVED_AMT =
ZSDSV_COL_STATUS-RECEIVED_AMT .
ZSDSFIT038-RETENTION =
ZSDSV_COL_STATUS-RETENTION .
ZSDSFIT038-INCOME_AMT =
ZSDSV_COL_STATUS-INCOME_AMT .
ZSDSFIT038-CASH_CON =
ZSDSV_COL_STATUS-CASH_CON .
ZSDSFIT038-ADV_AMT =
ZSDSV_COL_STATUS-ADV_AMT .
ZSDSFIT038-PAYIN_AMT =
ZSDSV_COL_STATUS-PAYIN_AMT .
ZSDSFIT038-REMAIN_AMT =
ZSDSV_COL_STATUS-REMAIN_AMT .
ZSDSFIT038-REMAIN_C_AMT =
ZSDSV_COL_STATUS-REMAIN_C_AMT .
ZSDSFIT038-KOSTL =
ZSDSV_COL_STATUS-KOSTL .
ZSDSFIT038-PRCTR =
ZSDSV_COL_STATUS-PRCTR .
ZSDSFIT038-HBKID =
ZSDSV_COL_STATUS-HBKID .
ZSDSFIT038-HKTID =
ZSDSV_COL_STATUS-HKTID .
ZSDSFIT038-PYMT_METHOD =
ZSDSV_COL_STATUS-PYMT_METHOD .
ZSDSFIT038-ACTION_TYPE =
ZSDSV_COL_STATUS-ACTION_TYPE .
ZSDSFIT038-STATUS =
ZSDSV_COL_STATUS-STATUS .
ZSDSFIT038-REMARK =
ZSDSV_COL_STATUS-REMARK .
ZSDSFIT038-PAYMENT_DATE =
ZSDSV_COL_STATUS-PAYMENT_DATE .
ZSDSFIT038-RECEIVED_DATE =
ZSDSV_COL_STATUS-RECEIVED_DATE .
ZSDSFIT038-RECEIPT_NO =
ZSDSV_COL_STATUS-RECEIPT_NO .
ZSDSFIT038-BANK_DATE =
ZSDSV_COL_STATUS-BANK_DATE .
ZSDSFIT038-CHEQUE_NO =
ZSDSV_COL_STATUS-CHEQUE_NO .
ZSDSFIT038-BANKN =
ZSDSV_COL_STATUS-BANKN .
ZSDSFIT038-BANKL =
ZSDSV_COL_STATUS-BANKL .
ZSDSFIT038-TRANF_NO =
ZSDSV_COL_STATUS-TRANF_NO .
ZSDSFIT038-BANKK =
ZSDSV_COL_STATUS-BANKK .
ZSDSFIT038-ZBANK_ITEM =
ZSDSV_COL_STATUS-ZBANK_ITEM .
ZSDSFIT038-VBELN =
ZSDSV_COL_STATUS-VBELN .
ZSDSFIT038-FKDAT =
ZSDSV_COL_STATUS-FKDAT .
ZSDSFIT038-CHEQUE_DATE =
ZSDSV_COL_STATUS-CHEQUE_DATE .
ZSDSFIT038-FOLLOW_DATE =
ZSDSV_COL_STATUS-FOLLOW_DATE .
ZSDSFIT038-PO_REF =
ZSDSV_COL_STATUS-PO_REF .
ZSDSFIT038-BILLPL_AMT =
ZSDSV_COL_STATUS-BILLPL_AMT .
ZSDSFIT038-DOCUMENT_STATUS =
ZSDSV_COL_STATUS-DOCUMENT_STATUS .
ZSDSFIT038-INV_STATUS =
ZSDSV_COL_STATUS-INV_STATUS .
ZSDSFIT038-REMARK_VENDOR =
ZSDSV_COL_STATUS-REMARK_VENDOR .
ZSDSFIT038-REASON_VENDOR =
ZSDSV_COL_STATUS-REASON_VENDOR .
ZSDSFIT038-BILLING_CYCLE =
ZSDSV_COL_STATUS-BILLING_CYCLE .
ZSDSFIT038-COLLECTION_CYCLE =
ZSDSV_COL_STATUS-COLLECTION_CYCLE .
ZSDSFIT038-AWB_NO =
ZSDSV_COL_STATUS-AWB_NO .
ZSDSFIT038-DELETE_FLAG =
ZSDSV_COL_STATUS-DELETE_FLAG .
ZSDSFIT038-DELETE_DATE =
ZSDSV_COL_STATUS-DELETE_DATE .
ZSDSFIT038-ERDAT =
ZSDSV_COL_STATUS-ERDAT .
ZSDSFIT038-ERZMT =
ZSDSV_COL_STATUS-ERZMT .
ZSDSFIT038-UPDATE_BY =
ZSDSV_COL_STATUS-UPDATE_BY .
ZSDSFIT038-UPDATE_ON =
ZSDSV_COL_STATUS-UPDATE_ON .
ZSDSFIT038-UPDATE_TIME =
ZSDSV_COL_STATUS-UPDATE_TIME .
ZSDSFIT038-ERNAM_HIST =
ZSDSV_COL_STATUS-ERNAM_HIST .
ZSDSFIT038-ERDAT_HIST =
ZSDSV_COL_STATUS-ERDAT_HIST .
ZSDSFIT038-ERZMT_HIST =
ZSDSV_COL_STATUS-ERZMT_HIST .
    IF SY-SUBRC = 0.
    UPDATE ZSDSFIT038 ##WARN_OK.
    ELSE.
    INSERT ZSDSFIT038 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZSDSV_COL_STATUS-UPD_FLAG,
STATUS_ZSDSV_COL_STATUS-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZSDSV_COL_STATUS.
  SELECT SINGLE * FROM ZSDSFIT038 WHERE
DATA_TYPE = ZSDSV_COL_STATUS-DATA_TYPE AND
BUKRS = ZSDSV_COL_STATUS-BUKRS AND
BELNR = ZSDSV_COL_STATUS-BELNR AND
GJAHR = ZSDSV_COL_STATUS-GJAHR AND
BUZEI = ZSDSV_COL_STATUS-BUZEI AND
SEQ = ZSDSV_COL_STATUS-SEQ AND
SUB_SEQ = ZSDSV_COL_STATUS-SUB_SEQ .
ZSDSV_COL_STATUS-MANDT =
ZSDSFIT038-MANDT .
ZSDSV_COL_STATUS-DATA_TYPE =
ZSDSFIT038-DATA_TYPE .
ZSDSV_COL_STATUS-BUKRS =
ZSDSFIT038-BUKRS .
ZSDSV_COL_STATUS-BELNR =
ZSDSFIT038-BELNR .
ZSDSV_COL_STATUS-GJAHR =
ZSDSFIT038-GJAHR .
ZSDSV_COL_STATUS-BUZEI =
ZSDSFIT038-BUZEI .
ZSDSV_COL_STATUS-SEQ =
ZSDSFIT038-SEQ .
ZSDSV_COL_STATUS-SUB_SEQ =
ZSDSFIT038-SUB_SEQ .
ZSDSV_COL_STATUS-VBELN_VF =
ZSDSFIT038-VBELN_VF .
ZSDSV_COL_STATUS-BILLPL_NO =
ZSDSFIT038-BILLPL_NO .
ZSDSV_COL_STATUS-BILLPL_DATE =
ZSDSFIT038-BILLPL_DATE .
ZSDSV_COL_STATUS-PERNR =
ZSDSFIT038-PERNR .
ZSDSV_COL_STATUS-WORK_DATE =
ZSDSFIT038-WORK_DATE .
ZSDSV_COL_STATUS-KUNNR =
ZSDSFIT038-KUNNR .
ZSDSV_COL_STATUS-UMSKZ =
ZSDSFIT038-UMSKZ .
ZSDSV_COL_STATUS-XBLNR =
ZSDSFIT038-XBLNR .
ZSDSV_COL_STATUS-BLDAT =
ZSDSFIT038-BLDAT .
ZSDSV_COL_STATUS-BUDAT =
ZSDSFIT038-BUDAT .
ZSDSV_COL_STATUS-FAEDT =
ZSDSFIT038-FAEDT .
ZSDSV_COL_STATUS-WRBTR =
ZSDSFIT038-WRBTR .
ZSDSV_COL_STATUS-WAERS =
ZSDSFIT038-WAERS .
ZSDSV_COL_STATUS-DEDUCT_AMT =
ZSDSFIT038-DEDUCT_AMT .
ZSDSV_COL_STATUS-PAYNO =
ZSDSFIT038-PAYNO .
ZSDSV_COL_STATUS-BRNCH =
ZSDSFIT038-BRNCH .
ZSDSV_COL_STATUS-BAL_AMT =
ZSDSFIT038-BAL_AMT .
ZSDSV_COL_STATUS-EXPS_AMT =
ZSDSFIT038-EXPS_AMT .
ZSDSV_COL_STATUS-AUFNR_EXPS =
ZSDSFIT038-AUFNR_EXPS .
ZSDSV_COL_STATUS-WHT_AMT =
ZSDSFIT038-WHT_AMT .
ZSDSV_COL_STATUS-FEE =
ZSDSFIT038-FEE .
ZSDSV_COL_STATUS-AUFNR_FEE =
ZSDSFIT038-AUFNR_FEE .
ZSDSV_COL_STATUS-RECEIVED_AMT =
ZSDSFIT038-RECEIVED_AMT .
ZSDSV_COL_STATUS-RETENTION =
ZSDSFIT038-RETENTION .
ZSDSV_COL_STATUS-INCOME_AMT =
ZSDSFIT038-INCOME_AMT .
ZSDSV_COL_STATUS-CASH_CON =
ZSDSFIT038-CASH_CON .
ZSDSV_COL_STATUS-ADV_AMT =
ZSDSFIT038-ADV_AMT .
ZSDSV_COL_STATUS-PAYIN_AMT =
ZSDSFIT038-PAYIN_AMT .
ZSDSV_COL_STATUS-REMAIN_AMT =
ZSDSFIT038-REMAIN_AMT .
ZSDSV_COL_STATUS-REMAIN_C_AMT =
ZSDSFIT038-REMAIN_C_AMT .
ZSDSV_COL_STATUS-KOSTL =
ZSDSFIT038-KOSTL .
ZSDSV_COL_STATUS-PRCTR =
ZSDSFIT038-PRCTR .
ZSDSV_COL_STATUS-HBKID =
ZSDSFIT038-HBKID .
ZSDSV_COL_STATUS-HKTID =
ZSDSFIT038-HKTID .
ZSDSV_COL_STATUS-PYMT_METHOD =
ZSDSFIT038-PYMT_METHOD .
ZSDSV_COL_STATUS-ACTION_TYPE =
ZSDSFIT038-ACTION_TYPE .
ZSDSV_COL_STATUS-STATUS =
ZSDSFIT038-STATUS .
ZSDSV_COL_STATUS-REMARK =
ZSDSFIT038-REMARK .
ZSDSV_COL_STATUS-PAYMENT_DATE =
ZSDSFIT038-PAYMENT_DATE .
ZSDSV_COL_STATUS-RECEIVED_DATE =
ZSDSFIT038-RECEIVED_DATE .
ZSDSV_COL_STATUS-RECEIPT_NO =
ZSDSFIT038-RECEIPT_NO .
ZSDSV_COL_STATUS-BANK_DATE =
ZSDSFIT038-BANK_DATE .
ZSDSV_COL_STATUS-CHEQUE_NO =
ZSDSFIT038-CHEQUE_NO .
ZSDSV_COL_STATUS-BANKN =
ZSDSFIT038-BANKN .
ZSDSV_COL_STATUS-BANKL =
ZSDSFIT038-BANKL .
ZSDSV_COL_STATUS-TRANF_NO =
ZSDSFIT038-TRANF_NO .
ZSDSV_COL_STATUS-BANKK =
ZSDSFIT038-BANKK .
ZSDSV_COL_STATUS-ZBANK_ITEM =
ZSDSFIT038-ZBANK_ITEM .
ZSDSV_COL_STATUS-VBELN =
ZSDSFIT038-VBELN .
ZSDSV_COL_STATUS-FKDAT =
ZSDSFIT038-FKDAT .
ZSDSV_COL_STATUS-CHEQUE_DATE =
ZSDSFIT038-CHEQUE_DATE .
ZSDSV_COL_STATUS-FOLLOW_DATE =
ZSDSFIT038-FOLLOW_DATE .
ZSDSV_COL_STATUS-PO_REF =
ZSDSFIT038-PO_REF .
ZSDSV_COL_STATUS-BILLPL_AMT =
ZSDSFIT038-BILLPL_AMT .
ZSDSV_COL_STATUS-DOCUMENT_STATUS =
ZSDSFIT038-DOCUMENT_STATUS .
ZSDSV_COL_STATUS-INV_STATUS =
ZSDSFIT038-INV_STATUS .
ZSDSV_COL_STATUS-REMARK_VENDOR =
ZSDSFIT038-REMARK_VENDOR .
ZSDSV_COL_STATUS-REASON_VENDOR =
ZSDSFIT038-REASON_VENDOR .
ZSDSV_COL_STATUS-BILLING_CYCLE =
ZSDSFIT038-BILLING_CYCLE .
ZSDSV_COL_STATUS-COLLECTION_CYCLE =
ZSDSFIT038-COLLECTION_CYCLE .
ZSDSV_COL_STATUS-AWB_NO =
ZSDSFIT038-AWB_NO .
ZSDSV_COL_STATUS-DELETE_FLAG =
ZSDSFIT038-DELETE_FLAG .
ZSDSV_COL_STATUS-DELETE_DATE =
ZSDSFIT038-DELETE_DATE .
ZSDSV_COL_STATUS-ERDAT =
ZSDSFIT038-ERDAT .
ZSDSV_COL_STATUS-ERZMT =
ZSDSFIT038-ERZMT .
ZSDSV_COL_STATUS-UPDATE_BY =
ZSDSFIT038-UPDATE_BY .
ZSDSV_COL_STATUS-UPDATE_ON =
ZSDSFIT038-UPDATE_ON .
ZSDSV_COL_STATUS-UPDATE_TIME =
ZSDSFIT038-UPDATE_TIME .
ZSDSV_COL_STATUS-ERNAM_HIST =
ZSDSFIT038-ERNAM_HIST .
ZSDSV_COL_STATUS-ERDAT_HIST =
ZSDSFIT038-ERDAT_HIST .
ZSDSV_COL_STATUS-ERZMT_HIST =
ZSDSFIT038-ERZMT_HIST .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZSDSV_COL_STATUS USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZSDSV_COL_STATUS-DATA_TYPE TO
ZSDSFIT038-DATA_TYPE .
MOVE ZSDSV_COL_STATUS-BUKRS TO
ZSDSFIT038-BUKRS .
MOVE ZSDSV_COL_STATUS-BELNR TO
ZSDSFIT038-BELNR .
MOVE ZSDSV_COL_STATUS-GJAHR TO
ZSDSFIT038-GJAHR .
MOVE ZSDSV_COL_STATUS-BUZEI TO
ZSDSFIT038-BUZEI .
MOVE ZSDSV_COL_STATUS-SEQ TO
ZSDSFIT038-SEQ .
MOVE ZSDSV_COL_STATUS-SUB_SEQ TO
ZSDSFIT038-SUB_SEQ .
MOVE ZSDSV_COL_STATUS-MANDT TO
ZSDSFIT038-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZSDSFIT038'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZSDSFIT038 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZSDSFIT038'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
