*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZSDSV_ZSDSFIC031................................*
FORM GET_DATA_ZSDSV_ZSDSFIC031.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZSDSFIC031 WHERE
(VIM_WHERETAB) .
    CLEAR ZSDSV_ZSDSFIC031 .
ZSDSV_ZSDSFIC031-MANDT =
ZSDSFIC031-MANDT .
ZSDSV_ZSDSFIC031-BANK_CODE =
ZSDSFIC031-BANK_CODE .
ZSDSV_ZSDSFIC031-SERVICE_DESC =
ZSDSFIC031-SERVICE_DESC .
ZSDSV_ZSDSFIC031-MAX_PAYMENT =
ZSDSFIC031-MAX_PAYMENT .
ZSDSV_ZSDSFIC031-LIMIT_AMOUNT =
ZSDSFIC031-LIMIT_AMOUNT .
ZSDSV_ZSDSFIC031-WAERS =
ZSDSFIC031-WAERS .
<VIM_TOTAL_STRUC> = ZSDSV_ZSDSFIC031.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZSDSV_ZSDSFIC031 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZSDSV_ZSDSFIC031.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZSDSV_ZSDSFIC031-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZSDSFIC031 WHERE
  BANK_CODE = ZSDSV_ZSDSFIC031-BANK_CODE .
    IF SY-SUBRC = 0.
    DELETE ZSDSFIC031 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZSDSFIC031 WHERE
  BANK_CODE = ZSDSV_ZSDSFIC031-BANK_CODE .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZSDSFIC031.
    ENDIF.
ZSDSFIC031-MANDT =
ZSDSV_ZSDSFIC031-MANDT .
ZSDSFIC031-BANK_CODE =
ZSDSV_ZSDSFIC031-BANK_CODE .
ZSDSFIC031-SERVICE_DESC =
ZSDSV_ZSDSFIC031-SERVICE_DESC .
ZSDSFIC031-MAX_PAYMENT =
ZSDSV_ZSDSFIC031-MAX_PAYMENT .
ZSDSFIC031-LIMIT_AMOUNT =
ZSDSV_ZSDSFIC031-LIMIT_AMOUNT .
ZSDSFIC031-WAERS =
ZSDSV_ZSDSFIC031-WAERS .
    IF SY-SUBRC = 0.
    UPDATE ZSDSFIC031 ##WARN_OK.
    ELSE.
    INSERT ZSDSFIC031 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZSDSV_ZSDSFIC031-UPD_FLAG,
STATUS_ZSDSV_ZSDSFIC031-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZSDSV_ZSDSFIC031.
  SELECT SINGLE * FROM ZSDSFIC031 WHERE
BANK_CODE = ZSDSV_ZSDSFIC031-BANK_CODE .
ZSDSV_ZSDSFIC031-MANDT =
ZSDSFIC031-MANDT .
ZSDSV_ZSDSFIC031-BANK_CODE =
ZSDSFIC031-BANK_CODE .
ZSDSV_ZSDSFIC031-SERVICE_DESC =
ZSDSFIC031-SERVICE_DESC .
ZSDSV_ZSDSFIC031-MAX_PAYMENT =
ZSDSFIC031-MAX_PAYMENT .
ZSDSV_ZSDSFIC031-LIMIT_AMOUNT =
ZSDSFIC031-LIMIT_AMOUNT .
ZSDSV_ZSDSFIC031-WAERS =
ZSDSFIC031-WAERS .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZSDSV_ZSDSFIC031 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZSDSV_ZSDSFIC031-BANK_CODE TO
ZSDSFIC031-BANK_CODE .
MOVE ZSDSV_ZSDSFIC031-MANDT TO
ZSDSFIC031-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZSDSFIC031'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZSDSFIC031 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZSDSFIC031'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
