FUNCTION-POOL ZSDSFI01.                     "MESSAGE-ID ..

* INCLUDE LZSDSFI01D...                      " Local class definition

DATA : GC_ADDITIONAL_FILED TYPE C LENGTH 10 VALUE 'ZSDSFIS007'.

CONSTANTS : BEGIN OF GC_CON,
              DOC_TYPE                TYPE BLART       VALUE 'K1',
              CREDIT                  TYPE C           VALUE 'H',
              DEBIT                   TYPE C           VALUE 'S',
              ADDITIONAL_FILED        TYPE C LENGTH 10 VALUE 'ZSDSFIS007',
              ADDITIONAL_FILED_VENDOR TYPE C LENGTH 10 VALUE 'ZSDSFIS015',
              ADDITIONAL_FILED_V2     TYPE C LENGTH 10 VALUE 'ZSDSFIS016',
              BRNCH                   TYPE C LENGTH 4  VALUE '0000',
              BUPLA                   TYPE C LENGTH 4  VALUE '0000',
              WT_TYPE                 TYPE C LENGTH 2  VALUE '11',
              E                       TYPE C           VALUE 'E',
              S                       TYPE C           VALUE 'S',
              M                       TYPE C           VALUE 'M',
              IX                      TYPE C LENGTH 2  VALUE 'IX',
              STAR                    TYPE C           VALUE '*',
              MWVS                    TYPE C LENGTH 4  VALUE 'MWVS',
              VST                     TYPE C LENGTH 3  VALUE 'VST',
              40                      TYPE C LENGTH 2  VALUE '40',
              50                      TYPE C LENGTH 2  VALUE '50',
              31                      TYPE C LENGTH 2  VALUE '31',
              11                      TYPE C LENGTH 2  VALUE '11',
              03                      TYPE C LENGTH 2  VALUE '03',
              EGK                     TYPE C LENGTH 3  VALUE 'EGK',
              THB                     TYPE C LENGTH 3  VALUE 'THB',
              DIT                     TYPE C LENGTH 10 VALUE '0000001001',
              MIRO                    TYPE C LENGTH 4  VALUE 'MIRO',
              TAXTH                   TYPE C LENGTH 5  VALUE 'TAXTH',
              TX                      TYPE C LENGTH 2  VALUE 'TX',
              TH                      TYPE C LENGTH 2  VALUE 'TH',
              BANGKOK                 TYPE C LENGTH 9  VALUE 'กรุงเทพฯ',
              P109999                 TYPE C LENGTH 10  VALUE '0019999999',
              F43                     TYPE C LENGTH 3  VALUE 'F43',
              APVI                    TYPE C LENGTH 4  VALUE 'APVI',
              KR                      TYPE C LENGTH 2  VALUE 'KR',
              DN                      TYPE C LENGTH 2  VALUE 'DN',
              OT03                    TYPE C LENGTH 4  VALUE 'OT03',
              BCOD                    TYPE C LENGTH 4  VALUE 'BCOD',
              TXID                    TYPE C LENGTH 4  VALUE 'TXID',
              103                     TYPE C LENGTH 3  VALUE '103',
              RE                      TYPE C LENGTH 2  VALUE 'RE',
              VX                      TYPE C LENGTH 2  VALUE 'VX',
              ADMIN_PROFIT            TYPE C LENGTH 10 VALUE '0010999900',
            END OF GC_CON.
