*&---------------------------------------------------------------------*
*& Include          ZSDSFIR0230_TOP
*&---------------------------------------------------------------------*
*----------------------------------------------------------------------*
* MACROS
*----------------------------------------------------------------------*
DEFINE MC_SHOW_PROGRESS.
  IF sy-batch IS INITIAL.
*   Show progress online
    CALL FUNCTION 'SAPGUI_PROGRESS_INDICATOR'
      EXPORTING
        percentage = &1 ##NUMBER_OK
        text       = &2.
  ELSE.
*   Show message step in background
    MESSAGE i000(38) WITH &2 space space space.
  ENDIF.
END-OF-DEFINITION.
DEFINE %FCAT.
  <fcat>-scrtext_s = <fcat>-scrtext_m =
  <fcat>-scrtext_l = <fcat>-coltext =
  <fcat>-seltext   = <fcat>-tooltip =
  <fcat>-reptext   = &1.
END-OF-DEFINITION.
*----------------------------------------------------------------------*
* TABLES
*----------------------------------------------------------------------*
TABLES:
  KNA1,
  VBRK,
  VBAK,
  LIKP,
  PRPS,
  SSCRFIELDS.
*----------------------------------------------------------------------*
* TYPES
*----------------------------------------------------------------------*
TYPES:

  BEGIN OF TS_ZSTATUS,
    VALUE TYPE ZSDSFIT027-ZSTATUS,
    TEXT  TYPE DD07T-DDTEXT,
  END OF TS_ZSTATUS,
  TT_ZSTATUS  TYPE STANDARD TABLE OF TS_ZSTATUS,
  TT_STAT_ACT TYPE STANDARD TABLE OF ZSDSFIC028,
  BEGIN OF TS_SN_IV,
    BILNO       TYPE VBRK-VBELN,
    SO          TYPE VBAK-VBELN,
    BELNR       TYPE BKPF-BELNR,
    XBLNR       TYPE BKPF-XBLNR,
    PSPHI       TYPE PRPS-PSPHI,
    POST1       TYPE PROJ-POST1,
    KUNAG       TYPE VBRK-KUNAG,
    KUNAG_NM    TYPE KNA1-NAME1,
    KUNRG       TYPE VBRK-KUNRG,   "CH01 420000161+
    KUNRG_NM    TYPE KNA1-NAME1,   "CH01 420000161+
    FKDAT       TYPE VBRK-FKDAT,
    ZTERM       TYPE VBRK-ZTERM,
    VKBUR       TYPE VBAK-VKBUR,
    NETWR       TYPE VBRK-NETWR,
    MWSBK       TYPE VBRK-MWSBK,
    TOTAL       TYPE VBRK-NETWR,
    WAERK       TYPE VBRK-WAERK,
    VBELN       TYPE ZSDSFIT027-VBELN,
    ZCHECK      TYPE ZSDSFIT027-ZCHECK,
    ZSTATUS     TYPE ZSDSFIT027-ZSTATUS,
    ZSTATUS_TX  TYPE DD07T-DDTEXT,
    ZBLLST      TYPE ZSDSFIT027-ZBLLST,
    ZCLLST      TYPE ZSDSFIT027-ZCLLST,
    ZREMARK     TYPE ZSDSFIT027-ZREMARK,
    ZADMIN      TYPE ZSDSFIT027-ZADMIN,
    ZSEND_N     TYPE ZSDSFIT027-ZSEND_N,
    ZSEND_D     TYPE ZSDSFIT027-ZSEND_D,
    ZSEND_T     TYPE ZSDSFIT027-ZSEND_T,
    ZRCVD_N     TYPE ZSDSFIT027-ZRCVD_N,
    ZRCVD_D     TYPE ZSDSFIT027-ZRCVD_D,
    ZRCVD_T     TYPE ZSDSFIT027-ZRCVD_T,
    ZRCVD_PERNR TYPE ZSDSFIT027-ZRCVD_PERNR,    "CH05+
    SENT        TYPE FLAG,
    REJECTED    TYPE FLAG,
    MAIN        TYPE FLAG,
    FIELD_STYLE TYPE LVC_T_STYL,
  END OF TS_SN_IV,
  TT_SN_IV TYPE  STANDARD TABLE OF TS_SN_IV,
  BEGIN OF TS_RC_IV,
    KUNAG       TYPE VBRK-KUNAG,
    KUNAG_NM    TYPE KNA1-NAME1,
    STAT_ACT01  TYPE FLAG,
    STAT_ACT02  TYPE FLAG,
    STAT_ACT03  TYPE FLAG,
    STAT_ACT04  TYPE FLAG,
    STAT_ACT05  TYPE FLAG,
    ZBLLST      TYPE ZSDSFIT027-ZBLLST,
    VBELN       TYPE ZSDSFIT027-VBELN,
    BELNR       TYPE BKPF-BELNR,
    XBLNR       TYPE BKPF-XBLNR,
    PSPHI       TYPE PRPS-PSPHI,
    POST1       TYPE PROJ-POST1,
    ZBLLCYL     TYPE ZSDSFIC024-ZBLLCYL,
    ZBLLCOL     TYPE ZSDSFIC024-ZBLLCOL,
    ZREMARK     TYPE ZSDSFIT027-ZREMARK,
    KUNRG       TYPE VBRK-KUNRG,
    KUNRG_NM    TYPE KNA1-NAME1,
    ZTERM       TYPE VBRK-ZTERM,
    FKDAT       TYPE VBRK-FKDAT,
    NETDU       TYPE FAEDE-NETDT,
    NETWR       TYPE VBRK-NETWR,
    MWSBK       TYPE VBRK-MWSBK,
    TOTAL       TYPE VBRK-NETWR,
    WAERK       TYPE VBRK-WAERK,
    ADV_AMT     TYPE BSID_VIEW-DMBTR,
    VKBUR       TYPE VBAK-VKBUR,
    ZADMIN      TYPE ZSDSFIT027-ZADMIN,
    ZSEND_N     TYPE ZSDSFIT027-ZSEND_N,
    ZSEND_D     TYPE ZSDSFIT027-ZSEND_D,
    ZSEND_T     TYPE ZSDSFIT027-ZSEND_T,
    ZRCVD_N     TYPE ZSDSFIT027-ZRCVD_N,
    ZRCVD_D     TYPE ZSDSFIT027-ZRCVD_D,
    ZRCVD_T     TYPE ZSDSFIT027-ZRCVD_T,
    ZRCVD_PERNR TYPE ZSDSFIT027-ZRCVD_PERNR,    "CH05+
    ZCHECK      TYPE ZSDSFIT027-ZCHECK,
    RECEIVED    TYPE FLAG,
    REJECTED    TYPE FLAG,
    ZSTATUS     TYPE ZSDSFIT027-ZSTATUS,
    ZSTATUS_TX  TYPE DD07T-DDTEXT,
  END OF TS_RC_IV,
  TT_RC_IV TYPE  STANDARD TABLE OF TS_RC_IV,
  BEGIN OF TS_DP_IV,
    KUNAG        TYPE VBRK-KUNAG,
    KUNAG_NM     TYPE KNA1-NAME1,
    ZBLLST       TYPE ZSDSFIT027-ZBLLST,
    ZSTAT_ACT_TX TYPE ZSDSFIC028-FLD_DESC,
    VBELN        TYPE ZSDSFIT027-VBELN,
    BELNR        TYPE BKPF-BELNR,
    XBLNR        TYPE BKPF-XBLNR,
    PSPHI        TYPE PRPS-PSPHI,
    POST1        TYPE PROJ-POST1,
    ZBLLCYL      TYPE ZSDSFIC024-ZBLLCYL,
    ZBLLCOL      TYPE ZSDSFIC024-ZBLLCOL,
    ZCLLST       TYPE ZSDSFIT027-ZCLLST,
    ZREMARK      TYPE ZSDSFIT027-ZREMARK,
    KUNRG        TYPE VBRK-KUNRG,
    KUNRG_NM     TYPE KNA1-NAME1,
    ZTERM        TYPE VBRK-ZTERM,
    FKDAT        TYPE VBRK-FKDAT,
    NETDU        TYPE FAEDE-NETDT,
    NETWR        TYPE VBRK-NETWR,
    MWSBK        TYPE VBRK-MWSBK,
    WAERK        TYPE VBRK-WAERK,
    TOTAL        TYPE VBRK-NETWR,
    ADV_AMT      TYPE BSID_VIEW-DMBTR,
    VKBUR        TYPE VBAK-VKBUR,
    ZADMIN       TYPE ZSDSFIT027-ZADMIN,
    ZSEND_N      TYPE ZSDSFIT027-ZSEND_N,
    ZSEND_D      TYPE ZSDSFIT027-ZSEND_D,
    ZSEND_T      TYPE ZSDSFIT027-ZSEND_T,
    ZRCVD_N      TYPE ZSDSFIT027-ZRCVD_N,
    ZRCVD_D      TYPE ZSDSFIT027-ZRCVD_D,
    ZRCVD_T      TYPE ZSDSFIT027-ZRCVD_T,
    ZRCVD_PERNR TYPE ZSDSFIT027-ZRCVD_PERNR,    "CH05+
    ZCHECK       TYPE ZSDSFIT027-ZCHECK,
    SENT         TYPE FLAG,
    RECEIVED     TYPE FLAG,
    REJECTED     TYPE FLAG,
    ZSTATUS      TYPE ZSDSFIT027-ZSTATUS,
    ZSTATUS_TX   TYPE DD07T-DDTEXT,
    ZSTAT_ACT    TYPE ZSDSFIT027-ZSTAT_ACT,
  END OF TS_DP_IV,
  TT_DP_IV TYPE  STANDARD TABLE OF TS_DP_IV,
  BEGIN OF TS_PJ,
    DO           TYPE LIKP-VBELN,
    SO           TYPE VBAK-VBELN,
    BILNO        TYPE VBRK-VBELN, "CH01 420000161+
    PSPHI        TYPE PRPS-PSPHI,
    POST1        TYPE PROJ-POST1,
    KUNAG        TYPE LIKP-KUNAG,
    KUNAG_NM     TYPE KNA1-NAME1,
    KUNRG        TYPE VBRK-KUNRG,  "CH01 420000161+
    KUNRG_NM     TYPE KNA1-NAME1,  "CH01 420000161+
    ZSTAT_ACT_TX TYPE ZSDSFIC028-FLD_DESC,
    STAT_ACT01   TYPE FLAG,
    STAT_ACT02   TYPE FLAG,
    STAT_ACT03   TYPE FLAG,
    STAT_ACT04   TYPE FLAG,
    STAT_ACT05   TYPE FLAG,
    LFDAT        TYPE LIKP-LFDAT,
    ZSTATUS      TYPE ZSDSFIT028-ZSTATUS,
    ZSTATUS_TX   TYPE DD07T-DDTEXT,
    ZTERM        TYPE VBKD-ZTERM,
    VKBUR        TYPE LIPS-VKBUR,
    NETWR        TYPE VBAP-NETWR,
    MWSBP        TYPE VBAP-MWSBP,
    TOTAL        TYPE VBAP-NETWR,
    VBELN        TYPE ZSDSFIT028-VBELN,
    ZCHECK       TYPE ZSDSFIT028-ZCHECK,
    ZADMIN       TYPE ZSDSFIT028-ZADMIN,
    ZSEND_N      TYPE ZSDSFIT028-ZSEND_N,
    ZSEND_D      TYPE ZSDSFIT028-ZSEND_D,
    ZSEND_T      TYPE ZSDSFIT028-ZSEND_T,
    ZRCVD_N      TYPE ZSDSFIT028-ZRCVD_N,
    ZRCVD_D      TYPE ZSDSFIT028-ZRCVD_D,
    ZRCVD_T      TYPE ZSDSFIT028-ZRCVD_T,
    SENT         TYPE FLAG,
    RECEIVED     TYPE FLAG,
    REJECTED     TYPE FLAG,
  END OF TS_PJ,
  TT_PJ TYPE STANDARD TABLE OF TS_PJ.

*----------------------------------------------------------------------*
* CONSTANTS
*----------------------------------------------------------------------*
CONSTANTS:
  GC_TCODE           TYPE  SY-TCODE     VALUE 'ZSDSFI013',
  GC_TRUE            TYPE FLAG          VALUE 'X',
  GC_DOMNAME_ZSTATUS TYPE DD07T-DOMNAME VALUE 'ZSDSDM_FI_INVSTAT',
  BEGIN OF GC_ZCHECK,
    SENT     TYPE ZSDSFIT027-ZCHECK VALUE '1',
    RECEIVED TYPE ZSDSFIT027-ZCHECK VALUE '2',
    REJECTED TYPE ZSDSFIT027-ZCHECK VALUE 'X',
  END OF GC_ZCHECK,
  BEGIN OF GC_EXEC_TY,
    SN_IV TYPE CHAR2 VALUE 'I1',
    RC_IV TYPE CHAR2 VALUE 'I2',
    DP_IV TYPE CHAR2 VALUE 'I3',
    SN_PJ TYPE CHAR2 VALUE 'P1',
    RC_PJ TYPE CHAR2 VALUE 'P2',
    DP_PJ TYPE CHAR2 VALUE 'P3',
  END OF GC_EXEC_TY,
  GC_GBSTK_COMPLETE TYPE VBRK-GBSTK VALUE 'C',
  GC_SOLD_TO        TYPE VBPA-PARVW VALUE 'AG',
  GC_PAYER          TYPE VBPA-PARVW VALUE 'RG'.
*----------------------------------------------------------------------*
* RANGES
*----------------------------------------------------------------------*
DATA: GR_BANK_VENDOR    TYPE RANGE OF ZSDSFIC028-STAT_ACT ##NEEDED,
      GR_FKART_NO_FIDOC TYPE RANGE OF VBRK-FKART          ##NEEDED.
*----------------------------------------------------------------------*
* INTERNAL TABLES
*----------------------------------------------------------------------*
DATA:
  GT_SN_IV     TYPE  TT_SN_IV   ##NEEDED,
  GT_SN_IV_OLD TYPE  TT_SN_IV   ##NEEDED,
  GT_RC_IV     TYPE  TT_RC_IV   ##NEEDED,
  GT_RC_IV_OLD TYPE  TT_RC_IV   ##NEEDED,
  GT_DP_IV     TYPE  TT_DP_IV   ##NEEDED,
  GT_PJ        TYPE  TT_PJ      ##NEEDED,
  GT_PJ_OLD    TYPE  TT_PJ      ##NEEDED,
  GT_ZSTATUS   TYPE  TT_ZSTATUS ##NEEDED,
  GT_STAT_ACT  TYPE TT_STAT_ACT ##NEEDED.
*----------------------------------------------------------------------*
* VARIABLE
*----------------------------------------------------------------------*
DATA:
  GF_EXEC_TY TYPE  CHAR2       ##NEEDED,
  GF_EDIT    TYPE  CHAR1       ##NEEDED.
*----------------------------------------------------------------------*
* ALV VARIABLES
*----------------------------------------------------------------------*
CONSTANTS:
  GC_HEADER_HEIGHT_1 TYPE  I                VALUE 10,
  GC_ALV_HEIGHT_1    TYPE  I                VALUE 90.
*----------------------------------------------------------------------*
* SELECTION-SCREEN
*----------------------------------------------------------------------*
* Text-s01: Customer Selection
SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-S01.
  SELECT-OPTIONS:
    S_KUNNR FOR KNA1-KUNNR ,
    S_BUKRS FOR VBRK-BUKRS OBLIGATORY NO-EXTENSION NO INTERVALS DEFAULT 1000.
SELECTION-SCREEN END OF BLOCK B1.

* Text-s02: Sales Document Selection
SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME TITLE TEXT-S02.
  SELECT-OPTIONS:
    S_FKDAT FOR VBRK-FKDAT MODIF ID IV,
    S_BILNO FOR VBRK-VBELN MODIF ID IV,
    S_SO    FOR VBAK-VBELN,
    S_LFDAT FOR LIKP-LFDAT MODIF ID PJ,
    S_DO    FOR LIKP-VBELN MODIF ID PJ,
    S_PSPHI FOR PRPS-PSPHI MODIF ID PJ,
    S_ERNAM FOR VBRK-ERNAM.
  SELECTION-SCREEN SKIP 1.
  SELECT-OPTIONS:
    S_VKORG FOR VBRK-VKORG OBLIGATORY DEFAULT 1000 MEMORY ID VKO,
    S_VTWEG FOR VBRK-VTWEG,
    S_SPART FOR VBRK-SPART,
    S_VKGRP FOR VBAK-VKGRP,
    S_VKBUR FOR VBAK-VKBUR .
  PARAMETERS:
    P_INC_RC AS CHECKBOX MODIF ID RC,
    P_INC_RJ AS CHECKBOX MODIF ID RC.
SELECTION-SCREEN END OF BLOCK B2.
* TEXT-S04: Personal ID Infomation
SELECTION-SCREEN BEGIN OF BLOCK B21 WITH FRAME TITLE TEXT-S04.
  PARAMETERS:
    P_PERNR TYPE PA0002-PERNR MATCHCODE OBJECT ZSDSH_PERNR.
SELECTION-SCREEN END OF BLOCK B21.


* Text-s03: Operation Selection
SELECTION-SCREEN BEGIN OF BLOCK B3 WITH FRAME TITLE TEXT-S03.
  PARAMETERS:
    RB_SN_IV RADIOBUTTON GROUP R1 DEFAULT 'X' USER-COMMAND Z1,
    RB_RC_IV RADIOBUTTON GROUP R1,
    RB_DP_IV RADIOBUTTON GROUP R1,
    RB_SN_PJ RADIOBUTTON GROUP R1,
    RB_RC_PJ RADIOBUTTON GROUP R1,
    RB_DP_PJ RADIOBUTTON GROUP R1.
SELECTION-SCREEN END OF BLOCK B3  .
