*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZSDSV_ZSDSFIT036................................*
FORM GET_DATA_ZSDSV_ZSDSFIT036.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZSDSFIT036 WHERE
(VIM_WHERETAB) .
    CLEAR ZSDSV_ZSDSFIT036 .
ZSDSV_ZSDSFIT036-MANDT =
ZSDSFIT036-MANDT .
ZSDSV_ZSDSFIT036-KUNNR =
ZSDSFIT036-KUNNR .
ZSDSV_ZSDSFIT036-PSPHI =
ZSDSFIT036-PSPHI .
ZSDSV_ZSDSFIT036-STARTDATE =
ZSDSFIT036-STARTDATE .
ZSDSV_ZSDSFIT036-ENDDATE =
ZSDSFIT036-ENDDATE .
ZSDSV_ZSDSFIT036-SEQ =
ZSDSFIT036-SEQ .
ZSDSV_ZSDSFIT036-CREDIT_LIMIT =
ZSDSFIT036-CREDIT_LIMIT .
ZSDSV_ZSDSFIT036-ZTERM =
ZSDSFIT036-ZTERM .
ZSDSV_ZSDSFIT036-ZDEL_FLG =
ZSDSFIT036-ZDEL_FLG .
ZSDSV_ZSDSFIT036-ZCRT_DATE =
ZSDSFIT036-ZCRT_DATE .
ZSDSV_ZSDSFIT036-ZCRT_TIME =
ZSDSFIT036-ZCRT_TIME .
ZSDSV_ZSDSFIT036-ZCRT_USER =
ZSDSFIT036-ZCRT_USER .
ZSDSV_ZSDSFIT036-ZCRT_PGM =
ZSDSFIT036-ZCRT_PGM .
ZSDSV_ZSDSFIT036-ZUPD_DATE =
ZSDSFIT036-ZUPD_DATE .
ZSDSV_ZSDSFIT036-ZUPD_TIME =
ZSDSFIT036-ZUPD_TIME .
ZSDSV_ZSDSFIT036-ZUPD_USER =
ZSDSFIT036-ZUPD_USER .
ZSDSV_ZSDSFIT036-ZUPD_PGM =
ZSDSFIT036-ZUPD_PGM .
    SELECT SINGLE * FROM BUT000 WHERE
PARTNER = ZSDSFIT036-KUNNR .
    IF SY-SUBRC EQ 0.
ZSDSV_ZSDSFIT036-NAME_ORG1 =
BUT000-NAME_ORG1 .
    ENDIF.
<VIM_TOTAL_STRUC> = ZSDSV_ZSDSFIT036.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZSDSV_ZSDSFIT036 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZSDSV_ZSDSFIT036.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZSDSV_ZSDSFIT036-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZSDSFIT036 WHERE
  KUNNR = ZSDSV_ZSDSFIT036-KUNNR AND
  PSPHI = ZSDSV_ZSDSFIT036-PSPHI AND
  STARTDATE = ZSDSV_ZSDSFIT036-STARTDATE AND
  ENDDATE = ZSDSV_ZSDSFIT036-ENDDATE AND
  SEQ = ZSDSV_ZSDSFIT036-SEQ .
    IF SY-SUBRC = 0.
    DELETE ZSDSFIT036 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZSDSFIT036 WHERE
  KUNNR = ZSDSV_ZSDSFIT036-KUNNR AND
  PSPHI = ZSDSV_ZSDSFIT036-PSPHI AND
  STARTDATE = ZSDSV_ZSDSFIT036-STARTDATE AND
  ENDDATE = ZSDSV_ZSDSFIT036-ENDDATE AND
  SEQ = ZSDSV_ZSDSFIT036-SEQ .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZSDSFIT036.
    ENDIF.
ZSDSFIT036-MANDT =
ZSDSV_ZSDSFIT036-MANDT .
ZSDSFIT036-KUNNR =
ZSDSV_ZSDSFIT036-KUNNR .
ZSDSFIT036-PSPHI =
ZSDSV_ZSDSFIT036-PSPHI .
ZSDSFIT036-STARTDATE =
ZSDSV_ZSDSFIT036-STARTDATE .
ZSDSFIT036-ENDDATE =
ZSDSV_ZSDSFIT036-ENDDATE .
ZSDSFIT036-SEQ =
ZSDSV_ZSDSFIT036-SEQ .
ZSDSFIT036-CREDIT_LIMIT =
ZSDSV_ZSDSFIT036-CREDIT_LIMIT .
ZSDSFIT036-ZTERM =
ZSDSV_ZSDSFIT036-ZTERM .
ZSDSFIT036-ZDEL_FLG =
ZSDSV_ZSDSFIT036-ZDEL_FLG .
ZSDSFIT036-ZCRT_DATE =
ZSDSV_ZSDSFIT036-ZCRT_DATE .
ZSDSFIT036-ZCRT_TIME =
ZSDSV_ZSDSFIT036-ZCRT_TIME .
ZSDSFIT036-ZCRT_USER =
ZSDSV_ZSDSFIT036-ZCRT_USER .
ZSDSFIT036-ZCRT_PGM =
ZSDSV_ZSDSFIT036-ZCRT_PGM .
ZSDSFIT036-ZUPD_DATE =
ZSDSV_ZSDSFIT036-ZUPD_DATE .
ZSDSFIT036-ZUPD_TIME =
ZSDSV_ZSDSFIT036-ZUPD_TIME .
ZSDSFIT036-ZUPD_USER =
ZSDSV_ZSDSFIT036-ZUPD_USER .
ZSDSFIT036-ZUPD_PGM =
ZSDSV_ZSDSFIT036-ZUPD_PGM .
    IF SY-SUBRC = 0.
    UPDATE ZSDSFIT036 ##WARN_OK.
    ELSE.
    INSERT ZSDSFIT036 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZSDSV_ZSDSFIT036-UPD_FLAG,
STATUS_ZSDSV_ZSDSFIT036-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZSDSV_ZSDSFIT036.
  SELECT SINGLE * FROM ZSDSFIT036 WHERE
KUNNR = ZSDSV_ZSDSFIT036-KUNNR AND
PSPHI = ZSDSV_ZSDSFIT036-PSPHI AND
STARTDATE = ZSDSV_ZSDSFIT036-STARTDATE AND
ENDDATE = ZSDSV_ZSDSFIT036-ENDDATE AND
SEQ = ZSDSV_ZSDSFIT036-SEQ .
ZSDSV_ZSDSFIT036-MANDT =
ZSDSFIT036-MANDT .
ZSDSV_ZSDSFIT036-KUNNR =
ZSDSFIT036-KUNNR .
ZSDSV_ZSDSFIT036-PSPHI =
ZSDSFIT036-PSPHI .
ZSDSV_ZSDSFIT036-STARTDATE =
ZSDSFIT036-STARTDATE .
ZSDSV_ZSDSFIT036-ENDDATE =
ZSDSFIT036-ENDDATE .
ZSDSV_ZSDSFIT036-SEQ =
ZSDSFIT036-SEQ .
ZSDSV_ZSDSFIT036-CREDIT_LIMIT =
ZSDSFIT036-CREDIT_LIMIT .
ZSDSV_ZSDSFIT036-ZTERM =
ZSDSFIT036-ZTERM .
ZSDSV_ZSDSFIT036-ZDEL_FLG =
ZSDSFIT036-ZDEL_FLG .
ZSDSV_ZSDSFIT036-ZCRT_DATE =
ZSDSFIT036-ZCRT_DATE .
ZSDSV_ZSDSFIT036-ZCRT_TIME =
ZSDSFIT036-ZCRT_TIME .
ZSDSV_ZSDSFIT036-ZCRT_USER =
ZSDSFIT036-ZCRT_USER .
ZSDSV_ZSDSFIT036-ZCRT_PGM =
ZSDSFIT036-ZCRT_PGM .
ZSDSV_ZSDSFIT036-ZUPD_DATE =
ZSDSFIT036-ZUPD_DATE .
ZSDSV_ZSDSFIT036-ZUPD_TIME =
ZSDSFIT036-ZUPD_TIME .
ZSDSV_ZSDSFIT036-ZUPD_USER =
ZSDSFIT036-ZUPD_USER .
ZSDSV_ZSDSFIT036-ZUPD_PGM =
ZSDSFIT036-ZUPD_PGM .
    SELECT SINGLE * FROM BUT000 WHERE
PARTNER = ZSDSFIT036-KUNNR .
    IF SY-SUBRC EQ 0.
ZSDSV_ZSDSFIT036-NAME_ORG1 =
BUT000-NAME_ORG1 .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZSDSV_ZSDSFIT036-NAME_ORG1 .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZSDSV_ZSDSFIT036 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZSDSV_ZSDSFIT036-KUNNR TO
ZSDSFIT036-KUNNR .
MOVE ZSDSV_ZSDSFIT036-PSPHI TO
ZSDSFIT036-PSPHI .
MOVE ZSDSV_ZSDSFIT036-STARTDATE TO
ZSDSFIT036-STARTDATE .
MOVE ZSDSV_ZSDSFIT036-ENDDATE TO
ZSDSFIT036-ENDDATE .
MOVE ZSDSV_ZSDSFIT036-SEQ TO
ZSDSFIT036-SEQ .
MOVE ZSDSV_ZSDSFIT036-MANDT TO
ZSDSFIT036-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZSDSFIT036'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZSDSFIT036 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZSDSFIT036'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZSDSV_ZSDSFIT036 USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZSDSFIT036-MANDT =
ZSDSV_ZSDSFIT036-MANDT .
ZSDSFIT036-KUNNR =
ZSDSV_ZSDSFIT036-KUNNR .
ZSDSFIT036-PSPHI =
ZSDSV_ZSDSFIT036-PSPHI .
ZSDSFIT036-STARTDATE =
ZSDSV_ZSDSFIT036-STARTDATE .
ZSDSFIT036-ENDDATE =
ZSDSV_ZSDSFIT036-ENDDATE .
ZSDSFIT036-SEQ =
ZSDSV_ZSDSFIT036-SEQ .
ZSDSFIT036-CREDIT_LIMIT =
ZSDSV_ZSDSFIT036-CREDIT_LIMIT .
ZSDSFIT036-ZTERM =
ZSDSV_ZSDSFIT036-ZTERM .
ZSDSFIT036-ZDEL_FLG =
ZSDSV_ZSDSFIT036-ZDEL_FLG .
ZSDSFIT036-ZCRT_DATE =
ZSDSV_ZSDSFIT036-ZCRT_DATE .
ZSDSFIT036-ZCRT_TIME =
ZSDSV_ZSDSFIT036-ZCRT_TIME .
ZSDSFIT036-ZCRT_USER =
ZSDSV_ZSDSFIT036-ZCRT_USER .
ZSDSFIT036-ZCRT_PGM =
ZSDSV_ZSDSFIT036-ZCRT_PGM .
ZSDSFIT036-ZUPD_DATE =
ZSDSV_ZSDSFIT036-ZUPD_DATE .
ZSDSFIT036-ZUPD_TIME =
ZSDSV_ZSDSFIT036-ZUPD_TIME .
ZSDSFIT036-ZUPD_USER =
ZSDSV_ZSDSFIT036-ZUPD_USER .
ZSDSFIT036-ZUPD_PGM =
ZSDSV_ZSDSFIT036-ZUPD_PGM .
    SELECT SINGLE * FROM BUT000 WHERE
PARTNER = ZSDSFIT036-KUNNR .
    IF SY-SUBRC EQ 0.
ZSDSV_ZSDSFIT036-NAME_ORG1 =
BUT000-NAME_ORG1 .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZSDSV_ZSDSFIT036-NAME_ORG1 .
    ENDIF.
ENDFORM.
