*&---------------------------------------------------------------------*
*& Include          ZSDSFIR0750_TOP
*&---------------------------------------------------------------------*
*-----------------------------------------------------------------------
* T A B L E S
*-----------------------------------------------------------------------
TABLES : VBRK,
         BKPF,
         LIKP,
         LIPS,
         BSEG,
         VBPA,
         KNB1,
         ZSDSFIC027,
         ZSDSFIT040,
         SSCRFIELDS.
*-----------------------------------------------------------------------
* T Y P E S
*-----------------------------------------------------------------------
TYPES : BEGIN OF GY_RESULT,

          PIC_PERNR     TYPE ZSDSFIC027-PIC_PERNR,
          PIC_NAME1     TYPE TEXT80,
          VBELN_BILL    TYPE VBRK-VBELN,
          BUKRS         TYPE BKPF-BUKRS,
          BELNR         TYPE BKPF-BELNR,
          GJAHR         TYPE BKPF-GJAHR,
          BUZEI         TYPE BSID_VIEW-BUZEI,
          XBLNR         TYPE BSID_VIEW-XBLNR,
          XREF1         TYPE BSID_VIEW-XREF1, "CH04 420000219+
          KUNNR         TYPE BSID_VIEW-KUNNR,
          KUNNR_NAME1   TYPE KNA1-NAME1,
          BUSAB         TYPE KNB1-BUSAB,
          SGTXT         TYPE BSID_VIEW-SGTXT,
          POST1         TYPE PRPS-POST1,
          BSTKD         TYPE VBKD-BSTKD,
          INV_REMARK    TYPE TEXT40,
          VBELN_DO      TYPE LIKP-VBELN,
          RPDAT         TYPE SY-DATUM,
          BUDAT         TYPE BSID_VIEW-BUDAT,
          DUEDT1        TYPE SY-DATUM,
          NEW_DUEDT2    TYPE ZSDSFIT040-NEW_DUEDT2,
          NEW_DUEDT3    TYPE ZSDSFIT040-NEW_DUEDT3,
          INV_AGE       TYPE I,
          RNG_INV_AGE   TYPE TEXT20,
          OVDUE1        TYPE I,
          OVDUE2        TYPE I,
          OVDUE3        TYPE I,
          WITHIN_DUE1   TYPE TEXT20,
          RNG_OVDUE1    TYPE TEXT20,
          WITHIN_DUE2   TYPE TEXT20,
          RNG_OVDUE2    TYPE TEXT20,
          WITHIN_DUE3   TYPE TEXT20,
          RNG_OVDUE3    TYPE TEXT20,
          DMBTR         TYPE ZSDSFIT035-BILLPL_AMT,
          DMBTR_REMAIN  TYPE ZSDSFIT035-BILLPL_AMT,
          WAERS         TYPE T001-WAERS,
          HKONT_TX      TYPE TEXT30,
          VKGRP         TYPE VBRP-VKGRP,
          VKGRP_TX      TYPE TVGRT-BEZEI,
          VKBUR         TYPE VBRP-VKBUR,
          VKBUR_TX      TYPE TVKBT-BEZEI,
          BILLPL_NO     TYPE ZSDSFIT033-BILLPL_NO,
          BILLPL_DATE   TYPE ZSDSFIT033-BILLPL_DATE,
          ISSUE_LIST    TYPE ZSDSFIT040-ISSUE_LIST,
          ISSUE_LIST_TX TYPE DD07T-DDTEXT,
          FOLLOWDT      TYPE ZSDSFIT040-FOLLOWDT,
          TEXT1         TYPE TEXT50,       "CH04 420000332+
          TEXT2         TYPE TEXT50,       "CH04 420000332+
          TEXT3         TYPE TEXT50,       "CH04 420000332+
*    DETAIL1       TYPE ZSDSFIT040-DETAIL1, "CH04 420000332-
*    DETAIL2       TYPE ZSDSFIT040-DETAIL2, "CH04 420000332-
*    DETAIL3       TYPE ZSDSFIT040-DETAIL3, "CH04 420000332-
          SALEMAN       TYPE VBPA-PERNR,
          SALEMAN_NAME  TYPE TEXT80,
          ZTERM         TYPE BSID_VIEW-ZTERM,
          ZUONR         TYPE BSID_VIEW-ZUONR,
          UMSKZ         TYPE BSID_VIEW-UMSKZ,
          UPD_DATE      TYPE ZSDSFIT040-UPD_DATE,
          UPD_TIME      TYPE ZSDSFIT040-UPD_TIME,
          UPD_USER      TYPE ZSDSFIT040-UPD_USER,
          INDX          TYPE SY-TABIX,
          EXIST         TYPE FLAG,
          SEQNO         TYPE ZSDSFIT040-SEQNO,
          CHANGE_TX     TYPE FLAG,    "CH04 420000332
          CHECK         TYPE C,
        END OF GY_RESULT.


TYPES :
  BEGIN OF TS_KNA1,
    KUNNR TYPE KNA1-KUNNR,
    NAME1 TYPE KNA1-NAME1,
    XCPDK TYPE KNA1-XCPDK, "CH04 420000327+
  END OF TS_KNA1,
  TT_KNA1 TYPE SORTED TABLE OF TS_KNA1 WITH NON-UNIQUE KEY KUNNR.

  TYPES :
    BEGIN OF TS_KNA1_027,
    KUNNR     TYPE KNB1-KUNNR,
    BUSAB     TYPE KNB1-BUSAB,
    PIC_PERNR TYPE ZSDSFIC027-PIC_PERNR,
    FR_KUNNR  TYPE ZSDSFIC027-FR_KUNNR,
    TO_KUNNR  TYPE ZSDSFIC027-TO_KUNNR,
  END OF TS_KNA1_027,
  TT_KNA1_027 TYPE SORTED TABLE OF TS_KNA1_027 WITH NON-UNIQUE KEY KUNNR.

 TYPES :
  BEGIN OF TS_KNVV_027,
    KUNNR     TYPE KNVV-KUNNR,
    VKORG     TYPE KNVV-VKORG,
    VTWEG     TYPE KNVV-VTWEG,
    SPART     TYPE KNVV-SPART,
    VKBUR     TYPE KNVV-VKBUR,
    VKGRP     TYPE KNVV-VKGRP,
    PIC_PERNR TYPE ZSDSFIC027-PIC_PERNR,
    BUSAB     TYPE KNB1-BUSAB,
    FR_KUNNR  TYPE ZSDSFIC027-FR_KUNNR,
    TO_KUNNR  TYPE ZSDSFIC027-TO_KUNNR,
    FR_BUSAB  TYPE KNB1-BUSAB,
    TO_BUSAB  TYPE KNB1-BUSAB,
  END OF TS_KNVV_027,
  TT_KNVV_027 TYPE SORTED TABLE OF TS_KNVV_027 WITH NON-UNIQUE KEY KUNNR VKORG VTWEG SPART VKBUR VKGRP.

TYPES :
BEGIN OF TS_KNB1,
    KUNNR TYPE KNB1-KUNNR,
    BUKRS TYPE KNB1-BUKRS,
    BUSAB TYPE KNB1-BUSAB,
  END OF TS_KNB1,
  TT_KNB1 TYPE SORTED TABLE OF TS_KNB1 WITH NON-UNIQUE KEY KUNNR BUKRS.

TYPES :
BEGIN OF TS_BSEC,
    BUKRS  TYPE BSEC-BUKRS,
    BELNR  TYPE BSEC-BELNR,
    GJAHR  TYPE BSEC-GJAHR,
    BUZEI  TYPE BSEC-BUZEI,
    NATION TYPE ADRC-NATION,
    NAME1  TYPE ADRC-NAME1,
  END OF TS_BSEC,
  TT_BSEC TYPE SORTED TABLE OF TS_BSEC WITH NON-UNIQUE KEY BUKRS BELNR GJAHR BUZEI NATION.

  TYPES :
  BEGIN OF TS_CLEAR_DOC,
    BUKRS TYPE BSID_VIEW-BUKRS,
    REBZG TYPE BSID_VIEW-REBZG,
    REBZJ TYPE BSID_VIEW-REBZJ,
    REBZZ TYPE BSID_VIEW-REBZZ,
    GJAHR TYPE BSID_VIEW-GJAHR,
    BELNR TYPE BSID_VIEW-BELNR,
    BUZEI TYPE BSID_VIEW-BUZEI,
    SHKZG TYPE BSID_VIEW-SHKZG,
    DMBTR TYPE BSID_VIEW-DMBTR,
    AUGBL TYPE BSID_VIEW-AUGBL, "<<F36K909945++
    USED  TYPE FLAG,
  END OF TS_CLEAR_DOC,
  TT_CLEAR_DOC TYPE SORTED TABLE OF TS_CLEAR_DOC WITH NON-UNIQUE KEY BUKRS REBZG REBZJ REBZZ.

 TYPES :
  BEGIN OF TS_CLEAR_MGRTE,
    BUKRS          TYPE BSID_VIEW-BUKRS,
    XREF1          TYPE BSID_VIEW-XREF1,
    XBLNR          TYPE BSID_VIEW-XBLNR,
    GJAHR          TYPE BSID_VIEW-GJAHR,
    BELNR          TYPE BSID_VIEW-BELNR,
    BUZEI          TYPE BSID_VIEW-BUZEI,
    SHKZG          TYPE BSID_VIEW-SHKZG,
    UMSKZ          TYPE BSID_VIEW-UMSKZ,
    DMBTR          TYPE BSID_VIEW-DMBTR,
    USED           TYPE FLAG,
  END OF TS_CLEAR_MGRTE,
  TT_CLEAR_MGRTE     TYPE SORTED TABLE OF TS_CLEAR_MGRTE WITH NON-UNIQUE KEY BUKRS XREF1 GJAHR BELNR,
  TT_CLEAR_mgrte_CHK TYPE SORTED TABLE OF TS_CLEAR_MGRTE WITH NON-UNIQUE KEY BUKRS BELNR GJAHR BUZEI.

TYPES :
BEGIN OF TS_PA0002_PIC,
    PERNR TYPE PA0002-PERNR,
    VORNA TYPE PA0002-VORNA,
    NACHN TYPE PA0002-NACHN,
  END OF TS_PA0002_PIC,
  TT_PA0002_PIC TYPE SORTED TABLE OF TS_PA0002_PIC WITH NON-UNIQUE KEY PERNR.

  TYPES :
  BEGIN OF TS_PRPS,
    POSID TYPE PRPS-POSID,
    POST1 TYPE PRPS-POST1,
  END OF TS_PRPS,
  TT_PRPS TYPE SORTED TABLE OF TS_PRPS WITH NON-UNIQUE KEY POSID.

   TYPES :
  BEGIN OF TS_VBKD_SO,
    VBELN TYPE VBKD-VBELN,
    BSTKD TYPE VBKD-BSTKD,
  END OF TS_VBKD_SO,
  TT_VBKD_SO TYPE SORTED TABLE OF TS_VBKD_SO WITH NON-UNIQUE KEY VBELN.

 TYPES :
BEGIN OF TS_VBFA_INV_DO,
    VBELN TYPE VBFA-VBELN,
    VBELV TYPE VBFA-VBELV,
  END OF TS_VBFA_INV_DO,
  TT_VBFA_INV_DO TYPE SORTED TABLE OF TS_VBFA_INV_DO WITH NON-UNIQUE KEY VBELN,
  TT_040  TYPE SORTED TABLE OF ZSDSFIT040 WITH NON-UNIQUE KEY BUKRS BELNR GJAHR SEQNO,
  TT_024     TYPE SORTED TABLE OF ZSDSFIC024 WITH NON-UNIQUE KEY KUNNR.

  TYPES :
   BEGIN OF TS_BILLPL,
    BUKRS        TYPE ZSDSFIT033-BUKRS,
    BELNR        TYPE ZSDSFIT035-BELNR,
    GJAHR        TYPE ZSDSFIT035-GJAHR,
    BUZEI        TYPE ZSDSFIT035-BUZEI,
    BILLPL_NO    TYPE ZSDSFIT033-BILLPL_NO,
    BILLPL_DATE  TYPE ZSDSFIT033-BILLPL_DATE,
    BILLPL_PMTDT TYPE ZSDSFIT033-BILLPL_PMTDT,
    WORK_DATE    TYPE ZSDSFIT029-WORK_DATE, "CH02+
  END OF TS_BILLPL,
  TT_BILLPL  TYPE SORTED TABLE OF TS_BILLPL WITH NON-UNIQUE KEY BUKRS BELNR GJAHR BUZEI.

TYPES :
  BEGIN OF TS_SKAT,
    SAKNR TYPE SKAT-SAKNR,
    TXT20 TYPE SKAT-TXT20,
  END OF TS_SKAT,
  TT_SKAT TYPE SORTED TABLE OF TS_SKAT WITH NON-UNIQUE KEY SAKNR,
  BEGIN OF TS_T074T,
    SHBKZ TYPE T074T-SHBKZ,
    LTEXT TYPE T074T-LTEXT,
  END OF TS_T074T,
  TT_T074T TYPE SORTED TABLE OF TS_T074T WITH NON-UNIQUE KEY SHBKZ.

TYPES:
  BEGIN OF TS_T001,
    BUKRS TYPE T001-BUKRS,
    WAERS TYPE T001-WAERS,
    KTOPL TYPE T001-KTOPL,
  END OF TS_T001.






TYPES : BEGIN OF TS_CUST_KEY,
             KUNNR TYPE BSAD_VIEW-KUNNR,
           END OF TS_CUST_KEY.
    TYPES : TT_CUST_KEY TYPE HASHED TABLE OF TS_CUST_KEY WITH UNIQUE KEY KUNNR.

TYPES : BEGIN OF TS_FIDOC,
    BUKRS TYPE BSID_VIEW-BUKRS,
    BELNR TYPE BSID_VIEW-BELNR,
    GJAHR TYPE BSID_VIEW-GJAHR,
    BUZEI TYPE BSID_VIEW-BUZEI,
    VBELN TYPE BSID_VIEW-VBELN,
    BLART TYPE BSID_VIEW-BLART,
    KUNNR TYPE BSID_VIEW-KUNNR,
    XBLNR TYPE BSID_VIEW-XBLNR,
    SGTXT TYPE BSID_VIEW-SGTXT,
    DMBTR TYPE BSID_VIEW-DMBTR,
    HKONT TYPE BSID_VIEW-HKONT,
    UMSKZ TYPE BSID_VIEW-UMSKZ,
    BUDAT TYPE BSID_VIEW-BUDAT,
    BLDAT TYPE BSID_VIEW-BLDAT, "<<F36K909945++
    ZFBDT TYPE BSID_VIEW-ZFBDT,
    ZBD1T TYPE BSID_VIEW-ZBD1T,
    ZBD2T TYPE BSID_VIEW-ZBD2T,
    ZBD3T TYPE BSID_VIEW-ZBD3T,
    SHKZG TYPE BSID_VIEW-SHKZG,
    REBZG TYPE BSID_VIEW-REBZG,
    ZTERM TYPE BSID_VIEW-ZTERM,
    ZUONR TYPE BSID_VIEW-ZUONR,
    XREF1 TYPE BSID_VIEW-XREF1, "CH04 420000219+
    VKORG TYPE VBRK-VKORG,
    VTWEG TYPE VBRK-VTWEG,
    SPART TYPE VBRK-SPART,
    POSNR TYPE VBRP-POSNR,
    VKGRP TYPE VBRP-VKGRP,
    VKBUR TYPE VBRP-VKBUR,
    AUBEL TYPE VBRP-AUBEL,
    VGBEL TYPE VBRP-VGBEL,
  END OF TS_FIDOC,
  TT_FIDOC TYPE SORTED TABLE OF TS_FIDOC WITH NON-UNIQUE KEY BUKRS BELNR GJAHR VBELN.
TYPES : BEGIN OF TS_ISLIST,
    VALUE TYPE ZSDSFIT040-ISSUE_LIST,
    TEXT  TYPE DD07T-DDTEXT,
  END OF TS_ISLIST,
  TT_ISLIST TYPE SORTED TABLE OF TS_ISLIST WITH UNIQUE KEY VALUE.
TYPES : TT_RANGE_I TYPE RANGE OF I.
TYPES : BEGIN OF TS_DAY_RANGE,
    SEQNO TYPE ZSDSCAC001-SEQUENCE,
    RANGE TYPE TT_RANGE_I,
    DESC  TYPE ZSDSCAC001-VDESC,
  END OF TS_DAY_RANGE,
  TT_DAY_RANGE TYPE SORTED TABLE OF TS_DAY_RANGE WITH NON-UNIQUE KEY SEQNO.

TYPES :
TT_TVGRT           TYPE SORTED TABLE OF TVGRT  WITH NON-UNIQUE  KEY VKGRP,
TT_TVKBT           TYPE SORTED TABLE OF TVKBT  WITH NON-UNIQUE  KEY VKBUR,
TT_DATA1           TYPE STANDARD TABLE OF GY_RESULT.

*-----------------------------------------------------------------------
* D A T A
*-----------------------------------------------------------------------
DATA : GT_RESULT TYPE TABLE OF GY_RESULT,
       GS_RESULT TYPE GY_RESULT.

DATA : BDCDATA LIKE BDCDATA OCCURS 0 WITH HEADER LINE.

DATA : MESSTAB   LIKE BDCMSGCOLL OCCURS 0 WITH HEADER LINE,
       T_MESSTAB LIKE BDCMSGCOLL OCCURS 0 WITH HEADER LINE,
       S_MESSTAB LIKE BDCMSGCOLL.

DATA : DYNPFIELDS  LIKE DYNPREAD OCCURS 5 WITH HEADER LINE.

DATA : GT_FCAT   TYPE SLIS_T_FIELDCAT_ALV,
       GS_LAYOUT TYPE SLIS_LAYOUT_ALV,
       GT_SORT   TYPE SLIS_T_SORTINFO_ALV,
       GS_SORT   TYPE SLIS_SORTINFO_ALV.

DATA : GRT_RPDAT TYPE RANGE OF SY-DATUM .
DATA : GF_EXEC_TY TYPE CHAR2.
DATA :  GS_T001 TYPE TS_T001 ##NEEDED.
DATA :GT_ISLIST    TYPE TT_ISLIST.
DATA :GT_DAY_RANGE TYPE TT_DAY_RANGE.


*-----------------------------------------------------------------------
* C O N S T A N T S
*-----------------------------------------------------------------------
CONSTANTS: GC_I  TYPE C LENGTH 1 VALUE 'I',
           GC_EQ TYPE C LENGTH 2 VALUE 'EQ',
           GC_S  TYPE C LENGTH 1 VALUE 'S',
           GC_E  TYPE C LENGTH 1 VALUE 'E',
           GC_X  TYPE C LENGTH 1 VALUE 'X',
           GC_A  TYPE C LENGTH 1 VALUE 'A',
           GC_L  TYPE C LENGTH 1 VALUE 'L'.

CONSTANTS:
           BEGIN OF GC_EXEC_TY,
           FI TYPE CHAR2 VALUE 'FI',
           DO TYPE CHAR2 VALUE 'DO',
  END OF GC_EXEC_TY,

GC_BLART_MIGRATE   TYPE BKPF-BLART VALUE 'Z1',
GC_KOART_CUST     TYPE BSEG-KOART VALUE 'D',
GC_TDOBJECT_DETAIL TYPE THEAD-TDOBJECT VALUE  'ZSDSFI001',
GC_SHKZG_CREDIT   TYPE BSID_VIEW-SHKZG VALUE 'H',
GC_SHKZG_DEBIT    TYPE BSID_VIEW-SHKZG VALUE 'S'.

*-----------------------------------------------------------------------
* R A N G E S
*-----------------------------------------------------------------------
*DATA:
*-----------------------------------------------------------------------
* M A C R O S
*-----------------------------------------------------------------------
*DEFINE.
*END-OF-DEFINITION.

*-----------------------------------------------------------------------
* F I E L D – S Y M B O L S
*-----------------------------------------------------------------------
*FIELD-SYMBOLS:

*-----------------------------------------------------------------------
* F I E L D – G R O U P S
*-----------------------------------------------------------------------
*FIELD-GROUPS:
