FUNCTION Z_SDSFI_DISPLAY_FIX_ASSET.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(IT_FIX_ASSET_NO) TYPE  ZSDSFIS099_TT OPTIONAL
*"     VALUE(I_EMP_ID) TYPE  ANLZ-PERNR OPTIONAL
*"  EXPORTING
*"     VALUE(ET_RETURN) TYPE  ZSDSFIS098_TT
*"     VALUE(E_MESTYPE) TYPE  CHAR1
*"     VALUE(E_MESSAGE) TYPE  CHAR70
*"----------------------------------------------------------------------

  GS_DISPLAY-SELECTION_ASSET = IT_FIX_ASSET_NO.
  GS_DISPLAY-SELECTION_EMP   = I_EMP_ID.

  IF I_EMP_ID IS NOT INITIAL.
    LCL_DATA=>GET_EMP( ).
  ELSE.
    LCL_DATA=>GET_ASSET_BY_FIX( ).
  ENDIF.

  LCL_DATA=>MODIFY_DATA( ).

  ET_RETURN = GS_DISPLAY-EXPORT_RETURN.
  E_MESTYPE = GS_DISPLAY-EXPORT_MESTYPE.
  E_MESSAGE = GS_DISPLAY-EXPORT_MESSAGE.

ENDFUNCTION.
