FUNCTION Z_SDSFI_DELETE_FILE.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(IM_FILE_PATH) TYPE  STRING
*"     REFERENCE(IM_LONG_FILE_PATH) TYPE  STRING
*"  EXPORTING
*"     REFERENCE(EX_SUBRC) TYPE  SY-SUBRC
*"     REFERENCE(EX_RETURN) TYPE  BAPIRET2
*"----------------------------------------------------------------------

  DATA: LREF_CX_FO TYPE REF TO CX_SY_FILE_OPEN,
        LREF_CX_CP TYPE REF TO CX_SY_CODEPAGE_CONVERTER_INIT,
        LREF_CX_CC TYPE REF TO CX_SY_CONVERSION_CODEPAGE,
        LREF_CX_FA TYPE REF TO CX_SY_FILE_AUTHORITY,
        LREF_CX_PI TYPE REF TO CX_SY_PIPES_NOT_SUPPORTED,
        LREF_CX_MF TYPE REF TO CX_SY_TOO_MANY_FILES,
        LREF_CX_FC TYPE REF TO CX_SY_FILE_CLOSE.

  DATA: LV_FILE_PATH  TYPE STRING,
        LV_E_MESSAGE  TYPE STRING,
        LV_UNIXCOM    TYPE STRING,
        LV_DEL_SCRIPT TYPE STRING,
        LV_SUBRC      TYPE SY-SUBRC.

  DATA: LT_IFILE      TYPE TABLE OF STRING.

  DATA: LWA_IFILE LIKE LINE OF LT_IFILE,
        LWA_MSG   TYPE ZSDSFIS034.

  IF IM_LONG_FILE_PATH IS NOT INITIAL.
    LV_FILE_PATH = IM_LONG_FILE_PATH.
  ELSEIF IM_FILE_PATH IS NOT INITIAL.
    LV_FILE_PATH = IM_FILE_PATH.
  ELSE.
    EX_RETURN-TYPE    = GC_ERROR.
    EX_RETURN-MESSAGE = TEXT-E07.
    RETURN.
  ENDIF.

  DELETE DATASET LV_FILE_PATH.
  IF SY-SUBRC IS INITIAL.
    LV_SUBRC        = 0.
    LWA_MSG-MSGTY   = GC_SUCCESS.
    LWA_MSG-MESSAGE = 'Delete file, Completed.'.
  ELSE.
    LV_SUBRC        = 8.
    LWA_MSG-MSGTY   = GC_ERROR.
    LWA_MSG-MESSAGE = 'Delete file, Failed.'.
  ENDIF.

  EX_SUBRC          = LV_SUBRC.
  EX_RETURN-TYPE    = LWA_MSG-MSGTY.
  EX_RETURN-MESSAGE = LWA_MSG-MESSAGE.



ENDFUNCTION.
