FUNCTION Z_SDSFI_PROJECT_DETAIL.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(IT_WBS) TYPE  ZSDSFIS184_TT OPTIONAL
*"  EXPORTING
*"     VALUE(ET_WBS_DETAIL) TYPE  ZSDSFIS186_TT
*"     VALUE(ET_WBS_COST_DETAIL) TYPE  ZSDSFIS187_TT
*"----------------------------------------------------------------------
  DATA GS_RESULT2 LIKE LINE OF ET_WBS_COST_DETAIL.


  SELECT VBAP~VBELN,
             VBAP~POSNR,
             VBAP~MATNR,
             VBAP~NETWR,
             VBAK~KUNNR,
        VBAP~PS_PSP_PNR

       FROM VBAP
        INNER JOIN VBAK ON VBAP~VBELN EQ VBAK~VBELN
        WHERE VBAP~PS_PSP_PNR IN @IT_WBS

        INTO TABLE @ET_WBS_DETAIL.

  SELECT EBAN~BANFN,
         EBAN~MATNR,
         EBAN~TXZ01,
         EBAN~PREIS,
         EKKO~EBELN,
         MSEG~MBLNR,
         EBKN~PS_PSP_PNR

    FROM EBAN

    INNER JOIN EBKN ON  EBAN~BANFN EQ EBKN~BANFN
                    AND EBAN~BNFPO EQ EBKN~BNFPO
                    AND EBKN~BNFPO EQ '01'
    LEFT JOIN EKPO   ON EBAN~BANFN EQ EKPO~BANFN
                    AND EBAN~BNFPO EQ EKPO~BNFPO
    LEFT JOIN EKKO   ON EKPO~EBELN EQ EKKO~EBELN
    LEFT JOIN MSEG   ON EKPO~EBELN EQ MSEG~EBELN
                    AND EKPO~EBELP EQ MSEG~EBELP

    WHERE  EBKN~PS_PSP_PNR IN @IT_WBS

    INTO TABLE @ET_WBS_COST_DETAIL.

  SELECT  EKKO~EBELN,
          EKPO~EBELP,
          EKPO~MATNR,
          EKPO~TXZ01,
          EKPO~NETPR,
          MSEG~MBLNR,
          MSEG~MJAHR,
          MSEG~ZEILE

    FROM EKPO
    INNER JOIN EKKO ON EKPO~EBELN EQ EKKO~EBELN
    INNER JOIN EKKN ON EKPO~EBELN EQ EKKN~EBELN
                   AND EKPO~BANFN =  @SPACE
    LEFT JOIN MSEG  ON EKPO~EBELN EQ MSEG~EBELN
                   AND EKPO~EBELP EQ MSEG~EBELP

    WHERE  EKKN~PS_PSP_PNR IN @IT_WBS

    INTO TABLE @DATA(LT_TMP_PO).

  SELECT MSEG~MBLNR,
         MSEG~MJAHR,
         MSEG~ZEILE,
         MSEG~MATNR,
         MSEG~SGTXT,
         MSEG~DMBTR

     FROM MSEG

     WHERE   MSEG~EBELN = @SPACE
     AND     MSEG~PS_PSP_PNR IN @IT_WBS

     INTO TABLE @DATA(LT_TMP_MIKO).

  DATA LV_TABIX    TYPE SY-TABIX.
  DATA LS_TMP_PO   LIKE LINE OF LT_TMP_PO.
  DATA LS_TMP_MIKO LIKE LINE OF LT_TMP_MIKO.

  LOOP AT LT_TMP_PO INTO LS_TMP_PO.
*      GS_RESULT2-BANFN = ''.
    GS_RESULT2-MATNR = LS_TMP_PO-MATNR.
    GS_RESULT2-TXZ01 = LS_TMP_PO-TXZ01.
    GS_RESULT2-PREIS = LS_TMP_PO-NETPR.
    GS_RESULT2-EBELN = LS_TMP_PO-EBELN.
    GS_RESULT2-MBLNR = LS_TMP_PO-MBLNR.
    APPEND GS_RESULT2 TO ET_WBS_COST_DETAIL.

  ENDLOOP.


  LOOP AT LT_TMP_MIKO INTO LS_TMP_MIKO.
*         GS_RESULT2-BANFN = ''.
    GS_RESULT2-MATNR = LS_TMP_MIKO-MATNR.
    GS_RESULT2-TXZ01 = LS_TMP_MIKO-SGTXT.
    GS_RESULT2-PREIS = LS_TMP_MIKO-DMBTR.
*         GS_RESULT2-EBELN = ''.
    GS_RESULT2-MBLNR = LS_TMP_MIKO-MBLNR.

    APPEND GS_RESULT2 TO ET_WBS_COST_DETAIL.


  ENDLOOP.





ENDFUNCTION.
