*&---------------------------------------------------------------------*
*& Include ZSDSFIR0350_TOP
*&---------------------------------------------------------------------*
TABLES: BKPF, SKA1, ZSDSFIS074, ZSDSFIS075, ZSDSFIS076.

*----------------------------------------------------------------------*
* TYPES
*----------------------------------------------------------------------*
TYPES: BEGIN OF TS_PERIOD,
         POPER TYPE POPER,
         BEGDA TYPE BEGDA, "Cal date
         ENDDA TYPE ENDDA, "Cal date
         BUDAT TYPE BUDAT, "Posting date  (End of month)
         BLDAT TYPE BLDAT, "Document date (End of month)
         DAY   TYPE I,
         TOTAL TYPE I,
       END OF TS_PERIOD.
TYPES: TT_PERIOD TYPE STANDARD TABLE OF TS_PERIOD.
TYPES: BEGIN OF TS_MAINITEM,
         GUID     TYPE ZSDSFIT024-GUID,
         RUNNO    TYPE ZSDSFIT024-RUNNO,
         BUDAT    TYPE ZSDSFIT024-BUDAT,
         WRBTR    TYPE ZSDSFIT024-WRBTR,
         HKONT_DR TYPE ZSDSFIT024-HKONT_DR,
         TXT20_DR TYPE SKAT-TXT20,
         HKONT_CR TYPE ZSDSFIT024-HKONT_CR,
         TXT20_CR TYPE SKAT-TXT20,
         AUFNR    TYPE ZSDSFIS075-AUFNR,
         PS_POSID TYPE ZSDSFIS075-PS_POSID,
         PRCTR    TYPE ZSDSFIS075-PRCTR,
       END OF TS_MAINITEM.
TYPES: TS_ACCA TYPE ZSDSFIS076.
TYPES: BEGIN OF TS_POST.
TYPES: STATUS TYPE ICON_NAME.
TYPES: MSGTX TYPE MSGTX.
       INCLUDE TYPE ZSDSFIS075.
TYPES: BSCHL TYPE BSCHL.
TYPES: HKONT TYPE HKONT.
TYPES: TXT20 TYPE SKAT-TXT20.
TYPES: LTEXT TYPE CSKT-LTEXT.
TYPES: SGTXT TYPE SGTXT.
TYPES END OF TS_POST.
TYPES: TT_POST TYPE STANDARD TABLE OF TS_POST.
*------ Document header and items for internal posting interface
TYPES: TT_FTPOST TYPE STANDARD TABLE OF FTPOST,
*------ Tax Data
       TT_FTTAX  TYPE STANDARD TABLE OF FTTAX,
*------ Financial Accounting document number table
       TT_BLNTAB TYPE STANDARD TABLE OF BLNTAB.

CONSTANTS: GC_TCODE TYPE SY-TCODE VALUE 'ZSDSFI028',
           GC_CRET  TYPE SYUCOMM  VALUE 'CRET',
           GC_DISP  TYPE SYUCOMM  VALUE 'DISP',
           GC_POST  TYPE SYUCOMM  VALUE 'POST',
           GC_REPT  TYPE SYUCOMM  VALUE 'REPT',
           GC_EDIT  TYPE SYUCOMM  VALUE 'EDIT',
           GC_TRUE  TYPE CHAR1    VALUE 'X'.

CONTROLS: TABSTRIP_CTRL TYPE TABSTRIP.
CONTROLS: TABLE_CTRL_MAIN TYPE TABLEVIEW USING SCREEN 9001 ##NUMBER_OK.
CONTROLS: TABLE_CTRL_ACCA TYPE TABLEVIEW USING SCREEN 9002 ##NUMBER_OK.

CONSTANTS: BEGIN OF C_TABSTRIP_CTRL,
             TAB1 LIKE SY-UCOMM VALUE 'TABSTRIP_CTRL_FC1',
             TAB2 LIKE SY-UCOMM VALUE 'TABSTRIP_CTRL_FC2',
             TAB3 LIKE SY-UCOMM VALUE 'TABSTRIP_CTRL_FC3',
           END OF C_TABSTRIP_CTRL.

DATA: BEGIN OF G_TABSTRIP_CTRL,
        SUBSCREEN   LIKE SY-DYNNR,
        PROG        LIKE SY-REPID VALUE 'ZSDSFIR0350',
        PRESSED_TAB LIKE SY-UCOMM VALUE C_TABSTRIP_CTRL-TAB1,
      END OF G_TABSTRIP_CTRL.

DATA: "ok_code                 LIKE sy-ucomm ##NEEDED,
  CONTAINER               TYPE REF TO CL_GUI_CUSTOM_CONTAINER ##NEEDED,
  GT_MAINITEM             TYPE STANDARD TABLE OF TS_MAINITEM ##NEEDED,
  GS_MAINITEM             TYPE TS_MAINITEM ##NEEDED, "work area
  GF_MAINITEM_COPIED      TYPE C LENGTH 1 ##NEEDED,           "copy flag
  G_TABLE_CTRL_MAIN_LINES LIKE SY-LOOPC  ##NEEDED,

  GT_ACCA                 TYPE STANDARD TABLE OF TS_ACCA ##NEEDED,
  GS_ACCA                 TYPE TS_ACCA ##NEEDED, "work area
  GR_TABLE                TYPE REF TO CL_SALV_TABLE ##NEEDED,
  GR_POSTITEM_TABLE       TYPE REF TO CL_SALV_TABLE ##NEEDED,
  GT_MAIN                 TYPE STANDARD TABLE OF ZSDSFIS074 ##NEEDED,
  GT_POSTITEM             TYPE TT_POST ##NEEDED,
  GF_OKCODE               TYPE SYUCOMM ##NEEDED,
  GF_MODE                 TYPE SYUCOMM ##NEEDED,
  GF_HEADER               TYPE STRING ##NEEDED,

*..Interface posting
  GT_FTPOST               TYPE TT_FTPOST ##NEEDED,
  GT_FTTAX                TYPE TT_FTTAX ##NEEDED,
  GT_BLNTAB               TYPE TT_BLNTAB ##NEEDED,
  GS_FTPOST               TYPE FTPOST ##NEEDED,
  GF_COUNT                TYPE I ##NEEDED.
