*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZSDSV_ZSDSFIC032................................*
FORM GET_DATA_ZSDSV_ZSDSFIC032.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZSDSFIC032 WHERE
(VIM_WHERETAB) .
    CLEAR ZSDSV_ZSDSFIC032 .
ZSDSV_ZSDSFIC032-MANDT =
ZSDSFIC032-MANDT .
ZSDSV_ZSDSFIC032-BUKRS =
ZSDSFIC032-BUKRS .
ZSDSV_ZSDSFIC032-WITHT =
ZSDSFIC032-WITHT .
ZSDSV_ZSDSFIC032-WT_WITHCD =
ZSDSFIC032-WT_WITHCD .
ZSDSV_ZSDSFIC032-WT_WITHCD_TXT =
ZSDSFIC032-WT_WITHCD_TXT .
ZSDSV_ZSDSFIC032-BANK_WITHTYPE =
ZSDSFIC032-BANK_WITHTYPE .
ZSDSV_ZSDSFIC032-WITHTYPE_EN =
ZSDSFIC032-WITHTYPE_EN .
ZSDSV_ZSDSFIC032-WITHTYPE_TH =
ZSDSFIC032-WITHTYPE_TH .
<VIM_TOTAL_STRUC> = ZSDSV_ZSDSFIC032.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZSDSV_ZSDSFIC032 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZSDSV_ZSDSFIC032.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZSDSV_ZSDSFIC032-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZSDSFIC032 WHERE
  BUKRS = ZSDSV_ZSDSFIC032-BUKRS AND
  WITHT = ZSDSV_ZSDSFIC032-WITHT AND
  WT_WITHCD = ZSDSV_ZSDSFIC032-WT_WITHCD .
    IF SY-SUBRC = 0.
    DELETE ZSDSFIC032 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZSDSFIC032 WHERE
  BUKRS = ZSDSV_ZSDSFIC032-BUKRS AND
  WITHT = ZSDSV_ZSDSFIC032-WITHT AND
  WT_WITHCD = ZSDSV_ZSDSFIC032-WT_WITHCD .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZSDSFIC032.
    ENDIF.
ZSDSFIC032-MANDT =
ZSDSV_ZSDSFIC032-MANDT .
ZSDSFIC032-BUKRS =
ZSDSV_ZSDSFIC032-BUKRS .
ZSDSFIC032-WITHT =
ZSDSV_ZSDSFIC032-WITHT .
ZSDSFIC032-WT_WITHCD =
ZSDSV_ZSDSFIC032-WT_WITHCD .
ZSDSFIC032-WT_WITHCD_TXT =
ZSDSV_ZSDSFIC032-WT_WITHCD_TXT .
ZSDSFIC032-BANK_WITHTYPE =
ZSDSV_ZSDSFIC032-BANK_WITHTYPE .
ZSDSFIC032-WITHTYPE_EN =
ZSDSV_ZSDSFIC032-WITHTYPE_EN .
ZSDSFIC032-WITHTYPE_TH =
ZSDSV_ZSDSFIC032-WITHTYPE_TH .
    IF SY-SUBRC = 0.
    UPDATE ZSDSFIC032 ##WARN_OK.
    ELSE.
    INSERT ZSDSFIC032 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZSDSV_ZSDSFIC032-UPD_FLAG,
STATUS_ZSDSV_ZSDSFIC032-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZSDSV_ZSDSFIC032.
  SELECT SINGLE * FROM ZSDSFIC032 WHERE
BUKRS = ZSDSV_ZSDSFIC032-BUKRS AND
WITHT = ZSDSV_ZSDSFIC032-WITHT AND
WT_WITHCD = ZSDSV_ZSDSFIC032-WT_WITHCD .
ZSDSV_ZSDSFIC032-MANDT =
ZSDSFIC032-MANDT .
ZSDSV_ZSDSFIC032-BUKRS =
ZSDSFIC032-BUKRS .
ZSDSV_ZSDSFIC032-WITHT =
ZSDSFIC032-WITHT .
ZSDSV_ZSDSFIC032-WT_WITHCD =
ZSDSFIC032-WT_WITHCD .
ZSDSV_ZSDSFIC032-WT_WITHCD_TXT =
ZSDSFIC032-WT_WITHCD_TXT .
ZSDSV_ZSDSFIC032-BANK_WITHTYPE =
ZSDSFIC032-BANK_WITHTYPE .
ZSDSV_ZSDSFIC032-WITHTYPE_EN =
ZSDSFIC032-WITHTYPE_EN .
ZSDSV_ZSDSFIC032-WITHTYPE_TH =
ZSDSFIC032-WITHTYPE_TH .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZSDSV_ZSDSFIC032 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZSDSV_ZSDSFIC032-BUKRS TO
ZSDSFIC032-BUKRS .
MOVE ZSDSV_ZSDSFIC032-WITHT TO
ZSDSFIC032-WITHT .
MOVE ZSDSV_ZSDSFIC032-WT_WITHCD TO
ZSDSFIC032-WT_WITHCD .
MOVE ZSDSV_ZSDSFIC032-MANDT TO
ZSDSFIC032-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZSDSFIC032'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZSDSFIC032 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZSDSFIC032'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
