FUNCTION Z_SDSFI_WS_CHECK_RD_SENT.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(IM_IT_DOCS) TYPE  ZSDSFIS063_TT
*"  EXPORTING
*"     REFERENCE(EX_IT_OUTPUT) TYPE  ZSDSFIS027_TT
*"     REFERENCE(EX_WA_BAPIRET2) TYPE  BAPIRET2
*"----------------------------------------------------------------------

  DATA: LO_SERVICE     TYPE REF TO ZCL_SDSFI_CO_IETAX_SERVICE,
        LREF_SYS_FAULT TYPE REF TO CX_AI_SYSTEM_FAULT,
        LREF_APP_FAULT TYPE REF TO CX_AI_APPLICATION_FAULT,
        LV_E_MESSAGE   TYPE STRING.

  DATA: LWA_INPUT  TYPE ZSDSFIS061,
        LWA_OUTPUT TYPE ZSDSFIS072.

  IF IM_IT_DOCS[] IS INITIAL.
    EX_WA_BAPIRET2-TYPE    = 'E'.
    EX_WA_BAPIRET2-MESSAGE = 'IM_IT_DOCS[] is empty.'.
    RAISE EMPTY_IT_DOCS.
  ENDIF.

  LWA_INPUT-REQUESTS-CHECK_STATUS_RD_SENT_REQUEST[] = IM_IT_DOCS[].

  TRY.
      CREATE OBJECT LO_SERVICE
        EXPORTING
          LOGICAL_PORT_NAME = GC_LOGICAL_PORT.

      CALL METHOD LO_SERVICE->CHECK_STATUS_RD_SENT
        EXPORTING
          INPUT  = LWA_INPUT
        IMPORTING
          OUTPUT = LWA_OUTPUT.

    CATCH CX_AI_SYSTEM_FAULT INTO LREF_SYS_FAULT.
      LV_E_MESSAGE = LREF_SYS_FAULT->GET_TEXT( ).

    CATCH CX_AI_APPLICATION_FAULT INTO LREF_APP_FAULT.
      LV_E_MESSAGE = LREF_APP_FAULT->GET_TEXT( ).
  ENDTRY.

  IF LV_E_MESSAGE IS NOT INITIAL.
    EX_WA_BAPIRET2-TYPE    = 'E'.
    EX_WA_BAPIRET2-MESSAGE = LV_E_MESSAGE.
    RAISE ERROR.
  ENDIF.

  EX_IT_OUTPUT[] = LWA_OUTPUT-CHECK_STATUS_RD_SENT_RESULT-CHECK_STATUS_RD_SENT_RESPONSE[].
ENDFUNCTION.
