*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZSDSV_ZSDSFIC024................................*
FORM GET_DATA_ZSDSV_ZSDSFIC024.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZSDSFIC024 WHERE
(VIM_WHERETAB) .
    CLEAR ZSDSV_ZSDSFIC024 .
ZSDSV_ZSDSFIC024-MANDT =
ZSDSFIC024-MANDT .
ZSDSV_ZSDSFIC024-KUNNR =
ZSDSFIC024-KUNNR .
ZSDSV_ZSDSFIC024-ZBLLCYL =
ZSDSFIC024-ZBLLCYL .
ZSDSV_ZSDSFIC024-ZBLLCOL =
ZSDSFIC024-ZBLLCOL .
ZSDSV_ZSDSFIC024-ZDAYS =
ZSDSFIC024-ZDAYS .
    SELECT SINGLE * FROM KNA1 WHERE
KUNNR = ZSDSFIC024-KUNNR .
    IF SY-SUBRC EQ 0.
ZSDSV_ZSDSFIC024-NAME1 =
KNA1-NAME1 .
    ENDIF.
<VIM_TOTAL_STRUC> = ZSDSV_ZSDSFIC024.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZSDSV_ZSDSFIC024 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZSDSV_ZSDSFIC024.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZSDSV_ZSDSFIC024-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZSDSFIC024 WHERE
  KUNNR = ZSDSV_ZSDSFIC024-KUNNR .
    IF SY-SUBRC = 0.
    DELETE ZSDSFIC024 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZSDSFIC024 WHERE
  KUNNR = ZSDSV_ZSDSFIC024-KUNNR .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZSDSFIC024.
    ENDIF.
ZSDSFIC024-MANDT =
ZSDSV_ZSDSFIC024-MANDT .
ZSDSFIC024-KUNNR =
ZSDSV_ZSDSFIC024-KUNNR .
ZSDSFIC024-ZBLLCYL =
ZSDSV_ZSDSFIC024-ZBLLCYL .
ZSDSFIC024-ZBLLCOL =
ZSDSV_ZSDSFIC024-ZBLLCOL .
ZSDSFIC024-ZDAYS =
ZSDSV_ZSDSFIC024-ZDAYS .
    IF SY-SUBRC = 0.
    UPDATE ZSDSFIC024 ##WARN_OK.
    ELSE.
    INSERT ZSDSFIC024 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZSDSV_ZSDSFIC024-UPD_FLAG,
STATUS_ZSDSV_ZSDSFIC024-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZSDSV_ZSDSFIC024.
  SELECT SINGLE * FROM ZSDSFIC024 WHERE
KUNNR = ZSDSV_ZSDSFIC024-KUNNR .
ZSDSV_ZSDSFIC024-MANDT =
ZSDSFIC024-MANDT .
ZSDSV_ZSDSFIC024-KUNNR =
ZSDSFIC024-KUNNR .
ZSDSV_ZSDSFIC024-ZBLLCYL =
ZSDSFIC024-ZBLLCYL .
ZSDSV_ZSDSFIC024-ZBLLCOL =
ZSDSFIC024-ZBLLCOL .
ZSDSV_ZSDSFIC024-ZDAYS =
ZSDSFIC024-ZDAYS .
    SELECT SINGLE * FROM KNA1 WHERE
KUNNR = ZSDSFIC024-KUNNR .
    IF SY-SUBRC EQ 0.
ZSDSV_ZSDSFIC024-NAME1 =
KNA1-NAME1 .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZSDSV_ZSDSFIC024-NAME1 .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZSDSV_ZSDSFIC024 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZSDSV_ZSDSFIC024-KUNNR TO
ZSDSFIC024-KUNNR .
MOVE ZSDSV_ZSDSFIC024-MANDT TO
ZSDSFIC024-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZSDSFIC024'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZSDSFIC024 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZSDSFIC024'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZSDSV_ZSDSFIC024 USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZSDSFIC024-MANDT =
ZSDSV_ZSDSFIC024-MANDT .
ZSDSFIC024-KUNNR =
ZSDSV_ZSDSFIC024-KUNNR .
ZSDSFIC024-ZBLLCYL =
ZSDSV_ZSDSFIC024-ZBLLCYL .
ZSDSFIC024-ZBLLCOL =
ZSDSV_ZSDSFIC024-ZBLLCOL .
ZSDSFIC024-ZDAYS =
ZSDSV_ZSDSFIC024-ZDAYS .
    SELECT SINGLE * FROM KNA1 WHERE
KUNNR = ZSDSFIC024-KUNNR .
    IF SY-SUBRC EQ 0.
ZSDSV_ZSDSFIC024-NAME1 =
KNA1-NAME1 .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZSDSV_ZSDSFIC024-NAME1 .
    ENDIF.
ENDFORM.
