*&---------------------------------------------------------------------*
*& Include          ZSDSFIR0290_TOP
*&---------------------------------------------------------------------*
*-----------------------------------------------------------------------
* TABLES
*-----------------------------------------------------------------------
TABLES:
  KNB1,
  VBRK,
  VBRP,
  BSEG,
  BKPF,
  SSCRFIELDS,
  ZSDSFIT033.

*-----------------------------------------------------------------------
* MACRO
*-----------------------------------------------------------------------
DEFINE APPEND_RANGE.
  clear &1.
  &1-sign = &2.
  &1-option = &3.
  &1-low  = &4.
  &1-high = &5.
  append &1 to &6.
END-OF-DEFINITION.
DEFINE MC_SHOW_PROGRESS.
  IF sy-batch IS INITIAL.
*   Show progress online
    CALL FUNCTION 'SAPGUI_PROGRESS_INDICATOR'
      EXPORTING
        percentage = &1 ##NUMBER_OK
        text       = &2.
  ELSE.
*   Show message step in background
    MESSAGE i000(38) WITH &2 space space space.
  ENDIF.
END-OF-DEFINITION.
DEFINE %FCAT.
  <fcat>-scrtext_s = <fcat>-scrtext_m =
  <fcat>-scrtext_l = <fcat>-coltext =
  <fcat>-seltext   = <fcat>-tooltip =
  <fcat>-reptext   = &1.
END-OF-DEFINITION.

*----------------------------------------------------------------------*
* TYPES:
*----------------------------------------------------------------------*
TYPES:
  TT_STAT_ACT TYPE STANDARD TABLE OF ZSDSFIC028,
  BEGIN OF TS_FI_DOC,
    KUNNR     TYPE BSID_VIEW-KUNNR,
    BUKRS     TYPE BKPF-BUKRS,
    BELNR     TYPE BKPF-BELNR,
    GJAHR     TYPE BKPF-GJAHR,
    BUZEI     TYPE BSID_VIEW-BUZEI,
    BLART     TYPE BKPF-BLART,
    XBLNR     TYPE BKPF-XBLNR,
    BKTXT     TYPE BKPF-BKTXT,
    AWTYP     TYPE BKPF-AWTYP,
    BLDAT     TYPE BKPF-BLDAT,
    VBELN     TYPE BSID_VIEW-VBELN,
    BUDAT     TYPE BSID_VIEW-BUDAT,
    ZTERM     TYPE BSID_VIEW-ZTERM,
    SHKZG     TYPE BSID_VIEW-SHKZG,
    DMBTR     TYPE BSID_VIEW-DMBTR,
    UMSKZ     TYPE BSID_VIEW-UMSKZ,
    SGTXT     TYPE BSID_VIEW-SGTXT, "Project
    BILLPL_NO TYPE ZSDSFIT035-BILLPL_NO,
    DELFG     TYPE ZSDSFIT033-DELFG,
  END OF TS_FI_DOC,
  TT_FI_DOC TYPE STANDARD TABLE OF TS_FI_DOC,
  BEGIN OF TS_FI_DOC_KEY,
    BUKRS TYPE BKPF-BUKRS,
    GJAHR TYPE BKPF-GJAHR,
    BELNR TYPE BKPF-BELNR,
    BUZEI TYPE BSID_VIEW-BUZEI,
  END OF TS_FI_DOC_KEY,
  TT_FI_DOC_KEY TYPE STANDARD TABLE OF TS_FI_DOC_KEY,
  BEGIN OF TS_VBKD,
    VBELN_BILL TYPE VBRK-VBELN,
    VBELN_SO   TYPE VBKD-VBELN,
    BSTKD      TYPE VBKD-BSTKD,
  END OF TS_VBKD,
  TT_VBKD TYPE STANDARD TABLE OF TS_VBKD,
  BEGIN OF TS_VBRP,
    VBELN_BILL TYPE VBRP-VBELN,
    PSPHI      TYPE PRPS-PSPHI,
  END OF TS_VBRP,
  TT_VBRP TYPE SORTED TABLE OF TS_VBRP WITH NON-UNIQUE KEY VBELN_BILL,
  BEGIN OF TS_SD_KEY,
    VBELN TYPE VBRP-VBELN,
  END OF TS_SD_KEY,
  TT_SD_KEY TYPE STANDARD TABLE OF TS_SD_KEY,
  BEGIN OF TS_CLEAR_DOC,
    BUKRS TYPE BSID_VIEW-BUKRS,
    REBZG TYPE BSID_VIEW-REBZG,
    REBZJ TYPE BSID_VIEW-REBZJ,
    REBZZ TYPE BSID_VIEW-REBZZ,
    GJAHR TYPE BSID_VIEW-GJAHR,
    BELNR TYPE BSID_VIEW-BELNR,
    BUZEI TYPE BSID_VIEW-BUZEI,
    SHKZG TYPE BSID_VIEW-SHKZG,
    DMBTR TYPE BSID_VIEW-DMBTR,
  END OF TS_CLEAR_DOC,
  TT_CLEAR_DOC TYPE SORTED TABLE OF TS_CLEAR_DOC WITH NON-UNIQUE KEY BUKRS REBZG REBZJ REBZZ,
  BEGIN OF TS_ACTION_TYPE,
    VALUE TYPE ZSDSFIT033-ACTION_TYPE,
    TEXT  TYPE DD07T-DDTEXT,
  END OF TS_ACTION_TYPE,
  TT_ACTION_TYPE TYPE SORTED TABLE OF TS_ACTION_TYPE WITH UNIQUE KEY VALUE,
  BEGIN OF TS_STATUS,
    VALUE TYPE ZSDSFIT033-STATUS,
    TEXT  TYPE DD07T-DDTEXT,
  END OF TS_STATUS,
  TT_STATUS TYPE SORTED TABLE OF TS_STATUS WITH UNIQUE KEY VALUE,
  TT_034    TYPE STANDARD TABLE OF ZSDSFIT034,
  BEGIN OF TS_CHK_INV,
    VBELN_BILL    TYPE VBRK-VBELN,
    VBELN_SO      TYPE VBAK-VBELN,
    PSPHI         TYPE PRPS-PSPHI,
    VBELN_INV_CHK TYPE ZSDSFIT028-VBELN,
    ZCHECK        TYPE ZSDSFIT028-ZCHECK,
    ZSTAT_ACT     TYPE ZSDSFIT028-ZSTAT_ACT,
  END OF TS_CHK_INV,
  TT_CHK_INV TYPE SORTED TABLE OF TS_CHK_INV WITH NON-UNIQUE KEY VBELN_BILL,
  BEGIN OF TS_PROJ,
    PSPNR TYPE PROJ-PSPNR,
    PSPID TYPE PROJ-PSPID,
    POST1 TYPE PROJ-POST1,
  END OF TS_PROJ,
  TT_PROJ TYPE SORTED TABLE OF TS_PROJ WITH NON-UNIQUE KEY PSPNR,
  BEGIN OF TS_PROJ_FI,
    PSPID TYPE PROJ-PSPID,
    POST1 TYPE PROJ-POST1,
  END OF TS_PROJ_FI,
  TT_PROJ_FI TYPE SORTED TABLE OF TS_PROJ_FI WITH NON-UNIQUE KEY PSPID,
*------------BEGIN declare as same in smartform -------
  BEGIN OF TS_DATA1,
    KUNNR          TYPE BSID_VIEW-KUNNR,
    NAME1          TYPE KNA1-NAME1,
    BILLPL_NO      TYPE ZSDSFIT033-BILLPL_NO,
    BILLPL_DATE    TYPE ZSDSFIT033-BILLPL_DATE,
    VBELN          TYPE VBRK-VBELN,
    BELNR          TYPE BSID_VIEW-BELNR,
    GJAHR          TYPE BSID_VIEW-GJAHR,
    BUZEI          TYPE BSID_VIEW-BUZEI,
    BLART          TYPE BSID_VIEW-BLART,
    XBLNR          TYPE BKPF-XBLNR,
    BKTXT          TYPE BKPF-BKTXT,
    BSTKD          TYPE TEXT80,
    RECEIPT        TYPE BKPF-XBLNR,
    BUDAT          TYPE BSID_VIEW-BUDAT,
    ZTERM          TYPE BSID_VIEW-ZTERM,
    OPEN_AMT       TYPE ZSDSFIT035-BILLPL_AMT,
    BILLPL_AMT     TYPE ZSDSFIT035-BILLPL_AMT,
    UMSKZ          TYPE BSID_VIEW-UMSKZ,
    PROJK          TYPE PROJ-PSPID,
    POST1          TYPE PROJ-POST1,
    CRDAT          TYPE ZSDSFIT033-CRDAT,
    CRUSR          TYPE ZSDSFIT033-CRUSR,
    CR_PERNR       TYPE ZSDSFIT033-CR_PERNR, "CH02+
    NETDT          TYPE FAEDE-NETDT,
    BILLPL_PMTDT   TYPE ZSDSFIT033-BILLPL_PMTDT,
    ACTION_TYPE    TYPE ZSDSFIT033-ACTION_TYPE,
    ACTION_TYPE_TX TYPE DD07T-DDTEXT,
    STATUS         TYPE ZSDSFIT033-STATUS,
    STATUS_TX      TYPE DD07T-DDTEXT,
    WAERS          TYPE T001-WAERS,
    FIELD_STYLE    TYPE LVC_T_STYL,
    ROW_COLOR      TYPE CHAR4,
    COL_COLOR      TYPE LVC_T_SCOL,
    SEL            TYPE FLAG,
    SUM            TYPE FLAG,
  END OF TS_DATA1,
  TT_DATA1 TYPE STANDARD TABLE OF TS_DATA1,
  BEGIN OF TS_COMP,
    BUKRS            TYPE T001-BUKRS,
    WAERS            TYPE T001-WAERS,
    STCEG            TYPE T001-STCEG,
    TH_NAME1         TYPE ADRC-NAME1,
    TH_STREET        TYPE ADRC-STREET,
    TH_CITY2         TYPE ADRC-CITY2,
    TH_CITY1         TYPE ADRC-CITY1,
    TH_POST_CODE1    TYPE ADRC-POST_CODE1,
    EN_NAME1         TYPE ADRC-NAME1,
    EN_STREET        TYPE ADRC-STREET,
    EN_CITY2         TYPE ADRC-CITY2,
    EN_CITY1         TYPE ADRC-CITY1,
    EN_POST_CODE1    TYPE ADRC-POST_CODE1,
    TEL_NUMBER       TYPE ADRC-TEL_NUMBER,
    TEL_EXT_NO       TYPE ZSDSCAC001-VALUE_LOW,
    COMMERCIAL_REGIS TYPE ZSDSCAC001-VALUE_LOW,
    QF_FORM_NO       TYPE ZSDSCAC001-VALUE_LOW,
    BANK_ID          TYPE T012K-BANKN,
    TH_BANK_NAME     TYPE ZSDSCAC001-VALUE_LOW,
    EN_BANK_NAME     TYPE ZSDSCAC001-VALUE_LOW,
  END OF TS_COMP,
  BEGIN OF TS_CUST,
    KUNNR      TYPE KNA1-KUNNR,
    STCD3      TYPE KNA1-STCD3,
    NAME1      TYPE ADRC-NAME1,
    NAME2      TYPE ADRC-NAME2,
    NAME3      TYPE ADRC-NAME3, "CH01+
    NAME4      TYPE ADRC-NAME4, "CH01+
    STREET     TYPE ADRC-STREET,
    STR_SUPPL3 TYPE ADRC-STR_SUPPL3,
    LOCATION   TYPE ADRC-LOCATION,
    CITY2      TYPE ADRC-CITY2,
    HOME_CITY  TYPE ADRC-HOME_CITY,
    CITY1      TYPE ADRC-CITY1,
    POST_CODE1 TYPE ADRC-POST_CODE1,
    TEL_NUMBER TYPE ADRC-TEL_NUMBER,
    FAX_NUMBER TYPE ADRC-FAX_NUMBER,
    J_1TPBUPL  TYPE FITHA_PBUPL_D-J_1TPBUPL,
  END OF TS_CUST,
  TT_CUST TYPE SORTED TABLE OF TS_CUST WITH NON-UNIQUE KEY KUNNR.
*------------END declare as same in smartform -------

*----------------------------------------------------------------------*
* RANGES
*----------------------------------------------------------------------*
DATA:
  GRT_INV_BLART TYPE RANGE OF BKPF-BLART      ##NEEDED,
  GRT_UMSKZ     TYPE RANGE OF BSID_VIEW-UMSKZ ##NEEDED.

*----------------------------------------------------------------------*
* INTERNAL TABLE
*----------------------------------------------------------------------*
DATA:
  GT_STATUS      TYPE TT_STATUS      ##NEEDED,
  GT_ACTION_TYPE TYPE TT_ACTION_TYPE ##NEEDED,
  GT_STAT_ACT    TYPE TT_STAT_ACT    ##NEEDED,
  GT_DATA1       TYPE TT_DATA1       ##NEEDED,
  GT_DATA1_OLD   TYPE TT_DATA1       ##NEEDED,
  GT_CUST        TYPE TT_CUST        ##NEEDED,
  GT_DATA1_PRINT TYPE TT_DATA1       ##NEEDED.
*----------------------------------------------------------------------*
* WORK AREAS
*----------------------------------------------------------------------*
DATA:
  GS_COMP TYPE TS_COMP       ##NEEDED,
  GS_CUST TYPE TS_CUST       ##NEEDED.
*----------------------------------------------------------------------*
* VARIABLE
*----------------------------------------------------------------------*
DATA:
  GF_EXEC_TY TYPE  CHAR2 ##NEEDED,
  GF_EDIT    TYPE  CHAR1 ##NEEDED.

*----------------------------------------------------------------------*
* CONSTANTS
*----------------------------------------------------------------------*
CONSTANTS:
  GC_TCODE               TYPE SY-TCODE               VALUE 'ZSDSFI029',
  GC_TRUE                TYPE FLAG                   VALUE 'X',
  GC_FALSE               TYPE FLAG                   VALUE '',
  GC_ZCHECK_RECEIVED     TYPE ZSDSFIT027-ZCHECK      VALUE '2',
  GC_AWTYP_VBRK          TYPE BKPF-AWTYP             VALUE 'VBRK',
  GC_DOMNAME_ACTION_TYPE TYPE DD07T-DOMNAME          VALUE 'ZSDSDM_ACTION_TYPE',
  GC_DOMNAME_STATUS      TYPE DD07T-DOMNAME          VALUE 'ZSDSDM_COL_STATUS',
  GC_ACTION_TYPE_DEFAULT TYPE ZSDSFIT033-ACTION_TYPE VALUE '10',
  GC_STATUS_DEFAULT      TYPE ZSDSFIT033-STATUS      VALUE '01',
  GC_NUMBER_OBJECT       TYPE INRI-OBJECT            VALUE 'ZFI001',
  GC_PRINT_1             TYPE SY-UCOMM               VALUE 'PRINT_1',
  GC_CANCEL_1            TYPE SY-UCOMM               VALUE 'CANC_1',
  GC_SMARTFORM_NAME      TYPE TDSFNAME               VALUE 'ZSDSFI009',
  BEGIN OF GC_EXEC_TY,
    NEW     TYPE CHAR2 VALUE 'N',
    DETAIL  TYPE CHAR2 VALUE 'E1',
    REPRINT TYPE CHAR2 VALUE 'E2',
    CANCEL  TYPE CHAR2 VALUE 'E3',
  END OF GC_EXEC_TY.
*----------------------------------------------------------------------*
* ALV VARIABLES
*----------------------------------------------------------------------*
CONSTANTS:
  GC_HEADER_HEIGHT_1 TYPE  I                VALUE 10,
  GC_ALV_HEIGHT_1    TYPE  I                VALUE 90.
*----------------------------------------------------------------------*
* SELECTION-SCREEN
*----------------------------------------------------------------------*
* Text-s01: Customer Selection
SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-S01.
  SELECT-OPTIONS:
   S_KUNNR FOR KNB1-KUNNR OBLIGATORY.
  PARAMETERS: P_BUKRS TYPE KNB1-BUKRS DEFAULT '1000' OBLIGATORY.
SELECTION-SCREEN END OF BLOCK B1.
*BOI CH02
* TEXT-S05: Personal ID Infomation
SELECTION-SCREEN BEGIN OF BLOCK B4 WITH FRAME TITLE TEXT-S05.
  PARAMETERS:
    P_PERNR TYPE PA0002-PERNR MATCHCODE OBJECT ZSDSH_PERNR OBLIGATORY.
SELECTION-SCREEN END OF BLOCK B4.
*EOI CH02
* -------Create Bill Placement
PARAMETERS: RB_NEW RADIOBUTTON GROUP G1 DEFAULT 'X' USER-COMMAND RB1.

SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME .
* Text-s02: Sales Document
  SELECTION-SCREEN BEGIN OF BLOCK B21 WITH FRAME TITLE TEXT-S02.
    SELECT-OPTIONS:
      S_VBELN FOR VBRK-VBELN MODIF ID A,
      S_FKDAT FOR VBRK-FKDAT MODIF ID A,
      S_VKORG FOR VBRK-VKORG OBLIGATORY DEFAULT 1000 MEMORY ID VKO MODIF ID A,
      S_VTWEG FOR VBRK-VTWEG MODIF ID A,
      S_SPART FOR VBRK-SPART MODIF ID A,
      S_VKGRP FOR VBRP-VKGRP MODIF ID A,
      S_VKBUR FOR VBRP-VKBUR MODIF ID A.
  SELECTION-SCREEN END OF BLOCK B21.


  PARAMETERS: P_SELFI AS CHECKBOX USER-COMMAND FI MODIF ID A.
* Text-s03: FI Document
  SELECTION-SCREEN BEGIN OF BLOCK B22 WITH FRAME TITLE TEXT-S03.
    SELECT-OPTIONS:
    S_XBLNR FOR BKPF-XBLNR MODIF ID AFI ,
    S_BELNR FOR BSEG-BELNR MODIF ID AFI .
    PARAMETERS:
    P_BUDAT TYPE BKPF-BUDAT MODIF ID AFI DEFAULT SY-DATUM.
    PARAMETERS:
      P_SPCGL  AS CHECKBOX MODIF ID AFI.
  SELECTION-SCREEN END OF BLOCK B22.

SELECTION-SCREEN END OF BLOCK B2.

SELECTION-SCREEN BEGIN OF BLOCK B23 WITH FRAME TITLE TEXT-S04.
  PARAMETERS:
    P_WTH_RC AS CHECKBOX DEFAULT 'X',
    P_WTH_PJ AS CHECKBOX DEFAULT 'X'.
SELECTION-SCREEN END OF BLOCK B23.
* ------List Existing Bill Placement
PARAMETERS: RB_EXIST RADIOBUTTON GROUP G1.
SELECTION-SCREEN BEGIN OF BLOCK B3 WITH FRAME .
  PARAMETERS:
    RB_E_DET RADIOBUTTON GROUP G2 DEFAULT 'X' USER-COMMAND RB2 MODIF ID B,
    RB_E_RP  RADIOBUTTON GROUP G2 MODIF ID B,
    RB_E_CNC RADIOBUTTON GROUP G2 MODIF ID B.
  SELECT-OPTIONS:
    S_BP_NO FOR ZSDSFIT033-BILLPL_NO MODIF ID B,
    S_BP_DT FOR ZSDSFIT033-BILLPL_DATE MODIF ID B,
    S_AC_TY FOR ZSDSFIT033-ACTION_TYPE MODIF ID B,
    S_STAT  FOR ZSDSFIT033-STATUS MODIF ID B.
SELECTION-SCREEN END OF BLOCK B3.
