*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZSDSV_COL_LOG...................................*
FORM GET_DATA_ZSDSV_COL_LOG.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZSDSFIT046 WHERE
(VIM_WHERETAB) .
    CLEAR ZSDSV_COL_LOG .
ZSDSV_COL_LOG-MANDT =
ZSDSFIT046-MANDT .
ZSDSV_COL_LOG-BUKRS =
ZSDSFIT046-BUKRS .
ZSDSV_COL_LOG-BELNR =
ZSDSFIT046-BELNR .
ZSDSV_COL_LOG-GJAHR =
ZSDSFIT046-GJAHR .
ZSDSV_COL_LOG-BUZEI =
ZSDSFIT046-BUZEI .
ZSDSV_COL_LOG-SEQ =
ZSDSFIT046-SEQ .
ZSDSV_COL_LOG-TRANF_NO =
ZSDSFIT046-TRANF_NO .
ZSDSV_COL_LOG-STATUS_DOC_UPDATE =
ZSDSFIT046-STATUS_DOC_UPDATE .
ZSDSV_COL_LOG-STATUS_FILE =
ZSDSFIT046-STATUS_FILE .
ZSDSV_COL_LOG-FILENAME =
ZSDSFIT046-FILENAME .
ZSDSV_COL_LOG-ERNAM =
ZSDSFIT046-ERNAM .
ZSDSV_COL_LOG-ERDAT =
ZSDSFIT046-ERDAT .
ZSDSV_COL_LOG-ERZMT =
ZSDSFIT046-ERZMT .
<VIM_TOTAL_STRUC> = ZSDSV_COL_LOG.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZSDSV_COL_LOG .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZSDSV_COL_LOG.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZSDSV_COL_LOG-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZSDSFIT046 WHERE
  BUKRS = ZSDSV_COL_LOG-BUKRS AND
  BELNR = ZSDSV_COL_LOG-BELNR AND
  GJAHR = ZSDSV_COL_LOG-GJAHR AND
  BUZEI = ZSDSV_COL_LOG-BUZEI AND
  SEQ = ZSDSV_COL_LOG-SEQ .
    IF SY-SUBRC = 0.
    DELETE ZSDSFIT046 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZSDSFIT046 WHERE
  BUKRS = ZSDSV_COL_LOG-BUKRS AND
  BELNR = ZSDSV_COL_LOG-BELNR AND
  GJAHR = ZSDSV_COL_LOG-GJAHR AND
  BUZEI = ZSDSV_COL_LOG-BUZEI AND
  SEQ = ZSDSV_COL_LOG-SEQ .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZSDSFIT046.
    ENDIF.
ZSDSFIT046-MANDT =
ZSDSV_COL_LOG-MANDT .
ZSDSFIT046-BUKRS =
ZSDSV_COL_LOG-BUKRS .
ZSDSFIT046-BELNR =
ZSDSV_COL_LOG-BELNR .
ZSDSFIT046-GJAHR =
ZSDSV_COL_LOG-GJAHR .
ZSDSFIT046-BUZEI =
ZSDSV_COL_LOG-BUZEI .
ZSDSFIT046-SEQ =
ZSDSV_COL_LOG-SEQ .
ZSDSFIT046-TRANF_NO =
ZSDSV_COL_LOG-TRANF_NO .
ZSDSFIT046-STATUS_DOC_UPDATE =
ZSDSV_COL_LOG-STATUS_DOC_UPDATE .
ZSDSFIT046-STATUS_FILE =
ZSDSV_COL_LOG-STATUS_FILE .
ZSDSFIT046-FILENAME =
ZSDSV_COL_LOG-FILENAME .
ZSDSFIT046-ERNAM =
ZSDSV_COL_LOG-ERNAM .
ZSDSFIT046-ERDAT =
ZSDSV_COL_LOG-ERDAT .
ZSDSFIT046-ERZMT =
ZSDSV_COL_LOG-ERZMT .
    IF SY-SUBRC = 0.
    UPDATE ZSDSFIT046 ##WARN_OK.
    ELSE.
    INSERT ZSDSFIT046 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZSDSV_COL_LOG-UPD_FLAG,
STATUS_ZSDSV_COL_LOG-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZSDSV_COL_LOG.
  SELECT SINGLE * FROM ZSDSFIT046 WHERE
BUKRS = ZSDSV_COL_LOG-BUKRS AND
BELNR = ZSDSV_COL_LOG-BELNR AND
GJAHR = ZSDSV_COL_LOG-GJAHR AND
BUZEI = ZSDSV_COL_LOG-BUZEI AND
SEQ = ZSDSV_COL_LOG-SEQ .
ZSDSV_COL_LOG-MANDT =
ZSDSFIT046-MANDT .
ZSDSV_COL_LOG-BUKRS =
ZSDSFIT046-BUKRS .
ZSDSV_COL_LOG-BELNR =
ZSDSFIT046-BELNR .
ZSDSV_COL_LOG-GJAHR =
ZSDSFIT046-GJAHR .
ZSDSV_COL_LOG-BUZEI =
ZSDSFIT046-BUZEI .
ZSDSV_COL_LOG-SEQ =
ZSDSFIT046-SEQ .
ZSDSV_COL_LOG-TRANF_NO =
ZSDSFIT046-TRANF_NO .
ZSDSV_COL_LOG-STATUS_DOC_UPDATE =
ZSDSFIT046-STATUS_DOC_UPDATE .
ZSDSV_COL_LOG-STATUS_FILE =
ZSDSFIT046-STATUS_FILE .
ZSDSV_COL_LOG-FILENAME =
ZSDSFIT046-FILENAME .
ZSDSV_COL_LOG-ERNAM =
ZSDSFIT046-ERNAM .
ZSDSV_COL_LOG-ERDAT =
ZSDSFIT046-ERDAT .
ZSDSV_COL_LOG-ERZMT =
ZSDSFIT046-ERZMT .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZSDSV_COL_LOG USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZSDSV_COL_LOG-BUKRS TO
ZSDSFIT046-BUKRS .
MOVE ZSDSV_COL_LOG-BELNR TO
ZSDSFIT046-BELNR .
MOVE ZSDSV_COL_LOG-GJAHR TO
ZSDSFIT046-GJAHR .
MOVE ZSDSV_COL_LOG-BUZEI TO
ZSDSFIT046-BUZEI .
MOVE ZSDSV_COL_LOG-SEQ TO
ZSDSFIT046-SEQ .
MOVE ZSDSV_COL_LOG-MANDT TO
ZSDSFIT046-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZSDSFIT046'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZSDSFIT046 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZSDSFIT046'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
