*&---------------------------------------------------------------------*
*& Include          ZSDSFII0030_SELECTION
*&---------------------------------------------------------------------*
*-----------------------------------------------------------------------
* P A R A M E T E R S   &   S E L E C T - O P T I O N S
*-----------------------------------------------------------------------
SELECTION-SCREEN BEGIN OF BLOCK BLOCK1 WITH FRAME TITLE TEXT-001.
SELECT-OPTIONS : S_VBELN   FOR VBAK-VBELN NO INTERVALS MODIF ID CRE.
SELECTION-SCREEN END OF BLOCK BLOCK1.

SELECTION-SCREEN BEGIN OF BLOCK BLOCK2 WITH FRAME TITLE TEXT-002.
SELECT-OPTIONS : S_VBELNS  FOR VBAK-VBELN NO INTERVALS MODIF ID CRE.
SELECTION-SCREEN END OF BLOCK BLOCK2.

SELECTION-SCREEN BEGIN OF BLOCK BLOCK3 WITH FRAME TITLE TEXT-003.
SELECT-OPTIONS : S_IHREZ   FOR VBAK-IHREZ NO-EXTENSION NO INTERVALS MODIF ID CRE.
SELECTION-SCREEN END OF BLOCK BLOCK3.

SELECTION-SCREEN BEGIN OF BLOCK BLOCK4 WITH FRAME TITLE TEXT-004.
SELECT-OPTIONS : S_KUNNR FOR VBAK-KUNNR NO-EXTENSION NO INTERVALS MODIF ID MOD.
SELECT-OPTIONS : S_BSTNK FOR VBAK-BSTNK NO-EXTENSION NO INTERVALS MODIF ID MOD.
SELECTION-SCREEN END OF BLOCK BLOCK4.
