*&---------------------------------------------------------------------*
*& Include          ZSDSFIR0390_TOP
*&---------------------------------------------------------------------*
*----------------------------------------------------------------------*
* TABLES
*----------------------------------------------------------------------*
TABLES:
  VBRK,
  BKPF,
  LIKP,
  LIPS,
  BSEG,
  VBPA,
  KNB1,
  ZSDSFIC027,
  ZSDSFIT040,
  SSCRFIELDS.
*----------------------------------------------------------------------*
* TYPES
*----------------------------------------------------------------------*
TYPES:
  BEGIN OF TS_T001,
    BUKRS TYPE T001-BUKRS,
    WAERS TYPE T001-WAERS,
    KTOPL TYPE T001-KTOPL,
  END OF TS_T001,
  BEGIN OF TS_KNA1,
    KUNNR TYPE KNA1-KUNNR,
    NAME1 TYPE KNA1-NAME1,
    XCPDK TYPE KNA1-XCPDK, "CH04 420000327+
  END OF TS_KNA1,
  TT_KNA1 TYPE SORTED TABLE OF TS_KNA1 WITH NON-UNIQUE KEY KUNNR,
  BEGIN OF TS_KNA1_027,
    KUNNR     TYPE KNB1-KUNNR,
    BUSAB     TYPE KNB1-BUSAB,
    PIC_PERNR TYPE ZSDSFIC027-PIC_PERNR,
    FR_KUNNR  TYPE ZSDSFIC027-FR_KUNNR,
    TO_KUNNR  TYPE ZSDSFIC027-TO_KUNNR,
  END OF TS_KNA1_027,
  TT_KNA1_027 TYPE SORTED TABLE OF TS_KNA1_027 WITH NON-UNIQUE KEY KUNNR,
  BEGIN OF TS_CUST_KEY,
    KUNNR TYPE KNA1-KUNNR,
  END OF TS_CUST_KEY,
  TT_CUST_KEY TYPE SORTED TABLE OF TS_CUST_KEY WITH NON-UNIQUE KEY KUNNR,
  BEGIN OF TS_KNVV_027,
    KUNNR     TYPE KNVV-KUNNR,
    VKORG     TYPE KNVV-VKORG,
    VTWEG     TYPE KNVV-VTWEG,
    SPART     TYPE KNVV-SPART,
    VKBUR     TYPE KNVV-VKBUR,
    VKGRP     TYPE KNVV-VKGRP,     "CH07- "CH08+
    FR_VKGRP  TYPE ZSDSFIC027-FR_VKGRP, "CH07+
    TO_VKGRP  TYPE ZSDSFIC027-FR_VKGRP, "CH07+
    PIC_PERNR TYPE ZSDSFIC027-PIC_PERNR,
    BUSAB     TYPE KNB1-BUSAB,
    FR_KUNNR  TYPE ZSDSFIC027-FR_KUNNR,
    TO_KUNNR  TYPE ZSDSFIC027-TO_KUNNR,
    FR_BUSAB  TYPE KNB1-BUSAB,
    TO_BUSAB  TYPE KNB1-BUSAB,
  END OF TS_KNVV_027,
  TT_KNVV_027 TYPE SORTED TABLE OF TS_KNVV_027 WITH NON-UNIQUE KEY KUNNR VKORG VTWEG SPART VKBUR VKGRP, "CH07- "CH08+
*  TT_KNVV_027 TYPE SORTED TABLE OF TS_KNVV_027 WITH NON-UNIQUE KEY KUNNR VKORG VTWEG SPART VKBUR FR_VKGRP TO_VKGRP, "CH07+ "CH08-
*BOI CH08
  BEGIN OF TS_CUSTSD_KEY,
    KUNNR TYPE KNA1-KUNNR,
    VKORG TYPE VBRK-VKORG,
    VTWEG TYPE VBRK-VTWEG,
    SPART TYPE VBRK-SPART,
    VKGRP TYPE VBRP-VKGRP,
    VKBUR TYPE VBRP-VKBUR,
    VBELN TYPE VBRK-VBELN,
  END OF TS_CUSTSD_KEY,
  TT_CUSTSD_KEY TYPE SORTED TABLE OF  TS_CUSTSD_KEY WITH NON-UNIQUE KEY KUNNR VKORG VTWEG SPART VKGRP VKBUR,
*EOI CH08
  BEGIN OF TS_KNB1,
    KUNNR TYPE KNB1-KUNNR,
    BUKRS TYPE KNB1-BUKRS,
    BUSAB TYPE KNB1-BUSAB,
  END OF TS_KNB1,
  TT_KNB1 TYPE SORTED TABLE OF TS_KNB1 WITH NON-UNIQUE KEY KUNNR BUKRS,
*BOI CH04 420000327
  BEGIN OF TS_BSEC,
    BUKRS  TYPE BSEC-BUKRS,
    BELNR  TYPE BSEC-BELNR,
    GJAHR  TYPE BSEC-GJAHR,
    BUZEI  TYPE BSEC-BUZEI,
    NATION TYPE ADRC-NATION,
    NAME1  TYPE ADRC-NAME1,
  END OF TS_BSEC,
  TT_BSEC TYPE SORTED TABLE OF TS_BSEC WITH NON-UNIQUE KEY BUKRS BELNR GJAHR BUZEI NATION,
  BEGIN OF TS_CUST_ADRC,
    ADDRNUMBER TYPE ADRC-ADDRNUMBER,
    NATION     TYPE ADRC-NATION,
    NAME1      TYPE ADRC-NAME1,
  END OF TS_CUST_ADRC,
  TT_CUST_ADRC TYPE SORTED TABLE OF TS_CUST_ADRC WITH NON-UNIQUE KEY ADDRNUMBER NATION,
*EOI CH04 420000327
  BEGIN OF TS_FIDOC,
    BUKRS TYPE BSID_VIEW-BUKRS,
    BELNR TYPE BSID_VIEW-BELNR,
    GJAHR TYPE BSID_VIEW-GJAHR,
    BUZEI TYPE BSID_VIEW-BUZEI,
    VBELN TYPE BSID_VIEW-VBELN,
    BLART TYPE BSID_VIEW-BLART,
    KUNNR TYPE BSID_VIEW-KUNNR,
    XBLNR TYPE BSID_VIEW-XBLNR,
    SGTXT TYPE BSID_VIEW-SGTXT,
    DMBTR TYPE BSID_VIEW-DMBTR,
    HKONT TYPE BSID_VIEW-HKONT,
    UMSKZ TYPE BSID_VIEW-UMSKZ,
    BUDAT TYPE BSID_VIEW-BUDAT,
    BLDAT TYPE BSID_VIEW-BLDAT, "<<F36K909945++
    ZFBDT TYPE BSID_VIEW-ZFBDT,
    ZBD1T TYPE BSID_VIEW-ZBD1T,
    ZBD2T TYPE BSID_VIEW-ZBD2T,
    ZBD3T TYPE BSID_VIEW-ZBD3T,
    SHKZG TYPE BSID_VIEW-SHKZG,
    REBZG TYPE BSID_VIEW-REBZG,
    ZTERM TYPE BSID_VIEW-ZTERM,
    ZUONR TYPE BSID_VIEW-ZUONR,
    XREF1 TYPE BSID_VIEW-XREF1, "CH04 420000219+
    VKORG TYPE VBRK-VKORG,
    VTWEG TYPE VBRK-VTWEG,
    SPART TYPE VBRK-SPART,
    POSNR TYPE VBRP-POSNR,
    VKGRP TYPE VBRP-VKGRP,
    VKBUR TYPE VBRP-VKBUR,
    AUBEL TYPE VBRP-AUBEL,
    VGBEL TYPE VBRP-VGBEL,
  END OF TS_FIDOC,
  TT_FIDOC TYPE SORTED TABLE OF TS_FIDOC WITH NON-UNIQUE KEY BUKRS BELNR GJAHR VBELN,
  BEGIN OF TS_PA0002,
    PERNR TYPE PA0002-PERNR,
    VORNA TYPE PA0002-VORNA,
    NACHN TYPE PA0002-NACHN,
  END OF TS_PA0002,
  TT_PA0002 TYPE SORTED TABLE OF TS_PA0002 WITH NON-UNIQUE KEY PERNR,
  BEGIN OF TS_PRPS,
    POSID TYPE PRPS-POSID,
    POST1 TYPE PRPS-POST1,
  END OF TS_PRPS,
  TT_PRPS TYPE SORTED TABLE OF TS_PRPS WITH NON-UNIQUE KEY POSID,
  BEGIN OF TS_VBKD_SO,
    VBELN TYPE VBKD-VBELN,
    BSTKD TYPE VBKD-BSTKD,
  END OF TS_VBKD_SO,
  TT_VBKD_SO TYPE SORTED TABLE OF TS_VBKD_SO WITH NON-UNIQUE KEY VBELN,
  TT_040     TYPE SORTED TABLE OF ZSDSFIT040 WITH NON-UNIQUE KEY BUKRS BELNR GJAHR SEQNO,
  TT_024     TYPE SORTED TABLE OF ZSDSFIC024 WITH NON-UNIQUE KEY KUNNR,
  BEGIN OF TS_BILLPL,
    BUKRS        TYPE ZSDSFIT033-BUKRS,
    BELNR        TYPE ZSDSFIT035-BELNR,
    GJAHR        TYPE ZSDSFIT035-GJAHR,
    BUZEI        TYPE ZSDSFIT035-BUZEI,
    BILLPL_NO    TYPE ZSDSFIT033-BILLPL_NO,
    BILLPL_DATE  TYPE ZSDSFIT033-BILLPL_DATE,
    BILLPL_PMTDT TYPE ZSDSFIT033-BILLPL_PMTDT,
    WORK_DATE    TYPE ZSDSFIT029-WORK_DATE, "CH02+
  END OF TS_BILLPL,
  TT_BILLPL  TYPE SORTED TABLE OF TS_BILLPL WITH NON-UNIQUE KEY BUKRS BELNR GJAHR BUZEI,

  TT_RANGE_I TYPE RANGE OF I,
  BEGIN OF TS_DAY_RANGE,
    SEQNO TYPE ZSDSCAC001-SEQUENCE,
    RANGE TYPE TT_RANGE_I,
    DESC  TYPE ZSDSCAC001-VDESC,
  END OF TS_DAY_RANGE,
  TT_DAY_RANGE TYPE SORTED TABLE OF TS_DAY_RANGE WITH NON-UNIQUE KEY SEQNO,
  BEGIN OF TS_SKAT,
    SAKNR TYPE SKAT-SAKNR,
    TXT20 TYPE SKAT-TXT20,
  END OF TS_SKAT,
  TT_SKAT TYPE SORTED TABLE OF TS_SKAT WITH NON-UNIQUE KEY SAKNR,
  BEGIN OF TS_T074T,
    SHBKZ TYPE T074T-SHBKZ,
    LTEXT TYPE T074T-LTEXT,
  END OF TS_T074T,
  TT_T074T TYPE SORTED TABLE OF TS_T074T WITH NON-UNIQUE KEY SHBKZ,
  BEGIN OF TS_VBELN_KEY,
    VBELN TYPE VBRK-VBELN,
  END OF TS_VBELN_KEY,
  TT_VBELN_KEY TYPE SORTED TABLE OF TS_VBELN_KEY WITH NON-UNIQUE KEY VBELN,
  BEGIN OF TS_VBPA,
    VBELN TYPE VBPA-VBELN,
    POSNR TYPE VBPA-POSNR,
    PARVW TYPE VBPA-PARVW,
    PERNR TYPE VBPA-PERNR,
  END OF TS_VBPA,
  TT_VBPA TYPE SORTED TABLE OF TS_VBPA WITH NON-UNIQUE KEY VBELN,
  BEGIN OF TS_DO,
    VBELN_DO   TYPE LIKP-VBELN,
    POSNR_DO   TYPE LIPS-POSNR,
*    KUNAG      TYPE LIKP-KUNAG,  "CH04 420000327-
    KUNNR      TYPE VBPA-KUNNR,   "CH04 420000327+
    BLDAT      TYPE LIKP-BLDAT,
    VKORG      TYPE LIKP-VKORG,
    VTWEG      TYPE LIPS-VTWEG,
    SPART      TYPE LIPS-SPART,
    VKBUR      TYPE LIPS-VKBUR,
    VKGRP      TYPE LIPS-VKGRP,
    LFIMG      TYPE LIPS-LFIMG,
    VBELN_SO   TYPE VBAP-VBELN,
    POSNR_SO   TYPE VBAP-POSNR,
    NETWR_SO   TYPE VBAP-NETWR,
    KWMENG_SO  TYPE VBAP-KWMENG,
    WAERK      TYPE VBAK-WAERK,
    PS_PSP_PNR TYPE VBAP-PS_PSP_PNR, "wbs
    PSPHI      TYPE PRPS-PSPHI,   "project
    ADRNR      TYPE VBPA-ADRNR,   "CH04 420000327+
  END OF TS_DO,
  TT_DO TYPE SORTED TABLE OF TS_DO WITH NON-UNIQUE KEY VBELN_DO POSNR_DO VBELN_SO POSNR_SO,
  BEGIN OF TS_PRPS2,
    PSPNR TYPE PRPS-PSPNR,
    POST1 TYPE PRPS-POST1,
  END OF TS_PRPS2,
  TT_PRPS2 TYPE SORTED TABLE OF TS_PRPS2 WITH NON-UNIQUE KEY PSPNR,
  TT_041   TYPE SORTED TABLE OF ZSDSFIT041 WITH NON-UNIQUE KEY VBELN SEQNO,
  BEGIN OF TS_VBFA,
    VBELV   TYPE VBFA-VBELV,
    POSNV   TYPE VBFA-POSNV,
    VBTYP_V TYPE VBFA-VBTYP_V,
    VBELN   TYPE VBFA-VBELN,
    POSNN   TYPE VBFA-POSNN,
    VBTYP_N TYPE VBFA-VBTYP_N,
  END OF TS_VBFA,
  TT_VBFA TYPE SORTED TABLE OF TS_VBFA WITH NON-UNIQUE KEY VBELV POSNV,
  BEGIN OF TS_BILL,
    VBELN TYPE VBRK-VBELN,
    FKDAT TYPE VBRK-FKDAT,
  END OF TS_BILL,
  TT_BILL TYPE SORTED TABLE OF TS_BILL WITH NON-UNIQUE KEY VBELN,
  BEGIN OF TS_033_035_2,
    VBELN       TYPE ZSDSFIT035-VBELN,
    BILLPL_NO   TYPE ZSDSFIT033-BILLPL_NO,
    BILLPL_DATE TYPE ZSDSFIT033-BILLPL_DATE,
  END OF TS_033_035_2,
  TT_033_035_2 TYPE SORTED TABLE OF TS_033_035_2 WITH NON-UNIQUE KEY VBELN,
  BEGIN OF TS_ISLIST,
    VALUE TYPE ZSDSFIT040-ISSUE_LIST,
    TEXT  TYPE DD07T-DDTEXT,
  END OF TS_ISLIST,
  TT_ISLIST TYPE SORTED TABLE OF TS_ISLIST WITH UNIQUE KEY VALUE,
  BEGIN OF TS_CLEAR_DOC,
    BUKRS TYPE BSID_VIEW-BUKRS,
    REBZG TYPE BSID_VIEW-REBZG,
    REBZJ TYPE BSID_VIEW-REBZJ,
    REBZZ TYPE BSID_VIEW-REBZZ,
    GJAHR TYPE BSID_VIEW-GJAHR,
    BELNR TYPE BSID_VIEW-BELNR,
    BUZEI TYPE BSID_VIEW-BUZEI,
    SHKZG TYPE BSID_VIEW-SHKZG,
    DMBTR TYPE BSID_VIEW-DMBTR,
    AUGBL TYPE BSID_VIEW-AUGBL, "<<F36K909945++
    USED  TYPE FLAG, "CH06+
  END OF TS_CLEAR_DOC,
  TT_CLEAR_DOC TYPE SORTED TABLE OF TS_CLEAR_DOC WITH NON-UNIQUE KEY BUKRS REBZG REBZJ REBZZ,
  TT_CLEAR_CHK TYPE SORTED TABLE OF TS_CLEAR_DOC WITH NON-UNIQUE KEY BUKRS BELNR GJAHR BUZEI,
*BOI CH04 420000219
  BEGIN OF TS_CLEAR_MGRTE,
    BUKRS TYPE BSID_VIEW-BUKRS,
    XREF1 TYPE BSID_VIEW-XREF1,
    XBLNR TYPE BSID_VIEW-XBLNR,
    GJAHR TYPE BSID_VIEW-GJAHR,
    BELNR TYPE BSID_VIEW-BELNR,
    BUZEI TYPE BSID_VIEW-BUZEI,
    SHKZG TYPE BSID_VIEW-SHKZG,
    UMSKZ TYPE BSID_VIEW-UMSKZ,
    DMBTR TYPE BSID_VIEW-DMBTR,
    USED  TYPE FLAG, "CH06+
  END OF TS_CLEAR_MGRTE,
  TT_CLEAR_MGRTE     TYPE SORTED TABLE OF TS_CLEAR_MGRTE WITH NON-UNIQUE KEY BUKRS XREF1 GJAHR BELNR,
  TT_CLEAR_MGRTE_CHK TYPE SORTED TABLE OF TS_CLEAR_MGRTE WITH NON-UNIQUE KEY BUKRS BELNR GJAHR BUZEI,

*EOI CH04 420000219
  TT_TVGRT           TYPE SORTED TABLE OF TVGRT  WITH NON-UNIQUE  KEY VKGRP,
  TT_TVKBT           TYPE SORTED TABLE OF TVKBT  WITH NON-UNIQUE  KEY VKBUR,
* BOI CH04 420000327
  BEGIN OF TS_VBFA_INV_DO,
    VBELN TYPE VBFA-VBELN,
    VBELV TYPE VBFA-VBELV,
  END OF TS_VBFA_INV_DO,
  TT_VBFA_INV_DO TYPE SORTED TABLE OF TS_VBFA_INV_DO WITH NON-UNIQUE KEY VBELN,
* EOI CH04 420000327
  BEGIN OF TS_DATA1,
    PIC_PERNR     TYPE ZSDSFIC027-PIC_PERNR,
    PIC_NAME1     TYPE TEXT80,
    VBELN_BILL    TYPE VBRK-VBELN,
    BUKRS         TYPE BKPF-BUKRS,
    BELNR         TYPE BKPF-BELNR,
    GJAHR         TYPE BKPF-GJAHR,
    BUZEI         TYPE BSID_VIEW-BUZEI,
    XBLNR         TYPE BSID_VIEW-XBLNR,
    XREF1         TYPE BSID_VIEW-XREF1, "CH04 420000219+
    KUNNR         TYPE BSID_VIEW-KUNNR,
    KUNNR_NAME1   TYPE KNA1-NAME1,
    BUSAB         TYPE KNB1-BUSAB,
    SGTXT         TYPE BSID_VIEW-SGTXT,
    POST1         TYPE PRPS-POST1,
    BSTKD         TYPE VBKD-BSTKD,
    INV_REMARK    TYPE TEXT40,
    VBELN_DO      TYPE LIKP-VBELN,
    RPDAT         TYPE SY-DATUM,
    BUDAT         TYPE BSID_VIEW-BUDAT,
    DUEDT1        TYPE SY-DATUM,
    NEW_DUEDT2    TYPE ZSDSFIT040-NEW_DUEDT2,
    NEW_DUEDT3    TYPE ZSDSFIT040-NEW_DUEDT3,
    INV_AGE       TYPE I,
    RNG_INV_AGE   TYPE TEXT20,
    OVDUE1        TYPE I,
    OVDUE2        TYPE I,
    OVDUE3        TYPE I,
    WITHIN_DUE1   TYPE TEXT20,
    RNG_OVDUE1    TYPE TEXT20,
    WITHIN_DUE2   TYPE TEXT20,
    RNG_OVDUE2    TYPE TEXT20,
    WITHIN_DUE3   TYPE TEXT20,
    RNG_OVDUE3    TYPE TEXT20,
    DMBTR         TYPE ZSDSFIT035-BILLPL_AMT,
    DMBTR_REMAIN  TYPE ZSDSFIT035-BILLPL_AMT,
    WAERS         TYPE T001-WAERS,
    HKONT_TX      TYPE TEXT30,
    VKGRP         TYPE VBRP-VKGRP,
    VKGRP_TX      TYPE TVGRT-BEZEI,
    VKBUR         TYPE VBRP-VKBUR,
    VKBUR_TX      TYPE TVKBT-BEZEI,
    BILLPL_NO     TYPE ZSDSFIT033-BILLPL_NO,
    BILLPL_DATE   TYPE ZSDSFIT033-BILLPL_DATE,
    ISSUE_LIST    TYPE ZSDSFIT040-ISSUE_LIST,
    ISSUE_LIST_TX TYPE DD07T-DDTEXT,
    FOLLOWDT      TYPE ZSDSFIT040-FOLLOWDT,
    TEXT1         TYPE TEXT50,       "CH04 420000332+
    TEXT2         TYPE TEXT50,       "CH04 420000332+
    TEXT3         TYPE TEXT50,       "CH04 420000332+
*    DETAIL1       TYPE ZSDSFIT040-DETAIL1, "CH04 420000332-
*    DETAIL2       TYPE ZSDSFIT040-DETAIL2, "CH04 420000332-
*    DETAIL3       TYPE ZSDSFIT040-DETAIL3, "CH04 420000332-
    SALEMAN       TYPE VBPA-PERNR,
    SALEMAN_NAME  TYPE TEXT80,
    ZTERM         TYPE BSID_VIEW-ZTERM,
    ZUONR         TYPE BSID_VIEW-ZUONR,
    UMSKZ         TYPE BSID_VIEW-UMSKZ,
    UPD_DATE      TYPE ZSDSFIT040-UPD_DATE,
    UPD_TIME      TYPE ZSDSFIT040-UPD_TIME,
    UPD_USER      TYPE ZSDSFIT040-UPD_USER,
    INDX          TYPE SY-TABIX,
    EXIST         TYPE FLAG,
    SEQNO         TYPE ZSDSFIT040-SEQNO,
    CHANGE_TX     TYPE FLAG,    "CH04 420000332
  END OF TS_DATA1,
  TT_DATA1 TYPE STANDARD TABLE OF TS_DATA1,
  BEGIN OF TS_DATA2,
    CMPFG         TYPE ZSDSFIT041-CMPFG,
    PIC_PERNR     TYPE ZSDSFIC027-PIC_PERNR,
    PIC_NAME1     TYPE TEXT80,
    VBELN_DO      TYPE ZSDSFIT041-VBELN,
    KUNNR         TYPE BSID_VIEW-KUNNR,
    KUNNR_NAME1   TYPE KNA1-NAME1,
    BUSAB         TYPE KNB1-BUSAB,
    PSPHI         TYPE PRPS-PSPHI,
    POST1         TYPE PRPS-POST1,
    BSTKD         TYPE VBKD-BSTKD,
    INV_REMARK    TYPE TEXT40,
    RPDAT         TYPE SY-DATUM,
    BLDAT         TYPE LIKP-BLDAT,
    DO_AGE        TYPE I,
    RNG_DO_AGE    TYPE TEXT20,
    NETWR         TYPE VBAK-NETWR,
    WAERK         TYPE VBAK-WAERK,
    VKGRP         TYPE VBAK-VKGRP,
    VKGRP_TX      TYPE TVGRT-BEZEI,
    VKBUR         TYPE VBAK-VKBUR,
    VKBUR_TX      TYPE TVKBT-BEZEI,
    VBELN_BILL    TYPE VBRK-VBELN,
    FKDAT         TYPE VBRK-FKDAT,
    BILLPL_NO     TYPE ZSDSFIT033-BILLPL_NO,
    BILLPL_DATE   TYPE ZSDSFIT033-BILLPL_DATE,
    ISSUE_LIST    TYPE ZSDSFIT041-ISSUE_LIST,
    ISSUE_LIST_TX TYPE DD07T-DDTEXT,
    FOLLOWDT      TYPE ZSDSFIT041-FOLLOWDT,
    TEXT1         TYPE TEXT50,       "CH04 420000332+
    TEXT2         TYPE TEXT50,       "CH04 420000332+
    TEXT3         TYPE TEXT50,       "CH04 420000332+
*    DETAIL1       TYPE ZSDSFIT041-DETAIL1, "CH04 420000332-
*    DETAIL2       TYPE ZSDSFIT041-DETAIL2, "CH04 420000332-
*    DETAIL3       TYPE ZSDSFIT041-DETAIL3, "CH04 420000332-
    SALEMAN       TYPE VBPA-PERNR,
    SALEMAN_NAME  TYPE TEXT80,
    UPD_DATE      TYPE ZSDSFIT041-UPD_DATE,
    UPD_TIME      TYPE ZSDSFIT041-UPD_TIME,
    UPD_USER      TYPE ZSDSFIT041-UPD_USER,
    INDX          TYPE SY-TABIX,
    EXIST         TYPE FLAG,
    SEQNO         TYPE ZSDSFIT040-SEQNO,
    CHANGE_TX     TYPE FLAG,  "CH04 420000332
  END OF TS_DATA2,
  TT_DATA2 TYPE STANDARD TABLE OF TS_DATA2.

*----------------------------------------------------------------------*
* CONSTANT
*----------------------------------------------------------------------*
CONSTANTS:
  GC_KOART_CUST     TYPE BSEG-KOART VALUE 'D',
  GC_PARVW_SALESMAN TYPE VBPA-PARVW VALUE 'VE',
  GC_VBTYP_DO       TYPE VBFA-VBTYP_N VALUE 'J',
  GC_VBTYP_BILL     TYPE VBFA-VBTYP_N VALUE 'M',
  GC_DOMNAME_ISLIST TYPE DD07T-DOMNAME VALUE 'ZSDSDM_ISLIST',
  GC_SHKZG_CREDIT   TYPE BSID_VIEW-SHKZG VALUE 'H',
  GC_SHKZG_DEBIT    TYPE BSID_VIEW-SHKZG VALUE 'S',
  BEGIN OF GC_EXEC_TY,
    FI TYPE CHAR2 VALUE 'FI',
    DO TYPE CHAR2 VALUE 'DO',
  END OF GC_EXEC_TY,
  GC_BLART_MIGRATE   TYPE BKPF-BLART VALUE 'Z1', "CH04 420000219+
  GC_TDOBJECT_DETAIL TYPE THEAD-TDOBJECT VALUE  'ZSDSFI001'.  "CH04 420000332+
*----------------------------------------------------------------------*
* VARIABLE
*----------------------------------------------------------------------*
DATA:
  GF_EXEC_TY TYPE CHAR2 ##NEEDED.
*----------------------------------------------------------------------*
* WORK-AREA
*----------------------------------------------------------------------*
DATA:
  GS_T001 TYPE TS_T001 ##NEEDED.

*----------------------------------------------------------------------*
* INTERNAL TABLE
*----------------------------------------------------------------------*
DATA:
  GT_DATA1     TYPE TT_DATA1 ##NEEDED,
  GT_DATA1_OLD TYPE TT_DATA1 ##NEEDED,
  GT_DATA2     TYPE TT_DATA2 ##NEEDED,
  GT_DATA2_OLD TYPE TT_DATA2 ##NEEDED,
  GT_DAY_RANGE TYPE TT_DAY_RANGE ##NEEDED,
  GT_ISLIST    TYPE TT_ISLIST ##NEEDED.
*----------------------------------------------------------------------*
* RANGES
*----------------------------------------------------------------------*
DATA:
*  GRT_BLART TYPE RANGE OF BKPF-BLART      ##NEEDED,
*  GRT_SHKZG TYPE RANGE OF BSID_VIEW-SHKZG ##NEEDED,
  GRT_GBSTK TYPE RANGE OF LIKP-GBSTK      ##NEEDED,
  GRT_RPDAT TYPE RANGE OF SY-DATUM        ##NEEDED.
*----------------------------------------------------------------------*
* ALV DECLARATION
*----------------------------------------------------------------------*
DEFINE MC_SHOW_PROGRESS.
  IF sy-batch IS INITIAL.
*   Show progress online
    CALL FUNCTION 'SAPGUI_PROGRESS_INDICATOR'
      EXPORTING
        percentage = &1 ##NUMBER_OK
        text       = &2.
  ELSE.
*   Show message step in background
    MESSAGE i000(38) WITH &2 space space space.
  ENDIF.
END-OF-DEFINITION.
DEFINE %FCAT.
  <fcat>-scrtext_s = <fcat>-scrtext_m =
  <fcat>-scrtext_l = <fcat>-coltext =
  <fcat>-seltext   = <fcat>-tooltip =
  <fcat>-reptext   = &1.
END-OF-DEFINITION.
CONSTANTS:
  GC_HEADER_HEIGHT_1 TYPE  I                VALUE 15,
  GC_ALV_HEIGHT_1    TYPE  I                VALUE 90,
  GC_TRUE            TYPE FLAG              VALUE 'X'.
DATA:
  GF_EDIT    TYPE  CHAR1       ##NEEDED.


*----------------------------------------------------------------------*
* SELECTION-SCREEN
*----------------------------------------------------------------------*
SELECTION-SCREEN BEGIN OF BLOCK BLK1 WITH FRAME TITLE TEXT-S01.
  PARAMETERS:
    RB_BILL RADIOBUTTON GROUP G1 DEFAULT 'X' USER-COMMAND RB1,
    RB_DO   RADIOBUTTON GROUP G1.
SELECTION-SCREEN END OF BLOCK BLK1 .
SELECTION-SCREEN BEGIN OF BLOCK BLK2 WITH FRAME TITLE TEXT-S02.
  SELECT-OPTIONS:
  S_BUKRS FOR BKPF-BUKRS OBLIGATORY DEFAULT 1000 NO-EXTENSION NO INTERVALS,
  S_BILL  FOR VBRK-VBELN MODIF ID FI,
  S_BELNR FOR BKPF-BELNR MODIF ID FI,
  S_DO    FOR LIKP-VBELN MODIF ID DO,
  S_KUNNR FOR BSEG-KUNNR OBLIGATORY.
  PARAMETERS:
    CB_OPEN AS CHECKBOX DEFAULT 'X' MODIF ID FI,
    CB_SPEC AS CHECKBOX MODIF ID FI.
  SELECT-OPTIONS:
  S_BLART  FOR BKPF-BLART,
  S_UMSKZ  FOR BSEG-UMSKZ MODIF ID FI,
  S_XBLNR  FOR BKPF-XBLNR MODIF ID FI,
  S_VKORGF FOR LIKP-VKORG MODIF ID FI,
  S_VKORGD FOR LIKP-VKORG DEFAULT 1000 MODIF ID DO,
  S_VTWEG FOR LIPS-VTWEG,
  S_SPART FOR LIPS-SPART,
  S_VKGRP FOR LIPS-VKGRP,
  S_VKBUR FOR LIKP-VKBUR,
  S_SALEM FOR VBPA-PERNR,
  S_PIC   FOR ZSDSFIC027-PIC_PERNR,
  S_BUSAB FOR KNB1-BUSAB.
  PARAMETERS:
  P_RPDAT TYPE SY-DATUM OBLIGATORY DEFAULT SY-DATUM.
  SELECT-OPTIONS:
  S_FLWDT FOR ZSDSFIT040-FOLLOWDT,
  S_UPDDT FOR ZSDSFIT040-UPD_DATE.
  PARAMETERS: P_COMP AS CHECKBOX MODIF ID DO.
SELECTION-SCREEN END OF BLOCK BLK2 .
