*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZSDSV_COL_INFO..................................*
FORM GET_DATA_ZSDSV_COL_INFO.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZSDSFIT029 WHERE
(VIM_WHERETAB) .
    CLEAR ZSDSV_COL_INFO .
ZSDSV_COL_INFO-MANDT =
ZSDSFIT029-MANDT .
ZSDSV_COL_INFO-DATA_TYPE =
ZSDSFIT029-DATA_TYPE .
ZSDSV_COL_INFO-BUKRS =
ZSDSFIT029-BUKRS .
ZSDSV_COL_INFO-BELNR =
ZSDSFIT029-BELNR .
ZSDSV_COL_INFO-GJAHR =
ZSDSFIT029-GJAHR .
ZSDSV_COL_INFO-BUZEI =
ZSDSFIT029-BUZEI .
ZSDSV_COL_INFO-SEQ =
ZSDSFIT029-SEQ .
ZSDSV_COL_INFO-VBELN_VF =
ZSDSFIT029-VBELN_VF .
ZSDSV_COL_INFO-BILLPL_NO =
ZSDSFIT029-BILLPL_NO .
ZSDSV_COL_INFO-BILLPL_DATE =
ZSDSFIT029-BILLPL_DATE .
ZSDSV_COL_INFO-PERNR =
ZSDSFIT029-PERNR .
ZSDSV_COL_INFO-WORK_DATE =
ZSDSFIT029-WORK_DATE .
ZSDSV_COL_INFO-KUNNR =
ZSDSFIT029-KUNNR .
ZSDSV_COL_INFO-UMSKZ =
ZSDSFIT029-UMSKZ .
ZSDSV_COL_INFO-XBLNR =
ZSDSFIT029-XBLNR .
ZSDSV_COL_INFO-BLDAT =
ZSDSFIT029-BLDAT .
ZSDSV_COL_INFO-BUDAT =
ZSDSFIT029-BUDAT .
ZSDSV_COL_INFO-FAEDT =
ZSDSFIT029-FAEDT .
ZSDSV_COL_INFO-WRBTR =
ZSDSFIT029-WRBTR .
ZSDSV_COL_INFO-WAERS =
ZSDSFIT029-WAERS .
ZSDSV_COL_INFO-DEDUCT_AMT =
ZSDSFIT029-DEDUCT_AMT .
ZSDSV_COL_INFO-PAYNO =
ZSDSFIT029-PAYNO .
ZSDSV_COL_INFO-BRNCH =
ZSDSFIT029-BRNCH .
ZSDSV_COL_INFO-BAL_AMT =
ZSDSFIT029-BAL_AMT .
ZSDSV_COL_INFO-EXPS_AMT =
ZSDSFIT029-EXPS_AMT .
ZSDSV_COL_INFO-AUFNR_EXPS =
ZSDSFIT029-AUFNR_EXPS .
ZSDSV_COL_INFO-WHT_AMT =
ZSDSFIT029-WHT_AMT .
ZSDSV_COL_INFO-FEE =
ZSDSFIT029-FEE .
ZSDSV_COL_INFO-AUFNR_FEE =
ZSDSFIT029-AUFNR_FEE .
ZSDSV_COL_INFO-RECEIVED_AMT =
ZSDSFIT029-RECEIVED_AMT .
ZSDSV_COL_INFO-RETENTION =
ZSDSFIT029-RETENTION .
ZSDSV_COL_INFO-INCOME_AMT =
ZSDSFIT029-INCOME_AMT .
ZSDSV_COL_INFO-CASH_CON =
ZSDSFIT029-CASH_CON .
ZSDSV_COL_INFO-ADV_AMT =
ZSDSFIT029-ADV_AMT .
ZSDSV_COL_INFO-PAYIN_AMT =
ZSDSFIT029-PAYIN_AMT .
ZSDSV_COL_INFO-REMAIN_AMT =
ZSDSFIT029-REMAIN_AMT .
ZSDSV_COL_INFO-REMAIN_C_AMT =
ZSDSFIT029-REMAIN_C_AMT .
ZSDSV_COL_INFO-KOSTL =
ZSDSFIT029-KOSTL .
ZSDSV_COL_INFO-PRCTR =
ZSDSFIT029-PRCTR .
ZSDSV_COL_INFO-HBKID =
ZSDSFIT029-HBKID .
ZSDSV_COL_INFO-HKTID =
ZSDSFIT029-HKTID .
ZSDSV_COL_INFO-ZBANK_ITEM =
ZSDSFIT029-ZBANK_ITEM .
ZSDSV_COL_INFO-PYMT_METHOD =
ZSDSFIT029-PYMT_METHOD .
ZSDSV_COL_INFO-ACTION_TYPE =
ZSDSFIT029-ACTION_TYPE .
ZSDSV_COL_INFO-STATUS =
ZSDSFIT029-STATUS .
ZSDSV_COL_INFO-REMARK =
ZSDSFIT029-REMARK .
ZSDSV_COL_INFO-PAYMENT_DATE =
ZSDSFIT029-PAYMENT_DATE .
ZSDSV_COL_INFO-RECEIVED_DATE =
ZSDSFIT029-RECEIVED_DATE .
ZSDSV_COL_INFO-RECEIPT_NO =
ZSDSFIT029-RECEIPT_NO .
ZSDSV_COL_INFO-BANK_DATE =
ZSDSFIT029-BANK_DATE .
ZSDSV_COL_INFO-CHEQUE_NO =
ZSDSFIT029-CHEQUE_NO .
ZSDSV_COL_INFO-BANKN =
ZSDSFIT029-BANKN .
ZSDSV_COL_INFO-BANKL =
ZSDSFIT029-BANKL .
ZSDSV_COL_INFO-TRANF_NO =
ZSDSFIT029-TRANF_NO .
ZSDSV_COL_INFO-BANKK =
ZSDSFIT029-BANKK .
ZSDSV_COL_INFO-VBELN =
ZSDSFIT029-VBELN .
ZSDSV_COL_INFO-FKDAT =
ZSDSFIT029-FKDAT .
ZSDSV_COL_INFO-CHEQUE_DATE =
ZSDSFIT029-CHEQUE_DATE .
ZSDSV_COL_INFO-FOLLOW_DATE =
ZSDSFIT029-FOLLOW_DATE .
ZSDSV_COL_INFO-PO_REF =
ZSDSFIT029-PO_REF .
ZSDSV_COL_INFO-BILLPL_AMT =
ZSDSFIT029-BILLPL_AMT .
ZSDSV_COL_INFO-DOCUMENT_STATUS =
ZSDSFIT029-DOCUMENT_STATUS .
ZSDSV_COL_INFO-INV_STATUS =
ZSDSFIT029-INV_STATUS .
ZSDSV_COL_INFO-REMARK_VENDOR =
ZSDSFIT029-REMARK_VENDOR .
ZSDSV_COL_INFO-REASON_VENDOR =
ZSDSFIT029-REASON_VENDOR .
ZSDSV_COL_INFO-BILLING_CYCLE =
ZSDSFIT029-BILLING_CYCLE .
ZSDSV_COL_INFO-COLLECTION_CYCLE =
ZSDSFIT029-COLLECTION_CYCLE .
ZSDSV_COL_INFO-AWB_NO =
ZSDSFIT029-AWB_NO .
ZSDSV_COL_INFO-DELETE_FLAG =
ZSDSFIT029-DELETE_FLAG .
ZSDSV_COL_INFO-DELETE_DATE =
ZSDSFIT029-DELETE_DATE .
ZSDSV_COL_INFO-ERDAT =
ZSDSFIT029-ERDAT .
ZSDSV_COL_INFO-ERZMT =
ZSDSFIT029-ERZMT .
ZSDSV_COL_INFO-UPDATE_BY =
ZSDSFIT029-UPDATE_BY .
ZSDSV_COL_INFO-UPDATE_ON =
ZSDSFIT029-UPDATE_ON .
ZSDSV_COL_INFO-UPDATE_TIME =
ZSDSFIT029-UPDATE_TIME .
<VIM_TOTAL_STRUC> = ZSDSV_COL_INFO.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZSDSV_COL_INFO .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZSDSV_COL_INFO.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZSDSV_COL_INFO-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZSDSFIT029 WHERE
  DATA_TYPE = ZSDSV_COL_INFO-DATA_TYPE AND
  BUKRS = ZSDSV_COL_INFO-BUKRS AND
  BELNR = ZSDSV_COL_INFO-BELNR AND
  GJAHR = ZSDSV_COL_INFO-GJAHR AND
  BUZEI = ZSDSV_COL_INFO-BUZEI AND
  SEQ = ZSDSV_COL_INFO-SEQ .
    IF SY-SUBRC = 0.
    DELETE ZSDSFIT029 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZSDSFIT029 WHERE
  DATA_TYPE = ZSDSV_COL_INFO-DATA_TYPE AND
  BUKRS = ZSDSV_COL_INFO-BUKRS AND
  BELNR = ZSDSV_COL_INFO-BELNR AND
  GJAHR = ZSDSV_COL_INFO-GJAHR AND
  BUZEI = ZSDSV_COL_INFO-BUZEI AND
  SEQ = ZSDSV_COL_INFO-SEQ .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZSDSFIT029.
    ENDIF.
ZSDSFIT029-MANDT =
ZSDSV_COL_INFO-MANDT .
ZSDSFIT029-DATA_TYPE =
ZSDSV_COL_INFO-DATA_TYPE .
ZSDSFIT029-BUKRS =
ZSDSV_COL_INFO-BUKRS .
ZSDSFIT029-BELNR =
ZSDSV_COL_INFO-BELNR .
ZSDSFIT029-GJAHR =
ZSDSV_COL_INFO-GJAHR .
ZSDSFIT029-BUZEI =
ZSDSV_COL_INFO-BUZEI .
ZSDSFIT029-SEQ =
ZSDSV_COL_INFO-SEQ .
ZSDSFIT029-VBELN_VF =
ZSDSV_COL_INFO-VBELN_VF .
ZSDSFIT029-BILLPL_NO =
ZSDSV_COL_INFO-BILLPL_NO .
ZSDSFIT029-BILLPL_DATE =
ZSDSV_COL_INFO-BILLPL_DATE .
ZSDSFIT029-PERNR =
ZSDSV_COL_INFO-PERNR .
ZSDSFIT029-WORK_DATE =
ZSDSV_COL_INFO-WORK_DATE .
ZSDSFIT029-KUNNR =
ZSDSV_COL_INFO-KUNNR .
ZSDSFIT029-UMSKZ =
ZSDSV_COL_INFO-UMSKZ .
ZSDSFIT029-XBLNR =
ZSDSV_COL_INFO-XBLNR .
ZSDSFIT029-BLDAT =
ZSDSV_COL_INFO-BLDAT .
ZSDSFIT029-BUDAT =
ZSDSV_COL_INFO-BUDAT .
ZSDSFIT029-FAEDT =
ZSDSV_COL_INFO-FAEDT .
ZSDSFIT029-WRBTR =
ZSDSV_COL_INFO-WRBTR .
ZSDSFIT029-WAERS =
ZSDSV_COL_INFO-WAERS .
ZSDSFIT029-DEDUCT_AMT =
ZSDSV_COL_INFO-DEDUCT_AMT .
ZSDSFIT029-PAYNO =
ZSDSV_COL_INFO-PAYNO .
ZSDSFIT029-BRNCH =
ZSDSV_COL_INFO-BRNCH .
ZSDSFIT029-BAL_AMT =
ZSDSV_COL_INFO-BAL_AMT .
ZSDSFIT029-EXPS_AMT =
ZSDSV_COL_INFO-EXPS_AMT .
ZSDSFIT029-AUFNR_EXPS =
ZSDSV_COL_INFO-AUFNR_EXPS .
ZSDSFIT029-WHT_AMT =
ZSDSV_COL_INFO-WHT_AMT .
ZSDSFIT029-FEE =
ZSDSV_COL_INFO-FEE .
ZSDSFIT029-AUFNR_FEE =
ZSDSV_COL_INFO-AUFNR_FEE .
ZSDSFIT029-RECEIVED_AMT =
ZSDSV_COL_INFO-RECEIVED_AMT .
ZSDSFIT029-RETENTION =
ZSDSV_COL_INFO-RETENTION .
ZSDSFIT029-INCOME_AMT =
ZSDSV_COL_INFO-INCOME_AMT .
ZSDSFIT029-CASH_CON =
ZSDSV_COL_INFO-CASH_CON .
ZSDSFIT029-ADV_AMT =
ZSDSV_COL_INFO-ADV_AMT .
ZSDSFIT029-PAYIN_AMT =
ZSDSV_COL_INFO-PAYIN_AMT .
ZSDSFIT029-REMAIN_AMT =
ZSDSV_COL_INFO-REMAIN_AMT .
ZSDSFIT029-REMAIN_C_AMT =
ZSDSV_COL_INFO-REMAIN_C_AMT .
ZSDSFIT029-KOSTL =
ZSDSV_COL_INFO-KOSTL .
ZSDSFIT029-PRCTR =
ZSDSV_COL_INFO-PRCTR .
ZSDSFIT029-HBKID =
ZSDSV_COL_INFO-HBKID .
ZSDSFIT029-HKTID =
ZSDSV_COL_INFO-HKTID .
ZSDSFIT029-ZBANK_ITEM =
ZSDSV_COL_INFO-ZBANK_ITEM .
ZSDSFIT029-PYMT_METHOD =
ZSDSV_COL_INFO-PYMT_METHOD .
ZSDSFIT029-ACTION_TYPE =
ZSDSV_COL_INFO-ACTION_TYPE .
ZSDSFIT029-STATUS =
ZSDSV_COL_INFO-STATUS .
ZSDSFIT029-REMARK =
ZSDSV_COL_INFO-REMARK .
ZSDSFIT029-PAYMENT_DATE =
ZSDSV_COL_INFO-PAYMENT_DATE .
ZSDSFIT029-RECEIVED_DATE =
ZSDSV_COL_INFO-RECEIVED_DATE .
ZSDSFIT029-RECEIPT_NO =
ZSDSV_COL_INFO-RECEIPT_NO .
ZSDSFIT029-BANK_DATE =
ZSDSV_COL_INFO-BANK_DATE .
ZSDSFIT029-CHEQUE_NO =
ZSDSV_COL_INFO-CHEQUE_NO .
ZSDSFIT029-BANKN =
ZSDSV_COL_INFO-BANKN .
ZSDSFIT029-BANKL =
ZSDSV_COL_INFO-BANKL .
ZSDSFIT029-TRANF_NO =
ZSDSV_COL_INFO-TRANF_NO .
ZSDSFIT029-BANKK =
ZSDSV_COL_INFO-BANKK .
ZSDSFIT029-VBELN =
ZSDSV_COL_INFO-VBELN .
ZSDSFIT029-FKDAT =
ZSDSV_COL_INFO-FKDAT .
ZSDSFIT029-CHEQUE_DATE =
ZSDSV_COL_INFO-CHEQUE_DATE .
ZSDSFIT029-FOLLOW_DATE =
ZSDSV_COL_INFO-FOLLOW_DATE .
ZSDSFIT029-PO_REF =
ZSDSV_COL_INFO-PO_REF .
ZSDSFIT029-BILLPL_AMT =
ZSDSV_COL_INFO-BILLPL_AMT .
ZSDSFIT029-DOCUMENT_STATUS =
ZSDSV_COL_INFO-DOCUMENT_STATUS .
ZSDSFIT029-INV_STATUS =
ZSDSV_COL_INFO-INV_STATUS .
ZSDSFIT029-REMARK_VENDOR =
ZSDSV_COL_INFO-REMARK_VENDOR .
ZSDSFIT029-REASON_VENDOR =
ZSDSV_COL_INFO-REASON_VENDOR .
ZSDSFIT029-BILLING_CYCLE =
ZSDSV_COL_INFO-BILLING_CYCLE .
ZSDSFIT029-COLLECTION_CYCLE =
ZSDSV_COL_INFO-COLLECTION_CYCLE .
ZSDSFIT029-AWB_NO =
ZSDSV_COL_INFO-AWB_NO .
ZSDSFIT029-DELETE_FLAG =
ZSDSV_COL_INFO-DELETE_FLAG .
ZSDSFIT029-DELETE_DATE =
ZSDSV_COL_INFO-DELETE_DATE .
ZSDSFIT029-ERDAT =
ZSDSV_COL_INFO-ERDAT .
ZSDSFIT029-ERZMT =
ZSDSV_COL_INFO-ERZMT .
ZSDSFIT029-UPDATE_BY =
ZSDSV_COL_INFO-UPDATE_BY .
ZSDSFIT029-UPDATE_ON =
ZSDSV_COL_INFO-UPDATE_ON .
ZSDSFIT029-UPDATE_TIME =
ZSDSV_COL_INFO-UPDATE_TIME .
    IF SY-SUBRC = 0.
    UPDATE ZSDSFIT029 ##WARN_OK.
    ELSE.
    INSERT ZSDSFIT029 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZSDSV_COL_INFO-UPD_FLAG,
STATUS_ZSDSV_COL_INFO-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZSDSV_COL_INFO.
  SELECT SINGLE * FROM ZSDSFIT029 WHERE
DATA_TYPE = ZSDSV_COL_INFO-DATA_TYPE AND
BUKRS = ZSDSV_COL_INFO-BUKRS AND
BELNR = ZSDSV_COL_INFO-BELNR AND
GJAHR = ZSDSV_COL_INFO-GJAHR AND
BUZEI = ZSDSV_COL_INFO-BUZEI AND
SEQ = ZSDSV_COL_INFO-SEQ .
ZSDSV_COL_INFO-MANDT =
ZSDSFIT029-MANDT .
ZSDSV_COL_INFO-DATA_TYPE =
ZSDSFIT029-DATA_TYPE .
ZSDSV_COL_INFO-BUKRS =
ZSDSFIT029-BUKRS .
ZSDSV_COL_INFO-BELNR =
ZSDSFIT029-BELNR .
ZSDSV_COL_INFO-GJAHR =
ZSDSFIT029-GJAHR .
ZSDSV_COL_INFO-BUZEI =
ZSDSFIT029-BUZEI .
ZSDSV_COL_INFO-SEQ =
ZSDSFIT029-SEQ .
ZSDSV_COL_INFO-VBELN_VF =
ZSDSFIT029-VBELN_VF .
ZSDSV_COL_INFO-BILLPL_NO =
ZSDSFIT029-BILLPL_NO .
ZSDSV_COL_INFO-BILLPL_DATE =
ZSDSFIT029-BILLPL_DATE .
ZSDSV_COL_INFO-PERNR =
ZSDSFIT029-PERNR .
ZSDSV_COL_INFO-WORK_DATE =
ZSDSFIT029-WORK_DATE .
ZSDSV_COL_INFO-KUNNR =
ZSDSFIT029-KUNNR .
ZSDSV_COL_INFO-UMSKZ =
ZSDSFIT029-UMSKZ .
ZSDSV_COL_INFO-XBLNR =
ZSDSFIT029-XBLNR .
ZSDSV_COL_INFO-BLDAT =
ZSDSFIT029-BLDAT .
ZSDSV_COL_INFO-BUDAT =
ZSDSFIT029-BUDAT .
ZSDSV_COL_INFO-FAEDT =
ZSDSFIT029-FAEDT .
ZSDSV_COL_INFO-WRBTR =
ZSDSFIT029-WRBTR .
ZSDSV_COL_INFO-WAERS =
ZSDSFIT029-WAERS .
ZSDSV_COL_INFO-DEDUCT_AMT =
ZSDSFIT029-DEDUCT_AMT .
ZSDSV_COL_INFO-PAYNO =
ZSDSFIT029-PAYNO .
ZSDSV_COL_INFO-BRNCH =
ZSDSFIT029-BRNCH .
ZSDSV_COL_INFO-BAL_AMT =
ZSDSFIT029-BAL_AMT .
ZSDSV_COL_INFO-EXPS_AMT =
ZSDSFIT029-EXPS_AMT .
ZSDSV_COL_INFO-AUFNR_EXPS =
ZSDSFIT029-AUFNR_EXPS .
ZSDSV_COL_INFO-WHT_AMT =
ZSDSFIT029-WHT_AMT .
ZSDSV_COL_INFO-FEE =
ZSDSFIT029-FEE .
ZSDSV_COL_INFO-AUFNR_FEE =
ZSDSFIT029-AUFNR_FEE .
ZSDSV_COL_INFO-RECEIVED_AMT =
ZSDSFIT029-RECEIVED_AMT .
ZSDSV_COL_INFO-RETENTION =
ZSDSFIT029-RETENTION .
ZSDSV_COL_INFO-INCOME_AMT =
ZSDSFIT029-INCOME_AMT .
ZSDSV_COL_INFO-CASH_CON =
ZSDSFIT029-CASH_CON .
ZSDSV_COL_INFO-ADV_AMT =
ZSDSFIT029-ADV_AMT .
ZSDSV_COL_INFO-PAYIN_AMT =
ZSDSFIT029-PAYIN_AMT .
ZSDSV_COL_INFO-REMAIN_AMT =
ZSDSFIT029-REMAIN_AMT .
ZSDSV_COL_INFO-REMAIN_C_AMT =
ZSDSFIT029-REMAIN_C_AMT .
ZSDSV_COL_INFO-KOSTL =
ZSDSFIT029-KOSTL .
ZSDSV_COL_INFO-PRCTR =
ZSDSFIT029-PRCTR .
ZSDSV_COL_INFO-HBKID =
ZSDSFIT029-HBKID .
ZSDSV_COL_INFO-HKTID =
ZSDSFIT029-HKTID .
ZSDSV_COL_INFO-ZBANK_ITEM =
ZSDSFIT029-ZBANK_ITEM .
ZSDSV_COL_INFO-PYMT_METHOD =
ZSDSFIT029-PYMT_METHOD .
ZSDSV_COL_INFO-ACTION_TYPE =
ZSDSFIT029-ACTION_TYPE .
ZSDSV_COL_INFO-STATUS =
ZSDSFIT029-STATUS .
ZSDSV_COL_INFO-REMARK =
ZSDSFIT029-REMARK .
ZSDSV_COL_INFO-PAYMENT_DATE =
ZSDSFIT029-PAYMENT_DATE .
ZSDSV_COL_INFO-RECEIVED_DATE =
ZSDSFIT029-RECEIVED_DATE .
ZSDSV_COL_INFO-RECEIPT_NO =
ZSDSFIT029-RECEIPT_NO .
ZSDSV_COL_INFO-BANK_DATE =
ZSDSFIT029-BANK_DATE .
ZSDSV_COL_INFO-CHEQUE_NO =
ZSDSFIT029-CHEQUE_NO .
ZSDSV_COL_INFO-BANKN =
ZSDSFIT029-BANKN .
ZSDSV_COL_INFO-BANKL =
ZSDSFIT029-BANKL .
ZSDSV_COL_INFO-TRANF_NO =
ZSDSFIT029-TRANF_NO .
ZSDSV_COL_INFO-BANKK =
ZSDSFIT029-BANKK .
ZSDSV_COL_INFO-VBELN =
ZSDSFIT029-VBELN .
ZSDSV_COL_INFO-FKDAT =
ZSDSFIT029-FKDAT .
ZSDSV_COL_INFO-CHEQUE_DATE =
ZSDSFIT029-CHEQUE_DATE .
ZSDSV_COL_INFO-FOLLOW_DATE =
ZSDSFIT029-FOLLOW_DATE .
ZSDSV_COL_INFO-PO_REF =
ZSDSFIT029-PO_REF .
ZSDSV_COL_INFO-BILLPL_AMT =
ZSDSFIT029-BILLPL_AMT .
ZSDSV_COL_INFO-DOCUMENT_STATUS =
ZSDSFIT029-DOCUMENT_STATUS .
ZSDSV_COL_INFO-INV_STATUS =
ZSDSFIT029-INV_STATUS .
ZSDSV_COL_INFO-REMARK_VENDOR =
ZSDSFIT029-REMARK_VENDOR .
ZSDSV_COL_INFO-REASON_VENDOR =
ZSDSFIT029-REASON_VENDOR .
ZSDSV_COL_INFO-BILLING_CYCLE =
ZSDSFIT029-BILLING_CYCLE .
ZSDSV_COL_INFO-COLLECTION_CYCLE =
ZSDSFIT029-COLLECTION_CYCLE .
ZSDSV_COL_INFO-AWB_NO =
ZSDSFIT029-AWB_NO .
ZSDSV_COL_INFO-DELETE_FLAG =
ZSDSFIT029-DELETE_FLAG .
ZSDSV_COL_INFO-DELETE_DATE =
ZSDSFIT029-DELETE_DATE .
ZSDSV_COL_INFO-ERDAT =
ZSDSFIT029-ERDAT .
ZSDSV_COL_INFO-ERZMT =
ZSDSFIT029-ERZMT .
ZSDSV_COL_INFO-UPDATE_BY =
ZSDSFIT029-UPDATE_BY .
ZSDSV_COL_INFO-UPDATE_ON =
ZSDSFIT029-UPDATE_ON .
ZSDSV_COL_INFO-UPDATE_TIME =
ZSDSFIT029-UPDATE_TIME .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZSDSV_COL_INFO USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZSDSV_COL_INFO-DATA_TYPE TO
ZSDSFIT029-DATA_TYPE .
MOVE ZSDSV_COL_INFO-BUKRS TO
ZSDSFIT029-BUKRS .
MOVE ZSDSV_COL_INFO-BELNR TO
ZSDSFIT029-BELNR .
MOVE ZSDSV_COL_INFO-GJAHR TO
ZSDSFIT029-GJAHR .
MOVE ZSDSV_COL_INFO-BUZEI TO
ZSDSFIT029-BUZEI .
MOVE ZSDSV_COL_INFO-SEQ TO
ZSDSFIT029-SEQ .
MOVE ZSDSV_COL_INFO-MANDT TO
ZSDSFIT029-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZSDSFIT029'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZSDSFIT029 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZSDSFIT029'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
