*&---------------------------------------------------------------------*
*& Include          ZSDSFIR0420_S01
*&---------------------------------------------------------------------*


SELECTION-SCREEN BEGIN OF BLOCK BOK1 WITH FRAME TITLE TEXT-001.
  PARAMETERS: P_BUKRS TYPE T001-BUKRS DEFAULT '1000' OBLIGATORY.
  SELECT-OPTIONS: S_MATNR FOR MARA-MATNR.
  SELECT-OPTIONS: S_EQUNR FOR ZSDSCMT003-EQUNR.
  SELECT-OPTIONS: S_VBELN FOR VBRK-VBELN.
  SELECT-OPTIONS: S_FKDAT FOR VBRK-FKDAT.
  SELECT-OPTIONS: S_VKORG FOR VBRK-VKORG.
  SELECT-OPTIONS: S_VTWEG FOR VBRK-VTWEG.
  SELECT-OPTIONS: S_SPART FOR VBRK-SPART.
  SELECT-OPTIONS: S_VKBUR FOR VBAK-VKBUR.
  SELECT-OPTIONS: S_VKGRP FOR VBAK-VKGRP.
*  SELECT-OPTIONS: S_PRDHA1 FOR MARA-PRDHA no-DISPLAY.
*  SELECT-OPTIONS: S_PRDHA2 FOR MARA-PRDHA no-DISPLAY.
*  SELECT-OPTIONS: S_PRDHA3 FOR MARA-PRDHA no-DISPLAY.
  SELECT-OPTIONS: S_ENDDT  FOR SY-DATUM NO-EXTENSION.
  PARAMETERS: CB_MGT AS CHECKBOX.
SELECTION-SCREEN END OF BLOCK BOK1.

SELECTION-SCREEN BEGIN OF BLOCK BOK2 WITH FRAME TITLE TEXT-002.
  SELECTION-SCREEN COMMENT /1(38) TEXT-H01.
  PARAMETERS: RB_M1 RADIOBUTTON GROUP RAD1 DEFAULT 'X'.
  PARAMETERS: RB_M2 RADIOBUTTON GROUP RAD1.
  SELECTION-SCREEN BEGIN OF BLOCK BOK3 WITH FRAME.
    PARAMETERS: P_BUDAT TYPE BUDAT DEFAULT SY-DATUM.
    PARAMETERS: P_RUNDT TYPE SY-DATUM DEFAULT SY-DATUM.
    PARAMETERS: P_BLART TYPE BLART DEFAULT 'SG'.
    PARAMETERS: CB_TEST AS CHECKBOX DEFAULT 'X'.
  SELECTION-SCREEN END OF BLOCK BOK3.

*  SELECTION-SCREEN COMMENT /1(38) TEXT-H02 .
*  PARAMETERS: RB_M3 RADIOBUTTON GROUP RAD1 DEFAULT 'X'.
*  SELECTION-SCREEN BEGIN OF BLOCK BOK4 WITH FRAME.
*    PARAMETERS: P_RPDAT TYPE SY-DATUM DEFAULT SY-DATUM.
*
*    SELECTION-SCREEN BEGIN OF LINE.
*      SELECTION-SCREEN COMMENT 1(20) TEXT-H03.
*      SELECTION-SCREEN POSITION 31.
*      PARAMETERS: CB_M1 AS CHECKBOX DEFAULT ''.
*      SELECTION-SCREEN COMMENT 35(20) TEXT-H04 FOR FIELD CB_M1.
*    SELECTION-SCREEN END OF LINE.
*
*    SELECTION-SCREEN BEGIN OF LINE.
*      SELECTION-SCREEN POSITION 31.
*      PARAMETERS: CB_M2 AS CHECKBOX DEFAULT 'X'.
*      SELECTION-SCREEN COMMENT 35(20) TEXT-H05 FOR FIELD CB_M2.
*    SELECTION-SCREEN END OF LINE.
*    SELECTION-SCREEN BEGIN OF LINE.
*      SELECTION-SCREEN POSITION 31.
*      PARAMETERS: CB_M3 AS CHECKBOX DEFAULT ''.
*      SELECTION-SCREEN COMMENT 35(20) TEXT-H06 FOR FIELD CB_M3.
*    SELECTION-SCREEN END OF LINE.
*  SELECTION-SCREEN END OF BLOCK BOK4.

SELECTION-SCREEN END OF BLOCK BOK2.
