*"* use this source file for any type of declarations (class
*"* definitions, interfaces or type declarations) you need for
*"* components in the private section
INTERFACE:
LIF_CRMS4_SRVORDER_FWD_HELPER." introduced to have better code coverage as per the  abap test double

  TYPES TY_SRV_DATA TYPE IF_CRMS4_RECO_HANDLER=>INPUT_SRV_DATA .
  TYPES:
    BEGIN OF  ERROR_MESSAGE,
      ITEM_GUID  TYPE  CRMT_OBJECT_GUID,
      OBJECT_ID  TYPE  CRMT_OBJECT_ID_DB,
      NUMBER_INT TYPE  CRMS4_NUMBER_INT,
      TYPE       TYPE  BAPI_MTYPE,
      ID         TYPE  SYMSGID,
      NUMBER     TYPE  SYMSGNO,
      MESSAGE    TYPE  BAPI_MSG,
      MESSAGE_V1 TYPE  SYMSGV,
      MESSAGE_V2 TYPE  SYMSGV,
      MESSAGE_V3 TYPE  SYMSGV,
      MESSAGE_V4 TYPE  SYMSGV,
    END OF ERROR_MESSAGE .
  TYPES:
    ERROR_MESSAGE_TAB TYPE STANDARD TABLE OF ERROR_MESSAGE .
  TYPES REQUIREMENT_FOR_CREATE TYPE CL_IRES_RESERVATION=>IF_IRES_RESERVATION~REQUIREMENT_FOR_CREATE .
  TYPES REQUIREMENT_FOR_UPDATE TYPE CL_IRES_RESERVATION=>IF_IRES_RESERVATION~REQUIREMENT_FOR_UPDATE .
  TYPES RESERVATION_FINAL_ISSUE TYPE CL_IRES_RESERVATION=>IF_IRES_RESERVATION~RESERVATION_FINAL_ISSUE .
  TYPES REQUIREMENTS_FOR_CREATE TYPE CL_IRES_RESERVATION=>IF_IRES_RESERVATION~REQUIREMENTS_FOR_CREATE .
  TYPES REQUIREMENTS_FOR_UPDATE TYPE CL_IRES_RESERVATION=>IF_IRES_RESERVATION~REQUIREMENTS_FOR_UPDATE .
  TYPES RESERVATIONS_FINAL_ISSUE TYPE CL_IRES_RESERVATION=>IF_IRES_RESERVATION~RESERVATIONS_FINAL_ISSUE .
  TYPES CREATE_RESULTS TYPE REF TO CL_IRES_RESERVATION=>IF_IRES_RESERVATION~ATP_CHECK_RESULTS_CREATE .
  TYPES: BEGIN OF TY_OP,
           OPERATION TYPE INT1,
         END OF TY_OP.


  TYPES:TY_INPUT_SRV_DATA TYPE CL_CRMS4_RECO_UTILITY=>IF_CRMS4_RECO_UTILITY~TY_INPUT_SRV_DATA.

  TYPES:
     INPUT_SRV_DATA_T TYPE STANDARD TABLE OF TY_INPUT_SRV_DATA .
  TYPES:
    BEGIN OF RESULT,
      RESERVATION         TYPE RSNUM,
      RESERVATIONITEM     TYPE RSPOS,
      SERVICEOBJECTTYPE   TYPE SWO_OBJTYP,
      SERVICEDOCUMENT     TYPE CRMT_OBJECT_ID_CO,
      SERVICEDOCUMENTITEM TYPE CRMS4_NUMBER_INT,
      CONFIRMED_QUANITY   TYPE CRMT_SCHEDLIN_QUAN,
      QUANTITY_UNIT       TYPE MEINS,
    END OF RESULT .
  TYPES:
    RESULT_T TYPE STANDARD TABLE OF RESULT .
  TYPES:
    BEGIN OF RETURN_MESSAGE,
      SERVICEOBJECTTYPE        TYPE SWO_OBJTYP,
      SERVICEDOCUMENT          TYPE CRMT_OBJECT_ID_CO,
      SERVICEDOCUMENTITEM      TYPE CRMS4_NUMBER_INT,
      MESSAGE                  TYPE IF_ABAP_BEHV=>T_MESSAGE,
      RESERVATION              TYPE RSNUM,
      RESERVATIONITEM          TYPE RSPOS,
      SERVICEDOCUMENTITEM_GUID TYPE CRMT_OBJECT_GUID,
    END OF RETURN_MESSAGE .
  TYPES:
    RETURN_MESSAGES TYPE STANDARD TABLE OF RETURN_MESSAGE .

  CONSTANTS GC_OP_FINAL_ISSUE TYPE INT1 VALUE '4' ##NO_TEXT.
  CONSTANTS GC_OP_RESEVATION_CREATE TYPE INT1 VALUE '2' ##NO_TEXT.
  CONSTANTS GC_OP_RESERVATION_UPDATE TYPE INT1 VALUE '1' ##NO_TEXT.

  METHODS HANDLE_RECO
    IMPORTING
      IT_SERVICE_DATA TYPE INPUT_SRV_DATA_T
    EXPORTING
      ET_RESULT_TAB   TYPE RESULT_T
      ET_RETURN       TYPE ERROR_MESSAGE_TAB .

  METHODS GET_STORAGE_LOCATION_PLANT " the actual method is inside the superclass cl_crms4_process_fwd which is being used
    IMPORTING
      IS_ORDERADM_I            TYPE CRMT_ORDERADM_I_WRK
      IT_ORGMAN                TYPE CRMT_ORGMAN_WRKT
      IT_PARTNERS              TYPE CRMT_PARTNER_EXTERNAL_WRKT
    EXPORTING
      EV_PLANT                 TYPE WERKS_D
      EV_STORAGE_LOCATION      TYPE LGORT_D
      EV_INDV_PLANT            TYPE WERKS_D
      EV_INDV_STORAGE_LOCATION TYPE LGORT_D
      ET_RETURN                TYPE BAPIRET2_T .

  METHODS GET_PARENT_ITEM_DETAILS
    IMPORTING
      IV_PARENT_ITEM_GUID TYPE CRMT_OBJECT_GUID
    EXPORTING
      ES_ORDERADM_I_WRK   TYPE CRMT_ORDERADM_I_WRK
    EXCEPTIONS
      ERROR_OCCURRED .

  METHODS GET_SRV_DATES_FROM_DB
    IMPORTING
      IV_REF_GUID TYPE CRMT_OBJECT_GUID
    EXPORTING
      ET_DATE_DB  TYPE SCSAPPTTAB
    EXCEPTIONS
      ENTRY_DOES_NOT_EXIST.

  METHODS DO_DATE_VALIDATION
    IMPORTING
      !IV_REQUESTED_START_DATETIME    TYPE ATP_REQ_MAT_AVAIL_TIMESTAMP
      !IV_REQUESTED_END_DATETIME      TYPE ATP_REQ_MAT_AVAIL_TIMESTAMP
      !IV_REQUESTED_START_DATETIME_DB TYPE ATP_REQ_MAT_AVAIL_TIMESTAMP OPTIONAL
      !IV_REQUESTED_END_DATETIME_DB   TYPE ATP_REQ_MAT_AVAIL_TIMESTAMP OPTIONAL
      IV_UPDATE_SCENARIO              TYPE ABAP_BOOL OPTIONAL
    EXPORTING
      !EV_RESERVATION_REQ_DATETIME    TYPE ATP_REQ_MAT_AVAIL_TIMESTAMP
      !ES_RETURN                      TYPE BAPIRET2
      EV_DATE_CHANGED                 TYPE ABAP_BOOL.


  METHODS GET_DELETED_RECO_ITEMS
    IMPORTING
      !IV_HEADER_GUID           TYPE CRMT_OBJECT_GUID
      !IR_RECO_UTIL             TYPE REF TO IF_CRMS4_RECO_UTILITY
    EXPORTING
      !ET_DELETED_ITEMS         TYPE CRMT_ORDERADM_I_WRKT
      !ET_DELETED_ITEMS_DOCFLOW TYPE CRMT_DOC_FLOW_WRKT .


  METHODS CHECK_RECO_SCENARIO_EXISTS
    IMPORTING
      !IV_PROCESS_TYPE                      TYPE CRMT_PROCESS_TYPE OPTIONAL
      !IV_ITEM_TYPE                         TYPE CRMT_ITEM_TYPE OPTIONAL
      !IV_ITEM_GUID                         TYPE CRMT_OBJECT_GUID OPTIONAL
      !IV_HEADER_GUID                       TYPE CRMT_OBJECT_GUID OPTIONAL
      !IR_RECO_UTIL                         TYPE REF TO IF_CRMS4_RECO_UTILITY
    EXPORTING
      VALUE(EV_RECO_LIFE_STATUS_IN_PROCESS) TYPE CRMS4_RECO_CR_STAT
      VALUE(EV_RECO_LIFE_STATUS_RELEASED)   TYPE CRMS4_RECO_CR_STAT
    RETURNING
      VALUE(RV_RECO_SCENARIO_FOUND)         TYPE CRMT_BOOLEAN .

  METHODS GET_RESERVATION_DETAILS
    IMPORTING
      !IV_RESERVATION_NUMBER  TYPE RSNUM
      !IV_RESERVATION_ITEM_NO TYPE RSPOS OPTIONAL
      !IR_RECO_UTIL           TYPE REF TO IF_CRMS4_RECO_UTILITY
    EXPORTING
      !ES_RESERVATION_DETAILS TYPE RESB .

  METHODS CHECK_STATUS
    IMPORTING
      !IV_GUID          TYPE CRMT_OBJECT_GUID
      !IV_BYPASS_BUFFER TYPE XFELD DEFAULT SPACE
      !IV_STATUS        TYPE CRM_JEST-STAT
      !IR_RECO_UTIL     TYPE REF TO IF_CRMS4_RECO_UTILITY
    RETURNING
      VALUE(RV_SUBRC)   TYPE SYST_SUBRC .


  METHODS DELTA_HANDLE
    IMPORTING
      !IS_SRV_DATA                TYPE TY_INPUT_SRV_DATA
      !IR_RECO_UTIL               TYPE REF TO IF_CRMS4_RECO_UTILITY
    EXPORTING
      !EV_PLANT_CHANGED           TYPE ABAP_BOOL
      !EV_DATE_CHANGED            TYPE ABAP_BOOL
    RETURNING
      VALUE(RV_DELTA_UPDATE_TRUE) TYPE ABAP_BOOL .

  METHODS DETERMINE_CHECKING_RULE
    IMPORTING
      !IR_RECO_UTIL           TYPE REF TO IF_CRMS4_RECO_UTILITY
      !IV_GOODS_MOVEMENT_DONE TYPE XWAOK OPTIONAL
    CHANGING
      !CS_SRV_DATA            TYPE TY_INPUT_SRV_DATA .
ENDINTERFACE.

CLASS LCL_CRMS4_PROC_SRVORDER_HELPER DEFINITION FINAL CREATE PRIVATE INHERITING FROM CL_CRMS4_PROCESS_FWD."
  " inheriting from cl_crms4_process_fwd as the protected method get_storage_location_plant needs t be called

  PUBLIC SECTION.

    INTERFACES LIF_CRMS4_SRVORDER_FWD_HELPER.
    CLASS-METHODS GET_INSTANCE
      RETURNING VALUE(RO_SRVORDER_FWD_HELPER) TYPE REF TO LIF_CRMS4_SRVORDER_FWD_HELPER.

  PRIVATE SECTION.

    CLASS-DATA MO_SRVORDER_FWD_HELPER TYPE REF TO LIF_CRMS4_SRVORDER_FWD_HELPER.

ENDCLASS.

INTERFACE: LIF_CRMS4_LOGINT_UTIL.

  METHODS IS_ADV_SHIPMENT_ACT
    IMPORTING
      !IV_ITEM_GUID              TYPE CRMT_OBJECT_GUID
    RETURNING
      VALUE(RV_LOG_SCENARIO_SUB) TYPE CRMS4_LOGSC_SUB .

ENDINTERFACE.

CLASS LCL_CRMS4_LOGINT_UTIL DEFINITION.

  PUBLIC SECTION.

    INTERFACES LIF_CRMS4_LOGINT_UTIL.

ENDCLASS.

INTERFACE LIF_ADV_SHIPMENT.
  METHODS:
    IS_ADV_SHIPMENT_ACT
      IMPORTING
        !IV_ITEM_GUID              TYPE CRMT_OBJECT_GUID
      RETURNING
        VALUE(RV_LOG_SCENARIO_SUB) TYPE BOOLEAN.
ENDINTERFACE.

CLASS LCL_ADV_SHIPMENT DEFINITION.
  PUBLIC SECTION.
    INTERFACES LIF_ADV_SHIPMENT.
ENDCLASS.
