*"* use this source file for the definition and implementation of
*"* local helper classes, interface definitions and type
*"* declarations

CLASS LCL_DATA DEFINITION.
  PUBLIC SECTION.
    CLASS-METHODS :
      CONVERT_AND_SAVE_STATUS CHANGING C_DATA TYPE ZSDSCMS001,
      UPDATE_SVO_DATA IMPORTING I_DATA TYPE ZSDSCMS001.
ENDCLASS.
CLASS LCL_DATA IMPLEMENTATION.
  METHOD CONVERT_AND_SAVE_STATUS.
    DATA : LS_ZSDSCMT011 TYPE ZSDSCMT011.

    LS_ZSDSCMT011-SF_WORK_ORDER = C_DATA-SF_WORKORDER_NO.
    LS_ZSDSCMT011-LINE_ITEM     = '000000'.
    LS_ZSDSCMT011-SAP_SVO_NO    = C_DATA-SVO_NO.
    LS_ZSDSCMT011-HEADER_STATUS = C_DATA-STATUS.
    LS_ZSDSCMT011-DETIAL_STATUS = ''.

    MODIFY ZSDSCMT011 FROM LS_ZSDSCMT011.
    CLEAR LS_ZSDSCMT011.

    IF C_DATA-ZMODE EQ SPACE.
      C_DATA-STATUS = 'D'.
    ENDIF.
    LOOP AT C_DATA-ITEM ASSIGNING FIELD-SYMBOL(<LFS_DATA>).
      LS_ZSDSCMT011-SF_WORK_ORDER = C_DATA-SF_WORKORDER_NO.
      LS_ZSDSCMT011-LINE_ITEM     = <LFS_DATA>-NUMBER_INT.
      LS_ZSDSCMT011-SAP_SVO_NO    = <LFS_DATA>-OBJECT_ID.
      LS_ZSDSCMT011-HEADER_STATUS = C_DATA-STATUS.
      LS_ZSDSCMT011-DETIAL_STATUS = <LFS_DATA>-STATUS.
      MODIFY ZSDSCMT011 FROM LS_ZSDSCMT011.
      CLEAR LS_ZSDSCMT011.
      IF C_DATA-ZMODE EQ SPACE.
        <LFS_DATA>-STATUS = 'D'.
      ENDIF.
    ENDLOOP.

  ENDMETHOD.
  METHOD UPDATE_SVO_DATA.
    UPDATE ZSDSCMT011 SET SAP_SVO_NO    =  I_DATA-SVO_NO
                    WHERE SF_WORK_ORDER EQ I_DATA-SF_WORKORDER_NO.
    COMMIT WORK AND WAIT.
  ENDMETHOD.
ENDCLASS.
