*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZSDSV_WRT_PKG...................................*
FORM GET_DATA_ZSDSV_WRT_PKG.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZSDSCMC002 WHERE
(VIM_WHERETAB) .
    CLEAR ZSDSV_WRT_PKG .
ZSDSV_WRT_PKG-MANDT =
ZSDSCMC002-MANDT .
ZSDSV_WRT_PKG-WRTPK =
ZSDSCMC002-WRTPK .
ZSDSV_WRT_PKG-MATKL =
ZSDSCMC002-MATKL .
ZSDSV_WRT_PKG-STWRT =
ZSDSCMC002-STWRT .
ZSDSV_WRT_PKG-ZDEL_FLG =
ZSDSCMC002-ZDEL_FLG .
ZSDSV_WRT_PKG-ZCRT_DATE =
ZSDSCMC002-ZCRT_DATE .
ZSDSV_WRT_PKG-ZCRT_TIME =
ZSDSCMC002-ZCRT_TIME .
ZSDSV_WRT_PKG-ZCRT_USER =
ZSDSCMC002-ZCRT_USER .
ZSDSV_WRT_PKG-ZCRT_PGM =
ZSDSCMC002-ZCRT_PGM .
ZSDSV_WRT_PKG-ZUPD_DATE =
ZSDSCMC002-ZUPD_DATE .
ZSDSV_WRT_PKG-ZUPD_TIME =
ZSDSCMC002-ZUPD_TIME .
ZSDSV_WRT_PKG-ZUPD_USER =
ZSDSCMC002-ZUPD_USER .
ZSDSV_WRT_PKG-ZUPD_PGM =
ZSDSCMC002-ZUPD_PGM .
<VIM_TOTAL_STRUC> = ZSDSV_WRT_PKG.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZSDSV_WRT_PKG .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZSDSV_WRT_PKG.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZSDSV_WRT_PKG-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZSDSCMC002 WHERE
  WRTPK = ZSDSV_WRT_PKG-WRTPK AND
  MATKL = ZSDSV_WRT_PKG-MATKL .
    IF SY-SUBRC = 0.
    DELETE ZSDSCMC002 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZSDSCMC002 WHERE
  WRTPK = ZSDSV_WRT_PKG-WRTPK AND
  MATKL = ZSDSV_WRT_PKG-MATKL .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZSDSCMC002.
    ENDIF.
ZSDSCMC002-MANDT =
ZSDSV_WRT_PKG-MANDT .
ZSDSCMC002-WRTPK =
ZSDSV_WRT_PKG-WRTPK .
ZSDSCMC002-MATKL =
ZSDSV_WRT_PKG-MATKL .
ZSDSCMC002-STWRT =
ZSDSV_WRT_PKG-STWRT .
ZSDSCMC002-ZDEL_FLG =
ZSDSV_WRT_PKG-ZDEL_FLG .
ZSDSCMC002-ZCRT_DATE =
ZSDSV_WRT_PKG-ZCRT_DATE .
ZSDSCMC002-ZCRT_TIME =
ZSDSV_WRT_PKG-ZCRT_TIME .
ZSDSCMC002-ZCRT_USER =
ZSDSV_WRT_PKG-ZCRT_USER .
ZSDSCMC002-ZCRT_PGM =
ZSDSV_WRT_PKG-ZCRT_PGM .
ZSDSCMC002-ZUPD_DATE =
ZSDSV_WRT_PKG-ZUPD_DATE .
ZSDSCMC002-ZUPD_TIME =
ZSDSV_WRT_PKG-ZUPD_TIME .
ZSDSCMC002-ZUPD_USER =
ZSDSV_WRT_PKG-ZUPD_USER .
ZSDSCMC002-ZUPD_PGM =
ZSDSV_WRT_PKG-ZUPD_PGM .
    IF SY-SUBRC = 0.
    UPDATE ZSDSCMC002 ##WARN_OK.
    ELSE.
    INSERT ZSDSCMC002 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZSDSV_WRT_PKG-UPD_FLAG,
STATUS_ZSDSV_WRT_PKG-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZSDSV_WRT_PKG.
  SELECT SINGLE * FROM ZSDSCMC002 WHERE
WRTPK = ZSDSV_WRT_PKG-WRTPK AND
MATKL = ZSDSV_WRT_PKG-MATKL .
ZSDSV_WRT_PKG-MANDT =
ZSDSCMC002-MANDT .
ZSDSV_WRT_PKG-WRTPK =
ZSDSCMC002-WRTPK .
ZSDSV_WRT_PKG-MATKL =
ZSDSCMC002-MATKL .
ZSDSV_WRT_PKG-STWRT =
ZSDSCMC002-STWRT .
ZSDSV_WRT_PKG-ZDEL_FLG =
ZSDSCMC002-ZDEL_FLG .
ZSDSV_WRT_PKG-ZCRT_DATE =
ZSDSCMC002-ZCRT_DATE .
ZSDSV_WRT_PKG-ZCRT_TIME =
ZSDSCMC002-ZCRT_TIME .
ZSDSV_WRT_PKG-ZCRT_USER =
ZSDSCMC002-ZCRT_USER .
ZSDSV_WRT_PKG-ZCRT_PGM =
ZSDSCMC002-ZCRT_PGM .
ZSDSV_WRT_PKG-ZUPD_DATE =
ZSDSCMC002-ZUPD_DATE .
ZSDSV_WRT_PKG-ZUPD_TIME =
ZSDSCMC002-ZUPD_TIME .
ZSDSV_WRT_PKG-ZUPD_USER =
ZSDSCMC002-ZUPD_USER .
ZSDSV_WRT_PKG-ZUPD_PGM =
ZSDSCMC002-ZUPD_PGM .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZSDSV_WRT_PKG USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZSDSV_WRT_PKG-WRTPK TO
ZSDSCMC002-WRTPK .
MOVE ZSDSV_WRT_PKG-MATKL TO
ZSDSCMC002-MATKL .
MOVE ZSDSV_WRT_PKG-MANDT TO
ZSDSCMC002-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZSDSCMC002'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZSDSCMC002 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZSDSCMC002'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
