*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZSDSV_CM_RAKEY..................................*
FORM GET_DATA_ZSDSV_CM_RAKEY.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZSDSCMC004 WHERE
(VIM_WHERETAB) .
    CLEAR ZSDSV_CM_RAKEY .
ZSDSV_CM_RAKEY-MANDT =
ZSDSCMC004-MANDT .
ZSDSV_CM_RAKEY-SALES_ORG_SD =
ZSDSCMC004-SALES_ORG_SD .
ZSDSV_CM_RAKEY-PROCESS_TYPE =
ZSDSCMC004-PROCESS_TYPE .
ZSDSV_CM_RAKEY-ITM_TYPE =
ZSDSCMC004-ITM_TYPE .
ZSDSV_CM_RAKEY-ABGSL =
ZSDSCMC004-ABGSL .
ZSDSV_CM_RAKEY-ZDEL_FLG =
ZSDSCMC004-ZDEL_FLG .
ZSDSV_CM_RAKEY-ZCRT_DATE =
ZSDSCMC004-ZCRT_DATE .
ZSDSV_CM_RAKEY-ZCRT_TIME =
ZSDSCMC004-ZCRT_TIME .
ZSDSV_CM_RAKEY-ZCRT_USER =
ZSDSCMC004-ZCRT_USER .
ZSDSV_CM_RAKEY-ZCRT_PGM =
ZSDSCMC004-ZCRT_PGM .
ZSDSV_CM_RAKEY-ZUPD_DATE =
ZSDSCMC004-ZUPD_DATE .
ZSDSV_CM_RAKEY-ZUPD_TIME =
ZSDSCMC004-ZUPD_TIME .
ZSDSV_CM_RAKEY-ZUPD_USER =
ZSDSCMC004-ZUPD_USER .
ZSDSV_CM_RAKEY-ZUPD_PGM =
ZSDSCMC004-ZUPD_PGM .
<VIM_TOTAL_STRUC> = ZSDSV_CM_RAKEY.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZSDSV_CM_RAKEY .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZSDSV_CM_RAKEY.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZSDSV_CM_RAKEY-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZSDSCMC004 WHERE
  SALES_ORG_SD = ZSDSV_CM_RAKEY-SALES_ORG_SD AND
  PROCESS_TYPE = ZSDSV_CM_RAKEY-PROCESS_TYPE AND
  ITM_TYPE = ZSDSV_CM_RAKEY-ITM_TYPE .
    IF SY-SUBRC = 0.
    DELETE ZSDSCMC004 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZSDSCMC004 WHERE
  SALES_ORG_SD = ZSDSV_CM_RAKEY-SALES_ORG_SD AND
  PROCESS_TYPE = ZSDSV_CM_RAKEY-PROCESS_TYPE AND
  ITM_TYPE = ZSDSV_CM_RAKEY-ITM_TYPE .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZSDSCMC004.
    ENDIF.
ZSDSCMC004-MANDT =
ZSDSV_CM_RAKEY-MANDT .
ZSDSCMC004-SALES_ORG_SD =
ZSDSV_CM_RAKEY-SALES_ORG_SD .
ZSDSCMC004-PROCESS_TYPE =
ZSDSV_CM_RAKEY-PROCESS_TYPE .
ZSDSCMC004-ITM_TYPE =
ZSDSV_CM_RAKEY-ITM_TYPE .
ZSDSCMC004-ABGSL =
ZSDSV_CM_RAKEY-ABGSL .
ZSDSCMC004-ZDEL_FLG =
ZSDSV_CM_RAKEY-ZDEL_FLG .
ZSDSCMC004-ZCRT_DATE =
ZSDSV_CM_RAKEY-ZCRT_DATE .
ZSDSCMC004-ZCRT_TIME =
ZSDSV_CM_RAKEY-ZCRT_TIME .
ZSDSCMC004-ZCRT_USER =
ZSDSV_CM_RAKEY-ZCRT_USER .
ZSDSCMC004-ZCRT_PGM =
ZSDSV_CM_RAKEY-ZCRT_PGM .
ZSDSCMC004-ZUPD_DATE =
ZSDSV_CM_RAKEY-ZUPD_DATE .
ZSDSCMC004-ZUPD_TIME =
ZSDSV_CM_RAKEY-ZUPD_TIME .
ZSDSCMC004-ZUPD_USER =
ZSDSV_CM_RAKEY-ZUPD_USER .
ZSDSCMC004-ZUPD_PGM =
ZSDSV_CM_RAKEY-ZUPD_PGM .
    IF SY-SUBRC = 0.
    UPDATE ZSDSCMC004 ##WARN_OK.
    ELSE.
    INSERT ZSDSCMC004 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZSDSV_CM_RAKEY-UPD_FLAG,
STATUS_ZSDSV_CM_RAKEY-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZSDSV_CM_RAKEY.
  SELECT SINGLE * FROM ZSDSCMC004 WHERE
SALES_ORG_SD = ZSDSV_CM_RAKEY-SALES_ORG_SD AND
PROCESS_TYPE = ZSDSV_CM_RAKEY-PROCESS_TYPE AND
ITM_TYPE = ZSDSV_CM_RAKEY-ITM_TYPE .
ZSDSV_CM_RAKEY-MANDT =
ZSDSCMC004-MANDT .
ZSDSV_CM_RAKEY-SALES_ORG_SD =
ZSDSCMC004-SALES_ORG_SD .
ZSDSV_CM_RAKEY-PROCESS_TYPE =
ZSDSCMC004-PROCESS_TYPE .
ZSDSV_CM_RAKEY-ITM_TYPE =
ZSDSCMC004-ITM_TYPE .
ZSDSV_CM_RAKEY-ABGSL =
ZSDSCMC004-ABGSL .
ZSDSV_CM_RAKEY-ZDEL_FLG =
ZSDSCMC004-ZDEL_FLG .
ZSDSV_CM_RAKEY-ZCRT_DATE =
ZSDSCMC004-ZCRT_DATE .
ZSDSV_CM_RAKEY-ZCRT_TIME =
ZSDSCMC004-ZCRT_TIME .
ZSDSV_CM_RAKEY-ZCRT_USER =
ZSDSCMC004-ZCRT_USER .
ZSDSV_CM_RAKEY-ZCRT_PGM =
ZSDSCMC004-ZCRT_PGM .
ZSDSV_CM_RAKEY-ZUPD_DATE =
ZSDSCMC004-ZUPD_DATE .
ZSDSV_CM_RAKEY-ZUPD_TIME =
ZSDSCMC004-ZUPD_TIME .
ZSDSV_CM_RAKEY-ZUPD_USER =
ZSDSCMC004-ZUPD_USER .
ZSDSV_CM_RAKEY-ZUPD_PGM =
ZSDSCMC004-ZUPD_PGM .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZSDSV_CM_RAKEY USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZSDSV_CM_RAKEY-SALES_ORG_SD TO
ZSDSCMC004-SALES_ORG_SD .
MOVE ZSDSV_CM_RAKEY-PROCESS_TYPE TO
ZSDSCMC004-PROCESS_TYPE .
MOVE ZSDSV_CM_RAKEY-ITM_TYPE TO
ZSDSCMC004-ITM_TYPE .
MOVE ZSDSV_CM_RAKEY-MANDT TO
ZSDSCMC004-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZSDSCMC004'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZSDSCMC004 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZSDSCMC004'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
