*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZSDSV_CM_GLACC..................................*
FORM GET_DATA_ZSDSV_CM_GLACC.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZSDSCMC005 WHERE
(VIM_WHERETAB) .
    CLEAR ZSDSV_CM_GLACC .
ZSDSV_CM_GLACC-MANDT =
ZSDSCMC005-MANDT .
ZSDSV_CM_GLACC-SALES_ORG_SD =
ZSDSCMC005-SALES_ORG_SD .
ZSDSV_CM_GLACC-PROCESS_TYPE =
ZSDSCMC005-PROCESS_TYPE .
ZSDSV_CM_GLACC-ITM_TYPE =
ZSDSCMC005-ITM_TYPE .
ZSDSV_CM_GLACC-BKLAS =
ZSDSCMC005-BKLAS .
ZSDSV_CM_GLACC-SAKTO =
ZSDSCMC005-SAKTO .
ZSDSV_CM_GLACC-ZDEL_FLG =
ZSDSCMC005-ZDEL_FLG .
ZSDSV_CM_GLACC-ZCRT_DATE =
ZSDSCMC005-ZCRT_DATE .
ZSDSV_CM_GLACC-ZCRT_TIME =
ZSDSCMC005-ZCRT_TIME .
ZSDSV_CM_GLACC-ZCRT_USER =
ZSDSCMC005-ZCRT_USER .
ZSDSV_CM_GLACC-ZCRT_PGM =
ZSDSCMC005-ZCRT_PGM .
ZSDSV_CM_GLACC-ZUPD_DATE =
ZSDSCMC005-ZUPD_DATE .
ZSDSV_CM_GLACC-ZUPD_TIME =
ZSDSCMC005-ZUPD_TIME .
ZSDSV_CM_GLACC-ZUPD_USER =
ZSDSCMC005-ZUPD_USER .
ZSDSV_CM_GLACC-ZUPD_PGM =
ZSDSCMC005-ZUPD_PGM .
<VIM_TOTAL_STRUC> = ZSDSV_CM_GLACC.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZSDSV_CM_GLACC .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZSDSV_CM_GLACC.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZSDSV_CM_GLACC-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZSDSCMC005 WHERE
  SALES_ORG_SD = ZSDSV_CM_GLACC-SALES_ORG_SD AND
  PROCESS_TYPE = ZSDSV_CM_GLACC-PROCESS_TYPE AND
  ITM_TYPE = ZSDSV_CM_GLACC-ITM_TYPE AND
  BKLAS = ZSDSV_CM_GLACC-BKLAS .
    IF SY-SUBRC = 0.
    DELETE ZSDSCMC005 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZSDSCMC005 WHERE
  SALES_ORG_SD = ZSDSV_CM_GLACC-SALES_ORG_SD AND
  PROCESS_TYPE = ZSDSV_CM_GLACC-PROCESS_TYPE AND
  ITM_TYPE = ZSDSV_CM_GLACC-ITM_TYPE AND
  BKLAS = ZSDSV_CM_GLACC-BKLAS .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZSDSCMC005.
    ENDIF.
ZSDSCMC005-MANDT =
ZSDSV_CM_GLACC-MANDT .
ZSDSCMC005-SALES_ORG_SD =
ZSDSV_CM_GLACC-SALES_ORG_SD .
ZSDSCMC005-PROCESS_TYPE =
ZSDSV_CM_GLACC-PROCESS_TYPE .
ZSDSCMC005-ITM_TYPE =
ZSDSV_CM_GLACC-ITM_TYPE .
ZSDSCMC005-BKLAS =
ZSDSV_CM_GLACC-BKLAS .
ZSDSCMC005-SAKTO =
ZSDSV_CM_GLACC-SAKTO .
ZSDSCMC005-ZDEL_FLG =
ZSDSV_CM_GLACC-ZDEL_FLG .
ZSDSCMC005-ZCRT_DATE =
ZSDSV_CM_GLACC-ZCRT_DATE .
ZSDSCMC005-ZCRT_TIME =
ZSDSV_CM_GLACC-ZCRT_TIME .
ZSDSCMC005-ZCRT_USER =
ZSDSV_CM_GLACC-ZCRT_USER .
ZSDSCMC005-ZCRT_PGM =
ZSDSV_CM_GLACC-ZCRT_PGM .
ZSDSCMC005-ZUPD_DATE =
ZSDSV_CM_GLACC-ZUPD_DATE .
ZSDSCMC005-ZUPD_TIME =
ZSDSV_CM_GLACC-ZUPD_TIME .
ZSDSCMC005-ZUPD_USER =
ZSDSV_CM_GLACC-ZUPD_USER .
ZSDSCMC005-ZUPD_PGM =
ZSDSV_CM_GLACC-ZUPD_PGM .
    IF SY-SUBRC = 0.
    UPDATE ZSDSCMC005 ##WARN_OK.
    ELSE.
    INSERT ZSDSCMC005 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZSDSV_CM_GLACC-UPD_FLAG,
STATUS_ZSDSV_CM_GLACC-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZSDSV_CM_GLACC.
  SELECT SINGLE * FROM ZSDSCMC005 WHERE
SALES_ORG_SD = ZSDSV_CM_GLACC-SALES_ORG_SD AND
PROCESS_TYPE = ZSDSV_CM_GLACC-PROCESS_TYPE AND
ITM_TYPE = ZSDSV_CM_GLACC-ITM_TYPE AND
BKLAS = ZSDSV_CM_GLACC-BKLAS .
ZSDSV_CM_GLACC-MANDT =
ZSDSCMC005-MANDT .
ZSDSV_CM_GLACC-SALES_ORG_SD =
ZSDSCMC005-SALES_ORG_SD .
ZSDSV_CM_GLACC-PROCESS_TYPE =
ZSDSCMC005-PROCESS_TYPE .
ZSDSV_CM_GLACC-ITM_TYPE =
ZSDSCMC005-ITM_TYPE .
ZSDSV_CM_GLACC-BKLAS =
ZSDSCMC005-BKLAS .
ZSDSV_CM_GLACC-SAKTO =
ZSDSCMC005-SAKTO .
ZSDSV_CM_GLACC-ZDEL_FLG =
ZSDSCMC005-ZDEL_FLG .
ZSDSV_CM_GLACC-ZCRT_DATE =
ZSDSCMC005-ZCRT_DATE .
ZSDSV_CM_GLACC-ZCRT_TIME =
ZSDSCMC005-ZCRT_TIME .
ZSDSV_CM_GLACC-ZCRT_USER =
ZSDSCMC005-ZCRT_USER .
ZSDSV_CM_GLACC-ZCRT_PGM =
ZSDSCMC005-ZCRT_PGM .
ZSDSV_CM_GLACC-ZUPD_DATE =
ZSDSCMC005-ZUPD_DATE .
ZSDSV_CM_GLACC-ZUPD_TIME =
ZSDSCMC005-ZUPD_TIME .
ZSDSV_CM_GLACC-ZUPD_USER =
ZSDSCMC005-ZUPD_USER .
ZSDSV_CM_GLACC-ZUPD_PGM =
ZSDSCMC005-ZUPD_PGM .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZSDSV_CM_GLACC USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZSDSV_CM_GLACC-SALES_ORG_SD TO
ZSDSCMC005-SALES_ORG_SD .
MOVE ZSDSV_CM_GLACC-PROCESS_TYPE TO
ZSDSCMC005-PROCESS_TYPE .
MOVE ZSDSV_CM_GLACC-ITM_TYPE TO
ZSDSCMC005-ITM_TYPE .
MOVE ZSDSV_CM_GLACC-BKLAS TO
ZSDSCMC005-BKLAS .
MOVE ZSDSV_CM_GLACC-MANDT TO
ZSDSCMC005-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZSDSCMC005'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZSDSCMC005 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZSDSCMC005'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
