*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZSDSV_SVO_TYPE..................................*
FORM GET_DATA_ZSDSV_SVO_TYPE.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZSDSCMT001 WHERE
(VIM_WHERETAB) .
    CLEAR ZSDSV_SVO_TYPE .
ZSDSV_SVO_TYPE-MANDT =
ZSDSCMT001-MANDT .
ZSDSV_SVO_TYPE-SVO_TYPE =
ZSDSCMT001-SVO_TYPE .
ZSDSV_SVO_TYPE-MATKL =
ZSDSCMT001-MATKL .
ZSDSV_SVO_TYPE-IS_BILLING =
ZSDSCMT001-IS_BILLING .
ZSDSV_SVO_TYPE-IS_PR =
ZSDSCMT001-IS_PR .
ZSDSV_SVO_TYPE-WARRANTY_CHECK =
ZSDSCMT001-WARRANTY_CHECK .
ZSDSV_SVO_TYPE-ITM_TYPE =
ZSDSCMT001-ITM_TYPE .
ZSDSV_SVO_TYPE-ZDEL_FLG =
ZSDSCMT001-ZDEL_FLG .
ZSDSV_SVO_TYPE-ZCRT_DATE =
ZSDSCMT001-ZCRT_DATE .
ZSDSV_SVO_TYPE-ZCRT_TIME =
ZSDSCMT001-ZCRT_TIME .
ZSDSV_SVO_TYPE-ZCRT_USER =
ZSDSCMT001-ZCRT_USER .
ZSDSV_SVO_TYPE-ZCRT_PGM =
ZSDSCMT001-ZCRT_PGM .
ZSDSV_SVO_TYPE-ZUPD_DATE =
ZSDSCMT001-ZUPD_DATE .
ZSDSV_SVO_TYPE-ZUPD_TIME =
ZSDSCMT001-ZUPD_TIME .
ZSDSV_SVO_TYPE-ZUPD_USER =
ZSDSCMT001-ZUPD_USER .
ZSDSV_SVO_TYPE-ZUPD_PGM =
ZSDSCMT001-ZUPD_PGM .
<VIM_TOTAL_STRUC> = ZSDSV_SVO_TYPE.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZSDSV_SVO_TYPE .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZSDSV_SVO_TYPE.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZSDSV_SVO_TYPE-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZSDSCMT001 WHERE
  SVO_TYPE = ZSDSV_SVO_TYPE-SVO_TYPE AND
  MATKL = ZSDSV_SVO_TYPE-MATKL AND
  IS_BILLING = ZSDSV_SVO_TYPE-IS_BILLING AND
  IS_PR = ZSDSV_SVO_TYPE-IS_PR AND
  WARRANTY_CHECK = ZSDSV_SVO_TYPE-WARRANTY_CHECK .
    IF SY-SUBRC = 0.
    DELETE ZSDSCMT001 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZSDSCMT001 WHERE
  SVO_TYPE = ZSDSV_SVO_TYPE-SVO_TYPE AND
  MATKL = ZSDSV_SVO_TYPE-MATKL AND
  IS_BILLING = ZSDSV_SVO_TYPE-IS_BILLING AND
  IS_PR = ZSDSV_SVO_TYPE-IS_PR AND
  WARRANTY_CHECK = ZSDSV_SVO_TYPE-WARRANTY_CHECK .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZSDSCMT001.
    ENDIF.
ZSDSCMT001-MANDT =
ZSDSV_SVO_TYPE-MANDT .
ZSDSCMT001-SVO_TYPE =
ZSDSV_SVO_TYPE-SVO_TYPE .
ZSDSCMT001-MATKL =
ZSDSV_SVO_TYPE-MATKL .
ZSDSCMT001-IS_BILLING =
ZSDSV_SVO_TYPE-IS_BILLING .
ZSDSCMT001-IS_PR =
ZSDSV_SVO_TYPE-IS_PR .
ZSDSCMT001-WARRANTY_CHECK =
ZSDSV_SVO_TYPE-WARRANTY_CHECK .
ZSDSCMT001-ITM_TYPE =
ZSDSV_SVO_TYPE-ITM_TYPE .
ZSDSCMT001-ZDEL_FLG =
ZSDSV_SVO_TYPE-ZDEL_FLG .
ZSDSCMT001-ZCRT_DATE =
ZSDSV_SVO_TYPE-ZCRT_DATE .
ZSDSCMT001-ZCRT_TIME =
ZSDSV_SVO_TYPE-ZCRT_TIME .
ZSDSCMT001-ZCRT_USER =
ZSDSV_SVO_TYPE-ZCRT_USER .
ZSDSCMT001-ZCRT_PGM =
ZSDSV_SVO_TYPE-ZCRT_PGM .
ZSDSCMT001-ZUPD_DATE =
ZSDSV_SVO_TYPE-ZUPD_DATE .
ZSDSCMT001-ZUPD_TIME =
ZSDSV_SVO_TYPE-ZUPD_TIME .
ZSDSCMT001-ZUPD_USER =
ZSDSV_SVO_TYPE-ZUPD_USER .
ZSDSCMT001-ZUPD_PGM =
ZSDSV_SVO_TYPE-ZUPD_PGM .
    IF SY-SUBRC = 0.
    UPDATE ZSDSCMT001 ##WARN_OK.
    ELSE.
    INSERT ZSDSCMT001 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZSDSV_SVO_TYPE-UPD_FLAG,
STATUS_ZSDSV_SVO_TYPE-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZSDSV_SVO_TYPE.
  SELECT SINGLE * FROM ZSDSCMT001 WHERE
SVO_TYPE = ZSDSV_SVO_TYPE-SVO_TYPE AND
MATKL = ZSDSV_SVO_TYPE-MATKL AND
IS_BILLING = ZSDSV_SVO_TYPE-IS_BILLING AND
IS_PR = ZSDSV_SVO_TYPE-IS_PR AND
WARRANTY_CHECK = ZSDSV_SVO_TYPE-WARRANTY_CHECK .
ZSDSV_SVO_TYPE-MANDT =
ZSDSCMT001-MANDT .
ZSDSV_SVO_TYPE-SVO_TYPE =
ZSDSCMT001-SVO_TYPE .
ZSDSV_SVO_TYPE-MATKL =
ZSDSCMT001-MATKL .
ZSDSV_SVO_TYPE-IS_BILLING =
ZSDSCMT001-IS_BILLING .
ZSDSV_SVO_TYPE-IS_PR =
ZSDSCMT001-IS_PR .
ZSDSV_SVO_TYPE-WARRANTY_CHECK =
ZSDSCMT001-WARRANTY_CHECK .
ZSDSV_SVO_TYPE-ITM_TYPE =
ZSDSCMT001-ITM_TYPE .
ZSDSV_SVO_TYPE-ZDEL_FLG =
ZSDSCMT001-ZDEL_FLG .
ZSDSV_SVO_TYPE-ZCRT_DATE =
ZSDSCMT001-ZCRT_DATE .
ZSDSV_SVO_TYPE-ZCRT_TIME =
ZSDSCMT001-ZCRT_TIME .
ZSDSV_SVO_TYPE-ZCRT_USER =
ZSDSCMT001-ZCRT_USER .
ZSDSV_SVO_TYPE-ZCRT_PGM =
ZSDSCMT001-ZCRT_PGM .
ZSDSV_SVO_TYPE-ZUPD_DATE =
ZSDSCMT001-ZUPD_DATE .
ZSDSV_SVO_TYPE-ZUPD_TIME =
ZSDSCMT001-ZUPD_TIME .
ZSDSV_SVO_TYPE-ZUPD_USER =
ZSDSCMT001-ZUPD_USER .
ZSDSV_SVO_TYPE-ZUPD_PGM =
ZSDSCMT001-ZUPD_PGM .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZSDSV_SVO_TYPE USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZSDSV_SVO_TYPE-SVO_TYPE TO
ZSDSCMT001-SVO_TYPE .
MOVE ZSDSV_SVO_TYPE-MATKL TO
ZSDSCMT001-MATKL .
MOVE ZSDSV_SVO_TYPE-IS_BILLING TO
ZSDSCMT001-IS_BILLING .
MOVE ZSDSV_SVO_TYPE-IS_PR TO
ZSDSCMT001-IS_PR .
MOVE ZSDSV_SVO_TYPE-WARRANTY_CHECK TO
ZSDSCMT001-WARRANTY_CHECK .
MOVE ZSDSV_SVO_TYPE-MANDT TO
ZSDSCMT001-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZSDSCMT001'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZSDSCMT001 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZSDSCMT001'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
