"Name: \PR:SAPLKAUF\FO:COSTING_CHANGE\SE:END\EI
ENHANCEMENT 0 ZSDS_CM_IO_COSTING_CHANGE.
*<-- Start of Insertion CME020 08.08.2024
* SDS: Change IO Attributes
  ZCL_SDSCM_ENHANCEMENT=>CHANGE_IO_COSTING(
    CHANGING
      CS_COAS = LS_COAS ).
*--> End of Insertion CME020 08.08.2024
ENDENHANCEMENT.
