*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZSDSV_MAT_WRT...................................*
FORM GET_DATA_ZSDSV_MAT_WRT.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZSDSCMC003 WHERE
(VIM_WHERETAB) .
    CLEAR ZSDSV_MAT_WRT .
ZSDSV_MAT_WRT-MANDT =
ZSDSCMC003-MANDT .
ZSDSV_MAT_WRT-WRTPK =
ZSDSCMC003-WRTPK .
ZSDSV_MAT_WRT-MATNR =
ZSDSCMC003-MATNR .
ZSDSV_MAT_WRT-ENDDA =
ZSDSCMC003-ENDDA .
ZSDSV_MAT_WRT-BEGDA =
ZSDSCMC003-BEGDA .
ZSDSV_MAT_WRT-GIWRT =
ZSDSCMC003-GIWRT .
ZSDSV_MAT_WRT-RGWRT =
ZSDSCMC003-RGWRT .
ZSDSV_MAT_WRT-ZDEL_FLG =
ZSDSCMC003-ZDEL_FLG .
ZSDSV_MAT_WRT-ZCRT_DATE =
ZSDSCMC003-ZCRT_DATE .
ZSDSV_MAT_WRT-ZCRT_TIME =
ZSDSCMC003-ZCRT_TIME .
ZSDSV_MAT_WRT-ZCRT_USER =
ZSDSCMC003-ZCRT_USER .
ZSDSV_MAT_WRT-ZCRT_PGM =
ZSDSCMC003-ZCRT_PGM .
ZSDSV_MAT_WRT-ZUPD_DATE =
ZSDSCMC003-ZUPD_DATE .
ZSDSV_MAT_WRT-ZUPD_TIME =
ZSDSCMC003-ZUPD_TIME .
ZSDSV_MAT_WRT-ZUPD_USER =
ZSDSCMC003-ZUPD_USER .
ZSDSV_MAT_WRT-ZUPD_PGM =
ZSDSCMC003-ZUPD_PGM .
<VIM_TOTAL_STRUC> = ZSDSV_MAT_WRT.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZSDSV_MAT_WRT .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZSDSV_MAT_WRT.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZSDSV_MAT_WRT-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZSDSCMC003 WHERE
  WRTPK = ZSDSV_MAT_WRT-WRTPK AND
  MATNR = ZSDSV_MAT_WRT-MATNR AND
  ENDDA = ZSDSV_MAT_WRT-ENDDA .
    IF SY-SUBRC = 0.
    DELETE ZSDSCMC003 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZSDSCMC003 WHERE
  WRTPK = ZSDSV_MAT_WRT-WRTPK AND
  MATNR = ZSDSV_MAT_WRT-MATNR AND
  ENDDA = ZSDSV_MAT_WRT-ENDDA .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZSDSCMC003.
    ENDIF.
ZSDSCMC003-MANDT =
ZSDSV_MAT_WRT-MANDT .
ZSDSCMC003-WRTPK =
ZSDSV_MAT_WRT-WRTPK .
ZSDSCMC003-MATNR =
ZSDSV_MAT_WRT-MATNR .
ZSDSCMC003-ENDDA =
ZSDSV_MAT_WRT-ENDDA .
ZSDSCMC003-BEGDA =
ZSDSV_MAT_WRT-BEGDA .
ZSDSCMC003-GIWRT =
ZSDSV_MAT_WRT-GIWRT .
ZSDSCMC003-RGWRT =
ZSDSV_MAT_WRT-RGWRT .
ZSDSCMC003-ZDEL_FLG =
ZSDSV_MAT_WRT-ZDEL_FLG .
ZSDSCMC003-ZCRT_DATE =
ZSDSV_MAT_WRT-ZCRT_DATE .
ZSDSCMC003-ZCRT_TIME =
ZSDSV_MAT_WRT-ZCRT_TIME .
ZSDSCMC003-ZCRT_USER =
ZSDSV_MAT_WRT-ZCRT_USER .
ZSDSCMC003-ZCRT_PGM =
ZSDSV_MAT_WRT-ZCRT_PGM .
ZSDSCMC003-ZUPD_DATE =
ZSDSV_MAT_WRT-ZUPD_DATE .
ZSDSCMC003-ZUPD_TIME =
ZSDSV_MAT_WRT-ZUPD_TIME .
ZSDSCMC003-ZUPD_USER =
ZSDSV_MAT_WRT-ZUPD_USER .
ZSDSCMC003-ZUPD_PGM =
ZSDSV_MAT_WRT-ZUPD_PGM .
    IF SY-SUBRC = 0.
    UPDATE ZSDSCMC003 ##WARN_OK.
    ELSE.
    INSERT ZSDSCMC003 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZSDSV_MAT_WRT-UPD_FLAG,
STATUS_ZSDSV_MAT_WRT-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZSDSV_MAT_WRT.
  SELECT SINGLE * FROM ZSDSCMC003 WHERE
WRTPK = ZSDSV_MAT_WRT-WRTPK AND
MATNR = ZSDSV_MAT_WRT-MATNR AND
ENDDA = ZSDSV_MAT_WRT-ENDDA .
ZSDSV_MAT_WRT-MANDT =
ZSDSCMC003-MANDT .
ZSDSV_MAT_WRT-WRTPK =
ZSDSCMC003-WRTPK .
ZSDSV_MAT_WRT-MATNR =
ZSDSCMC003-MATNR .
ZSDSV_MAT_WRT-ENDDA =
ZSDSCMC003-ENDDA .
ZSDSV_MAT_WRT-BEGDA =
ZSDSCMC003-BEGDA .
ZSDSV_MAT_WRT-GIWRT =
ZSDSCMC003-GIWRT .
ZSDSV_MAT_WRT-RGWRT =
ZSDSCMC003-RGWRT .
ZSDSV_MAT_WRT-ZDEL_FLG =
ZSDSCMC003-ZDEL_FLG .
ZSDSV_MAT_WRT-ZCRT_DATE =
ZSDSCMC003-ZCRT_DATE .
ZSDSV_MAT_WRT-ZCRT_TIME =
ZSDSCMC003-ZCRT_TIME .
ZSDSV_MAT_WRT-ZCRT_USER =
ZSDSCMC003-ZCRT_USER .
ZSDSV_MAT_WRT-ZCRT_PGM =
ZSDSCMC003-ZCRT_PGM .
ZSDSV_MAT_WRT-ZUPD_DATE =
ZSDSCMC003-ZUPD_DATE .
ZSDSV_MAT_WRT-ZUPD_TIME =
ZSDSCMC003-ZUPD_TIME .
ZSDSV_MAT_WRT-ZUPD_USER =
ZSDSCMC003-ZUPD_USER .
ZSDSV_MAT_WRT-ZUPD_PGM =
ZSDSCMC003-ZUPD_PGM .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZSDSV_MAT_WRT USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZSDSV_MAT_WRT-WRTPK TO
ZSDSCMC003-WRTPK .
MOVE ZSDSV_MAT_WRT-MATNR TO
ZSDSCMC003-MATNR .
MOVE ZSDSV_MAT_WRT-ENDDA TO
ZSDSCMC003-ENDDA .
MOVE ZSDSV_MAT_WRT-MANDT TO
ZSDSCMC003-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZSDSCMC003'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZSDSCMC003 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZSDSCMC003'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
