*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZSDSV_PLANT_SRV.................................*
FORM GET_DATA_ZSDSV_PLANT_SRV.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM CRMS4C_PLANT_SRV WHERE
(VIM_WHERETAB) .
    CLEAR ZSDSV_PLANT_SRV .
ZSDSV_PLANT_SRV-MANDT =
CRMS4C_PLANT_SRV-MANDT .
ZSDSV_PLANT_SRV-LAND1 =
CRMS4C_PLANT_SRV-LAND1 .
ZSDSV_PLANT_SRV-EMPLOYEE =
CRMS4C_PLANT_SRV-EMPLOYEE .
ZSDSV_PLANT_SRV-PLANT =
CRMS4C_PLANT_SRV-PLANT .
ZSDSV_PLANT_SRV-STORAGE_LOC =
CRMS4C_PLANT_SRV-STORAGE_LOC .
ZSDSV_PLANT_SRV-INDIV_STORAGE_LOC =
CRMS4C_PLANT_SRV-INDIV_STORAGE_LOC .
<VIM_TOTAL_STRUC> = ZSDSV_PLANT_SRV.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZSDSV_PLANT_SRV .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZSDSV_PLANT_SRV.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZSDSV_PLANT_SRV-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM CRMS4C_PLANT_SRV WHERE
  LAND1 = ZSDSV_PLANT_SRV-LAND1 AND
  EMPLOYEE = ZSDSV_PLANT_SRV-EMPLOYEE .
    IF SY-SUBRC = 0.
    DELETE CRMS4C_PLANT_SRV .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM CRMS4C_PLANT_SRV WHERE
  LAND1 = ZSDSV_PLANT_SRV-LAND1 AND
  EMPLOYEE = ZSDSV_PLANT_SRV-EMPLOYEE .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR CRMS4C_PLANT_SRV.
    ENDIF.
CRMS4C_PLANT_SRV-MANDT =
ZSDSV_PLANT_SRV-MANDT .
CRMS4C_PLANT_SRV-LAND1 =
ZSDSV_PLANT_SRV-LAND1 .
CRMS4C_PLANT_SRV-EMPLOYEE =
ZSDSV_PLANT_SRV-EMPLOYEE .
CRMS4C_PLANT_SRV-PLANT =
ZSDSV_PLANT_SRV-PLANT .
CRMS4C_PLANT_SRV-STORAGE_LOC =
ZSDSV_PLANT_SRV-STORAGE_LOC .
CRMS4C_PLANT_SRV-INDIV_STORAGE_LOC =
ZSDSV_PLANT_SRV-INDIV_STORAGE_LOC .
    IF SY-SUBRC = 0.
    UPDATE CRMS4C_PLANT_SRV ##WARN_OK.
    ELSE.
    INSERT CRMS4C_PLANT_SRV .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZSDSV_PLANT_SRV-UPD_FLAG,
STATUS_ZSDSV_PLANT_SRV-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZSDSV_PLANT_SRV.
  SELECT SINGLE * FROM CRMS4C_PLANT_SRV WHERE
LAND1 = ZSDSV_PLANT_SRV-LAND1 AND
EMPLOYEE = ZSDSV_PLANT_SRV-EMPLOYEE .
ZSDSV_PLANT_SRV-MANDT =
CRMS4C_PLANT_SRV-MANDT .
ZSDSV_PLANT_SRV-LAND1 =
CRMS4C_PLANT_SRV-LAND1 .
ZSDSV_PLANT_SRV-EMPLOYEE =
CRMS4C_PLANT_SRV-EMPLOYEE .
ZSDSV_PLANT_SRV-PLANT =
CRMS4C_PLANT_SRV-PLANT .
ZSDSV_PLANT_SRV-STORAGE_LOC =
CRMS4C_PLANT_SRV-STORAGE_LOC .
ZSDSV_PLANT_SRV-INDIV_STORAGE_LOC =
CRMS4C_PLANT_SRV-INDIV_STORAGE_LOC .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZSDSV_PLANT_SRV USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZSDSV_PLANT_SRV-LAND1 TO
CRMS4C_PLANT_SRV-LAND1 .
MOVE ZSDSV_PLANT_SRV-EMPLOYEE TO
CRMS4C_PLANT_SRV-EMPLOYEE .
MOVE ZSDSV_PLANT_SRV-MANDT TO
CRMS4C_PLANT_SRV-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'CRMS4C_PLANT_SRV'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN CRMS4C_PLANT_SRV TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'CRMS4C_PLANT_SRV'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
