*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZSDSV_WRT_PKG_V1................................*
FORM GET_DATA_ZSDSV_WRT_PKG_V1.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZSDSCMC009 WHERE
(VIM_WHERETAB) .
    CLEAR ZSDSV_WRT_PKG_V1 .
ZSDSV_WRT_PKG_V1-MANDT =
ZSDSCMC009-MANDT .
ZSDSV_WRT_PKG_V1-WRTPK =
ZSDSCMC009-WRTPK .
ZSDSV_WRT_PKG_V1-MATKL =
ZSDSCMC009-MATKL .
ZSDSV_WRT_PKG_V1-STWRT =
ZSDSCMC009-STWRT .
ZSDSV_WRT_PKG_V1-STWRTM =
ZSDSCMC009-STWRTM .
ZSDSV_WRT_PKG_V1-ZDEL_FLG =
ZSDSCMC009-ZDEL_FLG .
ZSDSV_WRT_PKG_V1-ZCRT_DATE =
ZSDSCMC009-ZCRT_DATE .
ZSDSV_WRT_PKG_V1-ZCRT_TIME =
ZSDSCMC009-ZCRT_TIME .
ZSDSV_WRT_PKG_V1-ZCRT_USER =
ZSDSCMC009-ZCRT_USER .
ZSDSV_WRT_PKG_V1-ZCRT_PGM =
ZSDSCMC009-ZCRT_PGM .
ZSDSV_WRT_PKG_V1-ZUPD_DATE =
ZSDSCMC009-ZUPD_DATE .
ZSDSV_WRT_PKG_V1-ZUPD_TIME =
ZSDSCMC009-ZUPD_TIME .
ZSDSV_WRT_PKG_V1-ZUPD_USER =
ZSDSCMC009-ZUPD_USER .
ZSDSV_WRT_PKG_V1-ZUPD_PGM =
ZSDSCMC009-ZUPD_PGM .
<VIM_TOTAL_STRUC> = ZSDSV_WRT_PKG_V1.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZSDSV_WRT_PKG_V1 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZSDSV_WRT_PKG_V1.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZSDSV_WRT_PKG_V1-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZSDSCMC009 WHERE
  WRTPK = ZSDSV_WRT_PKG_V1-WRTPK AND
  MATKL = ZSDSV_WRT_PKG_V1-MATKL .
    IF SY-SUBRC = 0.
    DELETE ZSDSCMC009 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZSDSCMC009 WHERE
  WRTPK = ZSDSV_WRT_PKG_V1-WRTPK AND
  MATKL = ZSDSV_WRT_PKG_V1-MATKL .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZSDSCMC009.
    ENDIF.
ZSDSCMC009-MANDT =
ZSDSV_WRT_PKG_V1-MANDT .
ZSDSCMC009-WRTPK =
ZSDSV_WRT_PKG_V1-WRTPK .
ZSDSCMC009-MATKL =
ZSDSV_WRT_PKG_V1-MATKL .
ZSDSCMC009-STWRT =
ZSDSV_WRT_PKG_V1-STWRT .
ZSDSCMC009-STWRTM =
ZSDSV_WRT_PKG_V1-STWRTM .
ZSDSCMC009-ZDEL_FLG =
ZSDSV_WRT_PKG_V1-ZDEL_FLG .
ZSDSCMC009-ZCRT_DATE =
ZSDSV_WRT_PKG_V1-ZCRT_DATE .
ZSDSCMC009-ZCRT_TIME =
ZSDSV_WRT_PKG_V1-ZCRT_TIME .
ZSDSCMC009-ZCRT_USER =
ZSDSV_WRT_PKG_V1-ZCRT_USER .
ZSDSCMC009-ZCRT_PGM =
ZSDSV_WRT_PKG_V1-ZCRT_PGM .
ZSDSCMC009-ZUPD_DATE =
ZSDSV_WRT_PKG_V1-ZUPD_DATE .
ZSDSCMC009-ZUPD_TIME =
ZSDSV_WRT_PKG_V1-ZUPD_TIME .
ZSDSCMC009-ZUPD_USER =
ZSDSV_WRT_PKG_V1-ZUPD_USER .
ZSDSCMC009-ZUPD_PGM =
ZSDSV_WRT_PKG_V1-ZUPD_PGM .
    IF SY-SUBRC = 0.
    UPDATE ZSDSCMC009 ##WARN_OK.
    ELSE.
    INSERT ZSDSCMC009 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZSDSV_WRT_PKG_V1-UPD_FLAG,
STATUS_ZSDSV_WRT_PKG_V1-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZSDSV_WRT_PKG_V1.
  SELECT SINGLE * FROM ZSDSCMC009 WHERE
WRTPK = ZSDSV_WRT_PKG_V1-WRTPK AND
MATKL = ZSDSV_WRT_PKG_V1-MATKL .
ZSDSV_WRT_PKG_V1-MANDT =
ZSDSCMC009-MANDT .
ZSDSV_WRT_PKG_V1-WRTPK =
ZSDSCMC009-WRTPK .
ZSDSV_WRT_PKG_V1-MATKL =
ZSDSCMC009-MATKL .
ZSDSV_WRT_PKG_V1-STWRT =
ZSDSCMC009-STWRT .
ZSDSV_WRT_PKG_V1-STWRTM =
ZSDSCMC009-STWRTM .
ZSDSV_WRT_PKG_V1-ZDEL_FLG =
ZSDSCMC009-ZDEL_FLG .
ZSDSV_WRT_PKG_V1-ZCRT_DATE =
ZSDSCMC009-ZCRT_DATE .
ZSDSV_WRT_PKG_V1-ZCRT_TIME =
ZSDSCMC009-ZCRT_TIME .
ZSDSV_WRT_PKG_V1-ZCRT_USER =
ZSDSCMC009-ZCRT_USER .
ZSDSV_WRT_PKG_V1-ZCRT_PGM =
ZSDSCMC009-ZCRT_PGM .
ZSDSV_WRT_PKG_V1-ZUPD_DATE =
ZSDSCMC009-ZUPD_DATE .
ZSDSV_WRT_PKG_V1-ZUPD_TIME =
ZSDSCMC009-ZUPD_TIME .
ZSDSV_WRT_PKG_V1-ZUPD_USER =
ZSDSCMC009-ZUPD_USER .
ZSDSV_WRT_PKG_V1-ZUPD_PGM =
ZSDSCMC009-ZUPD_PGM .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZSDSV_WRT_PKG_V1 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZSDSV_WRT_PKG_V1-WRTPK TO
ZSDSCMC009-WRTPK .
MOVE ZSDSV_WRT_PKG_V1-MATKL TO
ZSDSCMC009-MATKL .
MOVE ZSDSV_WRT_PKG_V1-MANDT TO
ZSDSCMC009-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZSDSCMC009'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZSDSCMC009 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZSDSCMC009'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
