*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZSDSV_CM_PRCTR..................................*
FORM GET_DATA_ZSDSV_CM_PRCTR.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZSDSCMC001 WHERE
(VIM_WHERETAB) .
    CLEAR ZSDSV_CM_PRCTR .
ZSDSV_CM_PRCTR-MANDT =
ZSDSCMC001-MANDT .
ZSDSV_CM_PRCTR-SALES_ORG_SD =
ZSDSCMC001-SALES_ORG_SD .
ZSDSV_CM_PRCTR-PROCESS_TYPE =
ZSDSCMC001-PROCESS_TYPE .
ZSDSV_CM_PRCTR-SALES_OFFICE_SD =
ZSDSCMC001-SALES_OFFICE_SD .
ZSDSV_CM_PRCTR-SALES_GROUP_SD =
ZSDSCMC001-SALES_GROUP_SD .
ZSDSV_CM_PRCTR-PRCTR =
ZSDSCMC001-PRCTR .
ZSDSV_CM_PRCTR-ZDEL_FLG =
ZSDSCMC001-ZDEL_FLG .
ZSDSV_CM_PRCTR-ZCRT_DATE =
ZSDSCMC001-ZCRT_DATE .
ZSDSV_CM_PRCTR-ZCRT_TIME =
ZSDSCMC001-ZCRT_TIME .
ZSDSV_CM_PRCTR-ZCRT_USER =
ZSDSCMC001-ZCRT_USER .
ZSDSV_CM_PRCTR-ZCRT_PGM =
ZSDSCMC001-ZCRT_PGM .
ZSDSV_CM_PRCTR-ZUPD_DATE =
ZSDSCMC001-ZUPD_DATE .
ZSDSV_CM_PRCTR-ZUPD_TIME =
ZSDSCMC001-ZUPD_TIME .
ZSDSV_CM_PRCTR-ZUPD_USER =
ZSDSCMC001-ZUPD_USER .
ZSDSV_CM_PRCTR-ZUPD_PGM =
ZSDSCMC001-ZUPD_PGM .
<VIM_TOTAL_STRUC> = ZSDSV_CM_PRCTR.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZSDSV_CM_PRCTR .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZSDSV_CM_PRCTR.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZSDSV_CM_PRCTR-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZSDSCMC001 WHERE
  SALES_ORG_SD = ZSDSV_CM_PRCTR-SALES_ORG_SD AND
  PROCESS_TYPE = ZSDSV_CM_PRCTR-PROCESS_TYPE AND
  SALES_OFFICE_SD = ZSDSV_CM_PRCTR-SALES_OFFICE_SD AND
  SALES_GROUP_SD = ZSDSV_CM_PRCTR-SALES_GROUP_SD .
    IF SY-SUBRC = 0.
    DELETE ZSDSCMC001 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZSDSCMC001 WHERE
  SALES_ORG_SD = ZSDSV_CM_PRCTR-SALES_ORG_SD AND
  PROCESS_TYPE = ZSDSV_CM_PRCTR-PROCESS_TYPE AND
  SALES_OFFICE_SD = ZSDSV_CM_PRCTR-SALES_OFFICE_SD AND
  SALES_GROUP_SD = ZSDSV_CM_PRCTR-SALES_GROUP_SD .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZSDSCMC001.
    ENDIF.
ZSDSCMC001-MANDT =
ZSDSV_CM_PRCTR-MANDT .
ZSDSCMC001-SALES_ORG_SD =
ZSDSV_CM_PRCTR-SALES_ORG_SD .
ZSDSCMC001-PROCESS_TYPE =
ZSDSV_CM_PRCTR-PROCESS_TYPE .
ZSDSCMC001-SALES_OFFICE_SD =
ZSDSV_CM_PRCTR-SALES_OFFICE_SD .
ZSDSCMC001-SALES_GROUP_SD =
ZSDSV_CM_PRCTR-SALES_GROUP_SD .
ZSDSCMC001-PRCTR =
ZSDSV_CM_PRCTR-PRCTR .
ZSDSCMC001-ZDEL_FLG =
ZSDSV_CM_PRCTR-ZDEL_FLG .
ZSDSCMC001-ZCRT_DATE =
ZSDSV_CM_PRCTR-ZCRT_DATE .
ZSDSCMC001-ZCRT_TIME =
ZSDSV_CM_PRCTR-ZCRT_TIME .
ZSDSCMC001-ZCRT_USER =
ZSDSV_CM_PRCTR-ZCRT_USER .
ZSDSCMC001-ZCRT_PGM =
ZSDSV_CM_PRCTR-ZCRT_PGM .
ZSDSCMC001-ZUPD_DATE =
ZSDSV_CM_PRCTR-ZUPD_DATE .
ZSDSCMC001-ZUPD_TIME =
ZSDSV_CM_PRCTR-ZUPD_TIME .
ZSDSCMC001-ZUPD_USER =
ZSDSV_CM_PRCTR-ZUPD_USER .
ZSDSCMC001-ZUPD_PGM =
ZSDSV_CM_PRCTR-ZUPD_PGM .
    IF SY-SUBRC = 0.
    UPDATE ZSDSCMC001 ##WARN_OK.
    ELSE.
    INSERT ZSDSCMC001 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZSDSV_CM_PRCTR-UPD_FLAG,
STATUS_ZSDSV_CM_PRCTR-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZSDSV_CM_PRCTR.
  SELECT SINGLE * FROM ZSDSCMC001 WHERE
SALES_ORG_SD = ZSDSV_CM_PRCTR-SALES_ORG_SD AND
PROCESS_TYPE = ZSDSV_CM_PRCTR-PROCESS_TYPE AND
SALES_OFFICE_SD = ZSDSV_CM_PRCTR-SALES_OFFICE_SD AND
SALES_GROUP_SD = ZSDSV_CM_PRCTR-SALES_GROUP_SD .
ZSDSV_CM_PRCTR-MANDT =
ZSDSCMC001-MANDT .
ZSDSV_CM_PRCTR-SALES_ORG_SD =
ZSDSCMC001-SALES_ORG_SD .
ZSDSV_CM_PRCTR-PROCESS_TYPE =
ZSDSCMC001-PROCESS_TYPE .
ZSDSV_CM_PRCTR-SALES_OFFICE_SD =
ZSDSCMC001-SALES_OFFICE_SD .
ZSDSV_CM_PRCTR-SALES_GROUP_SD =
ZSDSCMC001-SALES_GROUP_SD .
ZSDSV_CM_PRCTR-PRCTR =
ZSDSCMC001-PRCTR .
ZSDSV_CM_PRCTR-ZDEL_FLG =
ZSDSCMC001-ZDEL_FLG .
ZSDSV_CM_PRCTR-ZCRT_DATE =
ZSDSCMC001-ZCRT_DATE .
ZSDSV_CM_PRCTR-ZCRT_TIME =
ZSDSCMC001-ZCRT_TIME .
ZSDSV_CM_PRCTR-ZCRT_USER =
ZSDSCMC001-ZCRT_USER .
ZSDSV_CM_PRCTR-ZCRT_PGM =
ZSDSCMC001-ZCRT_PGM .
ZSDSV_CM_PRCTR-ZUPD_DATE =
ZSDSCMC001-ZUPD_DATE .
ZSDSV_CM_PRCTR-ZUPD_TIME =
ZSDSCMC001-ZUPD_TIME .
ZSDSV_CM_PRCTR-ZUPD_USER =
ZSDSCMC001-ZUPD_USER .
ZSDSV_CM_PRCTR-ZUPD_PGM =
ZSDSCMC001-ZUPD_PGM .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZSDSV_CM_PRCTR USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZSDSV_CM_PRCTR-SALES_ORG_SD TO
ZSDSCMC001-SALES_ORG_SD .
MOVE ZSDSV_CM_PRCTR-PROCESS_TYPE TO
ZSDSCMC001-PROCESS_TYPE .
MOVE ZSDSV_CM_PRCTR-SALES_OFFICE_SD TO
ZSDSCMC001-SALES_OFFICE_SD .
MOVE ZSDSV_CM_PRCTR-SALES_GROUP_SD TO
ZSDSCMC001-SALES_GROUP_SD .
MOVE ZSDSV_CM_PRCTR-MANDT TO
ZSDSCMC001-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZSDSCMC001'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZSDSCMC001 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZSDSCMC001'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
