@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_FD6739E53583'

extend view A_SERVICECONTRACT with ZZ1_YCKQ5A4RSU237OETUQLAQTMP6U
  
{ 
  _Extension.ZZ1_PROACTIVITY as ZZ1_PROACTIVITY
}
