@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_D450C3C9E999'

extend view C_EXPIRINGSRVCCONTRITMDETAILS with ZZ1_PJKCFUDNAYJEW4TIQSP3YT4TOE
  
{ 
  _ServiceDocItemExt.ZZ1_VENDOR_TEAM as ZZ1_VENDOR_TEAM
}
