FUNCTION Z_SDSCA_OPT_GET_OVERLAY_FORM.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(REPID) TYPE  REPID
*"     REFERENCE(COMP_CODE) TYPE  BUKRS
*"     REFERENCE(DOC_TYPE) TYPE  CHAR4 OPTIONAL
*"     REFERENCE(CUSTOMER_COPY) TYPE  CHAR1 OPTIONAL
*"  CHANGING
*"     REFERENCE(TOA_DARA) TYPE  TOA_DARA
*"     REFERENCE(LAYOUT_SET) TYPE  ZSDSCAC007 OPTIONAL
*"----------------------------------------------------------------------
  DATA: LWA_LAYOUT_SET TYPE ZSDSCAC007.

  DATA: LV_LAYOUT_SET TYPE CHAR30,
        LV_CODE       TYPE CHAR4.

  SELECT SINGLE *
    INTO LWA_LAYOUT_SET
    FROM ZSDSCAC007
   WHERE PROGRAM_NAME EQ REPID
     AND TYPE         EQ DOC_TYPE.
  IF SY-SUBRC EQ 0.

    IF CUSTOMER_COPY IS INITIAL.
      LV_LAYOUT_SET = LWA_LAYOUT_SET-LAYOUT.
    ELSE.
      LV_LAYOUT_SET = LWA_LAYOUT_SET-CUSTOMER_LAYOUT.
    ENDIF.
    LAYOUT_SET    = LWA_LAYOUT_SET.

    LV_CODE       = COMP_CODE.

    IF LWA_LAYOUT_SET-SAP_OBJECT IS NOT INITIAL.
      TOA_DARA-SAP_OBJECT = LWA_LAYOUT_SET-SAP_OBJECT.
    ENDIF.

    IF CUSTOMER_COPY IS INITIAL.

      IF LWA_LAYOUT_SET-AR_OBJECT IS NOT INITIAL.
        TOA_DARA-AR_OBJECT  = LWA_LAYOUT_SET-AR_OBJECT.
      ENDIF.

    ELSE.

      IF LWA_LAYOUT_SET-CUST_AR_OBJECT IS NOT INITIAL.
        TOA_DARA-AR_OBJECT  = LWA_LAYOUT_SET-CUST_AR_OBJECT.
      ELSE.
        TOA_DARA-AR_OBJECT  = LWA_LAYOUT_SET-AR_OBJECT.
      ENDIF.

    ENDIF.

    IF LV_LAYOUT_SET IS NOT INITIAL.

      CALL FUNCTION 'J_8AFM_GET_SMART_FORM'
        EXPORTING
          CODE                   = LV_CODE
          LAYOUT_SET             = LV_LAYOUT_SET
        IMPORTING
          FORM_ARCH_ID           = TOA_DARA-FORMARCHIV
          FORM_DOC_ID            = TOA_DARA-FORM_ID
        EXCEPTIONS
          CODE_DOES_NOT_EXIST    = 1
          FORM_DOES_NOT_EXIST    = 2
          VERSION_DOES_NOT_EXIST = 3
          OTHERS                 = 4.
      IF SY-SUBRC <> 0.

      ENDIF.

    ENDIF.

  ENDIF.

ENDFUNCTION.
