*&---------------------------------------------------------------------*
*& Include          ZSDSCAR0020_SELECTION
*&---------------------------------------------------------------------*
*-----------------------------------------------------------------------
* P A R A M E T E R S   &   S E L E C T - O P T I O N S
*-----------------------------------------------------------------------
SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.
PARAMETERS: P_FILE LIKE RLGRAP-FILENAME OBLIGATORY LOWER CASE DEFAULT 'C:\',
            P_CHECK TYPE C NO-DISPLAY.
SELECTION-SCREEN END OF BLOCK B1.

SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME TITLE TEXT-002.
PARAMETERS: P_DOCNO TYPE C LENGTH 20 LOWER CASE,
            P_TYPE  TYPE C LENGTH 4 DEFAULT 'pdf' OBLIGATORY LOWER CASE,
            P_PATH  LIKE RLGRAP-FILENAME OBLIGATORY LOWER CASE.
SELECTION-SCREEN END OF BLOCK B2.

SELECTION-SCREEN BEGIN OF BLOCK B3 WITH FRAME TITLE TEXT-003.
PARAMETERS: R1 RADIOBUTTON GROUP LOG DEFAULT 'X' USER-COMMAND SY-UCOMM,
            R2 RADIOBUTTON GROUP LOG .
SELECTION-SCREEN END OF BLOCK B3.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN PUSHBUTTON (20) W_BUTTON   USER-COMMAND BUT1.
SELECTION-SCREEN END OF LINE.
