*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZSDSV_WBS_ITMTY.................................*
FORM GET_DATA_ZSDSV_WBS_ITMTY.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZSDSPSC001 WHERE
(VIM_WHERETAB) .
    CLEAR ZSDSV_WBS_ITMTY .
ZSDSV_WBS_ITMTY-MANDT =
ZSDSPSC001-MANDT .
ZSDSV_WBS_ITMTY-PRJTY =
ZSDSPSC001-PRJTY .
ZSDSV_WBS_ITMTY-ITMTY =
ZSDSPSC001-ITMTY .
ZSDSV_WBS_ITMTY-DESCP =
ZSDSPSC001-DESCP .
ZSDSV_WBS_ITMTY-REV_KSTAR =
ZSDSPSC001-REV_KSTAR .
ZSDSV_WBS_ITMTY-CST_KSTAR =
ZSDSPSC001-CST_KSTAR .
ZSDSV_WBS_ITMTY-ZDEL_FLG =
ZSDSPSC001-ZDEL_FLG .
ZSDSV_WBS_ITMTY-ZCRT_DATE =
ZSDSPSC001-ZCRT_DATE .
ZSDSV_WBS_ITMTY-ZCRT_TIME =
ZSDSPSC001-ZCRT_TIME .
ZSDSV_WBS_ITMTY-ZCRT_USER =
ZSDSPSC001-ZCRT_USER .
ZSDSV_WBS_ITMTY-ZCRT_PGM =
ZSDSPSC001-ZCRT_PGM .
ZSDSV_WBS_ITMTY-ZUPD_DATE =
ZSDSPSC001-ZUPD_DATE .
ZSDSV_WBS_ITMTY-ZUPD_TIME =
ZSDSPSC001-ZUPD_TIME .
ZSDSV_WBS_ITMTY-ZUPD_USER =
ZSDSPSC001-ZUPD_USER .
ZSDSV_WBS_ITMTY-ZUPD_PGM =
ZSDSPSC001-ZUPD_PGM .
<VIM_TOTAL_STRUC> = ZSDSV_WBS_ITMTY.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZSDSV_WBS_ITMTY .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZSDSV_WBS_ITMTY.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZSDSV_WBS_ITMTY-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZSDSPSC001 WHERE
  PRJTY = ZSDSV_WBS_ITMTY-PRJTY AND
  ITMTY = ZSDSV_WBS_ITMTY-ITMTY .
    IF SY-SUBRC = 0.
    DELETE ZSDSPSC001 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZSDSPSC001 WHERE
  PRJTY = ZSDSV_WBS_ITMTY-PRJTY AND
  ITMTY = ZSDSV_WBS_ITMTY-ITMTY .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZSDSPSC001.
    ENDIF.
ZSDSPSC001-MANDT =
ZSDSV_WBS_ITMTY-MANDT .
ZSDSPSC001-PRJTY =
ZSDSV_WBS_ITMTY-PRJTY .
ZSDSPSC001-ITMTY =
ZSDSV_WBS_ITMTY-ITMTY .
ZSDSPSC001-DESCP =
ZSDSV_WBS_ITMTY-DESCP .
ZSDSPSC001-REV_KSTAR =
ZSDSV_WBS_ITMTY-REV_KSTAR .
ZSDSPSC001-CST_KSTAR =
ZSDSV_WBS_ITMTY-CST_KSTAR .
ZSDSPSC001-ZDEL_FLG =
ZSDSV_WBS_ITMTY-ZDEL_FLG .
ZSDSPSC001-ZCRT_DATE =
ZSDSV_WBS_ITMTY-ZCRT_DATE .
ZSDSPSC001-ZCRT_TIME =
ZSDSV_WBS_ITMTY-ZCRT_TIME .
ZSDSPSC001-ZCRT_USER =
ZSDSV_WBS_ITMTY-ZCRT_USER .
ZSDSPSC001-ZCRT_PGM =
ZSDSV_WBS_ITMTY-ZCRT_PGM .
ZSDSPSC001-ZUPD_DATE =
ZSDSV_WBS_ITMTY-ZUPD_DATE .
ZSDSPSC001-ZUPD_TIME =
ZSDSV_WBS_ITMTY-ZUPD_TIME .
ZSDSPSC001-ZUPD_USER =
ZSDSV_WBS_ITMTY-ZUPD_USER .
ZSDSPSC001-ZUPD_PGM =
ZSDSV_WBS_ITMTY-ZUPD_PGM .
    IF SY-SUBRC = 0.
    UPDATE ZSDSPSC001 ##WARN_OK.
    ELSE.
    INSERT ZSDSPSC001 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZSDSV_WBS_ITMTY-UPD_FLAG,
STATUS_ZSDSV_WBS_ITMTY-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZSDSV_WBS_ITMTY.
  SELECT SINGLE * FROM ZSDSPSC001 WHERE
PRJTY = ZSDSV_WBS_ITMTY-PRJTY AND
ITMTY = ZSDSV_WBS_ITMTY-ITMTY .
ZSDSV_WBS_ITMTY-MANDT =
ZSDSPSC001-MANDT .
ZSDSV_WBS_ITMTY-PRJTY =
ZSDSPSC001-PRJTY .
ZSDSV_WBS_ITMTY-ITMTY =
ZSDSPSC001-ITMTY .
ZSDSV_WBS_ITMTY-DESCP =
ZSDSPSC001-DESCP .
ZSDSV_WBS_ITMTY-REV_KSTAR =
ZSDSPSC001-REV_KSTAR .
ZSDSV_WBS_ITMTY-CST_KSTAR =
ZSDSPSC001-CST_KSTAR .
ZSDSV_WBS_ITMTY-ZDEL_FLG =
ZSDSPSC001-ZDEL_FLG .
ZSDSV_WBS_ITMTY-ZCRT_DATE =
ZSDSPSC001-ZCRT_DATE .
ZSDSV_WBS_ITMTY-ZCRT_TIME =
ZSDSPSC001-ZCRT_TIME .
ZSDSV_WBS_ITMTY-ZCRT_USER =
ZSDSPSC001-ZCRT_USER .
ZSDSV_WBS_ITMTY-ZCRT_PGM =
ZSDSPSC001-ZCRT_PGM .
ZSDSV_WBS_ITMTY-ZUPD_DATE =
ZSDSPSC001-ZUPD_DATE .
ZSDSV_WBS_ITMTY-ZUPD_TIME =
ZSDSPSC001-ZUPD_TIME .
ZSDSV_WBS_ITMTY-ZUPD_USER =
ZSDSPSC001-ZUPD_USER .
ZSDSV_WBS_ITMTY-ZUPD_PGM =
ZSDSPSC001-ZUPD_PGM .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZSDSV_WBS_ITMTY USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZSDSV_WBS_ITMTY-ITMTY TO
ZSDSPSC001-ITMTY .
MOVE ZSDSV_WBS_ITMTY-PRJTY TO
ZSDSPSC001-PRJTY .
MOVE ZSDSV_WBS_ITMTY-MANDT TO
ZSDSPSC001-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZSDSPSC001'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZSDSPSC001 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZSDSPSC001'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
