*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZSDSV_PJ_RESPPER................................*
FORM GET_DATA_ZSDSV_PJ_RESPPER.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZSDSPSC003 WHERE
(VIM_WHERETAB) .
    CLEAR ZSDSV_PJ_RESPPER .
ZSDSV_PJ_RESPPER-MANDT =
ZSDSPSC003-MANDT .
ZSDSV_PJ_RESPPER-VKGRP =
ZSDSPSC003-VKGRP .
ZSDSV_PJ_RESPPER-VERNR =
ZSDSPSC003-VERNR .
ZSDSV_PJ_RESPPER-ZDEL_FLG =
ZSDSPSC003-ZDEL_FLG .
ZSDSV_PJ_RESPPER-ZCRT_DATE =
ZSDSPSC003-ZCRT_DATE .
ZSDSV_PJ_RESPPER-ZCRT_TIME =
ZSDSPSC003-ZCRT_TIME .
ZSDSV_PJ_RESPPER-ZCRT_USER =
ZSDSPSC003-ZCRT_USER .
ZSDSV_PJ_RESPPER-ZCRT_PGM =
ZSDSPSC003-ZCRT_PGM .
ZSDSV_PJ_RESPPER-ZUPD_DATE =
ZSDSPSC003-ZUPD_DATE .
ZSDSV_PJ_RESPPER-ZUPD_TIME =
ZSDSPSC003-ZUPD_TIME .
ZSDSV_PJ_RESPPER-ZUPD_USER =
ZSDSPSC003-ZUPD_USER .
ZSDSV_PJ_RESPPER-ZUPD_PGM =
ZSDSPSC003-ZUPD_PGM .
<VIM_TOTAL_STRUC> = ZSDSV_PJ_RESPPER.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZSDSV_PJ_RESPPER .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZSDSV_PJ_RESPPER.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZSDSV_PJ_RESPPER-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZSDSPSC003 WHERE
  VKGRP = ZSDSV_PJ_RESPPER-VKGRP .
    IF SY-SUBRC = 0.
    DELETE ZSDSPSC003 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZSDSPSC003 WHERE
  VKGRP = ZSDSV_PJ_RESPPER-VKGRP .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZSDSPSC003.
    ENDIF.
ZSDSPSC003-MANDT =
ZSDSV_PJ_RESPPER-MANDT .
ZSDSPSC003-VKGRP =
ZSDSV_PJ_RESPPER-VKGRP .
ZSDSPSC003-VERNR =
ZSDSV_PJ_RESPPER-VERNR .
ZSDSPSC003-ZDEL_FLG =
ZSDSV_PJ_RESPPER-ZDEL_FLG .
ZSDSPSC003-ZCRT_DATE =
ZSDSV_PJ_RESPPER-ZCRT_DATE .
ZSDSPSC003-ZCRT_TIME =
ZSDSV_PJ_RESPPER-ZCRT_TIME .
ZSDSPSC003-ZCRT_USER =
ZSDSV_PJ_RESPPER-ZCRT_USER .
ZSDSPSC003-ZCRT_PGM =
ZSDSV_PJ_RESPPER-ZCRT_PGM .
ZSDSPSC003-ZUPD_DATE =
ZSDSV_PJ_RESPPER-ZUPD_DATE .
ZSDSPSC003-ZUPD_TIME =
ZSDSV_PJ_RESPPER-ZUPD_TIME .
ZSDSPSC003-ZUPD_USER =
ZSDSV_PJ_RESPPER-ZUPD_USER .
ZSDSPSC003-ZUPD_PGM =
ZSDSV_PJ_RESPPER-ZUPD_PGM .
    IF SY-SUBRC = 0.
    UPDATE ZSDSPSC003 ##WARN_OK.
    ELSE.
    INSERT ZSDSPSC003 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZSDSV_PJ_RESPPER-UPD_FLAG,
STATUS_ZSDSV_PJ_RESPPER-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZSDSV_PJ_RESPPER.
  SELECT SINGLE * FROM ZSDSPSC003 WHERE
VKGRP = ZSDSV_PJ_RESPPER-VKGRP .
ZSDSV_PJ_RESPPER-MANDT =
ZSDSPSC003-MANDT .
ZSDSV_PJ_RESPPER-VKGRP =
ZSDSPSC003-VKGRP .
ZSDSV_PJ_RESPPER-VERNR =
ZSDSPSC003-VERNR .
ZSDSV_PJ_RESPPER-ZDEL_FLG =
ZSDSPSC003-ZDEL_FLG .
ZSDSV_PJ_RESPPER-ZCRT_DATE =
ZSDSPSC003-ZCRT_DATE .
ZSDSV_PJ_RESPPER-ZCRT_TIME =
ZSDSPSC003-ZCRT_TIME .
ZSDSV_PJ_RESPPER-ZCRT_USER =
ZSDSPSC003-ZCRT_USER .
ZSDSV_PJ_RESPPER-ZCRT_PGM =
ZSDSPSC003-ZCRT_PGM .
ZSDSV_PJ_RESPPER-ZUPD_DATE =
ZSDSPSC003-ZUPD_DATE .
ZSDSV_PJ_RESPPER-ZUPD_TIME =
ZSDSPSC003-ZUPD_TIME .
ZSDSV_PJ_RESPPER-ZUPD_USER =
ZSDSPSC003-ZUPD_USER .
ZSDSV_PJ_RESPPER-ZUPD_PGM =
ZSDSPSC003-ZUPD_PGM .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZSDSV_PJ_RESPPER USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZSDSV_PJ_RESPPER-VKGRP TO
ZSDSPSC003-VKGRP .
MOVE ZSDSV_PJ_RESPPER-MANDT TO
ZSDSPSC003-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZSDSPSC003'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZSDSPSC003 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZSDSPSC003'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
