"Name: \PR:R_FINS_PLAN_TRANS_CO_ERP_2_S4H\TY:LCL_TRANS_ERP_2_S4H\ME:PROCESS_LOG\SE:BEGIN\EI
ENHANCEMENT 0 ZSDS_PS_EXPORT_LOG.
*<-- Start of Insertion PSI001 07.05.2024 (Export Process Log)
  CONSTANTS:
    LC_MEMID  TYPE  CHAR20 VALUE 'ZSDS_EXP_LOG'.

  DATA:
    LF_EXPORT  TYPE  FLAG.

* Memory may export from method ZCL_SDSPS_PROJECT=>UPDATE_PLAN_COST_TABLE
  IMPORT EXPORT_FLAG TO LF_EXPORT FROM MEMORY ID LC_MEMID .
  IF LF_EXPORT EQ 'X'.
    FREE MEMORY ID LC_MEMID.
    EXPORT MESSAGE FROM CT_MESSAGE TO MEMORY ID LC_MEMID.
*   Disable result report
    SY-BATCH = 'X'.
  ENDIF.
*--> End of Insertion PSI001
ENDENHANCEMENT.
